### ISSUE TITLE
記事の更新履歴

### ISSUE THREAD

**Issue by yoshimov** [support-project/knowledge#10]
バージョン数限定でも良いので、各記事の更新履歴が見られると良いです。
Markdownの格納はGitなどを使うと楽かもしれません。

**Comment by koda-masaru** [comment]
なるほど。良いかもしれませんね。

Gitで管理しているソースなどの情報も、Knowledgeで検索出来たら嬉しいと
いう声もあるので、Gitとの連携は検討してみます。

**Comment by koda-masaru** [comment]
更新履歴を表示できるようにしました。
ナレッジを表示した画面で、「更新日時」の部分にリンクがあり、
そこから更新履歴の表示へ遷移するようにしました。
