### ISSUE TITLE
等幅フォント

### ISSUE THREAD

**Issue by TJ-Hidetaka-Takano** [support-project/knowledge#1006]
コンテンツを記述する際に等幅フォントでないので、
インデント量の確認がしにくいです。
特に表は致命的に書きづらいです。

**Comment by koda-masaru** [comment]
Are you trying to indent on Markdown content by some white space? 
If that is the case, I recommend indenting by Markdown's syntax.

**Comment by TJ-Hidetaka-Takano** [comment]
<pre>
|    項目     |    分類    |              説明                        |
|------------:|:----------:|:-----------------------------------------|
|    アイテム1|   AAAAA    |説明ほげほげ                              |
|    あいてむ2|    BBB     |Description foo bar                       |
|        品名3|  CCCCCCC   |せつめい                                  |
|       Item 4|    ○○    |Explanation about Item4                   |
</pre>
``
|    項目     |    分類    |              説明                        |
|------------:|:----------:|:-----------------------------------------|
|    アイテム1|   AAAAA    |説明ほげほげ                              |
|    あいてむ2|    BBB     |Description foo bar                       |
|        品名3|  CCCCCCC   |せつめい                                  |
|       Item 4|    ○○    |Explanation about Item4                   |

**Comment by TJ-Hidetaka-Takano** [comment]
```
|    項目     |    分類    |              説明                        |
|------------:|:----------:|:-----------------------------------------|
|    アイテム1|   AAAAA    |説明ほげほげ                              |
|    あいてむ2|    BBB     |Description foo bar                       |
|        品名3|  CCCCCCC   |せつめい                                  |
|       Item 4|    ○○    |Explanation about Item4                   |
```

**Comment by TJ-Hidetaka-Takano** [comment]
```
|    項目     |    分類    |              説明                        |
|------------:|:----------:|:-----------------------------------------|
|    アイテム1|   AAAAA    |説明ほげほげ                              |
|    あいてむ2|    BBB     |Description foo bar                       |
|        品名3|  CCCCCCC   |せつめい                                  |
|       Item 4|    ○○    |Explanation about Item4                   |

```

**Comment by TJ-Hidetaka-Takano** [comment]
No.
I mean when I writing a content including the table like below,
I feel a pretty inconvenience because of the difficulty to align the lenght.
I hope the "Knowledge" to support monospaced fonts.

```
|    Item     |    Type    |               Description                    |
|------------:|:----------:|:---------------------------------------------|
|      aaaaaa |   IIIIII   | Every Item's name is same amount of letters. |
|      iiiiii |   WWWWWW   | Type's also are intended same width.         |
|      wwwwww |   ＩＩＩ   | 全てのItem名は同じ文字数です。               |
|      llllll |   ＷＷＷ   | Typeも同じ幅で表示されることを期待します。   |
```

You can find my intention easily by copying and pasting the above code to Knowledge contents

**Comment by johiroshi** [comment]
等幅フォントとプロポーショナルフォントのことですね。
textarea内のフォント指定をmonospaceなどの等幅フォントにしてほしい、ということだと思います。

![monospace](https://user-images.githubusercontent.com/15374413/36407609-94d5c920-15f7-11e8-9da3-f38c8e76d862.png)

**Comment by koda-masaru** [comment]
I understand your issue that is to specify a monospaced font for the text area, is that right?
I will change the font for the text area in the next release.

**Comment by TJ-Hidetaka-Takano** [comment]
Thank you, johiroshi-san.
Koda-masaru-san, that's right!
Thanks a lot.
