### ISSUE TITLE
Create users without email

### ISSUE THREAD

**Issue by garp5000** [support-project/knowledge#1008]
Hello,

I would like to know if it is possible to create an user without register an email address. In some case, it could be interesting for some people to create an Knowledge account without associating it with an email (or to prepare account when no email wasn't created yet).

Best regards,

**Comment by koda-masaru** [comment]
You can create the user account without email by administrator role.
Please Log in as an administrator user and access the Users menu of System Config.
Then you can add the user by administrator role on this page.
In the case of adding a user by the administrator, you can any text in the Mail Address field.

**Comment by garp5000** [comment]
Ok, great, thank you for this answer :). It's works fine.
