### ISSUE TITLE
Notify.js によるデスクトップ通知が自動で消えない

### ISSUE THREAD

**Issue by akai-inu** [support-project/knowledge#101]
ソースコード上の問題を発見できず恐縮ですが、デスクトップ通知のNotify.jsが、通知後自動で消えません。

Ubuntu15.04上のOperaでの確認になりますが、 [公式のDEMO](https://alexgibson.github.io/notify.js/) 上では自動で消えることが確認出来たため、実装の問題なのではないかと思います。

毎回クリックするのが面倒なので修正して頂ければ幸いです。

(通知をクリックしたら該当のKnowledgeページに飛んでくれるとさらに嬉しいです :cat2:)

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

Notify.js の オプションで timeout が指定できるのですが、今のところ設定していないので、
通知が消えないようになっています。

たしかに毎回クリックするのは面倒ですので、3秒程度で消すように設定しようかと思います。

**Comment by koda-masaru** [comment]
後で対応するため、調べた事を記載します。

/knowledge/src/main/webapp/WEB-INF/views/commons/layout/commonScripts.jsp

に、Notify.js を使った部分が書かれているので、以下の部分を修正する。

- 修正前

```
				var myNotification = new Notify('Notify from Knowledge', {
					body: msg,
					notifyShow: onNotifyShow
				});
```

- 修正後

```
				var myNotification = new Notify('Notify from Knowledge', {
					body: msg,
					notifyShow: onNotifyShow,
					timeout: 3,
					notifyClick: onNotifyClick // クリックしたら Knowledgeのページへ遷移する
				});
```

**Comment by koda-masaru** [comment]
通知は3秒で消えるようにしました。
また、通知をクリックすると、通知されたナレッジを表示するようにしました。
次回のリリースをお待ち下さい。

**Comment by il-m-yamagishi** [comment]
ご対応ありがとうございます！
