### ISSUE TITLE
Knowledge freeze while previewing markdown doccument

### ISSUE THREAD

**Issue by geo-mm** [support-project/knowledge#102]
Hi,

I hosted a knowledge base system with Knowledge Docker, and I posted a markdown document basically  transferred from a wiki website, but Knowledge stop responding when I tried to preview or open the document after saving the document to Knowledge. The attachment is the document that cause the freeze, and you might want to take a look. Since I cannot upload files to this repository, I will provide the link from my google drive.

https://drive.google.com/file/d/0Bzfel_IWZzflT1pNblN4ZFFJY1k/view?usp=sharing

Thanks for all the hard works! This system is great and does all the jobs I need!

**Comment by koda-masaru** [comment]
Hi

Thank you for your bug reports.
Cause of the knowledge of the freeze is the highlight processing of code.
Code of highlights, it is processing in the browser's Javascript. 
library: highlight.js (https://highlightjs.org/)

I will change the process of code highlights.
Please wait until it can fix.

**Comment by geo-mm** [comment]
Thank you for your fast response :)

**Comment by koda-masaru** [comment]
I found cause to freeze.
URL scheme is a problem.
(e.g. imdb: // xxx)

I will change process to stop the code highlights, if there is a URL scheme in the code block.
(As a result of this change, the code block that contains a URL scheme will no longer highlight.)

Please wait for the next release.

**Comment by geo-mm** [comment]
Unless the URL is an <a> link, I don't think URL schemes hightlighting matters. And I don't think that is an important feature. Thank you for your help!
