### ISSUE TITLE
Error with new install

### ISSUE THREAD

**Issue by garp5000** [support-project/knowledge#1026]
Hi,
To check a restore procedure, I've removed from tomcat the application "Knowledge" and delete PostgreSQL databases. After that I reinstall Knowledge but it doesn't start and I've a connection error with the error message in logs : 

> ConnectionPoolImpl(127) Can't create a new connection for jdbc:postgresql://localhost:5432/Knowledge
> org.postgresql.util.PSQLException: FATAL: Ident authentication failed for user « Knowledge » (pgjdbc: autodetected server-encoding to be ISO-8859-1, if the message is not readable, please check database logs and/or host, port, dbname, user, password, pg_hba.conf)

It seems keep older connection information but I don't know how to do a full reset... or where changing authentification information...
Could you help me?

Thanks!

**Comment by koda-masaru** [comment]
Hi,

"Knowledge" creates a directory of ".knowledge" in the home directory of the invoking user and stores the service's data there.
note: you can change this directory path by Environment variable "KNOWLEDGE_HOME".

If you check this directory, you can find a file that name is "custom_connection.xml".
If this file exists, "Knowledge" will attempt to connect to the DB(PostgreSQL) with this file's setting.
For this reason, if you delete this file, you can reset full connection setting.

Best regards,

**Comment by garp5000** [comment]
Thank you very much. Good to know, in Windows environment, by default the home directory is set to : 
C:\Windows\System32\config\systemprofile
I finaly found it after a very long search. Maybe this information could help other peoples.

Thank you for your help, I found the custom_connection.xml file, and now all works again !

Best regards
