### ISSUE TITLE
navigation varがウィンドウ幅を縮小させると二段になってしまう

### ISSUE THREAD

**Issue by mayumi-kobayashi-recochoku** [support-project/knowledge#1027]
ヘッダーにnavigationバーを設定し、検索フォームとボタンを配置していますが、ウィンドウ幅を小さくさせるとnavigationバー内のボタンが画面に入りきらなくなることで、2段になってしまいます。その際に下のbody要素が隠れてしまい、body上部に設置したボタンが押せなくなってしまいます。

さらに幅を小さくさせるとスマホ対応のデザインに変わるのですが、その前に2段になるのを防ぎたいのですが、方法はありますでしょうか。

**Comment by koda-masaru** [comment]
たぶん、このファイルを調整すれば実現できると思います。
https://github.com/support-project/knowledge/blob/v1/src/main/webapp/WEB-INF/views/commons/layout/commonNavbar.jsp

**Comment by mayumi-kobayashi-recochoku** [comment]
無事解決いたしました。
早急な回答ありがとうございました。
