### ISSUE TITLE
Where is the WebAPI document?

### ISSUE THREAD

**Issue by hiro-icear** [support-project/knowledge#1031]
お世話になっております。
WebAPIを経由して記事を投稿しようとしています。
投稿の差異にタグと公開グループを付与した状態で行いたいのですが、
記述フォーマットが分かりません。
APIリファレンス等はありませんでしょうか？
使用バージョン　1.12.0

最終的にクローズド環境のknowledgeからエクスポートしたXMLの中から任意の記事を別のknowledgeにインポートすることを想定しています。

APIの利用はmatsumotohirokoさんのを参考にさせていただいています。
https://github.com/MatsumotoHiroko/knowledge_batch/blob/master/webapi_send_test.py

実行時に渡す情報(json)
```
        self.query = {
            'private_token': self.token,
            'tagIds': '16',
            'tagNames': '※調査中',
            'publicFlag': 0,
            'editors': {
                'groups': [],
                'users': []
            },
            'viewers': {
                'groups': [],
                'users': []
            },
            'template': 'knowledge',
            'templateItems': [],
            'title': 'APIインポートテストjson3',
            'content': 'APIインポートテスト(json)3 \n pythonコード内に直接本文を記述し、リテラルのjsonオブジェクトとして実行する \n タグ同時追加テスト'
        }
```
上記の書き方だと、タイトルと本文だけPOSTされ、ok(201)となって投稿されます。

**Comment by koda-masaru** [comment]
API Document は作成しようと思っているのですが、まだちゃんと作成できていません。
ただ、以下の手順で登録したいデータのJSON形式(タグと公開グループを付与)を確認できると思います。

### 手順
- 登録したいデータの形式の記事を画面から投稿する
   - [テストサイト](https://test-knowledge.support-project.org/) などの環境をご利用ください
- 上で投稿した記事を、Get のAPIで取得する
   - 取得できるJSONを参照すると、イメージが湧くのではないかと思います
   - 取得例↓ (api/knowledges/7 の「7」は記事の番号を指定）
   - https://test-knowledge.support-project.org/api/knowledges/7?private_token={ユーザのTokenを指定}
- 上で確認したJSONをPostしてみる（投稿）

--------

上記手順で取得してみたものは以下になります。


```
{
    "attachments": [], 
    "commentCount": 0, 
    "comments": [], 
    "content": "テストの記事です", 
    "editors": {
        "groups": [], 
        "users": []
    }, 
    "insertDatetime": "2018-03-28 22:18:17.982", 
    "insertUser": 1, 
    "knowledgeId": 7, 
    "likeCount": 0, 
    "publicFlag": 2, 
    "tags": [
        "Sample", 
        "テスト"
    ], 
    "template": "knowledge", 
    "templateItems": [], 
    "title": "グループとタグを設定した記事", 
    "updateDatetime": "2018-03-28 22:18:17.982", 
    "updateUser": 1, 
    "viewers": {
        "groups": [
            {
                "id": "1", 
                "name": "テストグループ"
            }
        ], 
        "users": [
            {
                "id": "1", 
                "name": "Administrator"
            }
        ]
    }
}
```

**Comment by hiro-icear** [comment]
さっそくの回答ありがとうございます。
一度GETすれば構成が構造が1発でわかる・・・そのとおりですね。
配列形式で格納することを失念しておりました。

再度試してみます。

**Comment by hiro-icear** [comment]
無事、タグとグループのインポートに成功しました。ありがとうございました。
グループはグループのIDが必要なのが運用上ネックかなと思いました。
　(簡単に調べられますがちょっとマニアックですね)

ちなみに、XMLでの出し入れはできるのでしょうか？
GETするときに　httpheaderをapplication/xmlにしましたがjsonで落ちてきました。
