### ISSUE TITLE
[Web API] How acquire the total count(number of active items)

### ISSUE THREAD

**Issue by hiro-icear** [support-project/knowledge#1034]
Web APIを使用した全件取得取得と類似の質問になるのですが、数百件取得する場合に、有効な総件数を先に取得したいと考えています。
それが分かることによって、後ろから10件分だけ取り出すなどが可能となり、高速化できると考えています。
property=totalcount　などの指定はできますでしょうか？

#993

**Comment by koda-masaru** [comment]
すみません、Issueに気づいていませんでした。
今、リリースしているバージョンでは、トータルの件数を取得することはできません。
開発中のバージョンでは対応していますので、しばらくすると取得できるようになります。

**Comment by hiro-icear** [comment]
開発中のバージョンでの対応　了解しました。
リリースをお待ちしております。
