### ISSUE TITLE
グループに投稿された記事のみ参照したい

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#105]
現状だと記事やコメント、タグでの絞り込みはできますがグループに投稿された記事だけを参照することができません。

グループにいっぱい所属してる場合や公開の記事がいっぱい投稿された場合に見つけづらくなるので
検索ページでグループ用のフォームを用意して(タグと同じ感じのイメージです)グループの投稿に絞って検索できるようにするのはいかがでしょうか？

またグループの詳細からそのグループの投稿記事一覧にいけるとユーザビリティ的にもいいかなと思います。

**Comment by koda-masaru** [comment]
なるほど。
グループで絞り込むというのは、ユーザにとってメリットも大きいし、実装も簡単で良いですね。

#72 に、プロジェクトのような単位で絞り込みたいというissueも上がっているのですが、それだとデータの変更などが少し大変かなと思っていて、なかなか着手出来ませんでした。

グループであれば、既にデータは登録されているので、対応が簡単に出来るかと思います。

**Comment by nagodon** [comment]
おっ、では対応したいですね。
検索フォームにグループ名のフォームを用意する感じがいいでしょうか？
もしくはGoogle見たくてprefixをつけて検索できる感じがいいでしょうか？

トップのキーワードで検索部分でも検索できるようにしようと思うとprefixの方がいいですよね？

**Comment by koda-masaru** [comment]
なるほど。prefixというのは良い案かと思います。

ただし、検索画面（キーワードとタグで絞り込む画面）では、グループの選択を
ダイアログ選択（タグの選択のような感じ）になっていると良いかと思います。

PC操作に慣れている人はprefix検索で良いのですが、そうでない人には、
GUI操作の方が直感的かと思います。

あと、タグでの絞り込みもprefix検索が出来るようになると嬉しいです。

**Comment by nagodon** [comment]
では検索画面はタグと同じくグループの選択を表示してキーワード入力はprefixで検索できるようにしますね。

prefixはそれぞれ下記でいいでしょうか？

- groups: グループ名 キーワード(optional)
- tags: タグ名 キーワード (optional)

**Comment by koda-masaru** [comment]
良いと思います :+1:

**Comment by nagodon** [comment]
ありがとうございます。
ではこの形で実装しますね。

**Comment by koda-masaru** [comment]
お願いします。
