### ISSUE TITLE
表示記事を絞り込んだ時のページ切り替えについて

### ISSUE THREAD

**Issue by yuichi0123** [support-project/knowledge#1052]
何らかの操作で記事の検索条件を設定したときの挙動について
確認させて頂きたいことがあります。

環境は現時点の最新で、Ver1.13.0、DBはPostgreSQLです。

例えばタグで絞り込みを行った場合
検索窓には「tags:(hogehoge)」と、絞り込み条件に応じた文字列が
表示されますが、
該当件数が多く、ページ切り替えが発生する場合、
次へボタンを押した先の表示にて、絞り込み条件が効いていないように思えます。

実際に検索窓にも文字列が何も表示されなくなります。

検索条件は引き継がれるのが正しい動きだと思われるのですが
いかがでしょうか？
※最近バージョンアップを実施したため、前バージョンでの挙動が
　どうだったのかが、確認できておらず、申し訳ありません。

**Comment by koda-masaru** [comment]
Thank you for your information.
I will release a version that fixes this bug soon.

------

ご連絡ありがとうございます。別の機能を変更していて、なんか変なふうにしてしまいました。
仕事とは違って、テストが甘くなるので困ったものです。。。
不具合を修正したバージョンをリリースします。

**Comment by yuichi0123** [comment]
お忙しい中、ご確認有難うございました。
そうですよね。テスト、甘くなりますよね...

不具合修正バージョン、お待ちしております。

**Comment by yuichi0123** [comment]
Ver1.13.1で修正されている事を確認できました。
ご対応ありがとうございました。
クローズとさせていただきます。
