### ISSUE TITLE
0.4.1から0.4.2にバージョンアップすると、ナレッジを開く際にNot Foundになる

### ISSUE THREAD

**Issue by yoshimov** [support-project/knowledge#11]
データベースファイルをそのまま利用して0.4.1から0.4.2にバージョンアップすると、ナレッジを開く際にNot Foundになるようです。
catalina.logには特にエラーは出ていません。
0.4.1に戻したらまた開けるようになったので、データベースが壊れたわけではなさそうです。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

私の環境では、0.4.1から0.4.2にあげても開けたので、データがある
一定の条件で発生するなど、どこかに不具合があるのだと思います。

ただ、すぐに原因は特定できないので、どうしようかなぁ、、、
原因についてはあとで調査しますが、いったんアナウンスを書こうと
思います。

**Comment by yoshimov** [comment]
DBを停止させてから0.4.2にしたら問題なく開けるようになりました。お騒がせしました。

**Comment by koda-masaru** [comment]
いえ、やはり不具合だったと思います。

内容は、スマートフォンなどではJavascriptやCSSを変更してもキャッシュが更新されずに、
古いもので動いてしまうということが原因だと思われます。
http://mathtti.hatenablog.com/entry/20111114/p1

というわけで、上記websiteの
*JavaScriptとCSSの呼び出し時に何らかの識別子をつける*
という対応を行い、バージョンアップ(0.4.3)を発行しました。

ご報告ありがとうございました。
