### ISSUE TITLE
外部から書き込もうとするとエラーになります

### ISSUE THREAD

**Issue by TakehideMorimoto** [support-project/knowledge#1113]
knowledge を導入してみようと環境構築中なのですが、クライアントマシンから何かしら書き込み操作(ユーザー登録、投稿など)やログの参照などをしようとすると、エラー403が起きます。

![knowledgeエラー拡大](https://user-images.githubusercontent.com/73085211/115339289-6b01ef80-a1df-11eb-852f-b6e354a7f794.png)

環境は下記の通りです。
> Application version: v1.13.1
> Database schema version: 1.13.0
> Tomcat 9.0.45
> Java: JRE 1.8.0_231
> サーバー: Windows Server 2008
> クライアント: Windows 10 Pro, Google Chrome バージョン: 90.0.4430.72（Official Build）（64 ビット）

サーバーのChrome からならば、IP を指定した URL で入って、冒頭の操作は全て成功します。
当初はこれもエラーになっていましたが、「IPアドレスでアクセスすると書き込みができない #566」を参照してこの点は解消しました。

インストールは、https://information-knowledge.support-project.org/install-ja の「インストール」セクションにある手順どおりに行ないました。

試しに、同じ手順で Windows 7 Pro 環境にインストールしてみると、外部からでも問題なく読み書き出来たので、Windows Server 2008 固有の問題だと思うのですが、原因の見当がつきません。
どなたか、解決策を授けて頂けませんでしょうか。

**Comment by TakehideMorimoto** [comment]
一応、自己解決しました。
データベースを PostgreSQL に切り換えると、外部からでも書き込み可能となりました。

**Comment by y-okumura-isp** [comment]
Windows 7 で上手く行っているとのことなので念の為の確認なのですが、Windows 2008 の IP address を 192.168.0.1、tomcat port を 8080 とすると以下の様にされていますでしょうか?

- ブラウザで指定する URL: http://192.168.0.1:8080/knowledge
- サービスのURL 設定: http://192.168.0.1:8080/knowledge

> サーバーのChrome からならば、IP を指定した URL で入って、冒頭の操作は全て成功します。

この際に指定する URL も http://192.168.0.1:8080/knowledge でしょうか?
文字列一致なので片方が IP アドレス・片方がホスト名でも #556 と同じ状態になります。

また Windows 7 との構成的な違いはありますでしょうか? 例えば、
- Windows 2008 機には複数 IP Address が割り当たっている
- 仮想 OS を使っている
- リバースプロキシしている
- などなど

ブラウザの開発者モードのコンソールログや、knowledge/tomcat のログがあると何か分かるかもしれません。
例えば #566 と同じ設定ミスですと以下の様なログがでます(サービス URL を `http://localhost:8080/knowledge`、同マシン上のブラウザから `http://127.0.0.1:8080/knowledge` にアクセスした例です)。

- chrome

```
POST http://127.0.0.1:8080/knowledge/protect.knowledge/save 403
```

- knowledge

```
tomcat_1         |  WARN 2021-04-24 01:03:57,395 HttpRequestCheckLogic(67) It is a request from outside the system.
tomcat_1         |  WARN 2021-04-24 01:03:57,397 HttpRequestCheckLogic(68) Request: http://127.0.0.1:8080/knowledge/protect.knowledge/save
tomcat_1         |  WARN 2021-04-24 01:03:57,397 HttpRequestCheckLogic(69) Referer: http://127.0.0.1:8080/knowledge/protect.knowledge/view_add
```

**Comment by TakehideMorimoto** [comment]
返信、ありがとうございます。
実は現在、PostgreSQL への切り換えに成功しまして、結果「外部からの書き込みに失敗する」問題自体は解決しております。一度は「自己解決しました」をアップしたのですが、その後何故か現象が再発し、Closed を取り下げました。ところがその後、再び問題が収まり、現在のところ謎の解決を見ております。現在、経過観察中です。
が、Windows Server 2008 & H2 の環境だと、恐らく何度でもこの現象は再現出来ると思うので、自分では引き続きこの問題を追っていこうかと考えているところです。

> この際に指定する URL も http://192.168.0.1:8080/knowledge でしょうか?
> 文字列一致なので片方が IP アドレス・片方がホスト名でも #556 と同じ状態になります。

使用した URL は両者で正確に一致しており、共に ↑ この形式です。

> Windows 2008 機には複数 IP Address が割り当たっている

確認しましたが、複数 IP は割り当ててはおりませんでした。

> 仮想 OS を使っている

Windows 7 は仮想環境で、Win Server は実機です。

> リバースプロキシしている

すみません。リバースプロキシが分かりません。何を見れば行なっているか否かが判別できるでしょうか。
人が作った環境を引き継いでいおり、把握しておりません。

以上、何か分かれば幸いです。

**Comment by y-okumura-isp** [comment]
なるほど、h2 との組み合わせですか。Win Server ならではのハマり所があるんですかね。

> すみません。リバースプロキシが分かりません。何を見れば行なっているか否かが判別できるでしょうか。

デフォルトでは tomcat は 8080 番ポートを listen しているので http://〜〜〜:8080 という URL になります。
フロントエンドに apache や nginx を立てて、 セキュリティの向上・負荷分散等々を行ないます。
一般的には URL にポート番号が不要になり http://〜〜〜 や https://〜〜〜 になります。

リバースプロキシが原因なら postgres 化で解決しないはずなので無関係でしょうね。

**Comment by TakehideMorimoto** [comment]
前述の通り、PostgreSQL に移行することで書き込みエラーが起こることは解決しました。一度、何故か現象が再発しましたが、直ぐに現象は収まり、その後安定しているので、収まったと見なすこととします。
H2 で問題が出ることは解決しておりませんが、マイナーなプラットフォーム固有の問題ということもありますし、目をつむるということで良いのではないでしょうか。これで Closed とさせていただきます。
