### ISSUE TITLE
リポジトリへの招待メールが届かない

### ISSUE THREAD

**Issue by SCKobayashiYurina** [support-project/knowledge#1138]
お世話になっております。

プロジェクト関係者にリポジトリへの招待メールを送ってもらったのですが、
メールが届きません。

通知設定から設定しているメールアドレスを確認しましたが、問題はありませんでした。
こちらどのようにすれば解決しますでしょうか。

**Comment by mzk4401** [comment]
おそらく招待側が質問者様をCollaboratorsに追加していないのではないでしょうか

招待側に問い合わせてみると良いかと思います。

[参考](https://code-schools.com/github-invite/)
