### ISSUE TITLE
記事に紐づく画像が削除できない

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#114]
コードを見る限り記事に紐づくものは削除できないようになっていますが、こちら仕様になりますか？

間違ってアップロードした場合など削除できた方がいいかなと思うのですがいかがでしょうか？

**Comment by koda-masaru** [comment]
ほんと、削除できませんね。
実装ミス＆テスト漏れです :sob: 

削除出来たほうが良いと思いますので、修正します。

**Comment by nagodon** [comment]
@koda-masaru 私の方で直しますね。

**Comment by koda-masaru** [comment]
ありがとうございます。
プルリクエストをマージしました。
