### ISSUE TITLE
グループ一覧ページのグループ名の横に投稿数を表示したい

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#115]
どのグループでどれくらいの投稿があるかが見れると便利かなと思います。

例えば公開されてるグループの中で入りたいグループの指標値になったりや自分が所属してるグループの投稿数を増やすモチベーションに繋がったりなどですね。

ご検討いただけると幸いです。

**Comment by koda-masaru** [comment]
機能検討ありがとうございます。

#105 の「グループに投稿された記事のみ参照したい」と合わせて実現できると
とても便利かと思います。
