### ISSUE TITLE
SpeakerDeckやSlideShareなどのスライドを記事に直接表示したい

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#116]
記事上で直接スライドが表示されると非常に便利かなと思います。
ご検討頂ければ幸いです。

**Comment by kounoike** [comment]
別件でブログにtwitter発言とか簡単に埋め込む方法を調べていたところ出てきたのですが、
Open Graphというらしいですね。

https://github.com/nfl/jquery-oembed-all を使うと色々なサイトへのリンクを埋め込むことができるみたいです。

**Comment by nagodon** [comment]
@kounoike ありがとうございます。
すごい便利ですね、このライブラリ。

これをうまくmarkdownと絡めれればいけそうですね。

**Comment by koda-masaru** [comment]
たしかに、スライドの表示などできると便利ですね。

@kounoike さんの教えていただいた方法で実現出来れば、実現したいですね。

@nagodon さん。対応してみます？

**Comment by nagodon** [comment]
@koda-masaru 

では対応してみたいと思います。
markedを拡張して専用のmarkdownで対応した方が良いでしょうか？
それとも直接aタグ入れてもらう方がいいでしょうか？

**Comment by kounoike** [comment]
markdownを変に拡張するよりも、まずはbookmark限定の機能として実装してみるというのはどうでしょうか？

**Comment by koda-masaru** [comment]
直接タグを埋め込んだりすることを許すと、XSSの脆弱性が発生しそうで大丈夫でしょうか？
markdownを拡張して、ユーザが自由にiframeやscriptタグを生成できるようになると危険な気がします。

このため、 @kounoike さんのご意見のように、 bookmarkのような形で slide といった
テンプレートを作成して、その中でスライドの内容表示をハンドリングした方が良いかもです。

**Comment by nagodon** [comment]
すいません、ちょっと語弊があったかもしれません。
https://github.com/nfl/jquery-oembed-all
こちらのライブラリはhtml中のaタグに`class="oembed"`という属性がついたaタグがあった場合に表示を試みるのでダイレクトにiframeやscriptタグを入れてもらう前提ではありませんでした。

例えばmarkdownの拡張というのは以下の形をイメージしておりました。

```
[oembed http://slideshare.net/xxxxx]
```

この形でmarkdownを書くと画面表示する際に

```
<a class="oembed" href="url"></a>
```

という形に変換されてスライド等が表示されるイメージでした。

また直接タグを入れてもらうというのはaタグはmarkdownパーサーでも通常リンク扱いになるのでご提案させて頂いた次第です。

**Comment by koda-masaru** [comment]
なるほど。
https://github.com/nfl/jquery-oembed-all のライブラリの使い方がわからなかったので、
食い違っていたようです。

上記のようであれば、XSS系の脆弱性も出ないので良いかと思います。

**Comment by koda-masaru** [comment]
なお、Markdownのパース（Markdown→HTML）は、
org.support.project.knowledge.logic.MarkdownLogic
で行っています。
この部分を拡張していけば、実現出来るかと思います。

なお、MarkdownはPegDownというJavaのライブラリを使ってパースしています。
また、PegDownが失敗した場合、Markd.jsというJavascriptのMarkdownパーサーを使ってパースします。
Gitbucketの作者さんが、gitbucket/markedj [https://github.com/gitbucket/markedj] という、Markd.jsをJavaにポーティングしたパーサーを作ったので、PegDownから乗り換えも検討しています。

参考：http://takezoe.hatenablog.com/entry/2015/10/03/143930

**Comment by nagodon** [comment]
ありがとうございます。
これを機にmarkedjに乗り換えますか？

**Comment by koda-masaru** [comment]
そうですね。
markedjの方が、「GitHub Flavored Markdownのより良いサポートを提供」と書いてあるので、
乗り換えてしまって良いかもです。

その上で、Forkして上記の拡張も実装するというアイディアも良いかもしれません。

**Comment by nagodon** [comment]
Forkして拡張を実装という形だと非常に助かりますね。
どうやって拡張しようかちょっと悩んでましたw

**Comment by koda-masaru** [comment]
では、Forkのプロジェクトを用意してみようと思います。
Forkして拡張して、うまく出来たら、gitbucket/markedjの作者さまにも伝えていくということでも良いかもしれませんね。（本家でもサポートしてくれるかも？）

**Comment by nagodon** [comment]
ありがとうございます。
なるほど、いいですね。

**Comment by koda-masaru** [comment]
Forkした markedj のパーサーを Knowledge内のMarkdownLogicで呼び出せるようにしてみました。
feature/issue116_slide のブランチにすると、Forkしたmarkedj でMarkdownのパースを行うようになります。

markedjに、上記の独自拡張の実装をお願いします。

**Comment by nagodon** [comment]
support-project/markedj#2 でまずmarkdown側のsyntaxの拡張行いました。

**Comment by nagodon** [comment]
#121 で対応しました
