### ISSUE TITLE
Markdownにアップロードした画像を表示したら、添付ファイルの一覧に表示しないでほしい

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#123]
- デモサイトへの投稿より
    - 画像を表示したら、編集モード以外は添付ファイルとして表示しないようにして欲しいです。

**Comment by johiroshi** [comment]
#230 より

> PDFやExcelはそれ自体で一つのknowledgeであり、PDFやExcelはそれらを含有するknowledgeとは分けて、リンクとして表示すべきだろうか

の件と前後するのですが、**「knowledgeとは何か」**という定義が以前より気になっていました。
knowlwdgeのランディング・ページにknowledgeというサービス自体の説明はあるのですが、記事投稿画面や記事が面にあるような「knowledge」というカテゴリの説明がうまく見つけられず、わかりませんでした。

もし定義のようなものがありましたら、教えていただいても良いでしょうか。

**Comment by koda-masaru** [comment]
確かに、「knowledge」とは何か？という定義は決めてませんでしたね。

「自分のグループに、Qiitaのような仕組みを提供して、チームでいろんな情報を共有したい」
というのが目的で作ったものなので、「チーム内で共有したい情報」というのが定義でしょうか。

私の使い方は、メーリングリストのように「メール」で、情報共有すると、情報が行方不明になりやすいので、それの置き換えを行っています。

メールだと、送信するときに宛先から漏れていると届きませんが、knowledgeだと、あとで公開範囲に入るとやりとり全てが見れるので便利です。

あと添付ファイルの中が検索対象になるので、本文は「これ見といて」だけで、内容は添付ファイルの中あるという事も多いです。

定義という話題からは少しずれましたが、使い方としてはこんな感じになります。

**Comment by johiroshi** [comment]
お返事ありがとうございます。

つまり、knowledge というサービスは、**「宛先が一つしかないメール・サービス」**ということでしょうか。

**E-Mailとknowledgeの比較**

/ | E-Mail | knowledge
------------ | ------------ | -------------
誰が | 差出人| ユーザー
誰に | 受取人 | knowledgeのリスト
タグ機能 | なし | あり
添付機能 | あり | あり
検索機能 | あり | あり
編集権限の設定 | 不可 | 可

みたいな。

**Comment by koda-masaru** [comment]
う〜ん。メールだけとは言えない感じです。
メール（宛先を絞って公開）＋掲示板（掲示しておいて誰でも見れる）といった感じでしょうか。
私は、社内用（イントラネット用）のQiitaのようなものと説明しています。

より効果的な情報共有の方法を考えた場合、「Knowledgeをどう使うか」が鍵となる気がします。
その意味で、*「knowledgeとは何か」という定義* があると良いのですが、 
運用をしながら試行錯誤している段階で、確固たる定義は未だ無いのが現状です。

**Comment by johiroshi** [comment]
御返事ありがとうございます。なんとなく掴めてきました。

サービスのコアとなる部分なので、試行錯誤、大事だと思います。

以前お話しした、ExcelやPDFもknowledgeの一つではないか、という意見は一旦取り下げます。これらの添付ファイルの扱いは今まで通りでも大丈夫だと思います。

その上で、話が前後するのですが、[添付ファイルの表示方法サンプル](https://support-project.org/knowledge/open.knowledge/view/210?keyword=&tag=&tagNames=&user=&offset=0&group=&groupNames=)を考えました。

![attached_sample1](https://cloud.githubusercontent.com/assets/15374413/12342935/9a6f892a-bb72-11e5-8a48-dc2b20fd92a8.png)

上記のように、画像以外の添付ファイルは外部リンク(<a>タグ)のように表せると、記事の見出し部分に添付ファイルを表示する必要がなくなり、記事の見た目がすっきりすると思います。如何でしょうか。

**Comment by koda-masaru** [comment]
本文の中にリンクを表示すると、見た目はすっきりしますね。
後はどのように、添付ファイルのリンクを、本文に埋め込むかの方法を考えないといけません。

すでに、ご利用中のユーザで、添付ファイルを付けてある投稿が多くあります。
これを「全て編集しなおして、添付ファイルを本文中にリンクを書いてください」とは言えないので、自動で本文に入れる必要があります。
そうすると、どこに入れるかというのが課題になるかと思います。

一番初めか、一番最後に自動で挿入という形になるかと思いますが、一番最後にすると目立たなくなり、添付ファイルに気づかないという事になるのが課題なんですよね。
（意外と、添付ファイルに気づかず情報共有漏れがあるので）

**Comment by nagodon** [comment]
こちら開閉式のデザインにするのは違う感じでしょうか？
デフォルトでは閉じてる状態にしてクリックすることで開かれて添付ファイルの一覧が観れるようなイメージです。

**Comment by johiroshi** [comment]
@koda-masaru さん
@nagodon さん

お返事遅れまして、ごめんなさい。

開閉式のデザイン、良いと思います。
添付ファイルは図1のように、件数が多くなればなるほど、見づらくなるので、まとまれば(図2参照)、ある程度見やすくなると思います。

**図1**
![knowledge 123](https://cloud.githubusercontent.com/assets/15374413/13388460/5e1ab0c6-df03-11e5-809f-8e51c4078c28.png)

**図2**：「▼」を押すと、添付ファイルが展開されて表示されるイメージ？
![knowledge 123_1](https://cloud.githubusercontent.com/assets/15374413/13388461/5e1b3500-df03-11e5-9be0-94652ad34dce.png)

**Comment by irgaly** [comment]
私の周囲での使われ方では、添付ファイルはあくまで資料であって、読ませたい情報はMarkdownに書き出すことが多いです。
@koda-masaru さんが当初から想定されている「添付ファイルそのものをKnowledgeとして扱い、簡単に共有・検索できる」という添付ファイルの使われ方とは異なります。
この添付ファイルに対する考え方の違いから、記事トップに添付ファイルを表示して目立たせる必要があるのかどうか、という議論があるように感じました。

個人的にはWikiの目次のように、記事の右上付近にfloat表示されていると、目立ちながらもMarkdown記事の邪魔にはならないので嬉しいです。

![fix-toc-ss0](https://cloud.githubusercontent.com/assets/1311446/13833406/f52e99a0-ec28-11e5-960f-e2993eb911c4.png)

別件ですが、添付ファイルも記事表示ページ内でインライン展開されるようになればとりあえず添付ファイルだけ
上げるという使い方も多用するかもしれないと思いました。 ( #172 のインライン表示ですね)

**Comment by koda-masaru** [comment]
v1.6.0 pre1でリリース済。クローズします。
リリースしたものに問題があれば、別途のissueを登録願います。
