### ISSUE TITLE
メール通知内のURL表記に誤り

### ISSUE THREAD

**Issue by johiroshi** [support-project/knowledge#127]
お世話になっております。

メール通知のURL表記内のIP部分に誤りが見られます。

- 使用用途：イントラネット内の情報共有
- 概要：サーバ構築時に使用していたIPアドレスが、サーバ構築後サーバのIPアドレスを別のアドレスに固定したにもかかわらず、通知メールに記載されているアドレスと変わりがない

以下は、メール通知の例です。

```

あなたの登録したナレッジにコメントが登録されました：13

http://192.168.0.222:8080/knowledge/protect.knowledge/view/13

------------------------------------------
here is content
------------------------------------------
------------------------------------------
※本メールはシステムより自動で送信されています。
 このメールに対する返信は出来ませんので御了承ください。

```

192.168.0.222は、サーバ構築時に使用していたIPですが、構築後、別のIPアドレス(192.168.0.102)に変更しました。
が、メール通知内のIPアドレスが、その変更に適応していないように見受けられます。

github、サーバ構築、などどれも初心者であるため、不適切な表現が含まれているかもしれません。ご迷惑をおかけしますが、ご対応よろしくお願いします。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

システムの管理者のメニューの中に、「システム設定」があり、システムのURLを変更できます。

はじめの起動時に、URLを自動設定するので、構築時のIPを保持していますが、変更できますのでお試しください。

**Comment by johiroshi** [comment]
ご対応ありがとうございます。

大変失礼しました。無事修正できました。

お手数をおかけしました。どうもありがとうございます。

**Comment by koda-masaru** [comment]
無事解決できたようで良かったです。

開発が楽しくて、機能説明などのヘルプをほとんど用意してないので分かりにくい事も多いと思います。

ご不明点などあれば、お気軽にお問い合わせください。

**Comment by johiroshi** [comment]
ありがとうございます。そう言っていただけると幸いです。

今後とも宜しくお願いします。

**Comment by koda-masaru** [comment]
対応が完了しましたので、クローズします。
