### ISSUE TITLE
クッキーを使ったログイン情報の保持

### ISSUE THREAD

**Issue by yoshimov** [support-project/knowledge#13]
現状はセッションが切れるとログインし直す必要がありますが、クッキーを使って数日間程度はログイン情報を保持していただけるとより使いやすくなるかと思います。

**Comment by koda-masaru** [comment]
なるほど。そうですね。
難しくはないので、後で機能追加しようと思います。

**Comment by koda-masaru** [comment]
作成してみました。
プレリリース（develop)で少し試して、問題なければmasterにマージします。

**Comment by yoshimov** [comment]
ありがとうございます！

**Comment by yoshimov** [comment]
0.4.2からpre-0.4.5にアップグレードしてみようとしましたが、どうもindexが表示されません。DBを元に戻して再チャレンジしてみます。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
う〜ん。なんでしょうか。私もあとで確認してみます。

このシステムでは、アプリケーションの起動時に、自動でDBのマイグレーションを実行しています。
その処理がうまくいっていないのかもしれません。
マイグレーション処理の結果はログでしか見れないので、結果を見れるようにした方が良いのかもしれませんね。

**Comment by yoshimov** [comment]
DBを元に戻して試してみたら正常に起動しました。シャットダウンの際にDBをクローズしていなかったのが原因のようです。

**Comment by koda-masaru** [comment]
いつもご連絡ありがとうございます。
現象が再現できなくて、原因がわからなかったのですが、
うまく動いたようで良かったです（＾＾

**Comment by koda-masaru** [comment]
いったんは問題なさそうなので、クローズします
