### ISSUE TITLE
ナレッジ一覧で宛先を表示

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#135]
ナレッジの「タグ」は、ナレッジ一覧で画面に表示していますが、
「グループ」は表示しません。
この場合、公開区分が「保護」としか表示していないので、
「保護」の場合は宛先を表示した方がわかりやすい。
（宛先は「グループ」や「ユーザ」になっている。）

**Comment by nagodon** [comment]
こちら対応しますね
