### ISSUE TITLE
行末にスペース2つを入力しなくても改行してほしい

### ISSUE THREAD

**Issue by 24appnet** [support-project/knowledge#139]
行末にスペース2つを入力しなくても、
編集画面で改行が入っていれば、反映してほしいです。

**Comment by nagodon** [comment]
こちらですが改行をそのまま改行として表現出来たほうがいいと思うので対応しますね。

**Comment by koda-masaru** [comment]
@nagodon ありがとうございます。お願いします。

**Comment by griffin-stewie** [comment]
github flavored markdown スタイルでは改行を `</br>` として認識しますね。

**Comment by koda-masaru** [comment]
#139 でMarkdownパーサーの修正を @nagodon さんが対応してくれたので、次バージョンでは改行が改行として反映されるようになります。

**Comment by koda-masaru** [comment]
v0.7.0 pre1 で対応済みです
