### ISSUE TITLE
表示されているタグに×ボタンがついているが、押しても何も起こらない

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#142]
利用しているライブラリの基本機能なのかと思いますが、×ボタンをはずせるならはずした方が良いかと思います。

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。

編集時には、「☓」を押すと設定したタグが消えるのですが、参照時だと消えない（何も起こらない）ようになっています。
ただ、ライブラリが「☓」を表示しているので、消しませんでした。

参照時には、編集時と同じライブラリを使う必要も無いので、ライブラリを使わないように変更して「☓」を表示しないようにする事を検討しようと思います。

**Comment by il-m-yamagishi** [comment]
:+1:

**Comment by koda-masaru** [comment]
v0.7.0 pre1にて対応しました
