### ISSUE TITLE
長いインラインコードが枠を突き抜ける

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#144]
![inline-code](https://cloud.githubusercontent.com/assets/15116901/11089459/3f0d7b16-88ad-11e5-8e90-02806021a01c.png)

普通ならば折り返されるのではないかなーと思いますので、ご一考お願いします。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

スタイルを変更すれば実現できると思いますので、折り返すようにしたいと思います。
（markdown.css の変更）

**Comment by il-m-yamagishi** [comment]
:+1:

**Comment by koda-masaru** [comment]
v0.7.0 pre1 にて対応済みです
