### ISSUE TITLE
新規記事投稿後に記事の閲覧ページに飛んで欲しい

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#145]
タイトルの通りです。ご一考願います。

**Comment by koda-masaru** [comment]
ご提案ありがとうございます。

この案についてはどのような画面フローが良いか、検討したいと思います。

といのも、私がナレッジを登録する際には、以下のようにすることが多いです

- 初めは「非公開（自分のみ）」にしておいて、ナレッジを編集する
    - 下書きのようなイメージ
    - 少し記事を書いたら「保存」しています（気軽に何度も）
    - このため、「保存」した後に閲覧ページに遷移すると、その後で、再度「編集」ボタンを押さなければならないたので面倒になる
- ナレッジがうまくかけたら「公開」にして保存しなおす
    - この際には、閲覧ページに遷移することでOK

----

ここまで書いて、ナレッジ編集画面に「下書き保存」機能があれば良い気がしてきました。
「下書き保存」の場合、そのまま編集画面を表示したままにして、
「保存」を押した場合には、閲覧ページに遷移するという案でいかがでしょうか？

上記のように、少し記事を書いて保存する欠点として、ナレッジの変更履歴に無駄な情報が多くなってしまう事があります。
この点でも、「下書き保存」は、変更履歴対象外とする事で無駄な履歴が保存されることを防げるので良いと思いました。

**Comment by il-m-yamagishi** [comment]
「下書き保存」「保存」を分ける案に賛成です!

**Comment by koda-masaru** [comment]
了解です。対応は、少し仕組み検討などが必要なので、少々お待ち下さい。

**Comment by griffin-stewie** [comment]
@il-m-yamagishi @koda-masaru 

個人的には `保存` という表現が曖昧に感じます。以下のような名称はどうでしょうか？

- `投稿` もしくは `公開`
    - 実際に公開範囲に基づいて公開される
- `保存` もしくは `下書き保存`
    - 公開はされず下書きとして保存される

**Comment by il-m-yamagishi** [comment]
@griffin-stewie `公開` / `下書き保存` 良いですね。

参考 : Qiitaだと `Qiitaに投稿` / `限定共有投稿` / `下書き保存` の三種類ですね。

**Comment by koda-masaru** [comment]
なるほど。
ボタンの名称は、いったん「公開」＆「下書き保存」にしようかと思います。

**Comment by koda-masaru** [comment]
対応完了済。
クローズします。
