### ISSUE TITLE
外部リンクに `target="_blank"` がない

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#151]
タイトルの通りです。bookmarkで作成したURLのみついてますが、他の記事中・コメント中のリンクが同一タブで開いてしまうので、 `target="_blank"` を追加して頂ければと思います。

**Comment by koda-masaru** [comment]
なるほど。たしかにそうですね。
簡単なのでスグ対応します。

**Comment by koda-masaru** [comment]
target="_blank" を付けるのは、外部リンクだけにしたほうがよいでしょうか？
内部リンク（knowledge内の別の記事など）へのリンクは、 target="_blank" を付けいない方が良いですか？

全てに付与するのは簡単（既に実装済み）なのですが、外部／内部と判定するのは、もう少し考えないといけないので、いったんご意見をいただければと思います。

**Comment by il-m-yamagishi** [comment]
@koda-masaru 内部リンクは同一タブの方がベターかと思いますが、別にタブ開いても問題ないかなー程度ですね。

**Comment by griffin-stewie** [comment]
ほかのサービスを使った所感ですが、同一ドメインでないなら別タブで開く印象があります。

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。

相対パスで始まるものを、同一ドメインと判定して、
httpから始まる場合はtarget="_blank"を付与して、
相対パスの時はつけないという案にしようと思います。

**Comment by irgaly** [comment]
:+1:

**Comment by koda-masaru** [comment]
v0.7.0 pre1 にて対応済みです
