### ISSUE TITLE
アカウントの情報表示

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#156]
ナレッジを登録したユーザの情報を表示する。

ユーザ情報には、以下を表示する。

- 今まで投稿した件数
- 「いいね」をもらった件数
- 「ストック」された記事の件数

以下は必要？

- 「いいね」をした件数
- その人の「ストック」
    - 「ストック」に「公開」「非公開」を持たせて、「公開」のものは表示
    - そのユーザ（≒有識者）がどんな情報をストックしたかがわかると、ちょっと便利？

**Comment by irgaly** [comment]
こちらの機能要望は「ユーザの情報もろもろにアクセスできるユーザページを作る」の話で良かったでしょうか？
もしくは、「記事ページへユーザ情報を表示する」というものでしょうか。

---

>「いいね」をした件数

いいねは何度も押せる仕様なので、何回いいねしたかはあまり意味がないように思います。

> その人の「ストック」
>        「ストック」に「公開」「非公開」を持たせて、「公開」のものは表示
>        そのユーザ（≒有識者）がどんな情報をストックしたかがわかると、ちょっと便利？

便利なので機能としてあっても良いと思いますが、あまり使う場面はない気はしました。
ストックの公開、非公開については、気持ちは分かるのですが、組織内の利用用途を想定した場合に非公開としたいものがあるのか...とは感じました。

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。

> 以下は必要？

と書いたものは、あまり表示する必要は無さそうですね。


- 今まで投稿した件数
- 「いいね」をもらった件数
- 「ストック」された記事の件数

を表示しようかなと思います。
