### ISSUE TITLE
記事保存時の「権限がありません」エラー

### ISSUE THREAD

**Issue by GtTmy** [support-project/knowledge#162]
記事保存時にまれに「権限がありません」というエラーが発生し，記事の保存が不可能になります．

ログインが解除されたわけではなく，他のページに移ってから記事を書き直すと保存できます．
どのような条件下で発生するかわかっていませんが，同じ記事を保存せずに長時間書いている場合に発生している印象です．

こちらの環境は
CentOS7, tomcat8, java8 ,postgreSQLで運用しています．

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
この問題が発生する原因は、たぶん、共同編集者から自分を消してしまって保存をした場合かと思います。
記事の作成者は、共同編集者に名前が無くても保存できるのですが、その他のユーザは編集画面に遷移後で、自分を編集者からクリアして保存しようとすると、権限がありませんのエラーになるかと思います。


書いていて、わかりづらいと思いましたので、なんらかの対策を検討しようと思います。

**Comment by GtTmy** [comment]
返信ありがとうございます。

自分自身で作成した記事にも発生しているので、別の原因だと思われます。
また、保存できない状況でもファイルアップロードは可能です。ただし記事が保存できないため、fileのindexは進んでいるようですが、参照できないファイルとなってしまいます。

**Comment by GtTmy** [comment]
firefox、chromeで同じ症状が確認できています。

**Comment by GtTmy** [comment]
状況を再現できました。

記事を新規追加後の画面(アドレスが/addになっている画面)での保存時に「編集権限がありません」と出るようです。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

不具合ですね。
次のリリースまでに対応したいと思います。

**Comment by GtTmy** [comment]
ご対応ありがとうございます．
解消されていることを確認いたしました

**Comment by koda-masaru** [comment]
ご確認いただきありがとうございます。
また何かあれば、ご指摘ください。

**Comment by koda-masaru** [comment]
v0.7.0正式リリース済みです。issueはクローズします。
