### ISSUE TITLE
tagやgroupの表示から各遷移先に飛びたい

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#177]
現状はリストや記事に表示されるtagやgroupはリンクではないですが
ここから絞り込まれたリストに飛べた方が便利だと思うのでリンクをつけたいです。

**Comment by koda-masaru** [comment]
はい。あったほうが便利だと思いますので、リンクをつけようと思います。

**Comment by koda-masaru** [comment]
v1.0.0pre1でリリース済み
