### ISSUE TITLE
閲覧履歴が表示されない

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#179]
## 事象
- 閲覧履歴が表示されない

## 環境とか
- Dockerコンテナで運用しています

- バージョン：v0.7.1pre1
- OS:CentOS6.6
- Dockerバージョン:1.5.0

- v0.6.1から使用させてもらっていますが、その頃から見えていません。

- 何か設定条件等ありますでしょうか。

（DEMO環境に登録された、問い合わせを転記）

**Comment by koda-masaru** [comment]
カンマ区切りの問題（ #164 ）が原因かも？とも思ったが別の原因かと思われる。

**Comment by koda-masaru** [comment]
@nagodon さんから助言

こちらなのですが、クッキーのパスがおかしくなってるせいかもしれません。
報告遅くなってしまったのですが社内も閲覧履歴がみれなくて調べてたらクッキーのパスが/ではなく/open.knowledge/viewになってました。
そのため参照できないようです。

**Comment by koda-masaru** [comment]
Cookieの処理を見直しました。次回のリリースに含めますので、それで様子を見ようと思います。

**Comment by nagodon** [comment]
私の環境では表示されるようになりました。
