### ISSUE TITLE
highlight.js のテーマを変えて欲しい

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#188]
コードのハイライト色はかなり個人の好き嫌いに左右されるものではあると思いますが、現状のデフォルトテーマだと、背景色が灰色系のため「記事の段落」なのか「ソースコード」なのかの区別が付きづらくなっています。

せめて背景色ダーク系にして、段落なのかソースコードなのかの区別が明確になればと思います。

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。

今、ちょうど、画面デザインについて、かなり大掛かりな変更を入れています。
コードハイライトについても、同時に検討しようと思います。

**Comment by koda-masaru** [comment]
v1.0.0pre1でリリース済み
