### ISSUE TITLE
メールの通知のリンクが、必ずログイン必須になっている

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#190]
#189 PRの議論から

「公開」のリンクをログインしないでも見れるようにした方が利便性は高い。

通知のリンクは、protectから始まるパス（ログインが必要）で通知しているが、
これをopenから始まるパス（ログインがいらない）で通知したら良いのではないか。

その場合、openのリンクでナレッジを表示した場合、

- 「公開」の場合はそのまま表示
- 「非公開」「保護」のリンクで、かつログインしていない場合、protectのパスにリダイレクトして、
ログインを促すといった変更をする
    - ログイン済みで、参照できる権限の場合、表示
    - ログイン済みで、参照権限が無い場合、表示しない（既にそうなっている）

**Comment by nagodon** [comment]
こちら対応してしまっても問題ないでしょうか？

**Comment by koda-masaru** [comment]
はい。対応できればお願いします。

**Comment by koda-masaru** [comment]
Release v1.1.0 リリースしました
