### ISSUE TITLE
ナレッジの一覧のタグ、グループの表示

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#208]
タグやグループのラベルにHOVERを設定して、押せる事を表しても良いかもしれません。

あと、タグやグループのラベルのデザインを変えたほうが見やすいかも。
タグはQiitaのように、右側が尖って、タグっぽくするなど。
タグとグループが見分けが付いたほうが、よりわかりやすいと思いました。

**Comment by nagodon** [comment]
なるほど。
見分けつけた方が良さそうですね。

デザインを考えてみようと思います。

**Comment by koda-masaru** [comment]
タグ／グループ／ストックの表示を変更してみました

#225 と一緒に対応

**Comment by koda-masaru** [comment]
v1.4.0でリリースしたため、issueはクローズします。
