### ISSUE TITLE
knowledgeのテーマでsandstoneを選ぶとメニューの文字が小さくなる

### ISSUE THREAD

**Issue by johiroshi** [support-project/knowledge#234]
knowledgeのテーマでsandstoneを選ぶとメニューの文字が小さくなりました。

**テーマ: sandstone(Local)**

![sandstone2 -](https://cloud.githubusercontent.com/assets/15374413/12192677/2ebf0546-b624-11e5-8734-e1a5dedabb81.png)

Live Demo でも同様の現象が確認できました。

ご確認、よろしくお願いします。

**Comment by koda-masaru** [comment]
これについては、テーマとして利用している、
bootswatch（ https://bootswatch.com/ ）の仕様なので、いったんはこのままになります。

bootswatchのサイトに、いろんなテーマがあったので、あの形にしたのですが、
Flatlyをデフォルトに、それのダークカラー版のDarklyで表示の調整をしています。
（プログラムを書く人は黒い画面が好きなものなのでDarklyも提供）

このため、選択肢はFlatlyとDarklyの2つのみとしたほうが良いかもしれません。

**Comment by johiroshi** [comment]
御返事ありがとうございます。
仕様だったのですね。。。それは失礼しました。

そうですね。２つに絞っても良いと思います。

**Comment by koda-masaru** [comment]
いえいえ。
どんなことでも、気になったときろは登録ください。

スタイルの2種類に絞ったりするのは、別途検討しますね。

スタイル切り替えを提供して、利用者に「このスタイルが好き」といった意見を聞こうと思っています。

**Comment by koda-masaru** [comment]
I close this Issue as no problem.
If there is a separate opinion on the style, I will register as another Issue.
