### ISSUE TITLE
編集履歴のユーザー・リンクがうまく機能しない？

### ISSUE THREAD

**Issue by johiroshi** [support-project/knowledge#235]
Live Demoに [Sample](https://support-project.org/knowledge/open.knowledge/view/174?keyword=&tag=&tagNames=&user=&offset=0&group=&groupNames=) を作りました。

以下のように、最終履歴のユーザー名とアイコンが一致していないように見受けられます。
記事作成者？のアイコンが残っているようです。

**記事閲覧画面**

![user_link -](https://cloud.githubusercontent.com/assets/15374413/12192976/33ecff84-b627-11e5-8af5-99213154c706.png)

**記事閲覧画面からユーザーで記事をフィルタリングした画面**

![user_link2 -](https://cloud.githubusercontent.com/assets/15374413/12192975/33e82c0c-b627-11e5-91f0-316692c80107.png)

Javaで直接直せなくてごめんなさい。現行が正しいのか判断できなかったのですが、ご確認お願いします。

**Comment by koda-masaru** [comment]
ご指摘ありがとうございます。

この問題については、すでに対応済みです。
次回のリリースで提供されますので、少々お待ち下さい。

**Comment by koda-masaru** [comment]
v1.0.0pre2で、修正しました。
お時間があるときにご確認願います。

**Comment by johiroshi** [comment]
すみません、対応済みだったのですね。気がつきませんでした。

Live Demoで確認しました。ご対応ありがとうございます。
