### ISSUE TITLE
ユーザー名に敬称をつけるべきか

### ISSUE THREAD

**Issue by johiroshi** [support-project/knowledge#236]
今日から、本格的に社内に導入しようか、とディスカッションをしていたのですが、その際に、『「ユーザー名」に「さん」などの敬称をつけた方が表現が柔らかくて良いのでは？』という意見がありました。

私は、「執筆者がわかれば良い」という方針だったので、全く気にも留めていなかったのですが、確かに日本人的には良いのかもしれない、と思い、お伝えさせていただきます。

**「ユーザー1」とする**

![san](https://cloud.githubusercontent.com/assets/15374413/12193151/ca02bb84-b628-11e5-96ac-3aae9df1b297.png)

**参考: サービス別の敬称比較**

サービス名  | 敬称
------------- | -------------
Facebook  | 「さん」
Google+ | なし
Instagram | なし
Twitter  | 「さん」
Qiita | なし

日本語へのローカライズをどれだけするか、という問題なのかもしれません。

**Comment by koda-masaru** [comment]
確かにそうかもしれませね。

ただ、「さん」を付けはじめると、その範囲が問題になりそうですね。
ユーザを指定して、一覧を絞り込んだ際にも、ユーザ名を表示しますし、
ナレッジの公開範囲や編集者の指定でもユーザ名が表示されます。
その全てで「さん」を付けるのはちょっと大変ですね。

ナレッジの一覧と表示画面のみ「さん」を付けるということでも良いかもしれませんが、、、、

いったん様子見でしょうか。

**Comment by griffin-stewie** [comment]
個人的にはユーザ名なので敬称とかは不要だと思っています。「さん」とかつけ出すと冗長というかノイズに感じます。

**Comment by koda-masaru** [comment]
@griffin-stewie さん

そうですね。
「さん」が無くても、システムの表示なので、失礼に感じるユーザも少ないと思います。

また、スマートフォンなど、小さな画面で見た場合には、余計な文字を入れない方が良いとも思いますし、いったん対応は見送りの方が良い気がします。

**Comment by johiroshi** [comment]
私も見送りに同意です。だいぶ細かい問題ですので、必要になったときで良いと思います。

**Comment by koda-masaru** [comment]
では、いったんは見送りといたします。
いったんissueはクローズしますね。
