### ISSUE TITLE
特定条件で保存又は更新すると記事が二重、三重に投稿されてしまう

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#239]
こちらちょっとまだ条件がわかってないのですが
作成より記事を保存後、手直しをして更新すると記事が新たに作られてしまうという現象が起きました。

引き続き調査いたします。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
原因がわかりましたら、ご連絡願います。
私の方でも調査してみようと思います。

**Comment by koda-masaru** [comment]
しばらく見守っていましたが、同じ現象の報告が無いため、いったんクローズします。

同様の現象が発生たした際に、再度issue登録か、ReOpenします。
