### ISSUE TITLE
カテゴリ分け

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#241]
Knoeledgeのデモサイトに登録されている意見から

---

大カテゴリ、中カテゴリ、小カテゴリというようにツリー形式でカテゴリ設定はできないでしょうか？
できれば、ビジュアルで見える化されていると使いやすいのですが。

https://support-project.org/knowledge/open.knowledge/view/178

**Comment by koda-masaru** [comment]
カテゴリ表示を行うとしたら、どのように行うかは検討が必要だと思います。
WindowsのエクスプローラーのようなUIで、細かく分けれるシステムを利用した事があるが、
逆に細かく分けすぎて、どこに情報があるのか分からなくなっていて不便だった記憶があります。

**Comment by griffin-stewie** [comment]
階層構造を持たせたいなら Wiki でいいと思ってしまいます。Knowledge の良いところは階層構造を意識しなくて良い点だと感じています。

**Comment by johiroshi** [comment]
同意です。

**Comment by koda-masaru** [comment]
では、いったん今のところは、カテゴリ分けについては無しにしようと思います。

**Comment by nagodon** [comment]
同じく同意です。

**Comment by koda-masaru** [comment]
カテゴリ化（階層型での構造化）は対応予定が無いのでクローズ
