### ISSUE TITLE
編集権限の有無を表示してほしい

### ISSUE THREAD

**Issue by johiroshi** [support-project/knowledge#244]
# 背景

自分に編集権限がない場合、

- 記事を編集するためのボタンはどこにあるのか -> 表示されていないから見つけられない
- なぜ「記事を編集」ボタンがないのか -> 編集権限がないから表示されていない

がわからないので、その旨を示唆する内容を表示してほしいです。

**編集権限があるときの画面(ユーザー1でログイン)**

![user1](https://cloud.githubusercontent.com/assets/15374413/12320094/eeb662a8-bae9-11e5-9c7c-6e71fe5bee3d.png)

**編集権限がないときの画面(ユーザー2でログイン)**

![user2](https://cloud.githubusercontent.com/assets/15374413/12320093/eeb09ee0-bae9-11e5-9fa2-d21e418b0678.png)

# 対案

たとえば以下のように。

![join_group_to_edit](https://cloud.githubusercontent.com/assets/15374413/12320229/d87dc322-baea-11e5-88e1-53b5f3e2f1ed.png)

よろしくお願いします。

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。
編集権限が無い場合は、それがわかるような表示を検討したいと思います。

**Comment by johiroshi** [comment]
ありがとうございます。よろしくお願いします。

**Comment by koda-masaru** [comment]
対応が完了したのでクローズします。
