### ISSUE TITLE
タグやキーワードによるフィルタリング機能が強化してほしい

### ISSUE THREAD

**Issue by johiroshi** [support-project/knowledge#245]
#42 より新しく立てました。

社内の利用者より、検索に対する機能要望です

- タグの複数選択機能
- Github のような ```is:issue is:open```などのコマンド

などで、「タグやキーワードによるフィルタリング機能が強化されると嬉しい」という声がありました。

**タグの複数選択機能**

![search_with_more_tag](https://cloud.githubusercontent.com/assets/15374413/12320640/0f48d5b6-baed-11e5-8136-a1c65bd65d3f.png)

コマンド検索は #105 でも言及されていましたが、```tag:tag_name``` のような形で既に使えるのでしょうか。

よろしくお願いします。

**Comment by koda-masaru** [comment]
タグの複数指定の検索は既に機能があります。
メニューの「詳細検索」から、タグを複数／グループを複数＋キーワード検索で検索できます。

<img width="989" alt="2016-01-14 23 27 27" src="https://cloud.githubusercontent.com/assets/10343517/12326983/3fcec7a2-bb17-11e5-98df-3c1928ccd03c.png">

<img width="994" alt="2016-01-14 23 28 31" src="https://cloud.githubusercontent.com/assets/10343517/12326986/44b3ff30-bb17-11e5-9986-246547d7249f.png">

<img width="987" alt="2016-01-14 23 28 41" src="https://cloud.githubusercontent.com/assets/10343517/12326990/4cab1df4-bb17-11e5-8c6a-a7d3993f6ffe.png">

**Comment by koda-masaru** [comment]
操作マニュアルが無いので、わかりづらいですね。
そこで、今、オンラインの操作マニュアルを作成しています。

**Comment by johiroshi** [comment]
### マニュアルの件

ありがとうございます。FAQだけでもあると助かります。

### 要望の訂正

すみません、御返事を読んで、伝え方が悪かったと気づきました。先の要望に付け加えて

1. 記事一覧画面から行いたい（クリック数が可能な限り少なく）
2. その結果をわかりやすく表示して欲しい

ですが、つまり、どういうことかと申しますと、

**記事一覧画面から行いたい**

![search_like_github](https://cloud.githubusercontent.com/assets/15374413/12342221/d193cf94-bb6b-11e5-98b2-ff0de982cc73.png)

そして、その検索結果を、キーワード / タグ / グループなど、検索種別で分けて、**結果をわかりやすく表示して欲しい**

![more_tab](https://cloud.githubusercontent.com/assets/15374413/12342207/a7dc7bd8-bb6b-11e5-9246-c1b35268401d.png)

という要望でした。すみません、舌足らずでした。

しかし、ここまで書いて要望しすぎではないか、と思いました。

また、2つ目の画像の、検索結果の表示例のデザインもイマイチなので、すみません、保留でも大丈夫です。

**Comment by nagodon** [comment]
キーワード検索でも下記の方法で検索可能ですね。

`groups:(group1 group2) tags:(vim php) キーワード`

**Comment by johiroshi** [comment]
@nagodon さん

使えました！どうもありがとうございます！！
