### ISSUE TITLE
作成ボタンを押した時の挙動変更

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#247]
グループで絞って一覧を表示してる時に作成ボタンを押したら
デフォルトで公開範囲を保護にしてそのグループが選択してる状態にしたいという要望を受けました。

こちらグループに対して連続投稿する場合だと確かに今のUIだとちょっと辛いところが
あるのでこういう場合は自動で選択されててもいいかなと思うのですがどうでしょうか？

**Comment by nagodon** [comment]
#61 の暫定対応的な位置付けにはなるかなと思います。

**Comment by koda-masaru** [comment]
なるほど。良いかと思います。

グループで情報共有がデフォルトになっている運用の場合、公開範囲を毎回選択するのは面倒だと思っていました。

**Comment by nagodon** [comment]
ありがとうございます。
すぐ対応できるのでやってしまいますね。
