### ISSUE TITLE
編集中画面でのマークダウン表示が異常

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#253]
現在、 flatly, darkula テーマで編集画面を利用していますが、プレビューした場合

![ss_062](https://cloud.githubusercontent.com/assets/15116901/12437765/f79b29ac-bf63-11e5-901b-3d088b25ab79.png)

このように、背景色なしで文字色のみハイライトされるような状況になっています(今回は ```sql によりはじめましたが、他の言語を指定しても同様)。

また、右側に不要なスクロールバーも出ています。

![ss_063](https://cloud.githubusercontent.com/assets/15116901/12437810/8484d76e-bf64-11e5-8195-f24cbbc3962c.png)

正しくはこう表示されるかと思います(上記SSは投稿後の閲覧画面)。

スタイルの指定ミスかなと思いますので、修正をお願いします。

**Comment by koda-masaru** [comment]
ご指摘ありがとうございます。
たしかに、編集時のプレビューで、コード部のスタイルの指定が間違っていますね。
次のリリースで修正しようと思います。

**Comment by il-m-yamagishi** [comment]
:+1:

**Comment by koda-masaru** [comment]
Release v1.1.0 リリースしました
