### ISSUE TITLE
Google Analytics を導入出来るようにして欲しい

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#254]
Knowledgeはクローズドな環境に使われる想定だと思いますが、そのクローズドな中でも、どれだけのユーザーがどの程度閲覧しているかによって運用方法が様変わりします。

管理画面側に統計機能を実装することでもこの要件は満たせると思いますが、実装コストを考えると、非常に簡易に導入出来る Google Analytics が最適なのではないかと思います。

ご一考おねがいします。

https://www.google.co.jp/intl/ja/analytics/

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。

ご指摘のように、クローズな環境なのでアクセス解析は必要無いかなと考えていました。
でも、アクセス解析を使いたいという要求はありそうですね。

対応としましては、全ての画面に共通のJavascriptやHTMLを、管理者が登録出来るように
しようかと考えています。
そうすれば、GoogleAnalyticsを使いたい人は、それ用のJavascriptを埋め込めばよいですし、
その他のアクセス解析を使いたい人でも、多くの場合は対応できるのではないかと思います。

**Comment by il-m-yamagishi** [comment]
とても良い改善だと思います :+1:

**Comment by koda-masaru** [comment]
Release v1.1.0 リリースしました
