### ISSUE TITLE
共同編集時に編集不可能になる

### ISSUE THREAD

**Issue by GtTmy** [support-project/knowledge#256]
以下のような状況で記事が編集不可能になります。

1. ユーザーAが、ユーザーAとユーザーBを共同編集者として記事作成
1. ユーザーBが記事を編集し保存
1. ユーザーBの画面から、当該記事の編集ボタンが消える。
1. ユーザーAで確認すると、ユーザーBの権限が消えている。

条件があまり分かっておらず具体例での報告で申し訳ないのですが、よろしくお願いいたします。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
調べてみます。

**Comment by mitsugogo** [comment]
現地点の最新版v1.4.1でも再現しました。

1. ユーザーA（管理者）がユーザーBとユーザーCを共同編集者として記事作成
2. ユーザーBが記事を編集して保存
3. ユーザーBの編集権限が消失する

こちらも状況報告で申し訳ありませんが、よろしくお願いします。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます 🙇 
共同編集者の制御に不具合がありそうですので修正しようと思います。
私の環境では、共同編集者の機能を使っているユーザが少なく、対応が遅くなり申し訳ないです。

**Comment by koda-masaru** [comment]
Release v1.5.0 にてリリース済
