### ISSUE TITLE
グループにユーザを追加した際、追加されたユーザは一度ログインしなおさないとグループ投稿を見れない

### ISSUE THREAD

**Issue by raa0121** [support-project/knowledge#269]
表題の通り、グループにユーザを追加すると、右側のメニューにグループの項目は増えるのですが、
ログインしなおさないとそのグループの投稿・投稿一覧が閲覧できない状態となってます。

お手数ですが、ご確認よろしくお願いします。

**Comment by koda-masaru** [comment]
ご指摘ありがとうございます。

確かに、現在はログイン時点でユーザが属しているグループを取得し、それを保持しています。
（あまり所属しているグループが変更することは無いと思ったので、毎回取得しないようにしていました。）

ただ、メニューなどは再度取得しており、閲覧時の権限チェックだけ保持したままにするのも変なので、修正しようと思います。
