### ISSUE TITLE
タグの文字が数値文字参照に化ける

### ISSUE THREAD

**Issue by D4prog** [support-project/knowledge#271]
はじめに、`Let's Encrypt` というタグがあるとします。
ナレッジの記事の投稿、編集画面でタグを追加するときサジェストが出ますが、このサジェストで`Let's Encrypt` を選んで追加しようとした場合、`Let&#39;s Encrypt` となります。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
文字列のエスケープ処理の問題かと思います。
修正しますので、少々お待ち下さい。

**Comment by koda-masaru** [comment]
#720 のMRにて修正済でしたが、issueヲクローズし忘れていました。
クローズします。
