### ISSUE TITLE
外からアクセスできるべきリソースまで認証が必要になっている

### ISSUE THREAD

**Issue by D4prog** [support-project/knowledge#272]
ログアウトして登録されていない閲覧者としてサインインページを開いたときのことです。

システム設定で **全ての機能には、ログインしないとアクセス不可** となっている環境で、
`/open.account/icon/` を取得できずに画像が出なくなっていました。

**Comment by koda-masaru** [comment]
ご指摘ありがとうございます。確かにそうですね。
修正しようと思います。

**Comment by koda-masaru** [comment]
Release v1.1.0 リリースしました
