### ISSUE TITLE
記事詳細のtitleタグで記事タイトルを先頭に表示してほしい

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#277]
#186 に類似するかもですが、複数タブを開いてる時に記事タイトルが先頭に来てないと
見た目でどの記事を開いてるわからないので記事タイトルを先頭に持ってきてほしいという要望を受けました。

**Comment by koda-masaru** [comment]
了解です。
ちょっと変更すればできると思います。
対応しましょう。
