### ISSUE TITLE
TOPページをカスタマイズしたい

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#278]
#186 に類似するかもですが、TOP(index)ページをカスタマイズできるようにしてほしいという要望を受けました。

**Comment by koda-masaru** [comment]
#186 と確かに似ている要望かと思います。

どのように実現するのが良いでしょうか？

/knowledge/src/main/webapp/WEB-INF/views/index/index.jsp
の内容（HTML）を全て管理画面で変更できるようにすればよいですかね？

**Comment by nagodon** [comment]
> どのように実現するのが良いでしょうか？
> 
> /knowledge/src/main/webapp/WEB-INF/views/index/index.jsp
の内容（HTML）を全て管理画面で変更できるようにすればよいですかね？

おそらくそうなるかなと思っています。

**Comment by koda-masaru** [comment]
#186 で対応済です。
トップページのHTMLを、管理者が変更できるようにしました。
