### ISSUE TITLE
一覧右のグループやタグをクリックした場合は、検索窓に条件を入れておいてほしい

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#279]
Githubなどと同じくグループやタグを選択してる時は検索窓にそれぞれの条件を入れておいてほしいという要望を受けました。

**Comment by koda-masaru** [comment]
要望承りました。
順次対応していきましょう。

どのように実現したら良いか考えてみると、検索している内容などは、
リクエストスコープでパラメータを引き回していたのですが、
セッションに登録してしまって、各画面で表示するようにしても良いかもしれませんね。

**Comment by nagodon** [comment]
> どのように実現したら良いか考えてみると、検索している内容などは、
> リクエストスコープでパラメータを引き回していたのですが、
> セッションに登録してしまって、各画面で表示するようにしても良いかもしれませんね。

セッションでもいいかもしれないですね
ただリクエストパラメータから選択してるものは取れるので一旦そちらから拾うようにしようと思います。
