### ISSUE TITLE
グループやタグを選択してる場合、右のメニューのそれぞれをハイライトしてほしい

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#280]
一覧の表示されてるもの限定にはなりますが、選択してるグループ、タグを一覧のhover時見たくハイライトしてほしいという要望を受けました。

**Comment by koda-masaru** [comment]
少しイメージがわきませんでした。
右側にある、グループやタグの一覧の中で選択しているものを色付けしてわかりやすくする
というコトでしょうか？

**Comment by nagodon** [comment]
> 右側にある、グループやタグの一覧の中で選択しているものを色付けしてわかりやすくする
というコトでしょうか？

はい、そうなります。
