### ISSUE TITLE
UI/UX改善要望

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#281]
UI/UXの改善要望を受けたので一旦まとめissueとさせていただきます。
#### 編集画面
1. 本文のテキストエリアの高さをもう少し長めにしてほしい  
     自身でリサイズできるが初期状態でもう少しあった方が書きやすい
2. プレビューボタンが本文と離れすぎてるのを改善してほしい  
      Githubのpreviewなど見たく本文の上にタブとしてあると編集しやすい
3. 公開対象はボタンなのにタグ選択はなぜかリンクなので統一感を出してほしい
4. Markdown supportedやタグ一覧のリンクをcursor: pointerにしてほしい
5. 縦に長くなりすぎていて編集しにくいためもう少しコンパクトにしてほしい  
     要素が全てwidth:100%のため縦に長くなりスクロールする必要がある
#### 記事詳細画面
1. 引用のfont-sizeをもう少し小さくしてほしい
#### ナビゲーションバー
1. ナビゲーションバーのボタンの色合いを調整してほしい  

議論すべきものもあると思うのでこのissueで検討していければと思います。

**Comment by koda-masaru** [comment]
issue登録ありがとうございます。
特に編集画面については、変更したいと思っていたのですが、
時間が取れずに変更できていないという感じです。
（#83 に登録はしていました）
上の要求を踏まえて、どのような画面にしていけば良いか決めていきましょう。


詳細画面の「引用」とは何を指しているでしょうか？
```
 [oembed https://github.com/support-project/knowledge]
```
の表示部分のことでしょうか？

ナビゲーションバーのボタンの色は、具体的にはどんな色合いだと良いでしょうか？
（デザインセンスに乏しいので、どんな色合いだと良いか意見が欲しいです）

**Comment by nagodon** [comment]
すいません、返事遅くなりました。

引用はmarkdownの引用のことですね。
ナビゲーションバーのボタンに関してはちょっと検討しますね。

レイアウトちょっと考えてみますね。

**Comment by koda-masaru** [comment]
はい。よろしくお願いします。

**Comment by koda-masaru** [comment]
編集画面のデザイン変更はv1.2.0で対応されました。
その他の部分はv1.3.0以降で検討しましょう。

**Comment by nagodon** [comment]
> 編集画面のデザイン変更はv1.2.0で対応されました。
> その他の部分はv1.3.0以降で検討しましょう。

了解しました。

**Comment by koda-masaru** [comment]
レイアウトや、ナビゲーションの色など、もろもろがissue登録した時点から更新されていますので、いったん本Issueはクローズします。
UI/UXに関しては、まだまだ改善の余地が多くあると思いますので、気になったところなどは、また、別のIssueで登録願います。
