### ISSUE TITLE
バージョン番号の表示

### ISSUE THREAD

**Issue by irgaly** [support-project/knowledge#282]
以前は左上にKnowledgeのバージョン番号が表示されていましたが、現在は表示されていません。
アップデート作業後に、アップデートされていることを確認できる場所がないので、WebUIのどこかでバージョン番号が確認できると嬉しいです。

* フッターへ表示？
* 管理画面へ表示？

**Comment by koda-masaru** [comment]
バージョン番号は、「一般のユーザには見せなくても良いのでは？」という意見から、
ヘッダーのような目立つ所に表示することをやめています。

しかしながら、私も確認するところが欲しかったので、画面のフッター部にある
「ライセンス」のリンクで遷移すると、バージョンを表示しています。

目立たないところですが、確認ください。

**Comment by irgaly** [comment]
ありがとうございます。そんなところに移っていたんですね、失礼しました。
ライセンス画面にてバージョン情報を確認できました。
issueはクローズいたします。

**Comment by koda-masaru** [comment]
確認ありがとうございます

**Comment by koda-masaru** [comment]
ちなみに、、、、

「気づくわけ無いじゃん！！」というレベルなのですが、
ソースの中に、HTMLのコメントで

```
<!-- Knowledge - v1.1.0 -->
```

と書いてあったりもします。ご参考までに。
