### ISSUE TITLE
記事のお気に入り機能

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#3]
- 気に入った記事をお気に入りに入れておく
- あとで見返すのが楽になると良い

**Comment by griffin-stewie** [comment]
:+1:

**Comment by akai-inu** [comment]
:+1:

**Comment by koda-masaru** [comment]
:+1:  が2ついたので、なるべく早く提供できるように頑張ります。

期の変わりなどで、あまり時間がとれずすみません。。。（←言い訳

**Comment by koda-masaru** [comment]
### 作業メモ

#### 出来た内容

- ストックにナレッジを登録できるようになった
- ストックに登録されたナレッジの一覧を表示できるようになった
    - 一覧から登録されているナレッジを参照できる
- ストックはユーザ毎に一つでは無く、フォルダのような形で管理するようにした（何個でも登録できる）
    - 「タグ」はナレッジの登録者が付与することにしている
    - 参照者が、例えば「Javascriptのお気に入りの記事のストック」「Dockerのお気に入りの記事のストック」といった形で種類分け出来ると便利かと思ったのでそうしている

#### TODO

- ナレッジに、ストックされた件数を表示
- ナレッジからそれがストックされている一覧へ遷移
- あとどんな機能があれば使いやすいかなぁ、、、

**Comment by koda-masaru** [comment]
- ナレッジに、件数表示を後で追加しようと思います
- 別issueで管理するので、本issueはクローズします
