### ISSUE TITLE
検索欄で「*」または「?」を先頭に入れるとエラーになる。

### ISSUE THREAD

**Issue by kurehajime** [support-project/knowledge#300]
## バージョン

v1.1.0

## 現象

記事検索の際、キーワードの先頭に「*」または「?」を入力すると、Internal Server Errorになる。
先頭以外では再現しない。スペース区切りで2つ目のキーワードに先頭「 * 」「?」を入れた場合でも発生。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
先頭に「 * 」「?」を入れると、全文検索エンジンのLuceneがエラーになりました。
「 * 」「?」が先頭にあった場合、それを削除して検索しようと思います。
