### ISSUE TITLE
データのエクスポート

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#31]
- 使い続けていくうちに自分に合わないと感じるかもしれない。別のシステムに移りたい場合にどうやってデータを取り出したら？
- Exportがあれば安心して仕事で使える。

**Comment by koda-masaru** [comment]
次のリリースで出す予定。

**Comment by griffin-stewie** [comment]
:+1:

**Comment by koda-masaru** [comment]
0.5.1 pre1でデータエクスポートを作ってみました。
いったん、管理者機能にしたので、管理者でログインするとデータを全てエクスポート出来ます。

**Comment by koda-masaru** [comment]
一般ユーザで、自分のデータをエクスポートする機能があっても良いかも。
その機能もすぐできそうなのでつくろうかな。

**Comment by yuann** [comment]
逆に、インポート出来る機能もあればいいかも知れません。
似たような別のシステムから移行したい場合に便利だと思います。
（他システムからのエクスポートデータのコンバートが必要ですが）

**Comment by koda-masaru** [comment]
たしかに、インポート機能はあっても良いですね。

移行元システムのエクスポートデータを変換する際には、
たぶん、プログラムを作らないといけないと思います。
だとすると、RestAPIを公開してそこからインポートでもよいのかもしれませんね。

インポート機能については、別のissue ( #36 ) に登録しました。
