### ISSUE TITLE
表示されている投稿日時が正しくない

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#311]
投稿一覧と投稿の詳細ヘッダーにおいて、

![ss_141](https://cloud.githubusercontent.com/assets/15116901/13483222/da6b8cca-e135-11e5-8c32-ba7d2d8fd6a8.png)
![ss_138](https://cloud.githubusercontent.com/assets/15116901/13483224/de361226-e135-11e5-9317-7ba66fab9ff7.png)

`2016/03/03 10:29 に投稿` と表示されていますが、編集履歴を見ると投稿日時は `2016/02/24 12:27` で、最終更新は `2016/02/24 12:59` となっていました。

この `2016/03/03 10:29` という時間は

![ss_140](https://cloud.githubusercontent.com/assets/15116901/13483250/30715212-e136-11e5-9a93-71b7dd2e776c.png)

コメントによる更新の日時によるものかと思いますが、これは投稿日時でも更新日時でもないので `2016/03/03 10:29 に投稿` ではなく `2016/03/03 10:29 に更新` とするか、正しい投稿日時を表示するように修正すべきと思います。

他の記事でも同様のケースが見られましたので、記事単体の問題ではないようです。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
私も投稿日時がおかしくなる（？）と感じることがあったので、ご指摘の通りかと思います。
原因を調べて、おかしくならないようにしますね。
