### ISSUE TITLE
データの保存先を変更

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#32]
- Windows環境で使っているのだが、データの保存先がシステムドライブなのがちょっと困る。
- 環境変数等でデータドライブに保存先を変更するようにできないだろうか。

**Comment by koda-masaru** [comment]
簡単なので対応中。
次のリリースで出します。

**Comment by koda-masaru** [comment]
0.5.1 pre1 で環境変数でデータの保存先変更に対応してみました。
「KNOWLEDGE_HOME」を環境変数に指定すると、そこに指定したディレクトリのパスにデータを保存します。

**Comment by yuann** [comment]
早速の対応ありがとうございます。Windows 7 環境で動作することを確認しました。

問題では無いのですが、階層が１段深いような気がします。
GitBucketやJenkinsでは環境変数で設定したディレクトリの直下にデータが格納されますが、knowledgeでは更に「.knowledge」ディレクトリを作成してその中にデータを格納しているようです。

**Comment by koda-masaru** [comment]
なるほど。それもそうですね。
では、次のリリースでは環境変数のディレクトリに直接データを格納するように変更します。
（環境変数が指定されていれば「.knowledge」ディレクトリは作らないようにする）
