### ISSUE TITLE
リバースプロキシへの対応

### ISSUE THREAD

**Issue by ars096** [support-project/knowledge#340]
リバースプロキシを介して Knowledge にアクセスさせようとしています。
おおむねリバースプロキシ側の URL で問題無く動いているのですが、ログイン時とコメント投稿時に、URL が Knowledge 側のホスト名に変わります。(フォームの submit を押すタイミング？)

クライアントは Knowledge サーバーへ直接アクセスできないので画面は更新されずに止まるのですが、別の画面 (投稿一覧など) へは逃げることができて、その後確認すると操作は正常に完了しているので、騙し騙し使い続けることはできています。

構成：

- リバースプロキシ
 - Apache + mod_proxy
 - ホスト名 : myhost
 - https://myhost/knowledge を http://192.168.x.x/knowledge に転送
- Knowledge
 - v1.3.1 (docker-knowledge を使用)
 - ホスト名 : 192.168.x.x
 - /usr/local/tomcat/webapp/ROOT.war を knowledge.war に名前変更

**Comment by koda-masaru** [comment]
たぶん、以下の手順で解決すると思います。

Knowledgeに管理者でアクセスするとか右上のメニューに「システム設定」のメニューが表示されます。
そのメニューの中に、さらに「システム設定」のメニューがあり、そこでシステムのURLを設定するようになっています。
このURLが192.168.X.Xになっていると思われるので、それをmyhostに変更してみてください。

**Comment by ars096** [comment]
早速のコメントありがとうございます。

管理者ログイン - システム設定 - システム設定 - サービスのURL は、すでに https://myhost/knowledge と変更していました。
ただ、「保存」をクリックしただけだったので、念のため、データベースサーバーを停止したあと、docker を再起動してみました (docker stop, docker start) が、同じ症状を再現します。

また、https://myhost/knowledge にアクセスした際に、https://myhost/knowledge/index へリダイレクトされると思いますが、ここでも http://192.168.x.x/knowledge/index へと渡されていました。

**Comment by koda-masaru** [comment]
サービスのURLがまちがっていないとなると、リバースプロキシの設定を見直すと良いかと思います。
少し調べてみましたが、ProxyPassReverseで、リダイレクト時のLocationを変換するのだと思います。

以下のURLは参考になりませんか？
http://hogem.hatenablog.com/entry/20091205/1260023908

ちなみに、私はリバースプロキシはNginxで構築して、同じくdockerでknowledgeを起動しています。
その環境では正常に動いているため、JavaやTomcat側で何か設定が必要ということは無いと思います。
私も「管理者ログイン - システム設定 - システム設定 - サービスのURL」の操作以外は何もしていませんので。

**Comment by ars096** [comment]
ご指摘の通り、ProxyPassReverse を設定していませんでした。
不勉強でお手数をおかけしてすみません。。。
参考になる URL もありがとうございます。

最終的に以下の設定でちゃんと動きました。
```
<Location /knowledge/>
  ProxyPass http://192.168.x.x/knowledge/
  ProxyPassReverse http://192.168.x.x/knowledge/
</Location>
```

**Comment by koda-masaru** [comment]
設定できたようで安心しました。
解決したようですのでクローズいたします。
