### ISSUE TITLE
masterブランチをビルド可能状態に保っていただけないでしょうか

### ISSUE THREAD

**Issue by yatszhash** [support-project/knowledge#343]
#331 で触れられているように、現在ローカル環境ですとmvn packageでビルドができません。

CIでビルド成功しているので微妙なラインですが、
oss開発ポリシーとして、masterを常にビルド可能状態に保っていただけないでしょうか。

場合によっては、masterのバージョンを戻すことも必要かもしれません。

**Comment by koda-masaru** [comment]
基本的にはmaaterはリリースするさいにマージしているのでbuildできる状態にすでになっています。

SSLの問題でbuildできないといわれた、 #331 のバージョンも、「お金」さえ払って有料の証明書を買えば警告も出ないので、ソースとしては問題ありません。SSL証明書をインポートすればbuildできますしね。

ただし、今後も、お金がかかるようなときは、問題ですね。。。

**Comment by yatszhash** [comment]
勘違いかもしれないのですが、#331にあったnokokさんが投稿された"SNAPSHOTが見つからない"問題は
現在のmaster(developではなく）では起こらないはずということでしょうか。

現在の最新のmasterをビルドしましたが、同じエラーがでました。

**Comment by koda-masaru** [comment]
はい。最新の master はbuild出来る状態になっています。

nokokさんも

> 諸々ご対応ありがとうございます。こちらでもビルドができました。

と回答しています。SNAPSHOTは、Maven Central Repository からではなく、SNAPSHOT用のリポジトリに登録されるので、masterブランチでは、そのリポジトリを参照するように設定しています。
http://oss.sonatype.org/content/repositories/snapshots

ちなみに、

> masterのバージョンを戻すことも必要かもしれません。

と書いていますが、バージョンを戻しても、buildはできません。サーバーのSSLの証明書の問題なので、ソースを戻せば直るという類の問題では無いからです。

**Comment by koda-masaru** [comment]
依存ライブラリをMaven Central Repositoryに登録しました。
たぶん、これでビルドできると思います。
いったんissueはクローズします。
