### ISSUE TITLE
ページでの通知機能

### ISSUE THREAD

**Issue by ars096** [support-project/knowledge#349]
機能要望です。

ログイン後のページの、「作成」、「一覧」、「メニュー」が並んでいるところに、「通知」はつかないでしょうか？Qiita の「お知らせ (通知？)」のような機能です。Qiita のように、通知の累積数が出るととても便利かと。

次のような業務フローを考えています：
- 想定している環境
  - ユーザー数 : 30名程度
    - よく投稿するユーザー : 10-20 名程度
    - よくコメントするユーザー : 10 名程度
  - 投稿数 : 10-20 件/日
  - 投稿の編集頻度 : 投稿数と同程度
- 投稿者の流れ
  - 新しい記事を投稿する
  - 記事へのレスポンスを、通知を通じて確認
    - ストック、いいね：着くとうれしいのでモチベーションが上がる
    - コメント : 投稿内容についての議論が深まる
    - 通知数が多くなってくると、メールやデスクトップ通知、自分で自分の記事を巡回するのは手間。できれば Knowledge のページ内で完結させたい。通知の累積と履歴が見れるとラクそう。
  - コメントを受けて、内容を編集、再投稿する
- 閲覧者の流れ
  - 一覧や検索、タグなどを巡回して記事を閲覧
  - 記事へのアクションを起こす
    - いい内容だと思ったら、いいね
    - 記事の更新やコメントなど今後の流れをウォッチングしたければ、ストック
    - 内容について気になる事 (間違いの指摘や、改良の提案など) があれば、コメント
      - コメントと同時にストックもしておく
  - コメントした記事が編集されたら、通知を通じて確認
    - 編集内容について、さらにコメントをするかも

要望をまとめると：
- 通知機能をページへ実装してほしい (Qiita の通知のようなもの)
  - 未確認の累積数、履歴を確認できる
  - 何を通知させるかカスタマイズできる
- 一覧ページは、新規投稿時刻でソートしてほしい
  - 現状は最終更新時刻でソート

過去 issues を見てみると、Knowledge とは？みたいなことも議論されているようなので、私の抱いている Knowledge に期待している役割、というか私の抱えている問題についても書いてみたいと思います。これを解決してくれるならうれしい、という個人的な意見ですが。。。
- 組織の情報を共有したい
  - ドキュメント化されるべきだったのだが、残念ながら、まだされていない情報も集めたい (そのような情報は、必要に迫られるまで気づかないことが多い)
- ある情報について、よく知っている人と、あまり知らない人、がいる
- よく知っている人は、たいてい忙しい
- 記事を新規に書くには手間がかかる
- 出来上がった記事 (完成度が完璧でなくても) にコメントするだけなら、いくらかラク

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。
「通知」はメールやデスクトップ通知で考えていましたが、↑のフローを見ると、
確かに通知の一覧がKnowledge上で時系列などで見れると良い気がしました。
機能追加を検討します。

**Comment by koda-masaru** [comment]
Knowledgeとは？という議論ですが、なかなか利用している皆さんが納得する回答は出せないのですが、私のグループでは以下のように、私から以下のように言って導入を進めています。

-----
■ 導入の際の説明

- 組織の情報を共有したい（個人の知識を、組織の知識へ）
- でも、そのために、余計な労力をかけたくないよね？
    - **よく知っている人は、たいてい忙しい** (その通り!）
- 既に共有すれば有益な「資料」は各自で持っていると思う
    - 検証結果や手順書など技術情報をまとめたものなどいっぱいある
    - Excel、Word、PowerPointが多い
- 記事には何も書かなくて良いから、資料だけKnowledgeに添付すれば皆が見れるよ！
    - 共有フォルダは後から探せない
    - バイナリファイル(ExcelやWord)はGitなどに登録しても、やっぱり探しづらい
    - Knowledgeにあげた資料は、中に書いてある内容で「検索」できる！！
- 出来る限り簡単に共有できるようにしたから、使ってみてください！

**Comment by koda-masaru** [comment]
いったん、メールで通知している内容を、Knowledge内で見れるようにしてみた。
メール送信を行っていない環境などで便利だと思う。

**Comment by koda-masaru** [comment]
This is supported by v1.11.0.
I will close this.
