### ISSUE TITLE
How can I sign in as administrator?

### ISSUE THREAD

**Issue by XGiton** [support-project/knowledge#354]
Hi, handsome boy, I am xgiton. I'm running this project in docker and everything is OK. But how can I sign in as a administrator. Thanks!

**Comment by koda-masaru** [comment]
Hi,

You can sign in as a administrator with this id and password.

```
id: admin
password: amin123
```

Also, please read this page about initial setup.

https://support-project.org/knowledge_info/open.manual/page/setup

**Comment by griffin-stewie** [comment]
@koda-masaru
Can you write this setup page URL on wiki in this repo?
It was hard to find this information before.

**Comment by koda-masaru** [comment]
@griffin-stewie 
Thank you for your advice.
I will write this information on wiki page.

**Comment by XGiton** [comment]
@koda-masaru Thank you! It works now.(*^__^*) ……

**Comment by koda-masaru** [comment]
I'm glad it worked 😄
