### ISSUE TITLE
添付ファイルの画像が表示されない

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#364]
アップロードした画像を表示するようにしたが、画像が表示されないことがあった。

調べてみると、DBの添付ファイルのテーブルの、knowledge_idが空になっていた。
それを設定したら表示できたが、なぜ空になってしまったかを調査して、修正する。

**Comment by il-m-yamagishi** [comment]
1. 任意の記事のコメント欄、または投稿の編集ページ
1. 「ファイルを添付する」を押す、またはドラッグアンドドロップで記事にファイルを添付する
1. 「コメントの追加」や「記事の保存」ボタンを押して投稿を更新 **せずに** ページ遷移する

以上の手順で、

- 記事の添付ファイル一覧に掲載されない
- アップロード者は直接 `/open.file/download?fileNo=xxx` を叩けばダウンロード出来る
- アップロード者以外は直接叩いても `Not Found` と表示される

という状態になりました。

ファイル添付時に `ファイルがアップロードされました` という通知が出るので、その段階で記事に紐付いたと誤認してしまうケースがあるのではないかと思います。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

記事に紐付いていない場合、アクセス権がわからないため、そのファイルをアップロードした人にのみダウンロードできるように制御しているのですが、それが原因になっていそうですね。
（保存すれば、添付したナレッジのIDがわかるので、そのナレッジの公開範囲に沿ったアクセス権制御になります）

たぶん以下のオペレーションで現象が発生したと思います。

- Knowledge作成画面を表示
- 画像ファイルをアップロードし、Markdownの中に画像を埋め込む ``` ![画像](/open.file/download?fileNo=xxx) ```
- 編集していた記事のMarkdownをマークダウンエディタなどにコピペ
- Knowledge作成画面を保存せずに閉じる（アップロードしたファイルはナレッジと紐付かない）
- 再度、別のタイミングでKnowledge作成画面を表示し、マークダウンエディタから貼り付け
- Knowledgeを保存
    - 先ほどアップロードした画像ファイルは、このKnowledgeの画面でアップロードしたわけでは無いので、保存したKnowledgeに紐付かない
- 投稿者は、アップロードした本人なのでファイルが見えるが、その他のユーザは、画像を見えない


アクセス権の制御としては、正しいような気がしますが、投稿者（アップロードした本人）は、自分以外は添付ファイルを表示できないことに気づけないのは問題ですので、何か対策がないか考えようと思います。

**Comment by koda-masaru** [comment]
添付ファイルを登録したときに、下書き保存を実行しておけば、添付ファイルの制御がうまくいく
ような気がしました。
いったん、その形にしてみようと思います。

**Comment by koda-masaru** [comment]
v1.10系でリリース済。クローズします。
