### ISSUE TITLE
質問：添付ファイル内の文字列を検索

### ISSUE THREAD

**Issue by IsSenseAG** [support-project/knowledge#365]
ナレッジを検索する際に、添付ファイル内の文字列も含めて検索するような機能はあるのでしょうか？

**Comment by koda-masaru** [comment]
@IsSenseAG さん

添付ファイルの中身は、何もしなくても検索するようになります。
（添付ファイルが登録された後、しばらくすると中身の文章を抽出して検索可能な状態にします）


デモサイトに例を登録しました。
ご確認ください。

https://support-project.org/knowledge/open.knowledge/view/447

**Comment by koda-masaru** [comment]
別途回答して解決しています（メール）。

## 以下、忘備録
- Knowledgeでは、Webアプリケーションから、別のJavaプロセスを実行して非同期に処理を行わせている
   - 添付ファイルの中身の解析とか、メールの送信など
- この定期的なバッチを、Tomcatのから呼び出す事が阻害されるという現象が発生
   - セキュリティなどの理由？原因はわからず。
- しかたがないので、定期的なバッチをCronやタスクマネージャーにセットして実行することで対応した
