### ISSUE TITLE
タグの表記ブレを簡単に修正したい

### ISSUE THREAD

**Issue by griffin-stewie** [support-project/knowledge#366]
現在、見た目上違いがわからないような表記ブレしたタグ（重複しているように見える）があります。
このままではタグベースで絞り込んだ際に本来表示されてほしい記事がリストアップされない可能性があると思っています。

タグを一括で変更して統一させる良い方法はないでしょうか？

**Comment by koda-masaru** [comment]
@griffin-stewie さん

現在のKnowledgeの仕様ですと、タグの一括変更といった機能は提供していません。

データベースに接続し、直接SQLで更新すれば更新できますが、、、
それを実施できますでしょうか？

SQLでの更新でも良いよ！ということであれば手順を記載しようと思います。

画面でそのような機能が欲しい！ということであれば、少し先になるかもしれませんが、
そのような機能の提供を検討しようと思います。
（Issueが溜まっているので、、、提供時期が遅くなるかもしれません）

**Comment by griffin-stewie** [comment]
私自身に接続する権限はないですが手順が分かれば依頼もしやすいです。よろしくお願いします。

**Comment by koda-masaru** [comment]
では、手順を記載します。

KnowledgeのデータベースのER図は以下にあります。
https://github.com/support-project/knowledge/blob/master/document/database/A5M2_knowledge.pdf

こちらを見ながらだと、イメージがつきやすいと思います。

-----

## 記載手順のシナリオ
類義のタグ「テスト」と「Test」があったとします。
「テスト」に統一するため、「Test」のタグが付いているものを、全て「テスト」に
付け替えるシナリオとします


## 手順[1] データベース更新（SQL）

1. 「Test」のタグのIDを「TAGS」テーブルから取得

```
SELECT TAG_ID FROM TAGS WHERE TAG_NAME = 'test'

-> タグのIDで "100" を取得したとします
```

2. 「テスト」のタグのIDを「TAGS」テーブルから取得

```
SELECT TAG_ID FROM TAGS WHERE TAG_NAME = 'テスト'

-> タグのIDで "200" を取得したとします
```

3. KNOWLEDGE_TAGS(ナレッジが持つタグ)テーブルの「Test」のタグを「テスト」に変更します

```
UPDATE KNOWLEDGE_TAGS SET TAG_ID = 200 WHERE TAG_ID = 100
```

※ ただし、同じナレッジに「Test」と「テスト」のタグが両方セットされているものがある場合、
「Test」を「テスト」に変更した場合、「テスト」のタグが2つになることになります。
この場合、同じタグは登録出来ないのでエラーになります。
もし、そのようなナレッジがある場合、「Test」のタグの設定を削除してください。


## 手順[2] 検索用インデックスの更新
- データベースを直接更新した場合、キーワード検索用の検索エンジンの情報は更新できません
- 管理者メニューに「検索用のインデックス再構築」という機能がありますので、それを使い検索エンジンの情報を更新してください

**Comment by griffin-stewie** [comment]
@koda-masaru 
非常にわかりやすい説明をありがとうございます。この方法で作業依頼をしてみたいと思います。

**Comment by griffin-stewie** [comment]
最終的には数が少なかったので直接記事を編集しました。ありがとうございました。
