### ISSUE TITLE
記事内の目次表示

### ISSUE THREAD

**Issue by irgaly** [support-project/knowledge#367]
ナレッジ記事内に目次があると便利です。

多くの記事は、内容量がそんなに多くはないのですが、情報量が多くなる記事のときには目次があると助かります。

KnowledgeのMarkdown記事に、<a>タグを記載して目次を手書きしている人がいるのを見て、これはKnowledge側で目次生成できたほうが良いかと思い、要望としてIssue登録させていただきます。

---

Qiitaは当初は記事の右上に折りたたみで目次を表示していたようですね。

http://blog.qiita.com/post/77055935852/qiita-toc

現在は、右側のサイドバーへ目次を表示しているようです。

**Comment by koda-masaru** [comment]
そうですね。Knowledgeでも、目次をつけることを検討します。

以下のようにしようと思います。
- 「#」から始まる、hタグの部分を抽出して目次のラベルとします。
   - 「#」の3階層くらいまでを対象
- 目次は、サイドバー部分の「一番上」に表示

**Comment by koda-masaru** [comment]
v1.4.0でリリースしましたのでissueをクローズします。
