### ISSUE TITLE
他ユーザーの記事を編集すると投稿者表示が変わってしまう

### ISSUE THREAD

**Issue by irgaly** [support-project/knowledge#369]
他ユーザーの記事を編集すると、Knowledge記事のトップに表示される「{ユーザー} が 2016/04/28 10:15 に投稿 」の表記が、編集したユーザー名で表示されてしまう。

投稿者と編集者は分けて表示されるのが正しいかと思います。以下の表示でしょうか。

```
{投稿ユーザー} が 2016/04/28 10:15 に投稿 
{最終編集ユーザー} が 2016/04/28 11:15 に編集
```

**Comment by koda-masaru** [comment]
初めは両方を表示していたのですが、あまりごちゃごちゃ文字が出ると見づらいという意見(issue)があり、「最終編集ユーザー」のみを表示するようにしています。

投稿者と編集者が頻繁に代わり、かつ、初めの登録者が誰であったかが重要な場合は、再度表示を
検討した方が良いかもですが、どんなものでしょう？

私のチームでは、共同編集の機能は、あまり使われておらず、、、
今のところどちらでも良いといった感じです。(投稿ユーザと最終編集ユーザが同じなので）

**Comment by mitsugogo** [comment]
複数人で実際に使用していますが、確かに @irgaly さんがおっしゃるように最終投稿者になるのはちょっと違和感があります。

Qiitaのような下記のようなフォーマットはいかがでしょうか？
（｢編集履歴(5)｣は既存の`/histories/{id}`へのリンク想定）
```
{投稿ユーザー} が 2016/06/06 に投稿 ({最終編集ユーザー} が 2016/06/06 に編集)・編集履歴(5)
```

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。
違和感があるということですので、いったんご提案の形で出してみようと思います。
それで、また反応をみようと思います。
対応までしばらくお待ちください。

**Comment by mitsugogo** [comment]
@koda-masaru ありがとうございます！

**Comment by koda-masaru** [comment]
マージしました。次回のリリースでお届けします。

**Comment by koda-masaru** [comment]
Release v1.5.0 にてリリース済

**Comment by johiroshi** [comment]
すみません。このIssueは確認を忘れていました。

```{投稿ユーザー} が 2016/06/06 に投稿 ({最終編集ユーザー} が 2016/06/06 に編集)・編集履歴(5)```という表示の仕方は表記としては正しいのですが冗長だと思います。記事の一覧ページで伝えるべき情報は「タイトル・執筆者・更新日時・概要」ではないでしょうか。編集履歴の詳細は記事のページで表示すればよく、不要な情報だと思います。現行のデザインですと、記事の概要は掲載されていないので、編集履歴よりもそちらを掲載する方が使いやすくなるのではないでしょうか。

また、「Qiitaのようなフォーマット」とありますがどのような内容でしょうか。2017/11/29では見つけられませんでした。

**Qiitaのようなフォーマット(2017/11/29)**
![qiita_view_all](https://user-images.githubusercontent.com/15374413/33359359-a6b61284-d511-11e7-9b9b-8112d283b0c7.png)
