### ISSUE TITLE
「URLをコピー」でクリップボードに入るURL

### ISSUE THREAD

**Issue by iga64** [support-project/knowledge#384]
「URLをコピー」ボタンを押下すると、クリップボードには以下の内容が入ります。
```
http://(サイトのURL)/knowledge/記事ID
```
このURLをブラウザで指定すると「Error Not Found」となります。
Docker上で運用し、コンテナのポートは49170->8080としています。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
URL作成の部分を間違えたと思います。
修正しますね。

**Comment by koda-masaru** [comment]
v1.4.0でリリースしましたのでissueをクローズします。
