### ISSUE TITLE
Windows環境でバックアップ対象の .knowledge フォルダが見当たらない

### ISSUE THREAD

**Issue by sumimi** [support-project/knowledge#391]
Windows 環境で Tomcat8.0 にて Knowledge を配備しましたが、
マニュアルにある .knowledge フォルダが作成されていないように見受けられます。

.knowledge フォルダは、tomcat 実行時ユーザのホームディレクトリに作成される認識です。
仮に tomcatuser で tomcat を実行しているとすると、
C:\Users\tomcatuser 配下に .knowledge フォルダが出来ている認識です。
認識に誤りがあればご指摘ください。

**Comment by koda-masaru** [comment]
認識はあっています。
Knowledgeのホームディレクトリの場所は、tomcatのログにも出力しています。
tomcatのlogs/catalina.out に以下のログが書かれていないでしょうか？

```
INFO  2016-06-09 07:47:37,424 [InitializationListener(49)] Knowledge start
INFO  2016-06-09 07:47:37,424 [InitializationListener(50)] knowledge install path: 'Knowledgeのwebappのパス'
INFO  2016-06-09 07:47:37,425 [InitializationListener(51)] knowledge home path: 'バックアップ対象のデータが格納されるパス'
```

このログの `バックアップ対象のデータが格納されるパス` が データを格納しているパスになります。
ご確認ください。

**Comment by sumimi** [comment]
ご回答、ありがとうございました！
ログ情報を元に、無事にバックアップを採取することができました。

以下、ご報告及びご質問になります_(._.)_
----
ログを確認したところ、Windows 10 環境では以下のフォルダがホームディレクトリになっていました。
ホームディレクトリを「C:\Users\{Username}」と思い込んでいました。。。お手数お掛け致しました。。。
　C:\Windows\System32\config\systemprofile\.knowledge

ついでの質問で申し訳ございませんが、ホームディレクトリを変更するための設定はございますでしょうか？
上記のフォルダでは、バッチによる自動バックアップが若干面倒に感じております。
重ね重ねお手数お掛けし恐縮ですが、ご回答頂けましたら幸いです。

**Comment by koda-masaru** [comment]
うまくいったようで良かったです。

データディレクトリは、環境変数に KNOWLEDGE_HOME というキーで、ディレクトリのパスを
指定する事で変更できます。
お試しください。

**Comment by koda-masaru** [comment]
こちらこそ、マニュアルをもっと整備しようと思っているのですが、なかなか
進んでいなくてすみません。
他に質問などあれば、お気軽にissue登録願います。

**Comment by koda-masaru** [comment]
解決しているので、issueをクローズします
