### ISSUE TITLE
カテゴリー化機能を追加していただけますか？

### ISSUE THREAD

**Issue by umbalaconmeogia** [support-project/knowledge#397]

**Comment by koda-masaru** [comment]
カテゴリーとはどのようなイメージでしょうか？
投稿内容にはタグをつけられますが、それとは違いますか？

**Comment by umbalaconmeogia** [comment]
カテゴリー化は階層的に分類することです。従来の掲示板のカテゴリーのことです。
確かにタグも便利ですが、ナレッジを整理して、文章体系の全体像を作るには、タグよりもカテゴリーのいいところがあると思います。
カテゴリーとタグ兼用はいいかがででょうか。

私はあまり詳しくなく、考え方が古いかもしれません。カテゴリー機能がなくても同じことができるなら、ご教示ください。

**Comment by koda-masaru** [comment]
回答ありがとうございます。

カテゴリー(階層を整理)の要望は、以前もあったのですが、階層を意識することで、逆に情報共有が活発にならないという意見もあり、いったんは見送っていたことを思い出しました。

以下も参照願います。
https://github.com/support-project/knowledge/issues/241


Webで情報を検索する場合も、yahooのような階層分けよりもGoogleのような、キーワードで検索することが主流になっていると思います。(階層を知らないと欲しい情報にたどりつけないので階層を利用しないことが多い)

いかがでしょうか？

**Comment by koda-masaru** [comment]
カテゴリ化（階層型での構造化）は対応予定が無いのでクローズ
