### ISSUE TITLE
DBはPostgreSQLを推奨するような記載をどこかに書く

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#40]
- 利用を簡単にするため、Knowledge起動時にH2Databaseを組み込んで、それを起動していた
- データ件数が多くなると、H2Databaseはパフォーマンスがかなり劣化する
- PostgreSQLに切り替えると、パフォーマンスが目に見えて改善する

**Comment by koda-masaru** [comment]
- ちなみに、管理者機能の中に、デフォルトのH2DatabaseからPostgreSQLへの切り替えが出来ます

**Comment by kounoike** [comment]
H2の信頼性という話がちょうどGitBucket方面でも上がっていて、
こんな話 https://twitter.com/ysobj/status/624069492688072704 がありました。
Knowledgeも1.4系列を使ってますよね？ Stableである1.3系列にした方が良いのかもしれませんね。
パフォーマンスがどうなるかは分かりませんが。

**Comment by koda-masaru** [comment]
なるほど。
Knowledgeの次のStableリリースでは、1.3系にする事も検討します。

でも、既に利用中のユーザのデータ（1.4系のデータ）があるので、
ライブラリを1.3系に切り替えて正常に動くかどうかが不安ですね。

Postgresにしても、いったん最新バージョンを使ってみましたが、
DBじたいのバージョンアップもあるし、
既に社内に稼働しているPostgresのバージョンとの関係もあり、
組み込むJDBCのバージョンについてはいろいろ課題がありそうです。

JDBCに関しては、利用者側で変更出来るような仕組みがあると良いのかもしれません。

**Comment by koda-masaru** [comment]
v1.4.0にてシステムメニューでPostgresを推奨するようにメッセージを表示しました。
