### ISSUE TITLE
ファイルサーバへのリンク

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#408]
Markdown本文の中で、ファイルサーバーへのリンクを記載したい。

以下のようなネットワークディレクトリの表記を行うと、Markdownのパース処理か
XSS対策処理の中で、パスを壊してしまうようで、リンクが変更されてしまうという
報告があった。

\\server_host\hoge\fuga\sample.txt

file://server_host/hoge/fuga/sample.txt

**Comment by koda-masaru** [comment]
Release v1.5.0 にてリリース済

**Comment by soogle53** [comment]
Release v1.5.0 にてリリース済のファイルサーバへのリンクについて
記事本文で以下のように記載しても、実際のリンクは「server_host」部分が消えてしまう。
使用ブラウザはFirefoxです。

file://server_host/hoge/fuga/sample.txt
↓
file:///hoge/fuga/sample.txt

別の記法があるのでしょうか？よろしくお願いいたします。

**Comment by koda-masaru** [comment]
特に特殊な記法はありません。デモ環境（v1.8.0pre3環境）にはなりますが
想定通りに動いていそうでした。

https://support-project.org/knowledge/open.knowledge/view/1159

コードを確認したのですが、消えてしまう理由をみつけられませんでした。
（特殊なserver_hostの場合に、消えてしまうといった条件があるのかも知れないですが）

**Comment by soogle53** [comment]
返信ありがとうございます。
リンクをオンマウスすると、file:///hoge/fuga/sample.txt のように
なってしまいますが、ソースを見ると正常でした。

Firefox側に原因があるのかもしれません。

**Comment by soogle53** [comment]
以下のURLの内容と同じことが起こっています。
http://forums.mozillazine.jp/viewtopic.php?f=2&t=15280

knowledge側で”file://///”をリンクとして認識させていただけないでしょうか？
