### ISSUE TITLE
コード表示内で「&」を入力すると「&amp」と表示される

### ISSUE THREAD

**Issue by smileclock** [support-project/knowledge#410]
1.4.1を使用していますが、記事中でバッククォートを使いコードを記述した際、「&」（半角アンパサンド）を使用すると「&amp」という文字列で表示されてしまいます。
（&read_data が&ampread_data に置き換わってしまう）

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
XSS対策のエスケープが、邪魔をしているようです。
対策方法を考えますね。

**Comment by koda-masaru** [comment]
Release v1.5.0 にてリリース済
