### ISSUE TITLE
公開範囲を絞っている場合、添付ファイルの中身を検索する場合に登録者しか検索できない

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#415]
添付ファイルの中身のテキストを全文検索エンジンに登録する際に、
「公開」の場合は、全ユーザが検索できるようにしている。

しかし「非公開」「保護（公開先を指定）」している場合、アクセス権を登録者のみにしていた。

非公開では問題ないが、「保護」の場合、公開範囲のユーザ／グループにアクセス権を付け忘れていた。

**Comment by koda-masaru** [comment]
Release v1.5.0 にてリリース済

**Comment by rainthestorm** [comment]
User権限だけを与えたユーザだと、公開範囲に入っていても検索にひっかかってこないようです。
Administrator権限を与えたら検索にひっかかるようになりました。
