### ISSUE TITLE
検索機能強化

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#42]
- 現在は、ナレッジに書かれている内容や、添付ファイルの中身、コメントで検索出来る（全文検索）
- タグや登録者などで絞り込んで検索出来るとうれしい

**Comment by koda-masaru** [comment]
タグ（複数指定可能）＋検索キーワードで検索可能にしてみました。
いったん、このくらいで良いでしょうか？

登録日時（範囲指定）、登録者など、条件を考えればいろいろありますが、
機能をあまり多くしすぎて、ごちゃごちゃすると逆に使いづらいでしょうか？

ナレッジに５段階評価をつけて、平均何点以上とか、
イイネの件数が何件以上　といった検索も、有効なナレッジの検索としては良いかも？
（評価の高いナレッジのみを検索するので）

**Comment by koda-masaru** [comment]
タグは、OR検索ではなく、AND検索にする（フィルタリングで絞り込むイメージ）

一覧で、絞り込みのタグを追加していけると良いかも。

**Comment by kuchikios** [comment]
タグのAND検索は既定にして欲しいくらいとても欲しい機能なので、検討して頂けると嬉しいです

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。
AND検索の対応は次のプレリリースに含める予定です。

ちなみに、OR検索→AND検索に変更しようと思ってます。
OR検索は出来なくなっても問題ないかと思うのですが、どうでしょう？？

**Comment by kuchikios** [comment]
「Aを含む、BまたはC」みたいな式が作れるならORはあっても良いと思うのですが、
ここでは一律なので、条件を指定すればするほどたくさんヒットしてしまうよりかは
良いと思います。

**Comment by koda-masaru** [comment]
いったん、タグで絞り込み検索（AND検索）に変更してみました。

ついでに、今まで一覧画面で「ナレッジの検索」を押すと、検索画面に遷移しますが、
その際に検索条件が初期化されていました。
絞り込み条件を追加しながら検索していくという使い方だと思うので、検索画面を
開く際には、検索条件を保持するようにしました。

**Comment by koda-masaru** [comment]
グループ検索 #105 なども追加しました。

引き続き、検索機能の強化は進めていきますが、
追加する検索に対し、新しいissueで管理していこうと思います。
（このissueだと終わりが無いので）

このissueはクローズします。
