### ISSUE TITLE
記事作成者以外にも編集ができるような機能が欲しい

### ISSUE THREAD

**Issue by griffin-stewie** [support-project/knowledge#43]
現在の knowledge では記事の作成者のみが記事の編集が可能だと思います。（管理者権限を除く）
実際の情報共有の場では

- 既存記事が古くなったので情報をアップデートしたい
- 共同で何かを作りたい（既存の Wiki のような使い方）

もあるのではと思います。

そこで Qiita の `編集リクエストを作成` のような機能があると良いなと感じました。

[年始の大型リリース第2弾！編集リクエスト機能をリリースしました！ - Qiita Blog](http://blog.qiita.com/post/40808687185/patch-request-release "年始の大型リリース第2弾！編集リクエスト機能をリリースしました！ - Qiita Blog")

**Comment by koda-masaru** [comment]
なるほど。その通りですね。

「編集リクエスト（プルリク）」と、「共同編集者」の機能については、今後のアップデートで機能拡張していこうと思います。

**Comment by koda-masaru** [comment]
いったん共同編集者を指定できるようにしました

**Comment by griffin-stewie** [comment]
@koda-masaru 
ご対応ありがとうございました。
全てのユーザに対して編集可能にしたいのですが、編集者の指定で all のようなものはないのでしょうか？

**Comment by koda-masaru** [comment]
いまのところ、編集指定で「ALL」はありません。
後で追加しますので少々お待ちください。

**Comment by koda-masaru** [comment]
ALLグループを追加しました。
登録されたユーザは、自動的にALLのユーザになります。
ALLに所属しているユーザを変更は出来ません。

**Comment by griffin-stewie** [comment]
0.5.3 pre3 で確認しました。ご対応ありがとうございました。

**Comment by koda-masaru** [comment]
確認ありがとうございます。
Qiitaのように、編集リクエストの機能も提供できるとよいのですが、
やり方を検討中という段階です。
編集リクエストについては、別のissue #76 で管理しようと思います。

**Comment by griffin-stewie** [comment]
ありがとうございました。
編集リクエストも期待しています。
