### ISSUE TITLE
記事IDによる記事同士のリンク

### ISSUE THREAD

**Issue by mitsugogo** [support-project/knowledge#436]
`#123`みたいな書き方で記事同士をリンクさせる方法はありますでしょうか？

サーバー移設等でドメインやIPアドレスが変わってしまった際に、`http://192.168.11.100/open.knowledge/view/123～`みたいなリンクを全部書き換えるのが面倒で、
記事番号でリンクできたらいいなと思いまして。

「参考記事は `#123` を見てね！」みたいな感じで使えると理想です。

**Comment by johiroshi** [comment]
@mitsugogo さん

[このような機能](https://support-project.org/knowledge/open.knowledge/view/672)でしたらありますよ。

**Comment by koda-masaru** [comment]
#数字 
のような形式が書かれていた場合、knowledge内の記事へリンクすることは出来ると思います。
そのように修正を検討しますね。

**Comment by mitsugogo** [comment]
@johiroshi @koda-masaru すでにあったんですね…！自分的にはこちらで必要十分です！

**Comment by koda-masaru** [comment]
@johiroshi さん 
説明ありがとうございます 😄 

@mitsugogo さん
johiroshi さんが書いている方法で必要充分とのことなので、いったんはその方法でご利用ください。
GitHubのように、Markdown中に「#数字」と書くとリンクが生成される機能も、そのうち提供したいと思います。

**Comment by irgaly** [comment]
@johiroshi @koda-masaru 
すみません、こちらで説明されているリンクはどのような記法になっているでしょうか。
記事を作成して「#(数字)」と記載してみましたが、リンクされず。

> GitHubのように、Markdown中に「#数字」と書くとリンクが生成される機能も、そのうち提供したいと思います。

 #数字 でリンクが張れるととても良いですね。

**Comment by koda-masaru** [comment]
@irgaly さん

Markdownの中で、以下のように記載すると、リンクを貼ることができます。

```
[#673(リンクテスト2)](673)へ
```

参考の記事：

https://support-project.org/knowledge/open.knowledge/view/672

**Comment by irgaly** [comment]
> `[#673(リンクテスト2)](673)へ`

ありがとうございます！こちらの記法で別記事へのリンクが可能でした。
相対リンクになっているんですね。
Preview内でリンクをクリックしたところ`/view_edit/...`が開いて記事編集画面に飛びました 😅

**Comment by il-m-yamagishi** [comment]
Githubのissueのように、どれかの記事にリンクされたら「この時期にリンクされています」のように表示されると、双方向で関連する記事にすぐに飛べて嬉しいかな、と思いました。

**Comment by koda-masaru** [comment]
@irgaly さん
ご連絡ありがとうございます。
#512 にissueを登録しました。

**Comment by koda-masaru** [comment]
@il-m-yamagishi さん
issue #513 に新たなissueとして登録しました。

**Comment by koda-masaru** [comment]
v1.6.0 にて、いったんリリースしましたので、本issueはクローズします。
（別途、追加の要望は新規にissueを作成しています）
