### ISSUE TITLE
ALL USERS グループの権限がデフォルトは不参加になっている

### ISSUE THREAD

**Issue by makarasa** [support-project/knowledge#437]
ユーザー登録した段階でuser_groupsのgroup_roleが0のため
ALL USERS グループの権限がデフォルトは不参加になっている。

しかし、「グループ表示」画面で権限を更新できない。

**Comment by koda-masaru** [comment]
上記を確認したバージョンは v1.4.1でしょうか？
v1.5になりますと、ALL_USERSグループのメンバーの表示は、正しく表示されるよう修正しています。

デモサイトで最新のv1.5を稼働していますので、これで問題無いかご確認ください。
https://support-project.org/knowledge

**Comment by makarasa** [comment]
回答ありがとうございます。
最新のv1.5にアップデートし、新規登録すると
ALL USERS グループの権限はデフォルト「状態: メンバー」になりました。
しかし、ALL USERS グループに編集権限が与えられている記事を編集できません。
ALL USERS グループに入りなおすと、編集できるようになります。

**Comment by koda-masaru** [comment]
@makarasa ご連絡ありがとうございます。編集権限のチェックでALL_USERのグループが効かないようになっていました。次のバージョンで修正しようと思います。

**Comment by koda-masaru** [comment]
v1.6.0 pre1でリリース済。クローズします。
リリースしたものに問題があれば、別途のissueを登録願います。
