### ISSUE TITLE
bookmark での URL が小さい

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#443]
該当のURLに関する記事内容のはずなので、まずその記事を読む前にURL先を見て欲しいのですが、記事に表示されるURLが本文と同じサイズなので非常に見つけづらいです。

**Comment by koda-masaru** [comment]
確かにそうですね。
サイズを大きくしようと思います。

**Comment by koda-masaru** [comment]
v1.6.0 pre1でリリース済。クローズします。
リリースしたものに問題があれば、別途のissueを登録願います。
