### ISSUE TITLE
コメントに 「いいね！」 をつけたい

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#444]
コメントに対してのコメントが引用程度しか出来ないので、Githubの `Reaction` と同じように、コメントにもいいね！を付けたいです。

**Comment by koda-masaru** [comment]
なるほど。あっても良いですね。

issueが溜まっているので、対応までは時間がかかるかもしれません。
いったんは、コメントの中に `:+1:` 👍  を書くという方法などをご利用ください。

**Comment by koda-masaru** [comment]
This is supported by v1.11.0.
You can add "Like" to a comment.
I will close this.
