### ISSUE TITLE
添付ファイルの数が増えるとうっとうしい

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#445]
![ss_001](https://cloud.githubusercontent.com/assets/15116901/17914692/38470edc-69df-11e6-9113-f14d88504f49.png)

添付ファイルが1個・2個の場合は特に気にならないのですが、画像ファイル数が多くなるとこのようにファーストビューがタイトルと添付ファイル一覧だけで埋まってしまいます。

添付ファイルを本文の下に置くなど移動して欲しいです。

また、pdfファイル等クリックして欲しいものを添付するような場合のために、本文中にこの添付ファイル一覧と同じ形式のリンクを置けると良いと思います。

`[](/open.file/download?fileNo=\d+)`  の場合は、ただのリンクではなくアイコン付きにするなどが良いのではないでしょうか。

**Comment by koda-masaru** [comment]
添付ファイルについては、以下のissueにも表示の見直し案があがっています。

https://github.com/support-project/knowledge/issues/123

使いやすい画面を検討しようと思います。

**Comment by koda-masaru** [comment]
v1.6.0 pre1でリリース済。クローズします。
リリースしたものに問題があれば、別途のissueを登録願います。
