### ISSUE TITLE
タグ一覧からタグを選択した後、保存を押すと、保存がいつまでも完了しない

### ISSUE THREAD

**Issue by soesoeEx** [support-project/knowledge#447]
不具合かどうかは分かりませんが、念のため、報告致します。

【現象】
投稿編集時、「タグ一覧」から「タグ」を選択（マウスでクリック）し、「保存」ボタンを押すと、「保存」ボタンがグレーアウトしたまま、保存がいつまでも完了しません。

「タグ一覧」を使用せず、「タグを直接入力（タグ文字列+半角カンマ+半角スペース）」、または、「直接入力中に表示されるドロップダウンから選択」した場合は、この現象は発生せず、正常に保存されます。

※色々確認したところ、「タグ一覧」から選択した「タグ」がある場合、保存が完了しなくなるようです。

【現象を確認した環境】
OS : 
　Windows 7 Professional SP1

ブラウザ：
　Chrome（バージョン 52.0.2743.116 m）、
　IE 11（バージョン : 11.0.9600.18426、更新バージョン : 11.0.34（KB3175443）

Knowledge：
　v1.4.1

**Comment by koda-masaru** [comment]
ご報告ありがとうございます。
デモサイトで確認したところでは、タグ一覧から選択した場合も保存できました。

タグ一覧で選択したタグは、どのような文字でしょうか？
`'` や `"` といった特殊文字が含まれているものであったりしますでしょうか？

もしくは、ブラウザの環境依存かもしれません。
（当方はMacでChrome 52.0.2743.116 (64-bit) で確認してみました）

また、Knowledgeのデータを保存するディレクトリに logs/app.logというファイルがあると思います。
そのログで、何かエラーが発生していませんでしょうか？

**Comment by soesoeEx** [comment]
> デモサイトで確認したところでは、タグ一覧から選択した場合も保存できました。
こちらでも、デモサイトで保存できることを確認致しました。
状況からすると、こちらで使用しているKnowledgeの設定やインストール方法に問題がありそうです。
（詳しくは後述致します）


> タグ一覧で選択したタグは、どのような文字でしょうか？
特殊文字は含まれておりません。
「Knowledge」や「テスト」といったタグです。
上記のようなタグを一つだけ選んだ状態でも現象が発生します。


> また、Knowledgeのデータを保存するディレクトリに logs/app.logというファイルがあると思います。
> そのログで、何かエラーが発生していませんでしょうか？

文字コードのエンコーディングに失敗したというようなニュアンスのエラーが出ているようです。
（EUC_JPでエンコードできないといった趣旨のメッセージのようです）

以下に、エラーメッセージ部分だけ抽出したものを配置致しました。
ご確認をお願い致します。
[app.log](https://gist.github.com/soesoeEx/4af210a45e8906505bad7321fc30b004)

なお、Knowledgeのインストール時に、DBの文字コードに「UTF-8」を指定して作成しております。

**Comment by koda-masaru** [comment]
私の環境で、エラーが再現できませんので、再確認させてください。

タグを手入力した場合は、エラーは発生せず、タグ一覧から選択した場合にのみエラーに
なるということであっていますでしょうか？
あと、Knowledgeといった、英数文字だけの文字でもエラーになるでしょうか？

環境依存の問題（エンコードが問題？）だと、一覧選択でも手入力でも、同じくエラーに
なりそうなものですが、それがエラーにならないのが不思議です。

KnowledgeをインストールしたサーバーのOSは何でしょうか？
OSのエンコードがEUC-JPだと、エラーが発生するのかもしれません。

**Comment by soesoeEx** [comment]
自己解決しました。
お騒がせして申し訳ありません。

DBのエンコーディング指定を「EUC-JP」→「UTF-8」に変更したところ、現象が再現しなくなりました。
（前回のコメントで、「DBの文字コードに「UTF-8」を指定して作成」と記載してしまいましたが、「EUC-JPを指定して作成」の誤りでした。申し訳ありません）

また、エンコーディング変更後、「タグを手入力した場合」と「タグ一覧から選択した場合」の両方で、app.log内のエンコーディング関連のエラーが発生しなくなったことを確認致しました。

ただ、ユーザーの操作で、エンコーディング関連のエラーが発生しなくなる点については、kodaさんがおっしゃいている通り、不思議です。
何か別の問題が隠れているのかもしれません。

現象は発生しなくなっていますが、念のため、kodaさんからの質問に、以下、回答致します。


> タグを手入力した場合は、エラーは発生せず、タグ一覧から選択した場合にのみエラーになるということであっていますでしょうか？

おおすじとしての回答は、「はい」となります。

厳密には以下の通りです。

app.logを監視しながら確認したわけではないので、厳密に、「タグ一覧から選択した場合のみエラーが出ていたか」までは確認しておりません。

挙動としては、以下の通りです。
「タグを手入力」または、「タグを手入力中のドロップダウン」から選択した場合は、保存ができます。
「タグ一覧からマウスでタグを選択した場合」は、保存ができません。（保存ボタングレーアウトのままで、待っていても保存が完了しません）

※タグ手入力時にもエラーが出ていた可能性は否定できませんが、DBのエンコーディングを変更し、現象およびエラーが発生しなくなったことから、「タグ一覧」を使ったときにのみエラーメッセージが発生していたと推測しております。

> あと、Knowledgeといった、英数文字だけの文字でもエラーになるでしょうか？

はい、なります。（厳密にはエラーではなく、保存できないことを確認しました）
選択したタグは、「Knowledge」、「C#」等です。
「Knowledge」一つだけを選択しても保存できませんでした。

> 環境依存の問題（エンコードが問題？）だと、一覧選択でも手入力でも、同じくエラーになりそうなものですが、それがエラーにならないのが不思議です。

同感です。
ブラウザや実装の問題が隠れているかもしれません。

> KnowledgeをインストールしたサーバーのOSは何でしょうか？
> OSのエンコードがEUC-JPだと、エラーが発生するのかもしれません。

OS: Debian jessie
バージョン: 8.5

デフォルトエンコード： None(LANG=C)
　EUC-JP、UTF-8は選択可能な状態です。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

> DBのエンコーディング指定を「EUC-JP」→「UTF-8」に変更したところ、現象が再現しなくなりました。
> また、エンコーディング変更後、「タグを手入力した場合」と「タグ一覧から選択した場合」の両方で、app.log内のエンコーディング関連のエラーが発生しなくなったことを確認致しました。

解決できたようで良かったです。

ブラウザの操作手順によりエラーが発生する／しないの現象がわかれるという点については謎が
残りますが、いったんは現象が発生しなくなったことですし、問題が再現するまで様子見しようと
思います。

**Comment by soesoeEx** [comment]
> 問題が再現するまで様子見しようと思います。

了解しました。
様子見ということですが、issueとしてはCloseしておいた方がよいでしょうか？

**Comment by koda-masaru** [comment]
そうですね。Closeでお願いします。
また同じ現象が再現したら、再度issueを登録していきたいと思います。

**Comment by soesoeEx** [comment]
> そうですね。Closeでお願いします。
> また同じ現象が再現したら、再度issueを登録していきたいと思います。

了解しました。
色々とご対応ありがとうございました。

Closeさせて頂きます。
