### ISSUE TITLE
非公開で更新され続けてきた記事が公開された初回の Webhook 通知の判定方法が知りたい

### ISSUE THREAD

**Issue by griffin-stewie** [support-project/knowledge#448]
私の利用環境では、Webhook の設定を行っており以下のような条件でチャットに通知を流すようにしています。
- パブリックなエントリであること
- status が `created` であること

この条件により、新規投稿のみをチャットに流せるようにしています。

しかし、最近のユーザの利用状況では初回は非公開として作成し、編集・更新を続けて、公開可能な状態になってから公開へと切り替えることが多くなっています。
このような利用状況では先に挙げた条件には引っかからなくなってしまいます。status が `updated` でもチャットに通知するようになると細かい編集作業がすべてチャット側に通知されてしまい不便です。

メール通知では、私が理想としているような「パブリックになった1回目の投稿のみ」のタイミングで送られてきています。

「パブリックになった1回目の投稿のみ」を Webhook 側で判定する材料はペイロードに含まれていますでしょうか?

以下の値が鍵になりそうですが、詳細な仕様がわかりません。
- type_id
- public_flag
- status

**Comment by koda-masaru** [comment]
> 「パブリックになった1回目の投稿のみ」を Webhook 側で判定する材料はペイロードに含まれていますでしょうか?

残念ながら、今の仕様では、送信された情報1件で「パブリックになった1回目の投稿のみ」を判定することはできません。
WebHookで届いたデータを保持していれば、public_flagが「0(公開)」で初めて届いたものが、「パブリックになった1回目の投稿のみ」と判定できますが、わざわざデータを保持しておかなければいけないので、あまり現実的では無いと思います。

ちなみに、上の「type_id」はKnowledgeの種類（KnowledgeかBookmarkかなど）を表し、「status」は登録なのか／更新なのかを表しています。
登録か／更新かのみしか取れないので、「非公開」で「登録」した後で、「公開」で「更新」しても、それが初めの1回目かどうかの判定ができません。

-----

私の環境でも、「初回は非公開として作成し、編集・更新を続けて、公開可能な状態になってから公
開」という使い方をするユーザが多くなってきました。
#150 の下書き機能があれば、このような運用は少なくなると思っているのですが、他のissueも溜まっていまして、直ぐに提供できそうもありません。

そこで、「パブリックになった1回目の投稿のみ」を判定できるようにして、それをWebhookやメール通知に渡せるようにできることを検討しようと思います。

> メール通知では、私が理想としているような「パブリックになった1回目の投稿のみ」のタイミングで送られてきています。

メール通知は、数分に1回の処理になっているため、その数分の間に何回保存しても1通のメールになります。その後のインターバルで更新が入ると、再度メールを送ります。
このため、同じナレッジに対し、編集時間が長いと、何通もメールが届くことがあるので、メール通知においても「パブリックになった1回目の投稿のみ」を通知する／変更も通知するを切り替えられた方が良いかと思っています。

**Comment by koda-masaru** [comment]
忘備録

WebhookLogicのgetKnowledgeData()の中で、WebHookで送るJSONを生成しているので、この処理の中で、「パブリックになった1回目の投稿のみ」かどうかを判定して、JSONにその値をセットすれば対応できる。

**Comment by griffin-stewie** [comment]
@koda-masaru 
早速、前向きに検討いただきありがとうございます。WebHook のみで判定できると大変ありがたいです。

**Comment by koda-masaru** [comment]
WebHookの仕様で相談があります。利用者の意見を伺いたいです。

１．「パブリックになった1回目の投稿のみ」のパブリックの定義

Knowledgeでは、公開の区分は「非公開」「公開」「保護」の3つがあります。
パブリックは「公開」と「保護」の2つ（「非公開」以外）で良いと思いますか？
「保護」は公開の対象を選んで公開するという意味になるかなと思っています。

２．Webhook通知のタイミング

現在、Webhookはアイテムが登録された場合に、全てを通知しています。
メールでの通知は、公開の区分が「公開」「保護」の場合に通知しています。
（「非公開」は通知していません）
Webhookも、「非公開」の場合は通知する必要は無いのかな？
と思ったのですが、いかがなものでしょうか？

**Comment by griffin-stewie** [comment]
@koda-masaru 
> パブリックは「公開」と「保護」の2つ（「非公開」以外）で良いと思いますか？

「保護」の投稿も「範囲を限定しての公開」であることには違いないので問題ないと思います。

> Webhookも、「非公開」の場合は通知する必要は無いのかな？

利便性を考えると通知自体は行った方がよいのではと思います。その情報を元にどう振る舞うかはユーザー側の判断に任せた方がいいという考えです。

--- 

そうなるとペイロード側に何らかの情報を追加しなくてはいけなくなってきてしまいますよね？足すとすると以下のような情報でしょうか？

- 前回の public_flag を追加
    - 前回と現在の public_flag の比較をユーザー側が行えば、「パブリックに変わった」と判断可能
- パブリックに変わったフラグ

**Comment by koda-masaru** [comment]
@griffin-stewie 

ご意見ありがとうございます。いったん以下の仕様にしようと思います。

- ペイロードに、初めて「パプリックになった」かどうかのフラグを追加
   - `became_public` という名称で、 true / false を送ります
   - 一つの投稿で、trueが通知されるのは1回のみになります
- パブリックは「公開」と「保護」の2つ
- 「非公開」の場合もWebhookは通知する
   - `became_public` はfalse

これにより、「非公開で更新され続けてきた記事が公開された初回の Webhook 通知の判定」は可能になるかと思います。

**Comment by koda-masaru** [comment]
対応完了済。
クローズします。
