### ISSUE TITLE
システム設定ページの誤字

### ISSUE THREAD

**Issue by rainthestorm** [support-project/knowledge#449]
issue登録するほどではないかもしれません

システム設定＞テンプレート登録　にてアイコンが設定できると思います。

 アイコン(Font Awesome[http://fortawesome.github.io/Font-Awesome/]から選択してください。 e.g. fa-book) 

上記のテキスト通り（リンクなし）の表示となっております。
おそらく、リンクのURLミス（fort⇒font）ではないでしょうか。

アイコンを検討する際にリンクで飛べると助かります。

**Comment by koda-masaru** [comment]
上記のURLですが、URLとしては正しいようです。
[http://fortawesome.github.io/Font-Awesome/](http://fortawesome.github.io/Font-Awesome/)

リンク無しになっているのは、その部分にリンクを設定しなかったためになります。
ご指摘のように、リンクになっていた方が、操作しやすいと思いますので、
リンクを設定するようにします。

あと、軽微なことでも、issue登録していただけると助かります。

**Comment by koda-masaru** [comment]
v1.6.0 pre1でリリース済。クローズします。
リリースしたものに問題があれば、別途のissueを登録願います。
