### ISSUE TITLE
テンプレートでコンテンツの初期値を設定できるようにしてほしい

### ISSUE THREAD

**Issue by taturou** [support-project/knowledge#451]
テンプレートへの機能追加の依頼です。

コンテンツの初期値を設定できるようにして欲しいです。
たとえば、WeeklyReportであればチームによりどのような内容を書くべきか、が決まっていると思います。
「進捗、問題点、連絡事項」の章が必要。など。
そのため、ナレッジを「新規作成」したときに、「コンテンツ」にそれが予め入力されていると便利です。

よろしくお願いします。

**Comment by koda-masaru** [comment]
テキスト入力の部分に、初期値をセットできるようになると嬉しいということですね。
確かに、あると便利ですね。
設定できるように機能拡張をしようと思います。
issueが溜まっているので、提供は少し遅くなるかもしれませんがご容赦ください。

**Comment by taturou** [comment]
ありがとうございます！
私の会社では、ディレクトリ型のナレッジDBを運用しているのですが、ディレクトリ型は「整理された内容をかかなきゃ」という心理が強く働くため、なかなか記事数が伸びないというのが悩みでした。
そこて、Qiitaのようなサービスを探していてKnowledgeを見つけました。
まだ、使用するかを検討しているところですが、ChatOptsにも使えそうなので、有力候補となっています。
とても良いプロダクトだと思います。

**Comment by koda-masaru** [comment]
ありがとうございます。
私の組織でも情報共有を活発にしたいと思い、このKnowledgeを作りました。
最近はいろいろなところで使われていて、嬉しく思っています。

社内だと「整理された内容をかかなきゃ」となりますし、そもそも、業務中に「情報共有の記事をゆっくり書く時間無いよ」というのが課題と感じています。
時間が無いので、ちゃんとした記事を書けず、結局、情報共有しないという課題につながるのかと。

そこで、Knowledgeでは、記事を書くのを極めて簡単にできるようにしようと思っています。
例えば、社内の勉強会などで発表した資料を添付して、記事の内容には何も書かなくても、
その添付ファイルの中身まで検索できるようになるので、情報共有ができます。
（後から、その情報が欲しい人がたどり着ける）
Bookmarkの機能では、WebのURLを書いておけば、そのURLに書いてある内容で検索できるようにします。

このようなところがユニークなところかと思っています。良かったら使ってみてくださいね。

**Comment by koda-masaru** [comment]
This is supported by v1.11.0.
I will close this.

-----

This is supported by v1.11.0.
I will close this.
