### ISSUE TITLE
Webhookの設定について

### ISSUE THREAD

**Issue by vtjkinoshita** [support-project/knowledge#454]
はじめまして

チーム内での情報共有に使用しようかと思い Ubuntu にTomcat等を設定して
knowledge 1.5.0インストールして使ってみています。
Slackに投稿を通知しようとWebhookの設定してみたのですが、全くSlackの
方に通知が送信されない状況となっており、何か設定等でミスがあるのか調べている
のですが皆目見当が付かない状態です。

ログの方ではテスト送信でエラーのステータスが帰っているのですが、通常の投稿
ではエラー等のログは何も出ておらず何が原因なのか全く分からない状態です。

``
ERROR 2016-08-24 18:20:39,229 [WebhookLogic(165)] Request failed: statusCode -> 500
INFO 2016-08-24 18:20:39,319 [LoggingFilter(100)] POST http://knowledge-local:8080/knowledge/admin.webhook/test 200 hogehoge 1867[ms]
INFO 2016-08-24 18:20:39,518 [LoggingFilter(100)] GET http://knowledge-local:8080/knowledge/open.account/icon/3 200 hogehoge 8[ms]
``

思い当たる原因等はありますでしょうか？また必要と思われる情報等がありましたら
お教えいただけると有り難いです。

以上、よろしくお願いいたします。

**Comment by koda-masaru** [comment]
サーバーを起動しているOSは何でしょうか？

Knowledgeでは、WebAppのプロセスから、定期的にバッチプログラムを呼び出しているのですが、
その定期的な処理が実行されないという現象がおきるようです。
インストールを簡単にするためにWebAppから定期的に実行しているのですが、本来、この処理は
Cronなどで実行しても良いものになります。

そして、WebHookのテスト送信は、リクエストがあった際に同期的に処理しますが、投稿があった
場合のWebHookは非同期でバッチで処理しています。
このバッチ処理が呼び出されないことが原因のような気がします。

以下に参考になる内容が書かれています。ご一読ください。

http://qiita.com/icebluefit/items/f4ed8e6d4c26a5a7d212

https://github.com/support-project/knowledge/issues/412

**Comment by koda-masaru** [comment]
ちなみに、Dockerイメージを使って起動していただければ、一通りの動作が簡単に確認できると思います。
自前で環境を作るより簡単なので、Dockerイメージの利用をオススメします。

https://hub.docker.com/r/koda/docker-knowledge/

**Comment by vtjkinoshita** [comment]
ご回答有り難うございます。

インストールした環境については

| インストールしたもの | バージョン |
|:---|:---|
| OS | Ubuntu Server 16.04 |
| java | jdk-8u102-linux-x64 |
| Tomcat | apache-tomcat-8.5.4 |

で、投稿のメール通知については問題はなくメールが送信されているのですが
Slackへの通知が行われていないという状況になっております。

昨日デバッグを追加してテスト送信時のログをとったところ下記の様なログが出ております
（一部認証関係の情報のため変更しておりますスミマセン）

``
DEBUG 2016-09-06 15:35:07,169 [DefaultClientConnection(268)] Sending request: POST /services/hogehoge HTTP/1.1
DEBUG 2016-09-06 15:35:07,170 [wire(72)]  >> "POST /services/hogehoge HTTP/1.1[\r][\n]"
DEBUG 2016-09-06 15:35:07,170 [wire(72)]  >> "Content-type: application/json[\r][\n]"
DEBUG 2016-09-06 15:35:07,170 [wire(72)]  >> "Content-Length: 450[\r][\n]"
DEBUG 2016-09-06 15:35:07,171 [wire(72)]  >> "Host: hooks.slack.com[\r][\n]"
DEBUG 2016-09-06 15:35:07,171 [wire(72)]  >> "Connection: Keep-Alive[\r][\n]"
DEBUG 2016-09-06 15:35:07,171 [wire(72)]  >> "User-Agent: Apache-HttpClient/4.3.1 (java 1.5)[\r][\n]"
DEBUG 2016-09-06 15:35:07,172 [wire(72)]  >> "[\r][\n]"
DEBUG 2016-09-06 15:35:07,175 [headers(272)] >> POST /services/hogehoge HTTP/1.1
DEBUG 2016-09-06 15:35:07,176 [headers(275)] >> Content-type: application/json
DEBUG 2016-09-06 15:35:07,176 [headers(275)] >> Content-Length: 450
DEBUG 2016-09-06 15:35:07,176 [headers(275)] >> Host: hooks.slack.com
DEBUG 2016-09-06 15:35:07,177 [headers(275)] >> Connection: Keep-Alive
DEBUG 2016-09-06 15:35:07,177 [headers(275)] >> User-Agent: Apache-HttpClient/4.3.1 (java 1.5)
DEBUG 2016-09-06 15:35:07,185 [wire(86)]  >> "{ "knowledge_id": 1, "title": "[0xe8][0xa8][0x98][0xe4][0xba][0x8b][0xe3][0x82][0xbf][0xe3][0x82][0xa4][0xe3][0x83][0x88][0xe3][0x83][0xab]", "content": "[0xe8][0xa8][0x98][0xe4][0xba][0x8b][0xe6][0x9c][0xac][0xe6][0x96][0x87]", "status": "created", "public_flag": 10, "tags": [    "Sample" ], "groups": [    "ALL USERS" ], "like_count": 2, "comment_count": 3, "type_id": -100, "link": "http://example.jp/knowledge/open.knowledge/view/1", "insert_user": "[0xe8][0xa8][0x98][0xe4][0xba][0x8b][0xe6][0x8a][0x95][0xe7][0xa8][0xbf][0xe3][0x83][0xa6][0xe3][0x83][0xbc][0xe3][0x82][0xb6][0xe5][0x90][0x8d]", "insert_date": "2016/04/11 01:42:40", "update_user": "[0xe8][0xa8][0x98][0xe4][0xba][0x8b][0xe6][0x9b][0xb4][0xe6][0x96][0xb0][0xe3][0x83][0xa6][0xe3][0x83][0xbc][0xe3][0x82][0xb6][0xe5][0x90][0x8d]", "update_date": "2016/04/11 01:42:40"}"
DEBUG 2016-09-06 15:35:07,791 [wire(72)]  << "HTTP/1.1 500 Server Error[\r][\n]"
DEBUG 2016-09-06 15:35:07,791 [wire(72)]  << "Content-Type: text/html[\r][\n]"
DEBUG 2016-09-06 15:35:07,792 [wire(72)]  << "Content-Length: 39[\r][\n]"
DEBUG 2016-09-06 15:35:07,793 [wire(72)]  << "Connection: keep-alive[\r][\n]"
DEBUG 2016-09-06 15:35:07,793 [wire(72)]  << "Access-Control-Allow-Origin: *[\r][\n]"
DEBUG 2016-09-06 15:35:07,794 [wire(72)]  << "Content-Security-Policy: referrer no-referrer;[\r][\n]"
DEBUG 2016-09-06 15:35:07,794 [wire(72)]  << "Date: Tue, 06 Sep 2016 06:35:07 GMT[\r][\n]"
DEBUG 2016-09-06 15:35:07,794 [wire(72)]  << "Server: Apache[\r][\n]"
DEBUG 2016-09-06 15:35:07,795 [wire(72)]  << "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload[\r][\n]"
DEBUG 2016-09-06 15:35:07,795 [wire(72)]  << "Vary: Accept-Encoding[\r][\n]"
DEBUG 2016-09-06 15:35:07,795 [wire(72)]  << "X-Frame-Options: SAMEORIGIN[\r][\n]"
DEBUG 2016-09-06 15:35:07,796 [wire(72)]  << "X-Slack-Backend: h[\r][\n]"
DEBUG 2016-09-06 15:35:07,796 [wire(72)]  << "X-Cache: Error from cloudfront[\r][\n]"
DEBUG 2016-09-06 15:35:07,796 [wire(72)]  << "Via: 1.1 f8ebfacf2280f8de661be7a1f87ba74e.cloudfront.net (CloudFront)[\r][\n]"
DEBUG 2016-09-06 15:35:07,797 [wire(72)]  << "X-Amz-Cf-Id: 2f4f64hFwKyqhPY2rFud1Fa_TAnTCTVdm60Zk0rV9D94Ysf01itkbw==[\r][\n]"
DEBUG 2016-09-06 15:35:07,797 [wire(72)]  << "[\r][\n]"
DEBUG 2016-09-06 15:35:07,797 [DefaultClientConnection(253)] Receiving response: HTTP/1.1 500 Server Error
``

JSON部分と思われるところを抜き出してみたところ
``
 "{ 
     "knowledge_id": 1, 
     "title": "[0xe8][0xa8][0x98][0xe4][0xba][0x8b][0xe3][0x82][0xbf][0xe3][0x82][0xa4][0xe3][0x83][0x88][0xe3][0x83][0xab]", 
     "content": "[0xe8][0xa8][0x98][0xe4][0xba][0x8b][0xe6][0x9c][0xac][0xe6][0x96][0x87]", 
     "status": "created", 
     "public_flag": 10, 
      "tags": [    
                  "Sample" 
      ], 
      "groups": [    
                   "ALL USERS"
       ], 
       "like_count": 2,
       "comment_count": 3, 
       "type_id": -100, "link": "http://example.jp/knowledge/open.knowledge/view/1", 
       "insert_user": "[0xe8][0xa8][0x98][0xe4][0xba][0x8b][0xe6][0x8a][0x95][0xe7][0xa8][0xbf][0xe3][0x83][0xa6][0xe3][0x83][0xbc][0xe3][0x82][0xb6][0xe5][0x90][0x8d]", 
        "insert_date": "2016/04/11 01:42:40", 
        "update_user": "[0xe8][0xa8][0x98][0xe4][0xba][0x8b][0xe6][0x9b][0xb4][0xe6][0x96][0xb0][0xe3][0x83][0xa6][0xe3][0x83][0xbc][0xe3][0x82][0xb6][0xe5][0x90][0x8d]", 
        "update_date": "2016/04/11 01:42:40"
}"
``
になるかと思われます。
SlackのWebHook設定に、送信するJSONには"text"というプロパティを含めることといった記述があるのですが、ログに出力されたこのJSON"text"というプロパティが無い様なので何か設定に不備があるかと考えております。

Dockerイメージについてはこちらの方も試してみたいと思います。有り難うございました。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

Knowledgeが出すWebHookがSlackに対応していないようですね。
（送信するJSONにtextプロパティは、もともと入っていません）

今のところ送信する形式は、固定なのですが、JSONの形式を変更できるように処理を拡張することも考えようと思います。

**Comment by vtjkinoshita** [comment]
textプロパティが入っていないということで了解いたしました。

チーム内で話したところ「どうしても投稿をSlackに送信して欲しい」という要望があり、ソースを取得して下記のソースを修正してWebリンク付きの投稿をSlackに対して行うように対応してみました。
/src/main/java/org/support/project/knowledge/logic/WebhookLogic.java

修正内容としては下記内容を付け加えたモノになっております。
ほとんど素人の手直しレベルで申し訳ございません、もっと良い修正があるようでしたらご指摘
いただけると幸いです。

イベント部分

``
    public Map<String, Object> getKnowledgeData(KnowledgesEntity knowledge, Integer type) {
    	Map<String, Object> jsonObject = new HashMap<String, Object>();

        String linktop = "<";
        String linkpipe = "|";
        String linkend = ">";
        
        StringBuffer SendBuff = new StringBuffer();
        SendBuff.append(linktop);
        SendBuff.append(NotifyLogic.get().makeURL(knowledge.getKnowledgeId()));
        SendBuff.append(linkpipe);
        SendBuff.append(knowledge.getTitle());
        SendBuff.append(linkend);
        String SendString = SendBuff.toString();

        jsonObject.put("text", SendString);
``

コメント部分

``
 public Map<String, Object> getCommentData(CommentsEntity comment, KnowledgesEntity knowledge) {
        Map<String, Object> jsonObject = new HashMap<String, Object>();

        String linktop = "<";
        String linkpipe = "|";
        String linkend = ">";
        
        StringBuffer SendBuff = new StringBuffer();
        SendBuff.append(linktop);
        SendBuff.append(NotifyLogic.get().makeURL(knowledge.getKnowledgeId()));
        SendBuff.append(linkpipe);
        SendBuff.append(knowledge.getTitle());
        SendBuff.append(linkend);
        String SendString = SendBuff.toString();
        
        jsonObject.put("text", SendString);
``

Slackへの投稿には対応したのですがチーム内から更に要望が出ており、修正を更に行う必要がありそうなので私共のチーム内向けに手作業で対応する方向で考えております。

以上、よろしくお願いいたします。

**Comment by koda-masaru** [comment]
> ほとんど素人の手直しレベルで申し訳ございません、もっと良い修正があるようでしたらご指摘
いただけると幸いです。

今回はSlackに対応させることが要求ですので、上の修正で問題無いと思います。
私でも同じように対応すると思います。

欲を言えば、Slack以外のツールにも連携できるように、WebHookに送信するJSONの形を、
設定画面で変換をかけたり出来ると嬉しいですね。
今後の改修の中で、検討しようと思います。

> Slackへの投稿には対応したのですがチーム内から更に要望が出ており、修正を更に行う必要がありそうなので私共のチーム内向けに手作業で対応する方向で考えております。

自分の組織用に、業務と関係なく作ったもなので、仕様書やテストコードがほぼ無いので、わかりづらいコードですみません。
アーキテクチャの説明や、コードの説明などのハンズオンのような説明会が開けると良いかなとも
思っているのですが、需要があるかな？という感じです。
わからないことなどあれば、またご連絡ください。

よかったらですが、プルリクも送ってくださいね。

**Comment by vtjkinoshita** [comment]
> 今回はSlackに対応させることが要求ですので、上の修正で問題無いと思います。
> 私でも同じように対応すると思います。

ひとまずの対応としては問題ないということで了解しました。

> 欲を言えば、Slack以外のツールにも連携できるように、WebHookに送信するJSONの形を、
> 設定画面で変換をかけたり出来ると嬉しいですね。
> 今後の改修の中で、検討しようと思います。

WebHookを対象となるサービスをドロップダウンリストで表示して選択すると選択した対応した
JSONを生成する様になるみたいなモノがあるのが良いのかもしれませんね。

>自分の組織用に、業務と関係なく作ったもなので、仕様書やテストコードがほぼ無いので、わかりづらいコードですみません。

いえいえ、ざっと見て大体のところは何となく分かったので大丈夫かと思います。

>アーキテクチャの説明や、コードの説明などのハンズオンのような説明会が開けると良いかなとも
思っているのですが、需要があるかな？という感じです。
>わからないことなどあれば、またご連絡ください。

そうですねコード読書会とか、使ってる人が集まってどの様に使っているかLTをしてもらったりするみたいなのがあると助かります。

プルリクですがPushで 403が帰ってきていて、現在アカウント周りを確認中です(汗 気長にお待ちください
以上、有り難うございました。

**Comment by nagodon** [comment]
@koda-masaru 
ご対応ありがとうございます。

@vtjkinoshita 
こちら実装時にまずhubotのhttp待ち受けなどを介してその他チャットサービスに通知する前提で作ったため既存チャットサービスに対応しておりませんでした。

**Comment by nagodon** [comment]
> WebHookを対象となるサービスをドロップダウンリストで表示して選択すると選択した対応した
> JSONを生成する様になるみたいなモノがあるのが良いのかもしれませんね。

こちらだと対応可能ですが、通知のフォーマットが指定したくなりそうですね。

**Comment by koda-masaru** [comment]
> WebHookを対象となるサービスをドロップダウンリストで表示して選択すると選択した対応した
JSONを生成する様になるみたいなモノがあるのが良いのかもしれませんね。

利用者が簡単に使えることを考えると、Slackのような良く使われるサービスを選択できる仕組みはありがたいでしょうね。

> こちらだと対応可能ですが、通知のフォーマットが指定したくなりそうですね。

私もフォーマット指定を出来ると良いと思いました。
WebHookを設定するような人（≒JSONなどの知識がある人）だと、自由にフォーマットを指定できるような仕組みがあっても、使いこなせるのではないでしょうか？

例えば、 `$KNOWLEDGE_ID' や '$TITLE' , '$CONTENT' といった予約語を定義しておいて、
JSONのフォーマットは自由にカスタマイズできるという方法があるかなと思います。

■フォーマット例

```
{
     "id": "$KNOWLEDGE_ID",
     "title": "$TITLE",
     "content": "$CONTENT"
}
```

カスタマイズとしては、例えば、 `"content": ` の部分を  `"text": ` に変えるといった事ができるようになります。

**Comment by vtjkinoshita** [comment]
@koda-masaru さん
先程プルリクをお送りしました。一応ご参考までにということで、よろしくお願いいたします。

>私もフォーマット指定を出来ると良いと思いました。
>WebHookを設定するような人（≒JSONなどの知識がある人）だと、自由にフォーマットを指定できるような仕組みがあっても、使いこなせるのではないでしょうか？

確かに使う人によって送信して欲しい情報とかが違ってくる場合もあるので使う人が指定できるというのはよさそうですね。

@nagodon  さん
>こちら実装時にまずhubotのhttp待ち受けなどを介してその他チャットサービスに通知する前提で作ったため既存チャットサービスに対応しておりませんでした。

まぁ、普通は機能については配布されているモノをそのまま使うものですし、オープンソースなのですから自分達で使う場合に足りない機能は基本自分達で何とかするもという認識ですので大丈夫です。
今回もチーム内で使ってもらったところ「Slackに送信できない以外は良く出来ているので何とかして」というのがキッカケでした。
また何かありましたら質問等をさせていただくかと思いますがよろしくお願いいたします。

**Comment by koda-masaru** [comment]
プルリクありがとうございました。

JSONに項目が追加されるだけなので、悪い影響は出ないと思いますし、
Slackと連携したいユーザも多いと思いますので、マージさせていただきます。
いずれは、フォーマット変更に対応しようと思います。

**Comment by vtjkinoshita** [comment]
マージいただき有り難うございました。
チーム内では要望があるようなので、ローカルで小幅な修正を行っていく方向です。
取りあえず、一旦こちらはクローズということでお願いしたいと思います。

ありがとうございました。

**Comment by koda-masaru** [comment]
こちらこそプルリクありがとうございました。
また何かご不明点などあればご連絡ください。

issueはリリースするまでそのまま開いておいて、
リリースノートを書いた後でクローズしています。
（リリースノートを書く履歴に使ってます）

もうしばらくしたら、v1.6.0のプレリリースを出そうと思っていますので、
その後にクローズしたいと思います。

**Comment by koda-masaru** [comment]
v1.6.0 pre1でリリース済。クローズします。
リリースしたものに問題があれば、別途のissueを登録願います。
