### ISSUE TITLE
IE対応

### ISSUE THREAD

**Issue by yuann** [support-project/knowledge#46]
## IE8
うちの社内だと年末までIE8推奨なので、対応してもらえると嬉しいです
（あと半年耐えればいい話ではあるのですが…）
http://qiita.com/kimromi/items/d2f234c90c07f5417a8f

## IE11
互換表示設定をされているIE11でも閲覧できるようになると嬉しいです
たぶん、以下の様な指定があると互換表示が働かなくなるとおもうのですが…

```html
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
```

**Comment by koda-masaru** [comment]
なるほど。
上を見ると、対応は難しく無さそうなので、後で対応します。

ただ、IEの環境が無いので、正しく動くかの確認が出来ません。。。。

**Comment by yuann** [comment]
動作は確認してみますのでよろしくお願いします！

**Comment by koda-masaru** [comment]
了解です:smile:
対応できたら、プレリリースします :+1:

**Comment by koda-masaru** [comment]
0.5.2 pre1 でIE対応してみました。動くでしょうか？？

**Comment by yuann** [comment]
出来ればwarファイルも作っていただけますでしょうか…。
うちの会社からだとデモサイトにアクセスできないみたいなので。
月曜日に動作確認してみます。

**Comment by koda-masaru** [comment]
warを添付したつもりが、上手くアップロード出来てませんでした。
プレリリースにwarをアップしましたので、確認お願いします :+1:

**Comment by yuann** [comment]
中間報告です。
IE11の開発者ツールで設定を変えて試しただけですが、IE8対応は駄目みたいですね。
私が提示したサイトの解決策

- html5shiv.js
- respond.js

ですと、HTMLとCSSは解決できるかもしれないですが、javascriptで問題が出るようです。
最低でも、jQueryを1.x系に、highlight.jsを使わない方向にしないといけないようで、おまけで対応するには重いと思われます。

**エラー内容**
> オブジェクトは 'forEach' プロパティまたはメソッドをサポートしていません。
プロパティ 'addEventListener' の値は Null または未定義で、Fuction オブジェクトではありません。

**Comment by koda-masaru** [comment]
確認ありがとうございます。
jQueryは2系から1系に変更して0.5.2pre1を作ったのですが、
その他のライブラリでエラーが出ましたか。。。

確かに、おまけで対応は難しいですね。

でも、エラーとか出ると言われるとなおしたくなります。
私がレガシーなIEの環境があれば確認できるのでなんとかなると思うのですが、、、、

いったん対応保留としますね。

**Comment by yuann** [comment]
互換表示設定されているIE11で問題なく表示できることが確認できました。
ということで、X-UA-Compatibleの設定のみしていただければいいかと思います。

**Comment by koda-masaru** [comment]
確認ありがとうございます :smile: 
すごく助かります。
では、まずはIE11用に「X-UA-Compatible」だけ設定しようと思います。

**Comment by koda-masaru** [comment]
IE11用の設定でリリースしたので、いったんクローズします
