### ISSUE TITLE
＃415 関連 公開範囲を絞っている場合、添付ファイルの中身を検索する場合に管理者しか検索できない

### ISSUE THREAD

**Issue by rainthestorm** [support-project/knowledge#461]
#415 に関連してのissue登録です。

公開範囲を保護に設定した記事について、添付ファイルの中身が、公開先Groupに含まれるUserが検索した際に引っかかってきません。
UserにAdministrator権限を与えたら、検索にひっかかるようになりました。
（追記：再度Administrator権限を外すと検索に出なくなったと記憶しています）
V1.5.0を使っています。

**Comment by koda-masaru** [comment]
v1.5.0より前に登録した添付ファイルではないでしょうか？
前に登録したファイルは、権限がセットされていないため検索にヒットしません。

v1.5.0へのマイグレーション時に、権限をセットしなおす事も考えたのですが、登録されている
添付ファイルの数が膨大な可能性もあるので、いったん再パース（≒権限の付け直し）は実施しない
ようにしました。

DBにつなぎ、以下のSQLを実行すると、全ての添付ファイルを再パースします。
（処理に時間がかかります＆それまでCPU負荷が高くなります）

```
UPDATE KNOWLEDGE_FILES SET PARSE_STATUS = 0;
```

特定のファイルを再パースしたい場合は、上記のSQLにWHEREを追加してください。

```
UPDATE KNOWLEDGE_FILES SET PARSE_STATUS = 0 WHERE FILE_NO = ?;
```

上記の対策で検索できるようになるかご確認願います。

**Comment by rainthestorm** [comment]
現在稼働させているサーバには構築時からV1.5.0を入れています（最近本格的にはじめました）
途中でDBを組み込みからPostgreSQLに変更したので、再パースが必要かも？
ご指示いただいた作業を試してみます。

**Comment by koda-masaru** [comment]
v1.5.0からお使いでしたか。
そうすると、添付ファイルの検索インデックス生成の部分の不具合のような気がします。
調べてみますので少々お待ち下さい。

**Comment by rainthestorm** [comment]
SQLからの再パースが上手く出来なかったため、
Knowledgeシステム設定内機能でのインデックス再構築を行ったところ、
User権限のみのアカウントでも、公開先Groupに所属していればファイルの中身まで検索できるようになりました。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
そういえば、「インデックス再構築」の機能で再パースできますね。
その機能があることを忘れていました。
自分で作った機能なのに、その機能があることを忘れてました。。。

とりあえず、解決できたようで安心しました。

**Comment by koda-masaru** [comment]
解決しましたので、本issueはクローズします。
他に問題があれば、別途のissueを登録願います。
