### ISSUE TITLE
添付ファイルクリック時の展開について

### ISSUE THREAD

**Issue by rainthestorm** [support-project/knowledge#462]
V1.5.0
記事に添付しているファイルについて、クリックするとpdfやテキストは現在のタブにて開かれます
Excelやwordを添付すると、クリックした際に“開こうとしているファイル`download`の形式は、ファイル拡張子が示す形式と異なります。。。”とダイアログが表示され、ファイル名がdownloadに変った状態で開かれます。
- target=”_blank”　にて開く
- ファイルを通常ダウンロードして開く
  のどちらかになると見やすいかと思います。

**Comment by koda-masaru** [comment]
ファイルはダウンロード時は、Httpヘッダの contentTypeに"application/octet-stream"を
指定しているため、基本的には全てファイルのダウンロードになると思います。
たぶん、ブラウザの設定毎の挙動の違いだと思われます。

参考までに、ブラウザは何をお使いでしょうか？
なお、ChromeとFirefoxで確認しています。
（IEやEdge、Safariは未確認になります）

**Comment by rainthestorm** [comment]
失礼しました、情報不足でした。
IE11を使用しています。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

IEですか。
すでにブラウザのシェアでIEはかなり低いですし、「標準」の動作とことなる動きが多いので積極的にサポートしていこうとは考えていません。
申し訳ありませんが、IEでのご利用時の制限ご理解ください。
（Chromeなど標準のブラウザであれば、添付ファイルはダウンロードになります）

**Comment by rainthestorm** [comment]
ご検討ありがとうございます。承知しました。

**Comment by koda-masaru** [comment]
対応完了済。
クローズします。
