### ISSUE TITLE
latex 数式の表示

### ISSUE THREAD

**Issue by yanagida** [support-project/knowledge#469]
初めまして，yanagidaと申します．

部署での情報共有を目的としてknowledgeを今テスト導入しているところです．

大方，こちらの要望する機能が備わっており不足なく使えそうな気がするのですが，一点気になるところがあります．
題名である程度予測できると思いますが，code block 内でlatexコードを書いたときに数式に変換されないことです．私事ですが，数式を扱う必要があるためぜひともほしい機能なのです．

類似サービスではよくMathJaxを使っているそうなのですが，これを実装することは可能でしょうか？
プログラミングは多少明るいのですが，tomcat, javaはあまり扱ったことがなく，お願いするだけになってしまい申し訳ないのですが，ご検討のほどしていただけると幸甚に存じます．

以上です．よろしくお願いします．

**Comment by koda-masaru** [comment]
MathJaxというライブラリは存じ上げなかったのですが、少し調べてみると、
かんたんに実装できそうです。

http://medemanabu.net/latex/mathjax/

数式表示を行いたいユーザさんも多いと思うので、追加してみようと思います。

**Comment by yanagida** [comment]
前向きな返答ありがとうございます．
実装楽しみにまたせていただきます．

**Comment by yanagida** [comment]
対応ありがとうございました．

まだ，さわりしか扱っていませんが今のところ問題なく使えています．

さて，使い心地に関してなのですが，
今の使い方では
```math でくくって，さらに内部でtex部分を$でくくる必要があります．
ですが，所感ではこれは冗長的であると感じます．

使用者は```mathセクションを指定した時点でtexコードを書き始めると思うのですが，
今の仕様では追加で$を書く必要があります．

ko-da さんはどのような意図をもってこのような仕様にしたのでしょうか．

**Comment by yanagida** [comment]
あと要望としましてはインラインで表示ができたらと存じます．
ほげほげ$$E = mc^2$$ふがふが．．．のような形で．

ですが，現時点でlatexに対応していただけただけで大変心嬉しい対応です．
余力がありニーズがあるときに対応していただけたら幸甚に存じます．

以上です．

**Comment by koda-masaru** [comment]
> 今の使い方では
> ```math でくくって，さらに内部でtex部分を$でくくる必要があります．
> ですが，所感ではこれは冗長的であると感じます．

特に意図はありませんでした。冗長だったのですね。
Markdownで数式を表現したことが無かったため、一般的にどのように記述するのが正解なのか、わかっていません。

そこで、どのように数式を表現するのか調べてみたら、
\`\`\`math で囲むという方法があるということを見つけたため、まずはそれで囲むようにして、
その後で、MathJaxを調べてみたら、今度は$で囲むとあったので、二重で囲む必要にしていました。（それが普通かとおもってました）

今調べてみたら、以下のURLにQiitaの数式表現の記載仕様が記載されています。

http://qiita.com/PlanetMeron/items/63ac58898541cbe81ada

これに準拠すると、使いやすいですか？

**Comment by yanagida** [comment]
恐らく，markdown的方言 ```mathと，従来のMathJaxの構文が混ざってしまったため，そのような誤解になってしまったのではないかと思います．

参考URLを確認しましたが，私は，この構文でmarkdownを書いています．

ですので参考URLのような構文に対応していただけると幸いです．

======
ちなみにインライン表示の対応願いの文中の，

> ほげほげ$$E = mc^2$$ふがふが．．．のような形で．

は文法ミスですね．
正しくは$--$ですね，失礼いたしました．

**Comment by koda-masaru** [comment]
確認ありがとうございます。
では、できるかぎり参考URLのような形で、数式表現を書けるように修正しようと思います。

修正後にv1.6.0pre3をリリースしますので、再度ご確認ください。

**Comment by yanagida** [comment]
V1.6.0 pre3 を評価してみました．
サンプル用のknowledge に "#469 tex 表示の評価"として投稿してみました．

気になる点が何点かありました．
* \\ （円マーク）がエスケープ文字として解釈される
* ```math block　のエラー
* 数式中に \\label を指定すると，コンテンツとプレビューを行き来したときにバグる．
* \\begin{aligin\*} blockを指定すると\*がボールドとして解釈される．

\\ のエスケープに関しては対応していただきたいバグ（ふるまい）です．
冗長的に書かなければならなくなりますし，可読性，流用性も低下してしまいます．

```math blockの挙動は恐らく内部処理的な問題だと思います．

\\label の挙動に関しても考えが及びませんのでバグとして報告させていただきます．

\\begin{align}は試してみたらできたので加えて報告します．
ただ，\\begin{align\*}を指定したときに\*がボールドとして処理されてしまいます．
両者の違いは式番をつけるかつけないかです．

もし，\\begin{align\*}の問題が解決できるのであれば MathJaxのconfigに，
`TeX: { equationNumbers: { autoNumber: "AMS" } }`を追加するのもいいかもしれません．
このコンフィグは，$$指定時またはalignで式を定義したときに自動的に式番を振る機能です．
私的にはこの機能はとても便利に感じます．
実は，ソースコードを解析してこのコンフィグを加えてみたら普通に動作しました．
ただ，エディタのプレビューでは見れて，パブリックのプレビューでは式番が消えてしまっていました．
まあ，多分私の設定ミスなのですが（views/protect/knowledge/partials/partials-edit-scripts.jsp をいじりました）．

以上です．よろしくお願いします．

**Comment by koda-masaru** [comment]
確認ありがとうございます。
数式の記法（LaTeX）について知識が無いので、とても助かります。
Markdownの中に、他の記法を組み込んでいるので、いろいろ課題がありますね。

例えば、

- \ （円マーク）がエスケープ文字として解釈される

ですが、Markdownでは、\ （円マーク）はエスケープ文字になります。コードブロックについても、
Markdownの中に書いているのでおかしい事になるのかなと思います。

この点を踏まえると、同じ記事内に2つの記法を混在させるのでは無く、記事の登録時点で
Markdownを選ぶ／LaTeXで数式の記法を選ぶかを選択した方が良い気がしてきました。
どう思いますか？

**Comment by yanagida** [comment]
記法を選ぶというのは反対です．
きっと書きやすいMarkdownだからこそ手軽に記事が書け，
同一のフォーマットだからこそ万人から利用されるのだと私は思います．

わざわざフォーマットを選択するのであるならば極論，latexでPDFを作成してそれをアップロードすればいいんじゃないかと思います．

とは言いつつ，やはりストレスなくlatexを書きたいという要望はありますが．
そこでちょろっと私自身で調べてみたら以下のような記事がありました．
[markdown+mathjaxをブラウザで](http://qiita.com/DUxCA/items/27b7b865a0ab28b5d530)
この記事の中でmarked + latex の変換時の問題で`<pre>`を使って回避しているとの記述があります．
この対策は今回の問題に適用させることができますでしょうか？

頼んでばかりで心苦しいですが，ご検討していただけると幸いです．

------
このプロジェクトに対して直接はコミットできませんが，私の隙間時間を見つけて，npm marked + latex + mathjax のふるまいを検討してみたいとも存じます．

**Comment by koda-masaru** [comment]
確かに記法を選択するのは、登録の敷居を上げてしまうかもしれませんね。
Markdownの中で、LaTexでの数式表記をもう少しうまく解釈できないか、
いじってみようと思います。（LaTexの数式表記に疎いので、思い通りに
ならないかもですが）

できたら、今度は pre4 を出してみようと思います。少々お待ちを。

**Comment by koda-masaru** [comment]
v1.6.0 pre4 をリリースしてみました。デモサイトも更新しています。

$$ブロックや \`\`\`math ブロックで、\\ （円マーク）をエスケープ文字として解釈しないようにしてみました。

また、\`\`\`math ブロックは、\`\`\`mathの中身を、内部的には$$ブロックにするように変更しました。
このため、\`\`\`math ブロックには、一つの数式しか書けないようになっていると思います。
（かわりに、\\\\ で改行して複数行の数式を正しく解釈すると思います。）

これで使いやすい登録記法になっているでしょうか？

**Comment by yanagida** [comment]
確認しました．

多少ですが癖を感じますが，あまり気にならない程度だと思います．
\\ のエスケープの対応をしていただいただけでも断然書きやすくなりました．
癖を感じる部分も投稿者が多少気に留めればいいレベルのものだと私は思います．

後は皆さんに使っていただいて，要望を叶えていくようにしてもいいと思います．（私も見落としがあると思いますし）
こればっかりに対応していては，せっかくの次期素晴らしい機能も塩漬けになってしまいますし．

以上です．

**Comment by koda-masaru** [comment]
確認ありがとうございます。

> 後は皆さんに使っていただいて，要望を叶えていくようにしてもいいと思います

そうですね。
pre4を正式リリース候補版として、少し様子見して問題がなさそうであれば正式リリースへ
進めようと思います。

いろいろアドバイスいただき、ありがとうございました 🙇

**Comment by koda-masaru** [comment]
v1.6.0を正式にリリースしたため、いったん、クローズします。
他に、何か気になることがあれば、別issueを作成します。
