### ISSUE TITLE
すでに登録済みのタグの文字列より短い文字列のタグを入れたい、などタグ入力時の挙動について

### ISSUE THREAD

**Issue by TakashiAbe** [support-project/knowledge#473]
たとえば「WEBサイト」というタグがすでに登録済みの場合において、
さらに「WEB」というタグを入れたいとき、どうやっても勝手に「WEBサイト」の補完が効いてしまって追加ができません。

また、MacのSafariの最新版でタグ入力にアルファベットが先頭の場合、タグ入力ができないことが多々あります。

ご確認のほどよろしくお願いいたします。

**Comment by koda-masaru** [comment]
タグで選択候補が表示されているときに、
ESCボタンを押すと、選択候補が消えます。
そうすることで、自動候補から選択しないで、新しいタグを登録できます。

MacのSafariについては何か問題があるか確認してみます。

**Comment by TakashiAbe** [comment]
ESCで回避できるということで試してみたところ、確かに回避できました。
MacのSafariの件もESCの件で再度確認してみたところ、特に問題ないかもしれないです。
ありがとうございました。

**Comment by koda-masaru** [comment]
ESCで回避はできるのですが、タグの入力保管が効きすぎるという意見は前からありましたので、
入力保管（typeahead）をOFFにできるスイッチのようなものを提供しようかと思います。

**Comment by koda-masaru** [comment]
#514 に新たなissueとして登録しました。
本issueとしては、いったん解決済ですので、クローズいたします。
