### ISSUE TITLE
v1.6.0 pre2 update 失敗?

### ISSUE THREAD

**Issue by yanagida** [support-project/knowledge#483]
latex 対応をお願いした者です．

v1.6.0 pre2 で早速latex対応してくれたらしく，とってもウキウキしながらreleases pageの'Downloads'のknowledge.warをダウンロードして，
tomcat/webapps/ 中のv1.6.0pre1の.warファイルと置換してtomcatを再起動したのですが，latexを変換表示することができませんでした．

そこで，デプロイしたknowledgeのライセンスページを表示してみると，
"Knowledge - v1.6.0 - pre1"
と表示されていました．
何度かダウンロードしなおしても，tomcatを再起動しても変わりませんでした．

これはupdateが失敗したのでしょうか？
それとも他の理由でしょうか？

ご指南いただけると幸甚に存じます．

**Comment by koda-masaru** [comment]
早速の確認、ありがとうございます。

私の環境にて、先日リリースしたv1.6.0pre2のwarをダウンロードして、確認してみたのですが
数式表示ができました。
https://github.com/support-project/knowledge/releases/download/v1.6.0pre2/knowledge.war

ライセンスページも、デモサイトと同じく、「Knowledge - v1.6.0 - pre2」の表示になりました。

とすると、warのアップデートがうまくいかなかったと思います。

warだけを上書きすればアップデートできると思ったのですが、warを展開したディレクトリも
削除しないとアップデートしないのかもしれません。
そこで、tomcat/webapps/ の中の knowledge.war 及び、 knowledgeディレクトリを削除した後
tomcatを再起動してみてください。

**Comment by yanagida** [comment]
お返事ありがとうございます．

深夜の眠たげな頭をいったんリセットし，改めて確認したところ，しょうもないサーバ側の設定ミスでした．
無事更新することができました．．

つまらないissueをたててしまいすいませんでした．
以上です．よろしくお願いします．

**Comment by koda-masaru** [comment]
無事に解決したようで安心しました。
本issueはクローズいたします。
