### ISSUE TITLE
Power point 表示　豆腐

### ISSUE THREAD

**Issue by yanagida** [support-project/knowledge#484]
knowledge 作成時にpptxファイルをアップロードし，”スライドショー表示”を指定してknowledgeを保存しました．
その後スライドを確認してみると日本語が豆腐になってしまいました．
英語は正常に表示されていました．

ご指南いただけると幸いです．

knowledge: v1.6.0 pre2
tomcat: Apache Tomcat/8.0.37
JVM: oracle 1.8.0_101-b13
OS: centos 6.8

**Comment by koda-masaru** [comment]
OSがcentos 6.8になっていますが、日本語が扱える環境でしょうか？
日本語フォントがインストールされていない環境だと、パワーポイントやPDFからスライドショーを
生成する際（スライドの画像を抽出しています）に、正しく表示できなくなります。

私の環境はUbuntsですが、以下の日本語環境のモジュールをインストールした環境でKnowledgeを
動かしています。

```
apt-get install language-pack-ja fonts-ipaexfont-gothic
```


また、もしDockerをご利用であれば、日本語環境でも簡単に動作できるように日本語のイメージを作成しました。以下でイメージを取得してご利用ください。
（デモサイトは、そのイメージをベースに動いています）

```
docker pull koda/docker-knowledge:pre-japanese
```

**Comment by yanagida** [comment]
無事変換できました．フォントの不足が原因でした．

OSはenglish imageをインストールしました．
ですが日本語フォントが必要だったので（tex compile server用として）IPA系のフォントを別途インストールしていました．
が，それではダメだったようです．
centos用の日本語サポートをインストールすると変換できました．
```bash
yum groupinstall "Japanese Support"
```

もしかしたらyumさんがいい具合に設定をいじってくれたのかもしれませんが，
素の英語環境では探しに行ってくれなかったそうです．

以上です．

**Comment by koda-masaru** [comment]
対応済みとしてissueはクローズいたします。
