### ISSUE TITLE
検索キーワードの末尾に全角二重引用符を使うと異常終了する

### ISSUE THREAD

**Issue by miyohide** [support-project/knowledge#485]
Release v1.4.1を使わせて頂いております（CentOS 6.8、Java 1.8.0_101、Tomcat 8.0.36、PostgreSQL 9.5上で稼動。クライアントはWindows 7＋InternetExplorer 11）。

検索キーワードに「"あああ”」（前の二重引用符は半角、後ろの二重引用符は全角（Unicode U+201CもしくはU+201D））と指定して検索処理を行うと、以下のスタックトレースを出力して異常終了（Internal Server Error）します。
文字列を全角の二重引用符（Unicode U+201CもしくはU+201D）で囲むと異常終了しません。

ご確認、よろしくお願いします。

> INFO  2016-10-06 14:25:32,553 [Intercepter(213)] error. [object]class org.support.project.knowledge.logic.KnowledgeLogic_$$_jvstedb_5[proceed]_d24searchKnowledge[param0]"あああ”[param1]null[param2]null[param3]null[param4]0[param5]50
> [throwable.getMessage()] Cannot parse '"あああ”': Lexical error at line 1, column 6.  Encountered: <EOF> after : "\"\u3042\u3042\u3042\u201d"
> ERROR 2016-10-06 14:25:32,553 [ControlManagerFilter(204)] ERROR SEND
> ERROR 2016-10-06 14:25:32,554 [LoggingFilter(64)] Any exception is thrown. [javax.servlet.ServletException]
> javax.servlet.ServletException: javax.servlet.ServletException: org.support.project.common.exception.SystemException:
>         at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:309)
>         at org.support.project.knowledge.listener.CloseAbleAuthenticationFilter.doFilter(CloseAbleAuthenticationFilter.java:94)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
>         at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:62)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
>         at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
>         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
>         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
>         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
>         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
>         at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
>         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
>         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
>         at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:873)
>         at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: javax.servlet.ServletException: org.support.project.common.exception.SystemException:
>         at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:214)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
>         at org.support.project.web.filter.MultipartFilter.doFilter(MultipartFilter.java:63)
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
>         at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:193)
>         ... 24 more
> Caused by: org.support.project.common.exception.SystemException:
>         at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:136)
>         at org.support.project.web.common.InvokeTarget.invoke(InvokeTarget.java:106)
>         at org.support.project.web.filter.ControlManagerFilter.doInvoke(ControlManagerFilter.java:360)
>         at org.support.project.web.filter.ControlFilter.invoke(ControlFilter.java:31)
>         at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:181)
>         ... 30 more
> Caused by: java.lang.reflect.InvocationTargetException
>         at org.support.project.common.util.ObjectUtils.invoke(ObjectUtils.java:132)
>         ... 34 more
> Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse '"あああ”': Lexical error at line 1, column 6.  Encountered: <EOF> after : "\"\u3042\u3042\u3042\u201d"
>         at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:133)
>         at org.support.project.knowledge.searcher.impl.LuceneSearcher.structQuery(LuceneSearcher.java:201)
>         at org.support.project.knowledge.searcher.impl.LuceneSearcher.search(LuceneSearcher.java:112)
>         at org.support.project.knowledge.logic.IndexLogic.search(IndexLogic.java:53)
>         at org.support.project.knowledge.logic.KnowledgeLogic.searchKnowledge(KnowledgeLogic.java:454)
>         at org.support.project.knowledge.logic.KnowledgeLogic.searchKnowledge(KnowledgeLogic.java:491)
>         at org.support.project.knowledge.control.open.KnowledgeControl.list(KnowledgeControl.java:439)
>         ... 35 more
> Caused by: org.apache.lucene.queryparser.classic.TokenMgrError: Lexical error at line 1, column 6.  Encountered: <EOF> after : "\"\u3042\u3042\u3042\u201d"
>         at org.apache.lucene.queryparser.classic.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1133)
>         at org.apache.lucene.queryparser.classic.QueryParser.jj_ntk(QueryParser.java:640)
>         at org.apache.lucene.queryparser.classic.QueryParser.Modifiers(QueryParser.java:138)
>         at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:182)
>         at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:172)
>         at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:123)
>         ... 41 more
>

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

検索キーワードに想定外の文字列が入力されるとエラーが発生する現象が他にも報告されていまして、v1.6.0 pre1 にて対応を行っています。
（issue #439 にて対応）

このため、v1.6.0pre1以降をご利用いただくとエラーが発生しなくなります。
もしプレリリース版は利用したくないということであれば、もう暫くしたらv1.6.0の正式版をリリースしますので、それまでお待ち下さい。

**Comment by miyohide** [comment]
@koda-masaru ご連絡ありがとうございます。v1.6.0 pre1で対応済みの件、了解しました。最新版で確認できておらず、申し訳ございません。

すでに対応済みということから、Closeいたします。お騒がせしました。
