### ISSUE TITLE
chrome 使用時にリロードF5すると内容が消える

### ISSUE THREAD

**Issue by yanagida** [support-project/knowledge#488]
V1.6.0 pre3を使用しています．

コンテンツに文書を追加した（変更を加えた）ときにページをリロードすると内容が消えてしまいます．

Firefox 49.0.1ではリロードしても内容が残っているのですが，
chrome 53.02785.143 m 64bit ではリロードすると内容が消えてしまいます．
ちなみにEdge 38.14393.0.0 ではリロードすると消えてしまいました．

これはブラウザの仕様なのでしょうか？

**Comment by koda-masaru** [comment]
> これはブラウザの仕様なのでしょうか？

はい。ブラウザの仕様です。
現在の作りですと、編集画面をリロードした場合、保存されている情報を再読込するため、
保存されていない変更は消えるのが普通です。

ただ、FireFoxはページ遷移しないでリロードすると、変更をブラウザが保持する性質を持っており、
そのために変更が残っているようになります。

**Comment by yanagida** [comment]
なるほど，了解いたしました．

**Comment by koda-masaru** [comment]
いったん解決済ですので、本issueはクローズします。
