### ISSUE TITLE
添付ファイルサイズ制限を設定可能に

### ISSUE THREAD

**Issue by CSKamonohasi** [support-project/knowledge#489]
添付ファイルのサイズ制限(10MB)をシステム設定で変更(例30MBとか100MBとか)できると使いやすいと思いますが、いかがでしょうか。

今般使用を開始して過去の研修レジュメデータなどを登録しようとしたところ10件中2件ほどが15MByte程度の大きなファイルでした。
ファイルを分割して登録しましたが、社内LANでのみ運用予定のため、サイズ制限はもうすこし緩くできるとありがたと感じました。

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。確かにそうですね。
変更はそれほど大変で無いので、今後追加していこうと思います。
