### ISSUE TITLE
編集画面のUI変更についての提案

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#490]
UIについての細かい話となってしまいますがご了承ください。
### 1. 説明文の表記について

![ss_006](https://cloud.githubusercontent.com/assets/15116901/19255229/a2669a58-8f96-11e6-976f-e40ebd1b3d09.png)

この「種類」などに関する説明文なのですが、初めて記事を書く場合は確認したい場合があると思いますが、二回目以降はもうわかっている情報なので表示する必要がないように思います。

そのため、記事を書いたことがない人だけチュートリアル的に表示し、1つ以上記事を持っている人は表示しない、またはツールチップでのみ表示する、などの修正が良いのではないかと思います。

また、「種類」説明文のみ背景色が設定されているため、見方によってはタイトルよりも目立つ状態になっているのも気になります。

---
### 2. メタ情報選択UIの一貫性

現状、「種類」と「公開範囲」によって入力可能なメタ情報が増減しています。

ですが、
- 種類
- 公開範囲
- タイトル
- タグ

は必須で、
- 公開先を選択(保護公開の場合のみ)
- Status(Weekly Reportの場合のみ)
- Problem(Weekly Reportの場合のみ)
- URL(bookmarkの場合のみ)

は各条件に適合する場合のみ必須となっています。

それらの増減する項目が、必須の間に入ったり入らなかったりしていて、若干の混乱があるように感じます。

---

そこで、サンプルとして構成を変更したものを提案させて頂きます。

![ss_009](https://cloud.githubusercontent.com/assets/15116901/19256294/840c269a-8fa0-11e6-8c25-762561eafb54.png)

変更点としては、
- 重要度や関連性を踏まえて、入力欄の順番を
  - タイトル, 種類, (種類の設定), 公開範囲, (保護範囲の設定), タイトル, タグ から
  - タイトル, タグ, 公開範囲, (公開先), 共同編集, 記事種類, (種類の設定) に変更
- grid構成にして各入力欄の幅を統一
- bootstrapのradioはONなのかOFFなのかパッと見わかりづらいのでbutton groupに変更
- 各種説明文は恒常表示せず、ツールチップ、または :question: ボタンで適宜表示
- 一貫性のため、ヘッダーのIDや更新日時を左側に寄せてまとめて表示
- タイトルは重要で絶対に書く項目なので、大きく表示
- 共同編集だけコンテンツの下にあったので、同じ入力をしやすい「公開先」の下に移動
- タブの直下にタブのメイン要素以外のものがあるのが違和感があるため、マークダウンサポートと絵文字をtextarea下部に移動

各入力欄のラベルに統一性がない点、高さ調整が適当な点、ウィンドウ幅が小さい時に表示が微妙になる点等、このサンプルでは不十分かと思われますが、このような形で一貫性をもたせると、より書きやすい、気持ちいいインターフェイスになるのではないかと思い、提案させて頂きました。

お忙しいとは思いますが、ご検討よろしくお願いします。

[画像作成時のgist](https://gist.github.com/il-m-yamagishi/2bbfd0a0c3d70205ac37cf1a768541c4) をリンクさせて頂きます。参考になれば幸いです。

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。参考にさせていただきます。

編集画面については、表示画面との差異が気になるといった意見も出ています。
（表示画面は、画面の右上に操作ボタンがまとまっているのに、編集画面は最下部にあるなど）

そのあたりも踏まえて、さらに使いやすい画面を提供していこうと思います。

**Comment by johiroshi** [comment]
いち意見ですが編集画面は現行のものが使いやすいです。

@il-m-yamagishi さんのおっしゃる通り、「『種類』のインパクトがタイトルに比べて大きい」という点はその通りだと思います。また、いくつかの項目が増減している点もその通りだと思います、
しかし、増減する項目のうち、Status, Problem, URLについては「種類」で何を選択したかに応じて増減するため、「公開先を選択」項目と一口には語れないのでは、という印象があります。

そして現行レイアウト案と新レイアウト案の最も多きな違いは、ラベルと入力欄が縦に並ぶか横に並ぶか、だと思います。後者のレイアウトの場合、タブレットやスマートフォンのときレイアウトが崩れてしまうので、現行のものが使いやすいように感じられます。

その上で、「種類」項目の位置を変える / 目立たせないようにする、などの方向性は賛成です。

**Comment by koda-masaru** [comment]
UIについては、いろいろ意見がありますね。

既に、かなり多くの組織で利用されているようなので、
大幅は変更は社内教育の手間などの面で課題もあるので、
慎重に考えていこうと思います。

**Comment by il-m-yamagishi** [comment]
最近のアップデートで一部の提案が取り込まれているようで、幸いです。

現行のUIで一定の満足を得られたので、このissueはcloseしても良いと思います。

よろしければcloseして頂ければと思います。

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。
そうですね。いったん、本issueはクローズして、
また何かあれば別のissueを登録するようにしようと思います。
