### ISSUE TITLE
タイトル入力中に誤ってEnterキーを押したときに記事が保存されないように

### ISSUE THREAD

**Issue by nztqa** [support-project/knowledge#494]
意に反して本文を入力する前に記事が確定、メール送信(本文がなく意味不明)される。
組織によって違いはあるでしょうが、弊社ではこのような人が多いです。
好みでしょうが、私はEnterキー無効でもいいかと思います。

```
$(document).ready(function() {
  $("#input_title").keypress(function(event) {
    function isEnterPressed(e) {
      return (e.which && e.which === 13) || (e.keyCode && e.keyCode === 13);
    }

    return !isEnterPressed(event);
  });
```

**Comment by koda-masaru** [comment]
たしかに、タイトルフォーカス中でEnterで、保存にならないようにすることは有効な気がします。

ただ、日本語のような言語の場合、文字の変換にEnterを使うと思うのですが、
上記のコードは、そのあたりの動作に変な影響はでないのでしょうか？
（すみません。ためしてません）

**Comment by nagodon** [comment]
@koda-masaru 上記コードでも日本語変換には影響は与えないので対応しようと思います。

**Comment by koda-masaru** [comment]
対応完了済。
クローズします。
