### ISSUE TITLE
検索文字が化ける

### ISSUE THREAD

**Issue by bunzaemon** [support-project/knowledge#495]
メールで解決済みですが、知識蓄積のために、ポストします。
## 質問

> 日本語で検索しようとすると 検索が出来ず、文字化けが生じます。 URLのクエリーとしては、きちんと日本語表示されていますが、 検索結果は、"XXX(化けた文字)" の結果はありません的な メッセージが出てしまいます。
## 環境

重要ではないけど、

| key | val |
| :-- | :-- |
| VirtualBox | バージョン 5.0.26 r108824 |
| CentOS Linux | release 7.2.1511 (Core) |
| Apache Tomcat | 7.0.54 |
| Knowledge | v1.6.0 Pre3 |
## 解決方法

原因は Tomcat 側の設定がされていない事によるもの。
### 1. server.xml の編集

`useBodyEncodingForURI="true"` を 72行目に挿入

```
$ cd /etc/tomcat     # 各人の環境で違うかも知れません。
$ diff server.xml server.xml.bak 
72c72
<                redirectPort="8443" useBodyEncodingForURI="true" />
---
>                redirectPort="8443" />
```
### 2. Tomcat の再起動

```
$ sudo systemctl restart tomcat
```

以上。

**Comment by koda-masaru** [comment]
登録ありがとうございました。
Tomcat8系だと設定は、上記の設定が無くても動くようなのですが、7系の場合は設定が必要になります。

これからKnowledgeの環境を作成するかたへの、有益な情報になると思います。
（issueはだれでも検索できるので）

**Comment by koda-masaru** [comment]
対応済みですので、クローズします。
（クローズしても検索にはヒットします）
