### ISSUE TITLE
IEで全体メッセージが何度も表示される

### ISSUE THREAD

**Issue by KeithK0720** [support-project/knowledge#496]
全体メッセージが、「次回も表示する」のチェックをいれていないにも関わらず、一覧表示の度に表示されてしまいます。
サインインしていない状態であれば、ブラウザを閉じるまでは再表示されません。
サインインした状態ですと、サインイン中は何度も表示されます。
一旦サインアウトしてから、再度サインインしても何度も表示されます。
いずれもIEでは発生しており、Chromeでは問題ありません。
確認すべき項目はないでしょうか？

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
IEは動作確認できていないので、情報はありがたいです。
IEのバージョンは何でしょうか？
あと、IEの環境を用意するのが手間なので、エラーの情報をおしえてほしいです。(私はMACなので)

**Comment by KeithK0720** [comment]
4台のWindows PCでこの現象を確認していましたが、今日になって再現するものと再現しないものとに分かれました。

(1)再現するPCのIEバージョン
・11.0.9600.18426
・11.0.9600.18314

(2)再現しなくなったPCのIEバージョン
・11.0.9600.18449
・11.0.9600.16428

OSはすべてWindows7です。

「エラーの情報」とはどこで確認できるでしょうか？

**Comment by koda-masaru** [comment]
バージョン違いで、再現する／しないがわかれるのですね。
というか、、、IEって11でもバージョンがいろいろ動いているものなのですね。
ますます、原因がわかりません。

全体メッセージを表示した後、既読にするのは、Javascriptで既読のリクエストを送信しています。
たぶん、このJavascriptがエラーになるのではと思っているので、開発者ツールのようなもので、
Javascriptのエラーが発生していないか確認いただけると助かります。

なお、管理者からの全体メッセージは、「メニュー」→「管理者からのメッセージ」の機能で
表示することができ、そこから既読にすることも出来たと思います。

その機能で既読にする（次回は表示しない）に変更すれば表示しないようになるのでは？
と思います。
お試しください。

**Comment by koda-masaru** [comment]
対応完了済。
クローズします。
