### ISSUE TITLE
承認待ち登録ユーザを削除したい

### ISSUE THREAD

**Issue by icebluefit** [support-project/knowledge#498]
承認待ち登録ユーザを削除する機能を実装していただけないでしょうか。

誤ったログイン用IDで登録してしまったユーザがあり、正しいログイン用IDで登録し直してもらったのですが、誤ったログイン用IDのユーザは承認するわけにもいかず、そのまま「承認待ちのユーザの一覧」の画面上に残ってしまいます。
一度ウソでも承認してから即時削除するのでもよいのですが、その場合承認メールが送信されてしまうのが気になります。

**Comment by koda-masaru** [comment]
そうですね。確かに一覧から消す機能はあったほうが良いと思います。
順次実装していこうと思います。

**Comment by icebluefit** [comment]
機能の実装およびマージ、感謝いたします。
v1.7のリリースを心待ちにしております。

**Comment by koda-masaru** [comment]
対応完了済。
クローズします。
