### ISSUE TITLE
スライドからスライドショーの作成に失敗する

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#499]
サーバーがWindowsやMacだとうまくいくことが多いが、
Linuxだと失敗することが多い。

インストールされているフォントや、パース処理のメモリ量の問題か？
調査して解決する。

**Comment by koda-masaru** [comment]
スライド作成のバッチプログラムの起動時の、最大メモリを指定してみた。
いったん、これで様子を見る。

**Comment by koda-masaru** [comment]
対応完了済。
クローズします。

**Comment by rainthestorm** [comment]
デモサイトおよびver１．７を適用した自社knowledgeにて、SLIDEを挿入しても表示されない現象がでています。

https://support-project.org/knowledge/open.knowledge/view/1040
https://support-project.org/knowledge/open.knowledge/view/1039
https://support-project.org/knowledge/open.knowledge/view/1025

SLIDE作成までに時間がかかるとのことですが、半日以上たった状態で
IE:×マーク
Chrome：Wait Parcing
となっています。
なお、右カラムの添付ファイルからDLすれば、ファイルの閲覧は可能です。

下記ページのスライドはchromeであれば一部表示されます。
https://support-project.org/knowledge/open.knowledge/view/768
