### ISSUE TITLE
webhook URL に、 proxy を利用するかしないかを選択したい

### ISSUE THREAD

**Issue by YutakaKawauchi** [support-project/knowledge#505]
現在社内で利用中です。bookmark では、インターネットアクセスが必要なため、 proxy を設定していますが、社社内ツールへの webhook は proxy を利用しないでアクセスしたいです。

現在は proxy 設定が存在すると、 webhook も proxy を経由する動きだと理解しておりますが、
webhook 先毎に proxy を利用するかしないかが設定できるとベターと思います。

よろしくお願いいたします。

**Comment by koda-masaru** [comment]
ご利用ありがとうございます。
確かに社内の別サービスへWebhookを通知したい場合、Proxyを経由しないでアクセスしたくなりますね。
Proxyを利用する／しないを設定できるようにしようと思います。

**Comment by koda-masaru** [comment]
This issue is available on v1.12.0 pre1.
