### ISSUE TITLE
目次を常に表示してほしい

### ISSUE THREAD

**Issue by morihiro1978** [support-project/knowledge#516]
記事で「目次を表示」したときに、ページをスクロールしても目次が常に右上に表示されるようにしてほしいです。

**Comment by koda-masaru** [comment]
ご要望ありがとうございます。
確かに、右側にあれば目次での遷移が今より簡単になりそうですね。
今後対応していこうと思います。

**Comment by taturou** [comment]
Release v1.7.0pre2で確認しました。
ありがとうございました！

**Comment by koda-masaru** [comment]
対応完了済。
クローズします。
