### ISSUE TITLE
タグの追加は、記事の更新として扱わないようにしてほしい

### ISSUE THREAD

**Issue by morihiro1978** [support-project/knowledge#517]
記事にタグを追加したたけのときは、更新として扱わないようにしてほしいです。
タグのつけ忘れなどで後からタグを追加したり、タグの整理で大量にタグの付け直したを行うことがあります。
それが記事の更新として扱われるため、記事の順序が変わりますし、Webhookにより大量の通知がされます。
そのため、気軽にタグを追加できません。

**Comment by koda-masaru** [comment]
「タグ」のみの更新の場合は、記事の更新とは判定しない方が良いということですね。

確かにその方が良い気がしますが、既に利用者が相当数いますので、
変更した方が良いものか、、、判断に少し悩みます。どうしようかな。
（挙動が変わると嫌がるユーザもいそうなので）

このissueを読んだかたで、上の変更に賛成のかたは、 「イイネ（thumbs up）」の
リアクションをしてくれると、判断の材料になったりします。

**Comment by johiroshi** [comment]
「**記事のタグを更新する**」ことで起きる問題は2種類あると思います。

1. 「タグを少し変更した（些末な更新をした）だけで、更新日時でソートされた記事に変動があって困る」
1. 「タグを少し変更する（些末な更新をする）度に、通知がきてうっとうしい」

> 記事の順序が変わりますし

とは「```http://server/knowledge/open.knowledge/list```」、記事一覧ページのことを指していると思うのですが、記事一覧ページは「**更新された日時が早い順に記事を表示する**」という仕様通りの動作をしているだけなので、記事の更新として扱わないというのはいかがなものかと考えます。

> Webhookにより大量の通知がされます

については、[Webhookの仕様](https://github.com/support-project/knowledge/issues/69#issuecomment-163598568)（古いかもしれません）をみると、「記事投稿日（insert_date）」「記事更新日（update_date）」という項目がJSONにあります。もし記事投稿日と記事更新日の日時が異なる場合に挙動が分けられるならば、通知方法を

- 記事投稿時のデスクトップ通知(Chrome/Firefoxのみ)
- 記事投稿・更新時のデスクトップ通知(Chrome/Firefoxのみ)

のように選べるようにするか、Webhookの通知を**記事投稿時に限定する**などの手段で通知の回数を減らす、というのはどうでしょうか。

**Comment by morihiro1978** [comment]
> 記事一覧ページは「更新された日時が早い順に記事を表示する」という仕様

色々な思想があると思いますが、私は以下のような仕様が良いと思いました。

* 一覧は記事が更新された順に並ぶ
* 「記事の更新」は記事のコンテンツ(タイトル、本文)
* タグはメタデータであり、修正しても「記事の更新」とはみなさない

---

Webhookに関しては、

* タイトルor本文、コメント、タグ、公開範囲などのメタデータ

が

* 作成された、更新された

が分かるようなフォーマットになっていると、受ける側でフィルターできるので、自由度が高まって良いと思いました。

**Comment by johiroshi** [comment]
### Webhook

Webhookに関しては「どうフィルタするか」という話に帰結するので、同意見ということになるのでしょうか。

---

### 「記事更新の仕様」

タグをメタデータと解釈する思想は良いと思いますし、事実その方法で通知も記事の順序の変動も抑えられます。
しかし、たとえば、

- タイトルを一文字変えた
- 本文に1行書き加えた
- 本文の誤字脱字を修正した

これらの小さな変更が複数回なされた場合、現行のタグの更新と同じように通知や記事の順序の変動が起こります。こちらは現状のままで良いのか気になります。

@morihiro1978 さんがタグの更新で煩わしく思われていることの根本は、記事更新の仕様というよりはむしろ

- knowledgeのリストのページは、記事をどのようにソートして表示するか？
- 記事の更新をどのように通知するか？

という問題に思われます。
たとえば、knowledgeのリストを**記事の作成日時順に表示する**場合、記事の順序の変動は起こりません。また、通知の方法を

1. すべての更新を検知して通知する
1. 本文とコメントに変更があったとき通知する
1. 通知しない

のように、通知方法が段階的に選べる場合、通知過多の問題も解消されます。

> タグはメタデータであり、修正しても「記事の更新」とはみなさない

という思想は、記事の更新を知る術が記事の更新日時や更新履歴を直接見るだけになってしまい、**記事の更新を通知する**という動作に矛盾する（通知機能なのに通知していない）ので、私は違和感を感じます。

@morihiro1978 さんが求められている変更は**記事更新の仕様変更**のみで、それ以外は現状のまま、が良いのでしょうか？

**Comment by koda-masaru** [comment]
本 issueに 👍 ×6 押されていることも鑑みると、

- タグはメタデータであり、修正しても「記事の更新」とはみなさない

という動作を期待している利用者が多いと感じました。

いったんは、その方向で検討しようかと思います。

あと、「更新」の判定ですが、以下が現実的でしょうか。

- 本文の修正は、誤字修正のような、1文字修正でもいったんは「更新」で良い気がします
- タイトルの変更も、いったんは、「更新」と判定する
- 記事の公開区分や公開範囲、共同編集者はメタデータとし、それのみの変更の場合、更新と判定しない


----

あと、一覧の並び順ですが、 @johiroshi さんが書かれたように

- 記事の作成日時順に表示する場合、記事の順序の変動は起こらない

に変更した方が、利用者はうれしいものでしょうか？



----

WebHookの通知は、対応の大変さも考えると、

- 「更新」と判定された場合は、Webhookを送る

くらいが、対応案としては良いかなと思いました。
通知を段階的に選択できる案も優れていると思いますが、作るのが大変（設定を持つようにDBを変更などの対応が必要になる）なわりには、そこまでの機能は無くても大丈夫なユーザが多い気がします。

**Comment by morihiro1978** [comment]
返信が遅くなりましてすみません。

@johiroshi さん、 @koda-masaru さん

> 記事更新の仕様というよりはむしろ
> * knowledgeのリストのページは、記事をどのようにソートして表示するか？
> * 記事の更新をどのように通知するか？
> 
> という問題に思われます。

考え直してみましたが、やはり私としては:

* タグはメタデータであり、修正しても「記事の更新」とはみなさないようにしてほしい

が要望になります。
タグの変更に関して、「変更したことを他の人が知りたいか」と考えたときに、そうでもないのでは？というのが私の考えです。

ソート順に関しては、現状の通り「記事が更新された」順で良いと思います。

通知のタイミングに関しても、 @koda-masaru さんが書かれているとおり「更新と判断された場合」で良いと思います。

タイトルや本文の更新の判断基準についてですが、現状どおり1バイトでも変更されたら「更新」と判断して良いと思います。
たしかに誤記を1文字変更しただけで「更新」と判断されると辛いですが、その判断基準は難しいと考えるからです。
1文字でも重要な変更なこともあるでしょうし、1行でも無駄な更新かもしれません。

---

これは追加機能になりますが。

記事の表示順を:

* 作成順
* 更新順

から選べる or どちらも表示すると良いのかも？と思いました。
以前使っていたナレッジベースのシステムは、「最近作成した記事トップ10」と「最近更新した記事トップ10」を表示するようになっており、便利でした。

**Comment by morihiro1978** [comment]
Release v1.7.0pre2 で確認しました。
要望通りです！
ありがとうございました m(_ _)m

**Comment by koda-masaru** [comment]
対応完了済。
クローズします。
