### ISSUE TITLE
一覧の表示順序について

### ISSUE THREAD

**Issue by icebluefit** [support-project/knowledge#522]
一覧画面には下記の通り4つのタブがあります。
- 一覧
- 人気
- ストック
- 履歴

このうち一覧については、 #517 で

> 「更新された日時が早い順に記事を表示する」

と記載されている方がおりましたが、他の人気、ストック、履歴はどのようなルールで順序付けされ、表示されているのでしょうか。
結果から推測してみたものの、やはり仕様を教えていただけた方が確実かなと思い、質問しました。

**Comment by koda-masaru** [comment]
4つのタブは、以下のように並び順を指定しています。

- 一覧
   - 「更新された日時が早い順に記事を表示する（更新が新しいものが上にくる）」
- 人気
   - 過去30日間の中で、「いいね」の件数が多い順に並べる
   - 過去30日間なので、合計の「いいね」件数ではないので日付が変わると変動していく
- ストック
   - ログインユーザがストックした記事を一覧に表示
   - ストックした日付順で並べる（新しいものが上）
   - ストックはユーザ毎に実施するので、ユーザごとに一覧の表示内容はことなる
- 閲覧履歴
   - ユーザが閲覧したものを新しいものが上にくるように一覧に表示
   - 当然ユーザ毎に一覧の内容はことなる

**Comment by icebluefit** [comment]
ご回答ありがとうございました。

**Comment by koda-masaru** [comment]
回答済ですので、クローズします。
