### ISSUE TITLE
データベースの接続先変更でエラー

### ISSUE THREAD

**Issue by n-nishijima** [support-project/knowledge#524]
- Amazon Linux(AWS EC2)
- v1.6.0pre4.war
- tomcat8
- PostgreSQL9.3.1

上記環境で、システム設定 > データベースの接続先変更 ページにて、PostgreSQL への移行を試していますがエラーが発生してPostgreSQLへの移行ができていない状態です。

以下、tomcatのログで確認したエラー内容です。
[localhost_log.txt](https://github.com/support-project/knowledge/files/619126/localhost_log.txt)

ざっくりしていて申し訳ありませんが、事象の原因をご確認頂けますでしょうか。。。
お渡しする情報に不備があればお知らせくださいませ。

**Comment by koda-masaru** [comment]
データコピー前の初期化処理で失敗しているようです。
初期化処理が、 @n-nishijima さんの環境にあっていないのかもしれません。
プログラムの修正が必要かもしれませんので、少々お待ちください。

**Comment by n-nishijima** [comment]
@koda-masaru さん
早速のコメントありがとうございます！
お手数をお掛けいたしますが、何卒宜しくお願い致します。

**Comment by koda-masaru** [comment]
@n-nishijima さん

ご連絡が遅くなりました。
v1.7.0pre3をリリースしたのですが、その中で接続先の変更が出来るように対応しました。
もしお時間がとれれば、v1.7.0pre3にて接続先の変更ができるか確認願います。

**Comment by naotoshin72** [comment]
@koda-masaru 様

v1.7.0pre3にてDB接続先を切り替えることができました！！！
ご対応頂きありがとうございます。

**Comment by koda-masaru** [comment]
対応完了済。
クローズします。
