### ISSUE TITLE
knowledge_id をタイトルや本文に差し込みたい

### ISSUE THREAD

**Issue by kawasakiRCS** [support-project/knowledge#535]
本文投稿後に設定されるIDを、タイトルや本文内の定位置に記入したいと考えております。
類似の記事の区別や大まかな時系列の把握など、記事毎の識別性を高くすることを目的としています。

参考URLとしてマカフィーさんのKBサイト例を下記に挙げます。
https://support.mcafee.com/ServicePortal/faces/knowledgecenter

投稿前から設定することが可能で、投稿後はロックできることが望ましいです。
#436 のようなマークダウンでの対応でも十分です。
テンプレートや画面のレイアウトのカスタマイズも解決の方針として考えられます。

既存の代替方法の指摘等でもかまいませんので、よろしくお願い致します。

**Comment by koda-masaru** [comment]
私も、 #436 でIDによって記事のリンクを行えるようにしたことから、IDを表示した方が良いと
思っていました。
IDを表示しようと思います。

**Comment by koda-masaru** [comment]
対応完了済。
クローズします。
