### ISSUE TITLE
サーバクラッシュ後にサイトが立ち上がらない

### ISSUE THREAD

**Issue by yuichi0123** [support-project/knowledge#540]
始めて投稿させていただきます。

VM上に立てた環境だったのですが、停電で強制シャットダウン後、Tomcatからknowledgeのサイトごと、立ち上がらなくなってしまいました。

環境は
　OS：CentOS6
　Java：8u111
　Tomcat：8.0.39
　PostgreSQL：9.5.5（H2からの移行済み）
　Knowledge：1.6.0
になります。

Tomcat上のログよりcatalina.outを確認すると、以下のようなエラーが出力されていました。

16-Dec-2016 18:02:09.502 情報 [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Webアプリケーションディレクトリ /opt/apache-tomcat-8.0.39/webapps/knowledge を配備します
16-Dec-2016 18:02:27.968 情報 [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Env [KNOWLEDGE_HOME] was not found.
INFO  2016-12-16 18:02:28,436 [GlobalInitializationListener(37)] [APP LOG] /home/tomcat/.knowledge/logs/app.log
INFO  2016-12-16 18:02:28,616 [DBConnenctionLogic(45)] Custom connection setting is exists.
ERROR 2016-12-16 18:02:28,800 [ConnectionPoolImpl(127)] Can't create a new connection for jdbc:postgresql://10.20.72.80:5432/knowledge
java.sql.SQLException: No suitable driver found for jdbc:postgresql://10.20.72.80:5432/knowledge
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
...

JDBCドライバが見つからない旨出ていますが、クラッシュ前は普通に使えていました。
knowledgeのlib以下にもドライバのJarファイルは存在してます。
また、PostgreSQL自身は、psqlでも外部よりpgAdminによる接続もできることは確認済みです。

この先調査すべき箇所が見当たらず、助言頂けると幸いです。

**Comment by koda-masaru** [comment]
サーバークラッシュ時に、tomcatのknowledge格納ディレクトリのファイルシステムがおかしくなったかもしれません。
一度、tomcat内のknowledgeディレクトリを削除し再起動してみてください。
なお、knowledgeはtomcat内のknowledgeディレクトリには何もデータを保存しないので、削除しても今までのデータが消えることはありません。

**Comment by yuichi0123** [comment]
さっそくのご返信ありがとうございます。

試してみたのですが、結果は変わりませんでした。

・Tomcat停止
・knowledgeディレクトリ、及びknowledge.warを削除
・Tomcat起動　⇒正常に起動
・Tomcat停止
・knowledge.warを配置
・Tomcat起動　⇒/knowledge/ サイトの立ち上げ時に同様のエラー

引き続きサポート頂けると助かります。

**Comment by koda-masaru** [comment]
warをおいてtomcatを起動すると、Knowledgeのディレクトリができると思います。
このディレクトリ内のWEB-INF/libディレクトリにPostgreSQLのライブラリ(.jar)はあるのですよね？
それなのに、ライブラリが読み込めないという現象ですよね？
う～ん。現象の原因が思い付きません。

Tomcatには、同時に稼働させているアプリがありますか？ま、Tomcatのサーバーのライブラリディレクトリに、、PostgreSQLのライブラリが登録されているということはあるでしょか？

**Comment by yuichi0123** [comment]
>warをおいてtomcatを起動すると、Knowledgeのディレクトリができると思います。
>このディレクトリ内のWEB-INF/libディレクトリにPostgreSQLのライブラリ(.jar)はあるのですよね？
>それなのに、ライブラリが読み込めないという現象ですよね？
>う～ん。現象の原因が思い付きません。

→はい、存在します。（名前は「postgresql-9.3-1103-jdbc41.jar」ですね）

>Tomcatには、同時に稼働させているアプリがありますか？

→Tomcat自体は特に凝ることなくインストールしたので、
　いわゆるデフォルトのサイト（「manager」や「examples」など）は存在しており
　これらは正常に立ち上がっています。

>ま、Tomcatのサーバーのライブラリディレクトリに、、PostgreSQLのライブラリが登録されているということはあ>るでしょか？

→これについては、元々登録されていなかったのですが、試しに入れて見たりは
　してみました。結果は変わらずです。

一つ分からないことがあるのですが、
Tomcatのログを見ると、jdbc接続の文字列が出力されており、
その際にドライバが見つからない旨のエラーでした。
このjdbc接続文字列の情報は、どこに格納されているのでしょうか？
knowledgeのディレクトリ内をgrepしても見つけられず、
そもそもDBに繋がっていないので、DB上にも無いと思いますので、
どこを見ているのかが気になっていました。
※その情報の付近に原因が無かろうかと思ったりしています。

また、現在はあくまで評価でのセットアップなので、最悪環境を
潰しても良いかと思っています。
ただ、今DBに登録している情報は保持しておきたいと思っており
それが可能であれば、簡単でも結構ですので、
手順をご教示頂ければと思ってます。

**Comment by koda-masaru** [comment]
> このjdbc接続文字列の情報は、どこに格納されているのでしょうか？

Knowledgeのデータディレクトリにあります。
データディレクトリは、

- 環境変数 `KNOWLEDGE_HOME` が指定されていれば、その値のパス
- 環境変数が無い場合、ユーザのホームディレクトリに、 `.knowledge` というディレクトリ

になります。

PostgreSQLを使う設定をした場合、その中に、 `custom_connection.xml` というファイルが作成します。
そのファイルがある場合は組み込みDBでは無く、PostgreSQLに接続する仕組みになっています。

**Comment by koda-masaru** [comment]
> 今DBに登録している情報は保持しておきたい

データのバックアップは、上記のデータディレクトリをバックアップしてください。
また、PostgreSQLをお使いの場合、別途PostgreSQLのデータもバックアップしてください。

下記のURLの情報もご確認願います。
https://support-project.org/knowledge_info/open.manual/page/backup

**Comment by yuichi0123** [comment]
ご連絡遅くなりました。
取り急ぎ、立ち上がることになりましたのでご報告です。

> Knowledgeのデータディレクトリにあります。
> データディレクトリは、
> 環境変数 KNOWLEDGE_HOME が指定されていれば、その値のパス
> 環境変数が無い場合、ユーザのホームディレクトリに、 .knowledge というディレクトリ
> になります。
> PostgreSQLを使う設定をした場合、その中に、 custom_connection.xml というファイルを作成します。
> そのファイルがある場合は組み込みDBでは無く、PostgreSQLに接続する仕組みになっています。

上記内容に従って、custom_connection.xmlの中身を覗いてみたのですが、
driverClassの値が「org.h2.Driver」になっておりました。
ポスグレに繋ぐのであれば「org.posgresql.Driver」だろう、という事で
修正した上でTomcatを再起動すると、エラーが発生しなくなり、
画面にも正常にアクセスできるようになりました。
※ちなみにdriverClass以外の値（例えばURLなど）は正しい値が入ってました。

そもそも、上記driverClassの値が、もともとどうなっていたのか不明で、
ここを変更することが、正しい復旧方法なのかも分からないのですが、
取り急ぎは復旧致しました。

もし上記のやり方は何かしらマズい、等あれば
お知らせ頂けると幸いです。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。上記の変更方法で問題ありません。

ちなみに、上記の状態はPostgreSQLに接続先を変更した後で、再度、その接続先変更画面で、DriverClassを「org.h2.Driver(1.4.183)  」を選択したのだと思います。

ここでDriverClassを選択できるようにしたのは、MySQLに対応する機能を追加予定で、
選択できるUIを作っていたなごりです。
MySQL対応は、なかなか進んでいませんし、org.h2.Driverを選択する意味がないので
（というか設定も間違えて起動できなくなる問題がありマイナスでしかない）
DriverClass選択はPostgreSQLのみにしようと思います。

**Comment by yuichi0123** [comment]
ご確認有難うございました。
それでは本件はクローズとさせていただきます。

ちなみに、サーバクラッシュ前は動いていた、という事は、
恐らく、何らかの操作で設定だけ変更され、
クラッシュ時に初めてTomcatが再起動扱いとなったことで
設定の変更内容が適用され、動かなくなったという事のようですね。
※変更した記憶がないのですが...

全然別の話になるのですが、クラッシュ前の挙動で、
添付ファイル付きで投稿した記事について、後から添付をDLしようとすると
Exceptionが発生する現象があり、これについても質問しようかと
思っていたのですが、
本件の解決と同時に、この問題も発生しなくなりました...
どういう因果関係があったのか、今となっては分かりませんが...

改めて、応対いただき、有難うございました。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。無事に動いたようで安心しました。

カスタムデータベースの設定ページで、「org.h2.Driver(1.4.183) 」が選択できるようになっていた部分を、 #553 にて修正しました。
次回のリリース以降、このようは現象になるユーザさんが減るかと思います。
