### ISSUE TITLE
tomcatの時間がずれる

### ISSUE THREAD

**Issue by atknico** [support-project/knowledge#541]
投稿失礼致します。
ここに投稿すればよいのかわからなかったのですが、
knowledgeをダウンロードしてtomcatに配置したところ
tomcatの時刻がずれてしまうという状況になり困っております。

OS：windows server 2008（windows7でも同現象を確認）
Java：8u111
tomcat：8.5.9
Knowledge：1.6.0

時刻のずれというのは現在の時刻より-9時間でGMTになっているようです。
http://localhost:[ポート]/manager/status/all
からステータスを確認すると各アプリのスタートタイム等が-9時間となっております。
そのためなのか他のwebアプリケーションでも時刻のずれが発生してしまっております。
Knowledge自体の時刻（投稿した時の更新日時等）は正しい時刻を示しておりました。
また、tomcatのlogsディレクトリにあるログ等の時間も問題ありませんでした。

この現象はKnowledgeをtomcatから削除すると解消されます。
原因がKnowledgeにあるのかどうかもわからないのですが、
どなたか解決方法をご存知の方がおりましたらご教示お願い致します。

**Comment by koda-masaru** [comment]
Knowledgeでは、起動時に内部的な時刻管理をGMTとしています。(世界中どこで使っても使えるように)
そのせいで、tomcatで動かしている別のアプリもGMTで動くようになってしまったのだと思います。
KnowledgeアプリのみにGMTのセットが有効になると思っていたのですが、その他のアプリにも影響がでるのか調査してみようと思います。

いったんは、Knowledgeを動かすtomcatを個別に用意していただくのが良いかと思います。

**Comment by atknico** [comment]
ご回答ありがとうございます。
調査していただけるということで、何かわかりましたら教えていただけると幸いです。
ご参考までに、時刻の影響が発生したwebアプリケーションは以下になります。
GroupSession
https://groupsession.jp/
以上、よろしくお願いいたします。

**Comment by koda-masaru** [comment]
@atknico さん
原因はわかったのですが、その部分を「GroupSession」と同一のTomcat上で共存できるように修正するのには時間がかかりそうです。
いったん、Knowledge用に個別のTomcatを用意いただき、起動ポートを別にするなどして運用いただくと良いかと思います。

**Comment by atknico** [comment]
承知いたしました。
とりあえずはKnowledge用のTomcatを用意したいと思います。

**Comment by koda-masaru** [comment]
忘備録
TimeZone.setDefaultで GMT をセットすると、JVM全体のタイムゾーンが変化する。
（webapp内だけだと思っていたが、同一tomcat内全てに影響が出る）

**Comment by takerushi** [comment]
自分の環境ではTomcatのアクセスログもGMTになってしまいました。
解決方法を知りませんか？

tomcat/bin/setenv.shに以下のファイルを配置してるのですが、catalinaのログにしか効いてません、、
```sh
CATALINA_OPTS='-Duser.timezone=Asia/Tokyo'
export CATALINA_OPTS
```

**Comment by takerushi** [comment]
環境はAlphine Linuxで、タイムゾーンはJSTにしています。（`date`コマンドで確認）

**Comment by koda-masaru** [comment]
タイムゾーンなどを考慮せず実装を簡単にするため、少し乱造なのですが、Knowledge内では時間を全てUTCで扱っています。（●●の環境では動かない、、といった環境依存が面倒なので）
ですので、ログなどがUTCで表示されることは、今のところ仕様になっています。

**Comment by takerushi** [comment]
> ログなどがUTCで表示されることは、今のところ仕様になっています。

分かりました。ありがとうございます。

**Comment by koda-masaru** [comment]
いったん仕様ということで、本Issueはクローズします。
