### ISSUE TITLE
スライドを本文に貼り付けられない

### ISSUE THREAD

**Issue by mitsugogo** [support-project/knowledge#545]
v1.7.0pre2にて発生を確認しました。

## 再現方法

- 記事を新規作成
- スライド(pdf)をアップロード
- 「スライドショー」を押下しても反応がなく、本文に差し込まれない

`[slide xxx]` と手書きで記入することで表示させることは出来るようですが、
v1.6.0では正常に貼り付けることができました。
画像は貼り付けられます。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
私の環境のv1.7.0pre2では、「スライドショー」ボタンで挿入できました。
たぶん、ブラウザ内のjavascriptが環境によって動かないことがあるのでは？と思います。
お使いのブラウザは何でしょうか？
(私はmac chrome 最新 55.0.2883.95で確認しました。)

**Comment by mitsugogo** [comment]
いろいろ試していたところ、添付のファイル名にシングルクォート(')が入っているのが原因でした。。
すいません、お手間おかけしました。

**Comment by koda-masaru** [comment]
なるほど。シングルクォートが入っていると、たしかにスライドショーボタンで挿入できませんね。
原因がわかったので、シングルクォートが入っていても動くように、後日修正します。
ただ、issueが貯まっているので、提供までは時間かかると思います。いったんはファイル名を修正することで対応願います。

**Comment by koda-masaru** [comment]
#565 にシングルクォートに対するissueを登録。
本issueとしてはクローズします。
