### ISSUE TITLE
箇条書き中ではインラインのコードがブロック要素になります

### ISSUE THREAD

**Issue by taturou** [support-project/knowledge#546]
Release v1.7.0pre2 で確認しました。

バッククオート1つによるマークアップがおかしいです。

以下のように文章中だと期待通り表示されます:

<pre>この関数は `x + 1` を返します。</pre>

しかし、以下のように箇条書きの中だと表示がおかしいです:

<pre>* この関数は `x + 1` を返します。</pre>
<pre>1. この関数は `x + 1` を返します。</pre>

これは、以下のように表示されます。

---

* この関数は
  ```
  x + 1
  ```
  を返します。

---

ご確認をお願いします。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
箇条書きのときのスタイルが正しくセットされていないのが原因のようです。
修正してリリースします。

**Comment by koda-masaru** [comment]
対応完了したのでClose
