### ISSUE TITLE
oembedでGoogle Mapが貼り付けられない

### ISSUE THREAD

**Issue by about518** [support-project/knowledge#549]
oembed拡張で貼り付けようと試みましたが、うまく貼り付けられませんでした
原因はjquery-oembed-allのライブラリが古い（というか、久しくアップデートされてない）ためで、
インストール後のjquery.oembed.jsを書き換えることにより貼付けできましたのでご報告致します。

元ファイルの945行目の
``
        new $.fn.oembed.OEmbedProvider("googleviews", "rich", ["(.*maps\\.google\\.com\\/maps\\?).+(output=svembed).+(cbp=(.*)).*"], "https://maps.google.com/maps?layer=c&panoid=$3&ie=UTF8&source=embed&output=svembed&cbp=$5", {templateRegex: /(.*maps\.google\.com\/maps\?).+(panoid=(\w+)&).*(cbp=(.*)).*/, embedtag: {tag: 'iframe', width: 480, height: 360}, nocache: 1 }),
``
を
``
        new $.fn.oembed.OEmbedProvider("googleviews", "rich", ["google\\.com\/maps\/embed\\?.+"], "https://www.google.com/maps/embed?$1", {templateRegex: /.*google\.com\/maps\/embed\?(.+)/, embedtag: {tag: 'iframe', width: 480, height: 360 }, nocache: 1}),
``
に書き換えることで、無事表示されました。

jquery-oembed-allをフォークして別リポジトリでインポートして反映して頂けますと幸いです。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
確かに、jquery-oembed-allはメンテナンスされていないように見えますので、
フォークした後に、上記対応を入れた後に、Knowledgeに取り込もうと思います。

以下に、フォークしたリポジトリを作成しました。
https://github.com/support-project/jquery-oembed-all

もし、お時間がとれるのであれば、上記のフォークリポジトリに、プルリクエストを
もらえるとありがたいです。

**Comment by about518** [comment]
ありがとうございます。早速プルリクエスト出しておきました
https://github.com/support-project/jquery-oembed-all/pull/1

**Comment by koda-masaru** [comment]
ありがとうございました。
動作確認もできたので、v1.7.0のリリースに含めようと思います。

**Comment by koda-masaru** [comment]
対応完了したのでClose
