### ISSUE TITLE
全てのページ遷移に時間がかかる

### ISSUE THREAD

**Issue by atknico** [support-project/knowledge#551]
社内LAN内のサーバーにKnowledgeをインストールしたところ
全てのページ遷移が異常に遅いという現象が発生しております。

OS：windows server 2008R2（windows7や8.1でも同現象を確認）
Java：8u112
tomcat：8.5.9
Knowledge：1.6.0

自分なりに検証を行うため、上記バージョンで様々な環境にKnowledgeをインストールしたところ、
社内LAN内（インターネット接続なし）にあるserver2008R2 win7 win8.1はどれもだめでした。
社内LANから切り離されたインターネット接続用PC（win7)にインストールしたところ当現象は発生せず快適できた。
また自宅PC（インターネット接続あり win7）も快適でした。
インターネット未接続が関係しているのかと思い、インターネットPCの回線を切断して検証もしましたが、
当現象は発生せず関係ありませんでした。
スペックやメモリ割り当ても関係なさそうです。

「tomcatの時間がずれる #541」で記載した
GroupSession
https://groupsession.jp/
は社内LAN内の同サーバーでページ遷移等問題なく動作しております。

再現する条件がわかっておらず申し訳ないのですが、
なんでもよいので情報があればご教示いただければと思います。

**Comment by koda-masaru** [comment]
遷移が遅くなる原因は、読み込んでいるデザインのライブラリ（bootswatch）かもしれません。
bootswatchでは、Googleのfontをインターネットから読み込むのですが、Proxyなどで、
そのアクセスがブロックされる場合などで、タイムアウトするまで画面遷移までブロックされる
ことがあるようです。

また、タイムアウトまで遷移が遅くなるというのは、利用ブラウザにより発生したり／しなかったり
することもあるようです。

Tomcatのwebappsディレクトリに展開されたknowledgeディレクトリ内を直接いじることで、
その部分が原因か確認することができます。

以下のファイルのフォントインポートの記述をクリアして後で、アクセスすると、
遷移が早くならないかお試しください。

− 対象のファイル（デフォルトのテーマ）
bower/bootswatch/flatly/bootstrap.min.css

− クリアする記述

```
@import url("https://fonts.googleapis.com/css?family=Lato:400,700,400italic");
```

**Comment by koda-masaru** [comment]
もし、フォントの読み込みが原因であれば、次バージョンでは、
フォントの読み込みの記述をクリアしようと思います。

**Comment by atknico** [comment]
ご回答ありがとうございます。
webブラウザについてIE、Chrome、Firefoxで試したときはいずれも改善しませんでした。
フォントの読み込み部分を削除する方法は、出社次第試してみてこちらに報告させていただきます。
よろしくお願いします。

**Comment by atknico** [comment]
先日教えていただきました箇所の記述をクリアしたところ、
全ページの遷移速度が改善したことを確認いたしました。
ありがとうございました。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。無事に解決できたようで安心しました。

Googleフォントへのリンクについては、 issue #555 を登録しました。
