### ISSUE TITLE
バージョン番号の表記

### ISSUE THREAD

**Issue by takajun** [support-project/knowledge#554]
Knowledgeページのどこかにバージョン番号の表記(v1.6.0やv1.7.0pre3など)をお願いできないでしょうか。
活発に開発していただいていることもあり、

- ユーザ問い合わせ対応上、運用版の版数を明確にしておきたい
- バージョンアップ作業後に正しく完了できているかどうか目安にしたい

などがあります。
表記場所は各ページのヘッダーまたはフッターを想定していますが、特にこだわりはありません。

**Comment by koda-masaru** [comment]
パージョン番号の表記は、ライセンスのページで表示しています。
画面下部のフッターに「ライセンス」というリンクがあると思いますが、そのリンク先の
画面を参照願います。

以下、デモサイトのライセンスページ
https://support-project.org/knowledge/open.license

**Comment by takajun** [comment]
ありがとうございます。ライセンスのページに表示されることを確認しました。
ここを目安にしたいと思います。
