### ISSUE TITLE
テーマのスタイルから、GoogleFontへのリンクを消す

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#555]
#551 から

テーマのスタイルに、以下のようなインターネット上のフォントへのリンクが書かれている。
```
@import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700");
```
このせいで、ネット上の上記URLにアクセスできない環境だと、画面遷移が異常に遅くなる
ことがある。

Knowledgeは、社内イントラなどのクローズな環境で動くことを想定しているので、
このフォントへのリンクを消し、それによりUIが崩れるようであれば、内部でGoogleFontを
持つようにする。（ライセンス的には問題なさそう）

**Comment by koda-masaru** [comment]
対応完了したのでClose

**Comment by rainthestorm** [comment]
お世話になります。closeのissueに失礼いたします。
社内イントラ（インターネット接続なし）環境にてknowledgeを運用しています。
本件、ｖ1.11にアップデートしたところ再度現象が発生しました。ｖ1.11では再度フォントの記述が加わっていませんか？
− 対象のファイル（デフォルトのテーマ）
bower/bootswatch/flatly/bootstrap.min.css
