### ISSUE TITLE
IEで画像が表示できません

### ISSUE THREAD

**Issue by siyomiya** [support-project/knowledge#556]
画像を埋め込んだ投稿を表示すると、IEでは旨く表示できません。このように表示されます。
![2017-01-05_16h56_39](https://cloud.githubusercontent.com/assets/24932531/21672789/f7a2f9c0-d367-11e6-8a4a-d4156d95d59e.png)

IEのバージョンは11です。
![2017-01-05_16h58_03](https://cloud.githubusercontent.com/assets/24932531/21672810/28ddd12c-d368-11e6-983d-3942609fc7e1.png)

Google Chrome 55.0.2883.87 m (64-bit)なら問題なく表示されます。
OSはWindows 7 (64-bit)です。

Knowledge v1.7.0 Pre3でこの事象が発生します。v1.6.0では発生しません。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
ですが、既にIEは旧いWebアプリを動かすためだけのブラウザになっております。
（Microsoft社がそのスタンス）

今後、IEのシェアが増えることはありえないと思いますし、そのために、
古い技術しか使えなくなるのもシンドいです。

このため、正式にIEはサポート対象外としようと思います。
（既に動作確認をIEでは行っていません）
申し訳有りませんが、IEで動かない場合、Chrome／FireFoxをお使いください。

**Comment by siyomiya** [comment]
IEをサポート対象外にする旨、承知しました。
Chrome／FireFoxで使うことにします。本件はクローズいたします。
