### ISSUE TITLE
共同編集者が添付ファイルを削除できない

### ISSUE THREAD

**Issue by takajun** [support-project/knowledge#557]
作成済みエントリにおいて、以下の事象を確認しました。
- エントリ作成者は、本文編集、エントリ削除、添付ファイルのみ削除ができる
- 共同編集者は、本文編集、エントリ削除はできるが、添付ファイルのみ削除ができない

v1.7.0pre3適用のデモサイトにおいても事象再現を確認しました。
共同編集者は添付ファイルのみ削除もできるべきだと考えておりますが、いかがでしょうか。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
添付ファイルの権限については、気づきませんでした。
共同編集者はその記事の添付ファイルを削除できるのが正しいと思いますので修正します。
少々お待ちを。

**Comment by koda-masaru** [comment]
対応完了したのでClose
