### ISSUE TITLE
IPアドレスでアクセスすると書き込みができない

### ISSUE THREAD

**Issue by CSKamonohasi** [support-project/knowledge#566]
apacheの設定なのかも知れませんが、切り分けができず、なにかお気づきの点があれば教えて頂けませんでしょうか。

環境は
> Windows7
> jre 1.8.0_101-b13
> Tomcat 8.5.9
> Knowledge 1.7.0pre4
> postgresql 9.6
> firefox 50.1.0

です。

http://localhost:8080/knowledge
の形式でアクセスすると正常なのですが、
http://[10.141.*.*]:8080/knowledge
とローカルIPの形式でアクセスした場合、サインイン、記事の閲覧はできるのですが、
記事の書き込みができません。
 error [403]
と表示されます。

httpd.confに特段のアクセス制限は記載していません。
Tomcatの動いているPCからアクセスしてもダメですし、別PCからもダメでした。
Windowsファイアウォールを無効にしてもかわりませんでした。

localhost_access_log　には
`10.141.*.* - - [08/Jan/2017:00:08:58 +0900] "POST /knowledge/protect.knowledge/draft HTTP/1.1" 403 8712`
と記録されていました。
POSTメソッドが拒否されているところまでは理解できたのですが、
その先で詰まりました。

ローカルのPCで試用していたのを、社内に公開しようとしたところ、問題が発覚しました。
postgres以外は最新にバージョンアップしたのですが、改善しませんでした。

よろしくお願いいたします。

**Comment by koda-masaru** [comment]
Knowledgeでは、Postなどのリクエストが正しいところからきているかをチェックしています。

具体的には、管理者メニューの「システム設定」にセットされている「サービスのURL」に書かれた
ところからリクエストがきているかどうかをチェックしています。

そこで、サービスのURLを「http://localhost:8080/knowledge」から、「http://[10.141..]:8080/knowledge」に変更してください。
そうすると、IPでの投稿ができるようになります。

**Comment by CSKamonohasi** [comment]
ありがとうございます。
設定を修正したところ、投稿ができるようになりました。

教えて頂きありがとうございました。

ちなみに、設定を行う際におっちょこちょいなことに、IPを打ち間違え、そのまま保存してしまいました。
SYSTEM_URL を直接編集して事なきを得たのですが、慌てました。
情けないことこの上ないですが、ミス事例でした。
