### ISSUE TITLE
絵文字が表示されない

### ISSUE THREAD

**Issue by hkato** [support-project/knowledge#568]
v1.7.0pre4にアップデートしたところ絵文字が表示されなくなりました。
ただいま現物にアクセスできないのでデモサイトの方を確認したところ同様でした。
インスペクタで確認すると画像ファイルが存在しないようです。
<img width="1150" alt="knowledge" src="https://cloud.githubusercontent.com/assets/12589/21889955/c3bcb41e-d90e-11e6-9df2-b5090b3c6593.png">

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
Minifyを設定したとき、絵文字の画像を正しくセットしていませんでした。

以下にて修正済です。
https://github.com/support-project/knowledge/pull/567
