### ISSUE TITLE
faviconが表示されない

### ISSUE THREAD

**Issue by rainthestorm** [support-project/knowledge#592]
お世話になります。

knowledge ver1.7
tomcat　9.0
ブラウザ：IE11

TOPページ（WELCOMEのページ）とLanguageページではKnowkledgeのファビコンが表示されるのですが、
一覧以下の階層のページではTomcatの猫ファビコンが表示されます。
IEがサポート対象外であることは承知しておりますが、何かお知恵をいただければ幸いです。
よろしくお願いします。

**Comment by koda-masaru** [comment]
以下のURLなどが参考になるかもしれません。IEで確認していないので、原因の特定はできませんが。

http://w3q.jp/t/1682
http://www.seotemplate.biz/free-seo/2195/

tomcatのwebappsにknowledge.warを置くと、起動時にknowledgeディレクトリができると思います。
そのknowledgeディレクトリ内の、以下のファイルにfaviconの記述がありますので、上記URLを参考に修正してお試しください。
{knowledge}/WEB-INF/views/commons/layout/commonHeader.jsp

■ 解決策？
- link rel=”shortcut icon” の記述を追加してみる
- パスの指定を絶対パスに変える

**Comment by rainthestorm** [comment]
Kodaさま早速のアドバイスありがとうございます。

解決策を試したところ、うまくいきました。

なぜか、エクスプローラー上のアイコンはTomcatとKnowledgeが入れ替わっていますが、支障はないので様子見します。。
（ダブルクリックでアイコンファイルを開くと正常なアイコンが表示される）

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
できましたら、参考までに、どのような対応で解決したのか教えて欲しいです。

**Comment by rainthestorm** [comment]
ご教示のとおり、
{knowledge}/WEB-INF/views/commons/layout/commonHeader.jsp
上記ファイルの記述を以下のように変更しました。

•link rel=”icon”　⇒　 link rel=”shortcut icon” 
•href=”favicon.ico”　⇒　href=”http://[servername].[Domainname]/knowledge/favicon.ico”

**Comment by koda-masaru** [comment]
ご返信ありがとうございました。
参考になりました。

**Comment by koda-masaru** [comment]
いったん解決したのでクローズします。
