### ISSUE TITLE
Codehighlightが動かない

### ISSUE THREAD

**Issue by suicabar** [support-project/knowledge#593]

**Comment by suicabar** [comment]
ver1.70を利用しているのですが
コードのhighlightがうまく機能しないのですが
考えられる原因ありますでしょうか？

**Comment by koda-masaru** [comment]
お使いのブラウザは何でしょうか？
もしIEであれば、動作しないかもしれません。
（動作保証外で、動作確認などはしていません）

**Comment by suicabar** [comment]
利用しているブラウザはChoromeです。
LiveDemoでは問題なく動作をしているのは確認しているのですが。
DOMをみたところどうもhilight.jsが呼び出されてない気がするのですが
原因がつかめず困っている感じです。

**Comment by koda-masaru** [comment]
ページを開いた時の通信の回数を減らすために、ライブラリのjavascriptファイルを
複数をまとめて圧縮して一つのファイルにしています。
（ファイル単位に通信が発生するので、ファイル数が多いとそれだけ時間がかかるため）

ですので、hilight.jsの内容は、以下のファイルの中にあります。
```
https://support-project.org/knowledge/js/page-common-79e6df9a6f.js
```

たぶん、このファイルを読み込めていないということは無いと思います。（そもそも動かなくなる）
となると、原因が謎です。

推測の域を出ないのですが、キャッシュなどが悪さをしているのではと思います。

Tomcatのknowledgeを再デプロイしてみてください
- Tomcat停止
- webapps内のknowledge.war 及び、 knowledgeディレクトリを削除
- 再度、knowledge.war をwebappsディレクトリに配置
- Tomcat起動

その後にChromeでアクセスしてみて、ブラウザのリロードボタンを押してみてください。

上記の手順で解決できないでしょうか？

**Comment by koda-masaru** [comment]
Since there is no reply, I think that it is solved and I will close it.
