### ISSUE TITLE
マークアップでページ内リンクを作成すると、リンク先がトップページに移動してしまう。

### ISSUE THREAD

**Issue by dcash872** [support-project/knowledge#594]
表題のとおりです。

Wikiのような感じで記事を書きたいと思い
目次をつけてページ内リンクを貼ったのですが、
実際に作成したリンクをクリックすると
Knowledgeのデフォルトのトップページへ移動してしまいます。

マークアップは以下のとおりです。

 <a id="index"></a>
 ## <a href="#index">目次</a>
 - [PHPMD の設定](#anchor1)

 ## <a href="#anchor1">PHPMD の設定</a>

Knowledge特有の編集方法があれば問題ないのですが、
お返事をいただければ幸いです。

**Comment by koda-masaru** [comment]
ページ内リンクについては、考慮していませんでした。

Knowledgeではコードを簡単に書くために、baseを設定していたのですが、それが悪さをしています。

```
<base href="/{context}/" />
```

ベースを指定しているので、

```
<a href="#index">目次</a>
```

の記述のリンクは、{host}/{context}/#index へのリンクになり、このためトップページに遷移してしまいます。
後日、ページ内リンクの方法を考えますが、いったんは以下のように記載いただくと、ページ内リンクを書くことができます。

```
<a href="/{context}/open.knowledge/view/1045/#index">目次</a>
<a href="/{context}/open.knowledge/view/{記事のID}/{アンカー}>{リンク文字}</a>
```

冗長な記述になり申し訳ありませんが、いったん上記のように書いていただけけると、
後日ベースを解除したとしても動作するのでオススメです。

**Comment by dcash872** [comment]
ありがとうございます！
一度、そのように対応したいと思います。

**Comment by koda-masaru** [comment]
いったんは解決したようですので、クローズします。
ページ内リンクについては、 #600 に新しいissueを登録しました。
