### ISSUE TITLE
Outgoing emails - setup/debug

### ISSUE THREAD

**Issue by 62ML** [support-project/knowledge#598]
Hi, I'm facing difficulties to setup email gateway. The test returns : "Mail Send Error [class javax.mail.MessagingException] - Could not connect to SMTP host: smtp.gmail.com, port: 465, response: -1". The SMTP serveur is GMail - SSL/TLS.
What's wrong ? How to debug it ?
Thanks

**Comment by koda-masaru** [comment]
Hi,
This error is connect error.
Your server may not be able to communicate with Gmail's server.
Is your server in protected network? (such as intranet or AWS VPC)
In a protected network, network administrators often block communication with external mail servers.
Could you check your network?

Regard,

**Comment by 62ML** [comment]
Hi,
I moved to a SMTP service using port 587 instead of 465 (for this last one I tested with firewall enabled/disabled and for two providers)... and it's working. So it's ok for me !
Thanks
M
