### ISSUE TITLE
スライドからスライドショーの作成に失敗する

### ISSUE THREAD

**Issue by rainthestorm** [support-project/knowledge#602]
デモサイトおよびver１．７を適用した自社knowledgeにて、SLIDEを挿入しても表示されない現象がでています。

https://support-project.org/knowledge/open.knowledge/view/1040
https://support-project.org/knowledge/open.knowledge/view/1039
https://support-project.org/knowledge/open.knowledge/view/1025

SLIDE作成までに時間がかかるとのことですが、半日以上たった状態で
IE:×マーク
Chrome：Wait Parcing
となっています。
なお、右カラムの添付ファイルからDLすれば、ファイルの閲覧は可能です。

下記ページのスライドはchromeであれば一部表示されます。
https://support-project.org/knowledge/open.knowledge/view/768

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

まず、IEですが、すでに旧いWebアプリを動かすためだけのブラウザになっておりますので
サポート対象外としています。（マイクロソフトもそのスタンスですので）
たぶん、利用しているライブラリのJavaScriptが、IEのような古い
ブラウザでは動かないため、スライドも表示できないのだと思います。

また、現在Chromeにてデモサイトを見ると、以下のスライドは表示できているようでした。
https://support-project.org/knowledge/open.knowledge/view/1040
https://support-project.org/knowledge/open.knowledge/view/1039
https://support-project.org/knowledge/open.knowledge/view/768

ただし、以下のファイルは表示できていません。
https://support-project.org/knowledge/open.knowledge/view/1025

違いを見ると、表示できたものはPDFのファイルで、表示できないものはPowerPoint(*.pptx)のファイルになります。
私自身、スライド作成機能を使ってみてわかったのですが、PDFの方がちゃんとスライドの画像を抽出できることが多いようです。
スライドの作成は、OSSのライブラリを使ってファイルから画像を抽出してスライド形式にしているのですが、このライブラリ内でエラーが発生しているようです。（特に日本語が書かれたファイルは失敗することが多いです）

#509 にも書いたのですが、サービスを稼働するOSがWindowsだと正しくパースできるかもしれません。また、今調べてみたところ、上記の画像を抽出しているライブラリがバージョンアップしていましたので、次バージョンに新しいバージョンを適用してみようと思います。
（近日中にプレリリースの形で、まずは提供します）

それまで、ご不便をかけてしまいますが少々お待ち下さい。

**Comment by rainthestorm** [comment]
kodaさま
お返事ありがとうございます。

chromeでは上記スライドは表示できるようになりました。
serverはWindowsOSでして、以前のバージョン（ｖ1.6など）ではスライドが作成できていました。
社内イントラ用ブラウザがIEなもので、サポート対象外であることは承知の上でご相談してしまいました。

DLすればファイルを見られるので、大きな問題ではありません。
バージョンアップお待ちしております。
