### ISSUE TITLE
グループがカウントされない

### ISSUE THREAD

**Issue by tnaoki0529** [support-project/knowledge#626]
ALL USERSの数が変わりません。
また、他のユーザーを作っても数が変わりません。
OS:centos7

**Comment by koda-masaru** [comment]
「数」というのは、どこの画面のことを言っていますか？
一覧画面の右側にあるグループに表示している数字のことですか？
もしそうならば、この数字は、そのグループに対する「投稿数」であり、「ユーザ数」ではありません。

**Comment by tnaoki0529** [comment]
投稿もしておりますが数値に変化致しません。
alluserの投稿数も0のままとなっています。

**Comment by koda-masaru** [comment]
データが不整合になっているのかもしれません。
考えてみたのですが、以下の操作を管理者で実施したということはないでしょうか？

1. グループの管理で「ALL USERS」のグループを削除してしまった
1. その後に、再度「ALL USERS」というグループを作成した

もし、データベースの情報を参照できたら、「groups」テーブルの「ALL USERS」のデータを
確認してください。 group_idのカラムが `0` 以外になっていないでしょうか？

**Comment by tnaoki0529** [comment]
> グループの管理で「ALL USERS」のグループを削除してしまった
> その後に、再度「ALL USERS」というグループを作成した
どちらも行っていません。
また、DB確認いたしましたが、group_idは0となっております。

**Comment by koda-masaru** [comment]
Knowledgeでは、投稿した記事の公開範囲を指定する機能があります。(公開範囲に「保護」を指定すると、宛先を指定できます。これにより、グループに限定して公開といったことが可能になってます。)

そして、グループの投稿数は、「グループに所属しているユーザーが投稿した数」ではなく、その「グループを宛先にした記事の数」になっています。
よく考えると、ALL USERグループ宛に投稿するのであれば、公開範囲を指定しない(「公開」で投稿する)ため、ALL USERグループヘの投稿数が増えないのではないでしょうか？

**Comment by koda-masaru** [comment]
ちなみに、書いていて、グループの投稿数は、「グループに所属しているユーザーが投稿した数」にしたほうが良い気もしてきました。
とりあえず上記が現在の仕様です。

**Comment by tnaoki0529** [comment]
ご回答ありがとうございます。
要件の優先度が上がりましたら変更していただけると嬉しいです。
