### ISSUE TITLE
検索の部分一致がされない

### ISSUE THREAD

**Issue by tnaoki0529** [support-project/knowledge#627]
件名を「キャプチャツール」とした場合、
「キャプチャ」では検索できない。
他のものも検索されるものとされないものがある。

**Comment by koda-masaru** [comment]
いまのところ仕様です。

全文検索では、N-gramを使わず、形態素解析の結果でインデックスを生成しています。
形態素の辞書はIPAのものを使っていますが、この辞書に「キャプチャ」が入っていないため、
インデックスの品詞になりません。

形態素でインデックスを生成している理由は「東京都」と「京都」を別の単語として認識するためですが、漏れなく検索するためには、N-gramインデックスを使った方が良いかもしれません。

**Comment by tnaoki0529** [comment]
ご回答ありがとうございます。
仕様とのこと承知しました。

システムとして満足してますのでありがとうございます。
