### ISSUE TITLE
Group の作成でグループに属するメンバーを Group 作成者側で自由に設定

### ISSUE THREAD

**Issue by griffin-stewie** [support-project/knowledge#63]
グループを作ったら、現在は各ユーザからそのグループに入ってもらわないといけない仕組みになっているかと思います。
グループ作成者側でそのグループに所属してもらいたいユーザを選べるようなフローを追加していただくことはできないでしょうか？

**Comment by koda-masaru** [comment]
なるほど。そのような使い方があったほうが便利ですね。

グループ作成時に、そのグループの管理者がメンバーを選択出来るようにも出来るようにします。
これも少々お待ちください。

**Comment by griffin-stewie** [comment]
ありがとうございます。

**Comment by griffin-stewie** [comment]
0.5.3 pre3 にて、公開範囲を `[保護]` にすることでグループ管理側が任意のユーザを追加できることを確認しました。

**Comment by koda-masaru** [comment]
確認ありがとうざいます :smiley:

**Comment by griffin-stewie** [comment]
ご対応いただきありがとうございました。
