### ISSUE TITLE
webライブラリがSNAPSHOTへの依存関係を持っている

### ISSUE THREAD

**Issue by YuyaItoh** [support-project/knowledge#635]
リリース版の`web-1.7.0.jar`ライブラリが`common-1.7.0-SNAPSHOT.jar`ライブラリへの依存関係を持っています．`common-1.7.0-SNAPSHOT.jar`は既にリポジトリから削除されているために，knowledgeの1.7.0改修を行いたい場合にビルドが出来ません．

`web-1.7.0jar`のライブラリの依存関係を修正 & 公開することは可能ですか．

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
master ブランチにて、v1.7.0 をベースに依存関係を修正しました。
現在のmasterブランチから改修していただければ、 v1.7.0の改修ができると思います。

なお、既に Maven Central Repository リリースしてしまったものを変更することは
良くないと思いましたので、 webモジュールの v1.7.0 をベースに dependency のみを 
common の v1.7.0 (SNAPSHOTでない）に変更したものを、 web-1.7.1 としてリリースしました。
knowledgeのmasterの最新は、この web 1.7.1 を参照するようにしています。

**Comment by YuyaItoh** [comment]
素早い対応ありがとうございます，
web-1.7.1を用いてビルドができることを確認できました！
