### ISSUE TITLE
ログイン時のリダイレクト先について

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#639]
長らく開発に参加できなくて申し訳ありません。
ログイン時のリダイレクト先について社内から要望がありまして
一覧ページにログインできないかというのがありました。

パッと見どこから遷移するのかわからないという意見とともにknowledge自体が記事の集合体なので
TOPページよりも一覧に遷移した方が良いのではないかと思いissue発行しました。

もし問題なければ私の方で対応しようと思います。

**Comment by koda-masaru** [comment]
ログイン後のページは、一覧の方がたしかに良いですね。
すごく簡単な修正なので、私のほうで対応しました。
#641 

あと開発は手の空いた時に、ご協力いただければ大丈夫です。
充分助かっています 😄

**Comment by nagodon** [comment]
ありがとうございます 👍
