### ISSUE TITLE
検索時のソートについて

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#640]
こちらも社内からの要望になります。
今現在検索した時のソート順はスコア順だと思うのですが
それを記事の投稿日時順でソートしてほしいというものです。

こちらも問題なければ私の方で対応しようと思います。

**Comment by koda-masaru** [comment]
ソートの順番変更は今までの利用者としては、賛否両論になるのかな？と思います。
スコア順の方が使いやすいという人もいるかもしれませんし。

このため、「スコア順」と「日付順」でソートを切り替えるスイッチを一覧の上の部分に
置くのはどうでしょうか？

また、ユーザ毎にソート順は保存しておくことにしておくと更に良いと思います。
（そのソートのスイッチを切り替えたタイミングで保存）
保存先は、Cookieか「user_configs」テーブルになるかと思っています。

**Comment by nagodon** [comment]
確かに賛否両論になりそうですね。
ログインしないで見る場面もあるかもしれないのでCookieに保存する対応でやってみようと思います。

**Comment by koda-masaru** [comment]
ありがとうございます。よろしくお願いします :bow:

**Comment by koda-masaru** [comment]
マージ済ですので、クローズします。
