### ISSUE TITLE
自分がストックしたナレッジ一覧に、消したストックにストックされていた記事がずっと表示される

### ISSUE THREAD

**Issue by kaho2063** [support-project/knowledge#643]
不具合かもしれないものです。
重大なバグではないと思いますので、時間があったときにでも閲覧お願いします。

発生した手順：
1. ストックを追加する
1. 追加したストックに、何でもいいのでナレッジをストックする
1. 追加したストックを削除する

以上の手順を踏むと、自分がストックしたナレッジ一覧に、消したストックにストックされていた記事がずっと表示されるようになります。どうにか消そうと思いましたが、消すことができませんでした。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
不具合ですね。ストックしたナレッジが削除されてた際の挙動の考慮漏れでした。
後で修正しようと思います。

**Comment by kaho2063** [comment]
返信ありがとうございます。恐らく大多数の利用者に影響のない不具合なので、多少放置していても問題無いでしょうね。

すごく個人的な話ですが、Twitterで言っていた聞きたかった件は別件、よくよく調べてみると古いバージョンで発生していた不具合でした。新しいバージョン(どのバージョンかは調べていない)では直っていましたので質問の予定はありません。お手数おかけしました。

**Comment by koda-masaru** [comment]
了解しました。また何か気付きましたら、ご連絡下さい。このissueの不具合は、今度直しますね。クリティカルでは無いですが、気づいたものを放置しておくのも気持ち悪いですし。。。
