### ISSUE TITLE
タグをクリックしても全記事が表示される

### ISSUE THREAD

**Issue by taturou** [support-project/knowledge#644]
全記事を表示した状態で、記事についているタグをクリックしても、そのタグに関する記事が表示されません。
URLが `https://support-project.org/knowledge/open.knowledge/list?tag=` となっています。

2017-02-14 15:57現在、デモサイトで確認しました。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
画面の部品分けしたときに、リンクの生成方法を間違えたようです。
修正しようと思います。
