### ISSUE TITLE
WAN access

### ISSUE THREAD

**Issue by 62ML** [support-project/knowledge#649]
Hi,
I'm using Koda on a Docker Synology server. To provide WAN accesses, I go through two firewalls (and two ports forwarding).
It's working perfectly to login and to consult knowledge base  .... but adding content failed with an error 403 forbidden. Hereby an extract of the Docker Log

![image](https://cloud.githubusercontent.com/assets/20791529/23013496/2a2a68c2-f42b-11e6-88b8-a9045435b675.png)

Thank you for your help,
M

**Comment by koda-masaru** [comment]
Hi,

Is the firewall missing Referer of Http Header?

This error occurred when the Referer check failed.
Knowledge checks Referer URL of Http Header for CSRF measures.
The URL used for checking is specified below:
  Menu -> System Config ->  System Config -> Service URL
(*This URL will also be used for notification emails)

Regards,
-- Koda

**Comment by 62ML** [comment]
Hi,
Thank you.
I have replaced to local one by the remote one ... and it's working ! But now the problem occurs locally. How could I set a list of URL (local, remote, ... ) ?
Regards,
Marc

**Comment by koda-masaru** [comment]
Hi,
Do you want to access one server with two URLs, local and remote?
(For example, one is https://example.com and the another one is https://localhost.com)

If that's the case, please access to Knowledge by one URL.
There is a reason why Knowledge can't set multiple URL.
Knowledge will send a notification email when new article was posted.
In this mail, Knowledge write the URL to access that post.
If there are multiple URLs, I do not know which URL should be set in this mail.

**Comment by 62ML** [comment]
Hi,
I have successfully configured a reverse proxy.
Seems to be OK now !
Thanks,
