### ISSUE TITLE
HTML Titleに記事タイトルを含める

### ISSUE THREAD

**Issue by irgaly** [support-project/knowledge#65]
現状ではHTML Titleが設定されていませんが、
記事ページでは記事のタイトルがHTML Titleに設定されていると分かりやすいと思います。
HTML Title + URLでコピーする、というようなツールを使って記事の共有がしやすくなります。

**Comment by koda-masaru** [comment]
なるほど。
HTMLの&lt;title&gt;には、記事のタイトルをセットするようにしようと思います。
対応が簡単なので、次のリリースには含められると思います。
少々お待ちください。

**Comment by griffin-stewie** [comment]
:+1:

**Comment by koda-masaru** [comment]
リリースしました。issueはクローズします。
