### ISSUE TITLE
記事更新時に更新日時をアップデートさせない

### ISSUE THREAD

**Issue by cross-xross** [support-project/knowledge#658]
更新日時で記事の表示順が決まる仕様になっていますが
記事更新時に更新日時を変更しないようなオプションがあると便利かと思いました。
微細な修正でも表示がトップに来てしまうと他の記事執筆者の記事が埋もれるので。

ご検討いただけましたら幸いです。

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。
そうですね。あっても良いかもしれません。

ただ、一般のユーザがわざわざ「更新日時を変更しない」という選択をして投稿するでしょうか？

- ボタンや選択肢増える　≒　ユーザが混乱する（使いにくく感じる）

だと思うので、追加は慎重に検討させてください。
（要望 👍  がとても多ければ、追加しようと思います）

**Comment by koda-masaru** [comment]
This is supported by v1.11.0.
You can choose to not update the timeline when saving.
I will close this.
