### ISSUE TITLE
Search field

### ISSUE THREAD

**Issue by 62ML** [support-project/knowledge#664]
Hi,
Is it possible to use boolean operators in the search field ? If yes, how ?
Is it possible to 'focus' on some metadata ( like for tags TAGS:(xxx) ) in the search field ? If yes, how ?
Is it possible to combine metadata in the search field ? if yes, how ?
Best Regards,

**Comment by koda-masaru** [comment]
Hi,

> Is it possible to use boolean operators in the search field ?

No it isn't. 

> Is it possible to 'focus' on some metadata ( like for tags TAGS:(xxx) ) in the search field ? If yes, how ?

Yes it is. but it does not cover all metadata.
In the search field, you can search by specifying group name and tag name.
For example, try entering `tags: (python) groups: (test)` in the search field on the demo site.
demo site: https://support-project.org/knowledge/open.knowledge/list

> Is it possible to combine metadata in the search field ? if yes, how ?

Some metadata is search target.
You can check metadata that can be used for search on Advanced search page.

Advanced search page:  https://support-project.org/knowledge/open.knowledge/search

Click the icon in the upper right to display the menu.
That menu has Advanced search.

Best Regards,

**Comment by koda-masaru** [comment]
Since there is no reply, I think that it is solved and I will close it.
