### ISSUE TITLE
記事編集開始後一定時間が経過すると403 Forbiddenが発生する

### ISSUE THREAD

**Issue by isogame3** [support-project/knowledge#666]
表題の通り、記事の作成画面、または編集画面を表示してから一定期間が経過すると（2～3時間ぐらい？）
「投稿する」ボタンをクリックしたときに、右上に「403 Forbidden」が表示されて保存が行われません。

ver1.5ぐらいのときは、そんなことは起きなかったように思いますので
最近の変更に起因しているのではないかとおもいますが、これが発生すると一度「コンテンツ」の内容をすべてコピーしてから
編集画面を再度開いて張り付けなおさないといけなくなってしまうので、不便です。

**Comment by koda-masaru** [comment]
こちらの対応は、CSRFの対策のための変更になります。
CSRF対策のリクエストトークンを発行しており、それには有効期限が設定されています。
この有効期限は、Tomcatなどサーバーのセッションの有効期限に依存しますので、
web.xmlなどを変更すると、3時間（180分）に延長といったことは可能です。
（Tomcatのディフォルトは30分です）

セキュリティ上、あまり長い有効期限を設定するのは好ましく無いため、これを長くするよりは、
追加されている「下書き保存」をこまめに利用していただくことを推奨いたします。

**Comment by koda-masaru** [comment]
バックグラウンドで定期的に、編集があったかどうかをチェックし、
編集があった場合に、自動的に下書き保存すれば良い気がしてきました。
いずれそのように実装しようかと思います。

**Comment by koda-masaru** [comment]
セッションが切れないように、5分に1回バックグラウンドでアクセスするようにしてみた
#693

**Comment by isogame3** [comment]
しばらく見ていない間に、何かいい対応をしていただいたみたいで
ありがとうございます！

**Comment by koda-masaru** [comment]
v1.9.0 pre1としてリリースしました。本issueはクローズします。
