### ISSUE TITLE
記事の投稿・編集ができない

### ISSUE THREAD

**Issue by hkato** [support-project/knowledge#678]
1.7.0 -> 1.8.0にwar置き換えでアップデートしたところ、新規投稿・編集ができなくなりました。(Internal Error)

試しにwarを古いファイルに戻したところ、
- 1.7.0 - OK
- 1.8.0pre1 - OK
- 1.8.0pre2 - OK
- 1.8.0pre3 - NG
- 1.8.0 - NG
でした。

Tomcatを使用していますが、次のエラーが発生しています 
```
3 23, 2017 5:34:04 午前 org.apache.catalina.core.ApplicationDispatcher invoke
重大: サーブレット jsp のServlet.service()が例外を投げました
org.apache.jasper.JasperException: JSPのクラスをコンパイルできません: 

JSPファイル: /WEB-INF/views/protect/knowledge/partials/partials-edit-meta.jsp の中の30行目でエラーが発生しました
Cannot cast from Object to int
27:                         <% 
28:                         int type = jspUtil.getValue("typeId", Integer.class);
29:                         if (pageContext.getAttribute("typeId") != null) {
30:                             type = (int) pageContext.getAttribute("typeId");
31:                         }
32:                         TemplateMastersEntity template = (TemplateMastersEntity) pageContext.getAttribute("template");
33:                         String id = "typeId_" + template.getTypeId();
```

Stacktrace不要かと思いますが念のため添付します
[localhost.yyyy-mm-dd.log.txt](https://github.com/support-project/knowledge/files/863927/localhost.yyyy-mm-dd.log.txt)

**Comment by koda-masaru** [comment]
以下の操作をお試しください。

1. Tomcat停止
2. Tomcatのworkディレクトリ削除
3. Tomcatを起動

この操作でもうまくいかない場合、お使いの環境のJavaのバージョンを教えてください。

**Comment by hkato** [comment]
すみません。試したのですがやはり動きませんでした。
次のような環境になります。
CentOS7にRPMでJava, Tomcat, PostgreSQLを入れて、knowledge.warを置いただけです。
```
$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
$ /usr/sbin/tomcat version
Server version: Apache Tomcat/7.0.69
Server built:   Nov 6 2016 01:55:51 UTC
Server number:  7.0.69.0
OS Name:        Linux
OS Version:     3.10.0-514.10.2.el7.x86_64
Architecture:   amd64
JVM Version:    1.8.0_121-b13
JVM Vendor:     Oracle Corporation
$ psql --version
psql (PostgreSQL) 9.2.18
```

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
Tomcatのバージョンが7.0.69になっておりますが、Knowledgeは8以降で動作確認をしています。

https://support-project.org/knowledge_info/open.manual/page/install
Tomcatのバージョンを上げることをご検討ください。

**Comment by hkato** [comment]
システム用件を確認せず、大変お手数おかけしました。
Tomcat8.5.12にしたところ無事動きました。

- Tomcat 7 - Servlet API 3.0 - NG
- Tomcat 8/8.5 - Servlet API 3.1 - OK

ということですね。ありがとうございました。
http://tomcat.apache.org/whichversion.html
