### ISSUE TITLE
PostgreSQL運用時のバックアップ対象について

### ISSUE THREAD

**Issue by irgaly** [support-project/knowledge#68]
PostgreSQL運用をしている場合に、サーバサイドでバックアップスクリプトを定期的に実行したいと考えています。

* PostgreSQLの対象データベース丸ごと
* {Tomcatの起動ユーザのホームディレクトリ}/.knowledgeディレクトリ

バックアップは上記の二つと考えていますが、.knowledgeディレクトリの内訳を教えていただけないでしょうか。

0.5.3pre1では以下の構成となっていますが、PostgreSQL運用時にはバックアップする必要があるのはcustom_connection.xmlだけでしょうか。

## .knowledgeディレクトリの構成

* custom_connection.xml
* dbディレクトリ
* indexディレクトリ
* logsディレクトリ
* tmpディレクトリ

**Comment by koda-masaru** [comment]
> PostgreSQL運用時にはバックアップする必要があるのはcustom_connection.xmlだけでしょうか。

はい。それで大丈夫です。後は、PostgresSQLのデータをバックアップしてください。

.knowledgeディレクトリの内容は以下になります。

- custom_connection.xml
    - 組み込みDB(H2Database)から、PostgreSQLに切り替える設定情報
- db ディレクトリ
   - 組み込みDBを使っている場合のDBのデータ（PostgreSQL運用時には必要無し）
- index ディレクトリ
   - ナレッジの検索で利用している全文検索エンジン(Lucene)のインデックス情報
   - バックアップしておかなくても、PostgreSQLのデータがあれば、管理者メニューの「検索用のインデックスの再作成」のメニューから再構築が可能です（バックアップしておいても良いです）
- logs ディレクトリ
   - アプリケーションや、非同期のバッチ処理などの各種ログを出力
- tmp ディレクトリ
   - 一時保存データの格納ディレクトリ
   - ナレッジに添付したファイルをアップロードした場合の一時保存や、添付ファイルの中身のテキストを抽出して内容で検索出来るようにする際の解析処理の一時保存などに利用しています

**Comment by irgaly** [comment]
ありがとうございます！
必要なファイルがはっきりしたので助かりました。
