### ISSUE TITLE
Internet Explorer 11での画像表示

### ISSUE THREAD

**Issue by cross-xross** [support-project/knowledge#688]
Internet Explorer 11を使ってKnowledgeを参照しています。
編集画面のUIが刷新されたver. 1.7以降、ページに添付した画像が表示されない問題が発生しており困っています。
開発者ツールでリクエストを追ったところ、略/knowledge/open.file/download?fileNo=○○に対するリクエストの結果が軒並み「中断」になっていることが分かりました。
最近のバージョンではIEがサポート対象外になった等の情報がありましたら教えていただけないでしょうか？

**Comment by koda-masaru** [comment]
IEですが、すでに旧いWebアプリを動かすためだけのブラウザになっているという認識です。
シェアもどんどん落ちていることから、今後サポートしていく気はありません。ご容赦ください。
（個人で作っているので、IEの対応に時間を割くよりは、もっと別のところに時間を割きたいと思っています。）

**Comment by hoppybeer** [comment]
実はEdgeでも同じ現象が出ます。

**Comment by Monota** [comment]
少し調べたところ、SeqFilter が追加されたときに X-Content-Type-Options 指定するようになったため、IE11 が Content Type を sniff しなくなり、その結果、本文中の画像を表示できなくなったようです。X-Content-Type-Options は必要なので、代替として明示的に Content Type (image/png とか) を指定することで IE11 でも画像表示できるようにはなったのですが、そうすると今度はどのブラウザでも添付ファイルをクリックすると同じタブで開いてしまうようになるため、IE11 だけを狙った対応は難しそうでした。
インライン画像と添付ファイルで API を分ければ対応可能そうですが、IE11 はサポート外ということなので対応するにはコストが高いですね。

あと、手元の Edge (Microsoft Edge 40.15063.0.0) で試してみましたが、本事象は再現しませんでした。IE 固有の問題かと思いますが、もしかすると古い Edge では再現するのかもしれません。

**Comment by cross-xross** [comment]
皆様、コメントありがとうございます。
UAからアクセス元を特定し、IEだけContent Typeを変更する処理を独自に追加して解決しました。
(社内標準ブラウザの)IEからのアクセスが大多数という特殊な環境だったため、上記の対応をしましたが

```
IEですが、すでに旧いWebアプリを動かすためだけのブラウザになっているという認識です。
シェアもどんどん落ちていることから、今後サポートしていく気はありません。
```

という点については完全に同意します。

**Comment by taturou** [comment]
cross-xross様
差し支えなければ、修正方法を教えていただけるとありがたいです。
うちも、社内のブラウザがIEに限定されており、画像が表示されずに困っています。
（ElectronでKnowledgeブラウザを作ろうかと考えているところ）

**Comment by cross-xross** [comment]
@taturou 

雑な対応で恐縮なのですが、私は以下のコード箇所を修正して対応しました。
https://github.com/support-project/knowledge/blob/master/src/main/java/org/support/project/knowledge/control/open/FileControl.java#L28-L41

```java
    public Boundary download() {
        LOG.trace("download()");

        Long fileNo = getParam("fileNo", Long.class);
        KnowledgeFilesEntity entity = fileLogic.getFile(fileNo, getLoginedUser());
        if (entity == null) {
            return sendError(HttpStatus.SC_404_NOT_FOUND, "NOT FOUND");
        }
        if (entity.getFileBinary() == null) {
            LOG.debug("File binary is null. [fileNo] " + fileNo);
            return sendError(HttpStatus.SC_404_NOT_FOUND, "NOT FOUND");
        }
        //TODO: IEの場合だけ実行するようにする
        if (isImageFile(entity)) {
        	return replaceContentTypeForImageFiles(entity);
        }
        
        return download(entity.getFileName(), entity.getFileBinary(), entity.getFileSize().longValue());
    }

    /**
     * @param entity
     * @return　ダウンロード対象が画像かどうかの判定結果
     */
    private boolean isImageFile(KnowledgeFilesEntity entity) {
    	if (entity.getFileName().toLowerCase().contains("png") ||
    			entity.getFileName().toLowerCase().contains("jpg") ||
    			entity.getFileName().toLowerCase().contains("gif")) {
    		return true;
    	}
    	return false;
    }
    
    /**
     * @param entity
     * @return ContentType修正後のBoundary
     */
    private Boundary replaceContentTypeForImageFiles(KnowledgeFilesEntity entity) {
    	if (entity.getFileName().toLowerCase().contains("png")) {
    		return download(entity.getFileName(), entity.getFileBinary(), entity.getFileSize().longValue(), "image/png");
    	}
    	if (entity.getFileName().toLowerCase().contains("jpg")) {
    		return download(entity.getFileName(), entity.getFileBinary(), entity.getFileSize().longValue(), "image/jpeg");
    	}
    	if (entity.getFileName().toLowerCase().contains("gif")) {
    		return download(entity.getFileName(), entity.getFileBinary(), entity.getFileSize().longValue(), "image/gif");
    	}
    	return download(entity.getFileName(), entity.getFileBinary(), entity.getFileSize().longValue());
    }
```

結果としてIE環境でも画像が表示されるようになりますが
@Monota が前のコメントで仰られている通り

>Options は必要なので、代替として明示的に Content Type (image/png とか) を指定することで IE11 でも画像表示できるようにはなったのですが、そうすると今度はどのブラウザでも添付ファイルをクリックすると同じタブで開いてしまうようになるため、IE11 だけを狙った対応は難しそうでした。

といった問題が発生するので完璧な対応にはなっておりません。

**Comment by Monota** [comment]
@koda-masaru さん、修正しても良ければ私の方で試みますが、いかがでしょうか。
たぶん簡単な方法は、

```<a href="<%= jspUtil.out("file.url") %>">```

のようになっている箇所（アンカータグのみ）を

```<a href="<%= jspUtil.out("file.url") %>&amp;attachment=true">```

のようにパラメーターを１つ追加して、```org.support.project.knowledge.control.open.FileContent``` の中で

```java
if (getParam("attachment").equals("")) {
    if (entity.getFileName().toLowerCase().endsWith(".png")) {
        return download(entity.getFileName(), entity.getFileBinary(), entity.getFileSize().longValue(), "image/png");
    }
    if (entity.getFileName().toLowerCase().endsWith(".jpg") || entity.getFileName().toLowerCase().endsWith(".jpeg")) {
        return download(entity.getFileName(), entity.getFileBinary(), entity.getFileSize().longValue(), "image/jpeg");
    }
    if (entity.getFileName().toLowerCase().endsWith(".gif")) {
        return download(entity.getFileName(), entity.getFileBinary(), entity.getFileSize().longValue(), "image/gif");
    }
}
return download(entity.getFileName(), entity.getFileBinary(), entity.getFileSize().longValue());
```

のような判定を加えることだと思います。スライドについては生成されるのは PNG 固定だと思いますので、SlideLogic の

```down.setContentType("application/octet-stream");```

を

```down.setContentType("image/png");```

にするだけで良いのではないかと思っています。

**Comment by Monota** [comment]
その後動作確認してみましたが、ナレッジに添付ファイルをアップロードした直後にできるファイル名のリンクをクリックしたときの動作が変わってしまうことに気づいたので、いったん考え直すことにします。

 * '''jspUtil.out("file.url")''' でパスを出力するパターン
 * 非同期リクエスト（JSON）で取得したパスを出力するパターン
 * DB から取得したパスを出力するパターン

に分かれることに気づきましたが、２つ目の JSON のパターンに気づいていませんでした。

**Comment by koda-masaru** [comment]
@Monota さん
調査ありがとうございます 👍 

FileControlへの修正は良いと思いました。IE限定かどうかを判定するには、以下のユーティリティをお使いください。（TODOの部分）

```
import org.support.project.web.common.HttpUtil;
   :
        if (HttpUtil.isIE(getRequest())) {
            // ContentTypeの判定
        }
```

（SlideLogicにも、IEかどうかの判定を入れて、同様にContentTypeをセットする）

IE限定に絞った対応になり、かつ、問題の「画像が表示されない」ということの修正を優先したほうが使いやすいということであれば、「ナレッジに添付ファイルをアップロードした直後にできるファイル名のリンクをクリックしたときの動作が変わってしまう」ということは、いったん仕方がない気がします。

IEかどうかの判定を入れておけば、多くのユーザには影響が無いと思いますし。
いかがでしょうか？

**Comment by Monota** [comment]
@koda-masaru さん、ありがとうございます。

content-type が application/octet-stream の場合、IE では img タグで表示不可、Firefox / Chrome は img タグで表示可能、ということがわかりました。また、content-type が image/gif などの場合、すべてのブラウザで img タグで表示可能ということもわかりました。以上から、本文中は content-type を image/gif などにすれば良いと考えました。

IE のみ対応することも考えましたが、上記理由から content-type で対応するのが本質的のような気がしています。

本文は DB （knowledges.content / comments.comment）にもリンクが含まれているので、これら既存データに影響を与えないように添付ファイルを DL する部分だけを attachement=true にしたいと考えています。

昨日書いた JSON に関する問題は Javascript を修正して対処できていて、現在動作確認しています。いったん PR 送らせていただきますので、取り込み難いようでしたら IE11 のみに絞るなど、別の検討を行いたいと思います。

content-type によるメリットは IE の分岐を作ることなく対処できてすべてのブラウザで挙動を統一できる点で、デメリットは添付ファイル（直接ダウンロード）の場合に attachment=true を付ける必要があるという点になると思います。

**Comment by Monota** [comment]
https://ancient-everglades-68752.herokuapp.com/open.knowledge/list
に修正版をデプロイしてみました。無料枠なのでたまにアクセスすると遅いと思いますがご了承ください。あとこの Issue が Close されたら削除します。

**Comment by koda-masaru** [comment]
ありがとうございました。問題なさそうですので、マージしたいと思います。
次回のプレリリースに含めて、利用者の環境でも問題ないことを確認しようと思います。

**Comment by koda-masaru** [comment]
Release v1.10.0 pre1 としてリリースしたためクローズします。
