### ISSUE TITLE
記事の投稿時・更新時などのイベント時に任意のスクリプトを実行したい

### ISSUE THREAD

**Issue by griffin-stewie** [support-project/knowledge#69]
現在はメール通知が表題のようなイベント時に送信されるようになっているかと思います。
メール以外にも各種のチャットサービスなどでも「こんな記事が投稿されましたよ」というような情報が通知できるといいなぁと感じています。

knowledge 側に多数あるチャットサービスに対応させるというのは現実的ではないかと思っています。
そこで、イベントをトリガーにスクリプトを実行できるような仕組みがあると、そのスクリプト内でユーザの好みに合わせた連携処理ができるのではないかと思いました。

GitHub のような WebHook のような仕組みでもいいのかもしれません。

ご検討いただけるとありがたいです。

**Comment by koda-masaru** [comment]
なるほど。アイディアありがとうございます :pray: 

WebHookのような仕組みを提供するのであれば、それほど難しくない気がするので、
対応を検討いたします。少々お待ちください。

**Comment by griffin-stewie** [comment]
:+1:

**Comment by irgaly** [comment]
こちらのissueの通り、メール通知だけでなくWebHookできると嬉しいです。
今のところ以下の対応策があるというところでしょうか。

* Knowledgeが利用者の多いサービスそれぞれに個別に対応
    * ChatWork/Slack... 設定は楽になるが、Knowledge側の機能維持が大変
* Knowledgeから任意のスクリプトを実行できるようにする
    * シェルスクリプトやrubyなど。自由度は高いが環境に依存することと、セキュリティに問題がないか気になります。
* KnowledgeがWebHookの仕組みを用意する
    * Knowldegeが任意のURLへデータを投げる仕組み。認証の仕組みは必要になる。

**Comment by koda-masaru** [comment]
なるほど。実現案はいくつかありそうですね。
私としては、「KnowledgeがWebHookの仕組みを用意する」の案を想定していました。

でも、「Knowledgeが利用者の多いサービスそれぞれに個別に対応」という案も、ユーザのメリットは大きそうですね。

「Knowledgeから任意のスクリプトを実行できるようにする」は、確かにいろいろ検討が必要かもしれません。

いったんは、「KnowledgeがWebHookの仕組みを用意する」を先に提供しようと考えています。

**Comment by griffin-stewie** [comment]
具体的に例えば `Slack対応` のように謳われていれば利用者にとっては簡単に利用できますが、実装対応される方々の負担が増大します。

Knowledge を設置して運用しているような個人・組織の場合、`WebHook` や `任意のスクリプトを実行` の手段さえ提供されていれば、利用者のスキルの高さが期待できるため（ど素人ではない）利用者の好きなようにカスタムできるかと思います。

また、Knowledge の場合は会社のようなクローズドな環境でも設置・運用できるのが特徴だと思っています。

そのあたりを踏まえても

- WebHock
- スクリプト実行

あたりが結果的に Win-Win 形に落ち着くように思います。

**Comment by koda-masaru** [comment]
なるほど。そうですね。
まずはWebHookを提供する方針でいきます。

**Comment by griffin-stewie** [comment]
@koda-masaru
現在、Webhook の実装を進めていただいているかと思いますが、どのような情報が渡ってくる予定でしょうか？
新規投稿と更新の区別はできるようになるとありがたいです。

**Comment by koda-masaru** [comment]
WebHookの検討／実装は @nagodon さんに担当していただいています。

それで、現在の仕様は以下になっていると把握しています。
WebHookで通知するイベントは

- ナレッジを登録／更新したとき
- コメントが投稿されたとき

を想定しています。

通知は、JSON形式で

- ナレッジの登録／更新時

```
{
	"knowledge_id": 1,
	"title": "記事タイトル",
	"content": "記事本文",
	"status": "created",
	"public_flag": 10,
	"tags": [
		"Sample"
	],
	"groups": [
		"ALL USERS"
	],
	"like_count": 2,
	"comment_count": 3,
	"type_id": -100,
	"insert_user": "記事投稿ユーザ名",
	"insert_date": "記事投稿日",
	"update_user": "記事更新ユーザ名",
	"update_date": "記事更新日"
}
```

- コメント投稿時

```
{
	"comment_no": 1,
	"comment": "記事へのコメント",
	"status": "created",
	"insert_user": "コメント投稿ユーザ名",
	"insert_date": "コメント投稿日",
	"update_user": "コメント更新ユーザ名",
	"update_date": "コメント更新日",
	"knowledge": {
		"knowledge_id": 1,
		"title": "記事タイトル",
		"content": "記事本文",
		"public_flag": 10,
		"tags": [
			"Sample"
		],
		"groups": [
			"ALL USERS"
		],
		"like_count": 2,
		"comment_count": 3,
		"type_id": -100,
		"insert_user": "記事投稿ユーザ名",
		"insert_date": "記事投稿日",
		"update_user": "記事更新ユーザ名",
		"update_date": "記事更新日"
	}
}

```

としています。


> 新規投稿と更新の区別はできるようになるとありがたいです。

"status" や "insert_date" と "update_date" の比較で、新規か更新の区別はできるかと思います。

より区別をはっきりさせるために、JSONの中に、 "event" の項目を持ち、
"knowledge_add" / "knowledge_update" / "commnet_add" といったイベント名を
通知するのでも良いかもしれません。

**Comment by koda-masaru** [comment]
あと、Gitterに仕様などを検討しているチャットのルームがあります。
もしよろしければ、そちらも参照願います。

https://gitter.im/support-project

**Comment by griffin-stewie** [comment]
@koda-masaru 
ありがとうございます。私がやりたい事は実現できそうです。リリースを楽しみにしています。

**Comment by koda-masaru** [comment]
使えそうで良かったです :smile: 
リリースまで少々お待ち下さい。

**Comment by nagodon** [comment]
@koda-masaru 
フォローありがとうございます。

@griffin-stewie @koda-masaru

statusにて新規投稿時にcreated、更新時にupdatedといった形で送ることを想定しています。
knowledgeイベントとcommentイベントにそれぞれ違うURLを設定できるのでそれぞれに対しての処理は自由にできるかなと思います。

もしevent名を明示的にしたほうが良ければ変更しようと思います。

**Comment by griffin-stewie** [comment]
@nagodon 

knowledge イベントと comment イベントで別れているんですね。私自身、他のサービスでも Webhook を使った事がないのでどういうものが使いやすいかどうか？というのが分からないので実際にリリースされたら使ってみたいと思います。

**Comment by griffin-stewie** [comment]
@nagodon 

記事の新規投稿時にその記事へのURLは、Webhook を受けた側が `knowledge_id` から生成する想定でしょうか？

**Comment by nagodon** [comment]
@griffin-stewie 

> knowledge イベントと comment イベントで別れているんですね。私自身、他のサービスでも Webhook を使った事がないのでどういうものが使いやすいかどうか？というのが分からないので実際にリリースされたら使ってみたいと思います

了解です
よろしくお願いいたします。

> 記事の新規投稿時にその記事へのURLは、Webhook を受けた側が knowledge_id から生成する想定でしょうか？

すいません、こちらsampleのjsonにないだけでした。
実際はlinkという項目にURLが出力されます。

**Comment by griffin-stewie** [comment]
@nagodon

回答ありがとうございます！

**Comment by koda-masaru** [comment]
マージしましたので、次回のv0.8系のリリースに含めていきます。

**Comment by koda-masaru** [comment]
v1.0.0pre1でリリース済み
