### ISSUE TITLE
LDAP filter to limit access

### ISSUE THREAD

**Issue by hkato** [support-project/knowledge#690]
For example;
(memberOf=CN=Knowledge Group,DC=Example,DC=com)
using RFC4515 style expression.

refs. GitLab ldap configuration.
https://docs.gitlab.com/ce/administration/auth/ldap.html#using-an-ldap-filter-to-limit-access-to-your-gitlab-server

---
例えば
(memberOf=CN=Knowledge Group,DC=Example,DC=com)
の様なRFC4515の形式でアクセスフィルタをかける。

**Comment by hkato** [comment]
このプロジェクトでなく、実際の処理は
https://github.com/support-project/web
org.support.project.web.logic.LdapLogic.java
ですかね？管理用のWebUIは除き。

**Comment by koda-masaru** [comment]
> このプロジェクトでなく、実際の処理は
> https://github.com/support-project/web
> org.support.project.web.logic.LdapLogic.java
> ですかね？管理用のWebUIは除き。

はい。そうです。

現在、 `(memberOf=CN=Knowledge Group,DC=Example,DC=com)` のような形でフィルタをかけることができると思ってましたが、機能が足りないでしょうか？
LDAPについて知識不足ですので、何かあったら教えてください。

**Comment by hkato** [comment]
検証環境がなく遅くなりました。
失礼しましたLDAPについて、よくわかってなかったです。ユーザ認証する部分とフィルタをかける部分が必要なものかと思ってました。
`(&(sAMAccountName=:userid)(memberOf=CN=Knowledge Group,DC=Example,DC=com))`
のように&を取ることによりできました。

**Comment by koda-masaru** [comment]
ご確認＆回答ありがとうございました。
恥ずかしながら、私もLDAPについては本当に基本的なことしか分からないため、
このような情報は助かります。
また何かありましたら、ご連絡ください。
