### ISSUE TITLE
tag Link encode

### ISSUE THREAD

**Issue by hoppybeer** [support-project/knowledge#704]
投稿一覧や投稿詳細を見た際のタグをクリックすると、encodeされないLinkになっているのをEncodeにしてもらえませんか？
キーワードで検索でタグ検索するとEncodeされているのでちょっと違和感が。

**Comment by koda-masaru** [comment]
そうですね。いずれ対応しようと思います。

**Comment by Monota** [comment]
こちらマージしていただいた #712 で対処された気がしています。ご確認お願いします。

**Comment by koda-masaru** [comment]
@Monota ご指摘ありがとうございます。確かに、 #712 で対応されていますね。
対応ありがとうございました。

**Comment by koda-masaru** [comment]
v1.9.0でリリース済です。クローズします。
