### ISSUE TITLE
Template item order

### ISSUE THREAD

**Issue by hoppybeer** [support-project/knowledge#706]
テンプレートを修正/作成する際に、項目の順序を変更できるようにしてほしいです。
あとから追加した項目を上のほうにもっていけるようになるといいのですが。。

**Comment by koda-masaru** [comment]
最新のソースだと、変更できるようになっています。
 #696 でテンプレートと、アンケートの項目の順番の変更が可能になっています。
次回のリリースをお待ち下さい。

**Comment by koda-masaru** [comment]
v1.9.0 pre1 でリリースしました。お時間のあるときにご確認ください。
本issueはクローズいたします。
