### ISSUE TITLE
became_public=true が送信されない場合がある

### ISSUE THREAD

**Issue by ikuko** [support-project/knowledge#708]
以下のようなケースで became_public=true が送信されない場合があります。

1. 非公開で記事を作成
1. 一定の時間待機
私の環境では５分程度でした。
この段階で became_public=false が WebHook で送信されます。
1. 記事を公開に変更
しばらく待っても WebHook が送信されません。

結果的に became_public=true が送信されてきませんので通知などの処理が行えません。

* (2.) の段階を踏まずに非公開で記事をすぐに公開へ切り替えると正常に became_public=true が送信されます。
* (3.) のあとか同時に記事本文を編集すれば WebHook が送信されます。

**Comment by koda-masaru** [comment]
ご報告ありがとうございます。
WebHookの判定処理に不具合がありそうですね。
後日、調べてみようと思います。
年度初めで時間がとれないため、少々時間がかかるかもしれませんがご容赦ください。

**Comment by koda-masaru** [comment]
この対応も、先日リリースした v1.9.0 stable に入っています。（アナウンス漏れです）
ご利用ください。

**Comment by eq5** [comment]
テストしてみたところ問題なさそうでした！
対応ありがとうございました！

**Comment by koda-masaru** [comment]
動いたようで良かったです。安心しました 😄 
Issueはクローズします。
