### ISSUE TITLE
新規インストール後にURLへアクセスするとError Not Foundになってしまう

### ISSUE THREAD

**Issue by YoshizoY** [support-project/knowledge#709]
過去ログ探してみましたが見つけられませんでした。
バージョン1.8.1、1.8.0、1.5.0で確認。
環境はWinSV 2012R2、Apache2.4.23、TomCat9.0、JAVA1.8.0.121

新規インストール後、アクセスするとError Not Foundになってしまう。
セットアップ用管理者ユーザでログインしても変わらず(サインインは出来ている様子)
ただ、右上？に管理者メニューも表示されません。

ページ内のリンクは何を押しても反応せず。
ただし、ChromeのURLの部分は変わる。
　http://xxxxxxx/knowledge/index
　http://xxxxxxx/knowledge/protect.config/index
　http://xxxxxxx/knowledge/protect.knowledge/view_add

<img width="578" alt="default" src="https://cloud.githubusercontent.com/assets/27852458/25273220/d766c25c-26c5-11e7-837b-9dd3a7c5489f.png">

**Comment by koda-masaru** [comment]
上記の情報だけですと、理由がわかりません。
たぶん、ApacheとTomcatの連携の設定に不備があるのでは（？）と思います。
Apacheを通さず、直接Tomcatにアクセスしてみたらどうなりますでしょうか？

**Comment by hoppybeer** [comment]
上記現象は一度うちでも起きました。

https://information-knowledge.support-project.org/install-ja
・Tomcat のインストールのパスには空白が入らないようにしてください

Tomcatを空白の入らないフォルダにインストールしなおして正常に動作するようになりました。

**Comment by YoshizoY** [comment]
返信遅くなりました。
Apache→Tomcatに関しては別のアプリ(GitBucketなど)は動作しているので連携に関しては
特に問題はないような気がします。

インストールパスの空白・・・ですが、確かに空白は入ってますねぇ・・・
デフォルトで突っ込んでたので、「C:\Program Files\Apache Software Foundation\Tomcat 9.0」って
感じなってます。
空白の問題はknowledgeの仕様って感じでしょうか。
だとすると・・・Tomcat、他も再インストールですかねぇ・・・

**Comment by koda-masaru** [comment]
@hoppybeer さん
教えていただきありがとうございました。

@YoshizoY さん
原因がわかれば修正できるので、修正しようと思います。
それまでは、もう一つTomcatをインストールするなどの対策でお願いします。

**Comment by YoshizoY** [comment]
ご回答ありがとうございました。
当面はご提案頂いた方法で対処してみます。

**Comment by koda-masaru** [comment]
GWにデバッグしようと思っていましたら、以下のプルリクエストにて、@Monota さんが対応してくれました。

https://github.com/support-project/common/pull/27

というわけで、次のリリースで修正されます。（GW中には次バージョンをリリースしたいと思っています）
