### ISSUE TITLE
脚注から正しくジャンプできない？

### ISSUE THREAD

**Issue by tAkihiko** [support-project/knowledge#711]
脚注記法を用いた際、付与されるリンクのURLで

* `http://<BASE-URL>/open.knowledge/view/N#fn-1`
* `http://<BASE-URL>/open.knowledge/view/N#fnref-1`

に（おそらく）なって欲しいところが、

* `http://<BASE-URL>/#fn-1`
* `http://<BASE-URL>/#fnref-1`

になっており、脚注の数字や矢印をクリックした際にトップページへページ遷移が発生するようです。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
別のところを変更したときに、脚注のリンクが正しくうごかないようにしてしまったようです。
修正しますので、少々お待ち下さい。

**Comment by koda-masaru** [comment]
v1.9.0 pre1 でリリースしました。お時間あるときにご確認願います。
本issueはクローズいたします。もし問題があれば、お手数ですが、再度issue登録をお願いします。
