### ISSUE TITLE
When tag name icludes "&", tag name search does not work correctly.

### ISSUE THREAD

**Issue by Monota** [support-project/knowledge#712]
タグ名に ＆ が含まれていると、そのタグ名をクリックしたときにタグ名で絞られずに全件表示される場合がある。具体的には、タグ ID で検索している箇所は正しく検索できるが、tag name で検索している箇所は正しく検索できない。

**Comment by Monota** [comment]
tagname=P&G のように & が含まれているとリクエストパラメーターが tagname=P で区切られているようですので、パーセントエンコーディングすると回避できるような気がします。ちょっと試してみます。

**Comment by Monota** [comment]
修正してみたら common / web / knowledge すべてに修正が入ってしまいました。お手数ですが不手際がありましたらすべて却下してください。

あと Github あまり使い慣れていないのでもっとこうした方がいいとかあれば教えて頂けると助かります。よろしくお願いします。

**Comment by koda-masaru** [comment]
@Monota さん
プルリクありがとうございます 😄 
内容を確認させていただきます。

**Comment by koda-masaru** [comment]
マージしたものを、v1.9.0 pre1 でリリースしました。お時間あるときにご確認願います。
本issueはクローズいたします。もし問題があれば、お手数ですが、再度issue登録をお願いします。
