### ISSUE TITLE
テンプレート使用時の表示

### ISSUE THREAD

**Issue by tnaoki0529** [support-project/knowledge#717]
テンプレート使用時に下記のように表示することは可能ですか？
機能としてはとても良いのですが、少し見づらいと感じています。
＝＝＝＝＝＝＝＝＝＝＝＝
テンプレート項目：中身
テンプレート項目：中身
テンプレート項目：null
＝＝＝＝＝＝＝＝＝＝＝＝
↓
＝＝＝＝＝＝＝＝＝＝＝＝
テンプレート項目：
中身

テンプレート項目：
中身

テンプレート項目：
（空白）
＝＝＝＝＝＝＝＝＝＝＝＝

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。今後検討していこうと思います。

上記のように変更することは難しくないのですが、テンプレートの項目名が長くなったときにレイアウトが崩れるので、どうしようか迷います。
特に、英語圏の場合、項目名とか長くなるので、海外のユーザが困るのではないかと。

表示形式を選択可能にするといった方法が良いのかもしれませんが、あんまり機能をつけると、また混乱するような気もしますね。難しい。

Knowledgeは、「機能は多くないけど、直観的で簡単に使える（投稿も簡単）」を目指しています。

**Comment by tnaoki0529** [comment]
ご返信ありがとうございます。
項目名がhタグ、中身がpタグ区切りでもレイアウト崩れが発生しますでしょうか？
本文がマークダウン形式で編集しているので似たようなレイアウトの方が見た目に差異がなくて良いと感じました。

**Comment by koda-masaru** [comment]
v1.10の中でデザインの修正を検討していこうと思います。まず、デモサイトでデザイン修正案をだしてみて、反応を見ようと思います。 
（#749 と一緒に検討します）

**Comment by koda-masaru** [comment]
@tnaoki0529 

テンプレートを追加した場合のデザインをどうするか検討していたのですが、 #281 で上記内容と逆に変更したことを思い出しました。（issue登録を受けたときには、忘れてました）

上で書かれている要望「項目ラベルの後改行し、その後に値を表示する」が #281 対応以前の表示で、#281 の中の「縦に長くなりすぎていて編集しにくいためもう少しコンパクトにしてほしい」という中で「項目ラベルの後に改行せずに、値を表示する」に変更しています。（テキストエリアの場合改行する）


```
＝＝＝＝＝＝＝＝＝＝＝＝
テンプレート項目：中身
テンプレート項目：中身
テンプレート項目：null
＝＝＝＝＝＝＝＝＝＝＝＝
↓
＝＝＝＝＝＝＝＝＝＝＝＝
テンプレート項目：
中身

テンプレート項目：
中身

テンプレート項目：
（空白）
＝＝＝＝＝＝＝＝＝＝＝＝
```

- 「項目ラベルの後改行し、その後に値を表示する」
    - 縦に長くなる
「項目ラベルの後に改行せずに、値を表示する」
    - 縦に長くならない

は相反する要求で、どちらを採用すれば良いか迷うところですが、前にデザイン変更を対応したものですので、また変更する（元に戻す）のもいかがなものかと思います。
とりあえず、現状では、今のまま（縦に長くならないようにする）を採用しておこうと思います。
（どちらのデザインが良いか、投票で決めるといった方法が良いのかも）

**Comment by koda-masaru** [comment]
Release v1.10.0 pre1 としてリリースしたためクローズします。
