### ISSUE TITLE
ユーザー情報変更時不具合

### ISSUE THREAD

**Issue by tnaoki0529** [support-project/knowledge#719]
ユーザー変更ができなくなってしまいました。
変更を行うとIDの部分が下記のようになってしまいます。

[Ljava.lang.String;@53e11db8

**Comment by koda-masaru** [comment]
@tnaoki0529 さん
ユーザ変更とは、どの機能のことでしょうか？
「メニュー」→「自分のアカウント情報」で更新する画面でしょうか？
また、ご利用のバージョンは何でしょうか？

テストサイトでは、「自分のアカウント情報」のメニューからは、更新できたのですが、発生した問題をもう少し詳細に教えてください。

**Comment by tnaoki0529** [comment]
「メニュー」→「自分のアカウント情報」、
「システム設定」→「ユーザ管理」
どちらからもユーザー情報の変更が反映されていない状態です。

また新規作成時はインターナルサーバーエラーが発生致します。

**Comment by tnaoki0529** [comment]
すいません。
状況を細かく見たところ、
「アカウント情報」、「ユーザの更新」ページに入ると自動的のパスワードが入力されており、不一致のため更新できないという状況ですした。
こちらは自動的にパスワードが入ってしまうのでしょうか。

新規に関してはインターナルサーバーエラーで登録できない状況になっています。

**Comment by koda-masaru** [comment]
@tnaoki0529 さん
自動的にパスワードが入るのは、お使いのブラウザの挙動になります。
最近のブラウザでは、パスワードをセットするのが普通のようですが、ブラウザの挙動ですので解除することはできません。（パスワードを保存しない設定にするとセットされないブラウザもあるのですが、パスワードを保存しないのは、非常に面倒になるので、やはり対応できません）

新規に関してですが、テスト環境などでエラー無くユーザ登録ができました。
管理者のシステムメニューに、ユーザ登録方法の選択がありますが、これが、
「ユーザ自身でメールアドレスを登録し、システムから招待のメールを出す（メール送信設定が必要です）」  
になっており、そしてメールの設定をしていないということは無いでしょうか？

**Comment by tnaoki0529** [comment]
カスタムDB→組み込みDBへコピー→新規カスタムDBコピー
することで問題が解消されました。
お手数をおかけいたしました。
