### ISSUE TITLE
アンケートの集計画面の表示に関する問題

### ISSUE THREAD

**Issue by il-m-yamagishi** [support-project/knowledge#724]
![a](https://cloud.githubusercontent.com/assets/15116901/26095613/2d35a6ac-3a59-11e7-8e22-eb8e4cf98b7e.png)

- 回答日時がUTCになっています。
- 右の `glyphicon glyphicon-export` アイコンが表示されていません。 `fa fa-download` あたりに変えてはいかがでしょうか。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
#726 で修正しました。

**Comment by koda-masaru** [comment]
v1.9.0でリリース済です。クローズします。
