### ISSUE TITLE
1.9.0 pre3に更新した後で記事を作成、更新すると「Forbidden [403]」と表示される

### ISSUE THREAD

**Issue by johiroshi** [support-project/knowledge#729]
ご無沙汰しています。昨日knowledge1.6.0→1.9.0 pre3に更新しました。本日knowledgeにて既存の記事を更新しようした際、「Forbidden [403]」と表示されました。新規に記事を作成した場合も同様の症状が観察されました。記事の閲覧などRead系の動作に関しては異常がないように見受けられます。参照すべきログの場所や対処などのご助言を頂きたいです。よろしくお願いします。

![forbidden](https://cloud.githubusercontent.com/assets/15374413/26230206/1a9752ae-3c82-11e7-8adc-f3cb1de8d389.png)

**Comment by koda-masaru** [comment]
管理者でログイン後、「システム設定」→「システム設定」のメニューに遷移していただき、「サービスのURL」をご利用の環境に合わせて設定を見直してください。
このURLがあっていないと、Forbidden [403]が発生するように変更を行っています。

変更理由：CSRF脆弱性への対策
CSRFの対策のために、KnowledgeではPostやPut、Deleteといったデータを変更する処理を実施する際に、その送信元が正しい送信元かをHttpHeaderのrefererを見てチェックします。このチェックに使うURLが、上記の「サービスのURL」になります）
（なおCSRF対策は「Referer が正しいリンク元かチェックする」「トークンを利用して正しいリクエストかチェックする」の2つで対策しています）

**Comment by johiroshi** [comment]
解決しました。ありがとうございます。
見落としていましたが、#566 が関連した内容みたいですね。
