### ISSUE TITLE
コメントの修正

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#73]
- コメントの修正ができれば、コメントの乱立を防ぐ事ができる

**Comment by anrcny** [comment]
ツイッタではお世話になってます。
同様にコメントの扱いで悩んでました。


修正案

- コメント記入者によるコメント修正、削除
```
コメント記入者が記入誤りの修正や、
コメント自体を削除する事を目的に提案。
```

- エンティティ管理者によるコメント折り畳み(エンティティ管理者が折り畳み理由を書き込みたい)
```
エンティティコンテントの修正要求コメントがあった場合
「○○から××へ変更済み(yyyy/mm/dd)」のように
エンティティ管理者コメントを付けてコメントを折り畳みたい。
残したいコメントだが、常に表示させる必要のないコメントが多いと
邪魔になってしまう状況に陥るため提案。
```

- エンティティ管理者によるコメント削除
```
コメントがエンティティコンテントから逸脱する話題になる事があった。
エンティティ管理者が別エンティティへ誘導するように催促後に
残ったコメントが邪魔になってしまっていたのでDBからコメントを直接削除していた。
そのため提案。
```

**Comment by koda-masaru** [comment]
コメントの扱いの要望は、コメントの修正以外にもありそうですね。
エビデンスとしてとっておくために、わざと修正も削除も出来ないようにしたのですが、
運用を考えると、ナレッジの編集者における折りたたみや削除も検討した方がよさそうです。
対応を検討しますので少々お待ちください。

**Comment by koda-masaru** [comment]
まずは、コメント修正／削除の機能を追加しました。
修正や削除は、コメントを登録したユーザか、もしくは、指定のナレッジの編集者（エンティティ管理者）が行えるようにしています。

**Comment by koda-masaru** [comment]
- エンティティ管理者によるコメント折り畳み(エンティティ管理者が折り畳み理由を書き込みたい)
- エンティティ管理者によるコメント削除
は、後で追加しようと思います。

**Comment by koda-masaru** [comment]
v0.7.0正式リリース済みです。issueはクローズします。
