### ISSUE TITLE
閲覧する権限が無い投稿が検索結果に表示されます

### ISSUE THREAD

**Issue by il-mtakada** [support-project/knowledge#731]
knowledgeのバージョンは1.9.0です。

ログインした状態でtagNamesやgroupNamesのクエリで検索すると権限が無い投稿が検索結果に表示されてしまうようでした。

下のようなクエリです。
knowledge/open.knowledge/list?tagNames=議事録

タグのボタンから検索した時にこのクエリが使われていました。

検索結果にタイトルなどが表示されますが権限がない投稿の内容自体は見れていないので大きな問題ではないと思われます。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。これは、不具合ですね。
修正しようと思います。

**Comment by nagodon** [comment]
@Monota ご対応ありがとうございます。
こちら自分が入れてしまった不具合ですね。。。
すみません。

**Comment by koda-masaru** [comment]
@nagodon 私も動きに気づきませんでしたし、お気になさらず。
ほんとは、私がちゃんとテストコードを用意するべきなんですよね :sweat_smile:
業務での開発と違い、趣味の開発ではテストがおざなりにしているので反省です。

**Comment by koda-masaru** [comment]
v1.9.0でリリース済です。クローズします。

**Comment by Monota** [comment]
@nagodon さん、私も全然気にしてないです。時間あるときに報告のあったバグを直しながら仕様理解に努めているところです。

**Comment by il-mtakada** [comment]
対応ありがとうございました :bow:
