### ISSUE TITLE
記事へのリンク方法は変わったのでしょうか？

### ISSUE THREAD

**Issue by johiroshi** [support-project/knowledge#732]
v1.6.0.までだと```[3](3)```でID3の記事にリンクできたのですが、v1.9,0pre3で先のようなリンクを踏むと「Not Found」と表示されます。一方、```[#3](#3)```と書くと、以前のようにハイパーリンクが機能します。これは仕様が変わったということでしょうか。

動作確認用URL
https://test-knowledge.support-project.org/open.knowledge/view/11

#512 など関連するIssueは探したのですが見つけられませんでした。

ご回答、よろしくお願いします。

**Comment by koda-masaru** [comment]
別の対応の副作用でリンク出来ないようになっていました。
`[3](3}` でも動作できるように修正しますので、少々お待ちください。
（既存の記事も正しく表示できるようにします。）

ちなみに、新しいバージョンでは、GitHubのように、 `#` から始まる記事の番号を書くと（ `#100` など）別の記事へのリンクになります。

**Comment by johiroshi** [comment]
了解です。
お忙しいところ申し訳ありませんが、よろしくお願いします。
IssueはOpenのままにしておきます。修正の後にCloseしてください。

**Comment by johiroshi** [comment]
たびたびすみません、ひとまず以前のリンクが動作するバージョンまで戻したいのですが、いくつから仕様が変わったか教えていただけますか？

**Comment by Monota** [comment]
データベースのバックアップがあるなら、1.6.0 にデータベースと一緒に戻すと良いと思います。

戻した先のバージョンがいくつにせよ、すでにデータベーススキーマは 1.9 のものに自動アップグレードしているはずなので、アプリケーションだけを安全に戻せる保証はないように思います。

**Comment by koda-masaru** [comment]
@johiroshi さん
先週末に、 #735 でパスがおかしくなる現象を修正しました。
v1.9.0に、 #735の対応のみしたものが最新になるのですが、それをリリースすることも可能です。
リリースした方が良いでしょうか？

バージョンを戻すのであれば、 @Monota さんの書かれているように、バックアップしてあったバージョンに戻すのが一番かと思います。

**Comment by koda-masaru** [comment]
ちなみに、テスト環境は、上記のパスの修正済のものを適用しています。
よろしければお試しください。
https://test-knowledge.support-project.org/open.knowledge/list

**Comment by johiroshi** [comment]
@Monota さん
データベースも戻さないといけないのは大変そうですね。どうもありがとうございます。

@koda-masaru さん
ご連絡ありがとうございます。
#735を見てパスの問題が修正されたかもしれないと考え、既に更新したのですが依然としてハイパーリンクが機能しませんでした。バージョンも1.9.0であることを確かめました。
![version](https://cloud.githubusercontent.com/assets/15374413/26381468/ffc58324-405f-11e7-95e1-fe536541d3e7.png)

テスト環境の方は動作が確認できたので、もう一度インストールをし直してみます。

**Comment by koda-masaru** [comment]
@johiroshi 
説明がわかりづらかったかもしれません。
上記の #735 の対応は、 v1.9.0 stable リリースの後に対応したため、リリースページからダウンロードできるwarにはその対応が入っていません。
このため、もし最新をご利用になりたい場合は、最新のビルドを出そうかな（どこかでダウンロードできるようにする）と考えていました。
今、最新版をビルドしていますので、少々お待ち下さい。できたらリリースページからダウンロードできるようにしますね。

**Comment by johiroshi** [comment]
ありがとうございます。すみません、よろしくお願いします。

**Comment by koda-masaru** [comment]
以下に、 #735 の対応を入れたものをリリースしました。ご確認願います。
https://github.com/support-project/knowledge/releases/tag/v1.9.1pre1

**Comment by johiroshi** [comment]
どうもありがとうございます。本日は記事編集中のユーザがいるため、明日の朝に確認させていただきます。

**Comment by johiroshi** [comment]
動作確認しました。大変助かります。どうもありがとうございます！
