### ISSUE TITLE
knowledge本文の文書に色を付けたい

### ISSUE THREAD

**Issue by johiroshi** [support-project/knowledge#734]
knowledge本文の文章中に色を付けたい、と社内ユーザからの機能改善要望がありました。
昔の```<color>```タグや```font-color```属性的な機能です。
Markdownの本来の意図とは逸れるので、難しいかも知れませんが、お伝えさせていただきます。よろしくお願いします。

**Comment by koda-masaru** [comment]
Knowledgeでは、Markdownの中でHTMLがあるていど書けるので、フォントの色を<font color="red">変えることは可能</font>です。（セキュリティ上危険なタグは消しています）
ただ、HTMLを直接書かないといけないので、少し面倒です。
要望の声が大きければ、それを簡易に編集する方法を考えてもよいかもしれません。
いったんは、以下のようにご利用ください。

以下をKnowledgeにコピ＆貼付けすると確認できます。

```
Knowledgeでは、Markdownの中でHTMLがあるていど書けるので、フォントの色を<font color="red">変えることは可能</font>です。
```

**Comment by johiroshi** [comment]
どうもありがとうございます。ひとまず、この情報を伝えてみます。
