### ISSUE TITLE
very minor Japanese typo 

### ISSUE THREAD

**Issue by corselia** [support-project/knowledge#736]
your product `Knowledge` is very awesome and useful, thanks so much!

in [`knowledge/src/main/resources/appresource_ja.properties` l495](https://github.com/support-project/knowledge/blob/master/src/main/resources/appresource_ja.properties#L495), Japanese expression has very minor typo.

- incorrect
`立って`

- correct
`経って`

please modify it when you have sufficient time because of very little typo :)

**Comment by koda-masaru** [comment]
Thank you for letting me know.
Would you create a pull request?

**Comment by corselia** [comment]
thanks, I see.
I'll send pr as soon as possible :)
