### ISSUE TITLE
in case embedded db is restored, Internal Server Error occurs when user info is tried to update

### ISSUE THREAD

**Issue by corselia** [support-project/knowledge#737]
# TL;DR
- 1. clean install by [docker version](https://github.com/support-project/docker-knowledge)
- 2. restore embedded db
- 3. start embedded db engine
- 4. delete custom db config
- 5. Internal Server Error occurs by user's info updated (system config menu)
- 6. more, embedded db stopped, the same error occurs and can't access `Knowledge` eternally this session

# other case as same result
- procedure from TL;DR's i. to iii. is the same 
- 4. copy data from embedded db to custom db (PostgreSQL)
- 5. Internal Server Error occurs by user's info updated (system config menu)

# small screenshot of Internal Server Error
![20170524125847](https://cloud.githubusercontent.com/assets/14275619/26389877/0149983e-4097-11e7-8aff-30091356821c.png)

# message of Internal Server Error
because of too long, attach [text file](https://github.com/support-project/knowledge/files/1024612/knowledge_internal_server_error_message.txt)

# note
- only docker version? 
- after trying to update user's info, `user id` has increased by case
- when create new user and update its user's info, error doesn't occur
- from error message, SQL should be not INSERT but UPDATE?
    - I'm a beginner so it may be incorrect

`Knowledge` is very very useful product, thanks a lot :)

**Comment by koda-masaru** [comment]
Thank you for letting me know.
I will investigate the cause of the error.

**Comment by Monota** [comment]
1. docker-compose up -d でコンテナを初回起動する（yml は[こちら](https://github.com/support-project/docker-knowledge/blob/master/docker-compose.yml)を利用）。
1. 組み込み DB を停止する。
1. 過去に保存しておいた別のバックアップから復元する。
1. 組み込み DB を開始する。
1. カスタム DB の設定を行う（通常は jdbc:postgresql://knowledge_db_1:5432/knowledge_production）。
1. 組み込み DB で保存していたデータをカスタム設定の DB にコピーする。
1. システム設定 -> ユーザー管理 から管理者を空更新する。

で再現するという捉え方で良いでしょうか？

可能性として、バックアップデータがすでに壊れていた可能性は考えられると思いますので、再現するバックアップデータを提供可能であればご提供いただけるとこちらでも再現しやすいかもしれません。

**Comment by corselia** [comment]
@Monota 
はい、そのような流れです。
「7.」については少々あいまいなのですが、「1.」～「6.」についてはその手順になります。

バックアップデータは確かに一度だけ取った同じものを用いて上記手順を繰り返していました。
改めてエクスポート含め、全体を通して確認してみたいと思います。

**Comment by koda-masaru** [comment]
I modified the handling of data in v1.11.0.
Therefore, I think that this problem is cured.
Would you please check with v1.11.0?

------

 v1.11.0 の中でデータの扱いを修正しました。
そこで、この問題も治っていると思います。
v1.11.0 で確認していただけないでしょうか？

**Comment by corselia** [comment]
@koda-masaru 
ご対応ありがとうございます。確認させて頂きますので、少々お待ち願います。

**Comment by corselia** [comment]
@koda-masaru 
遅れてしまいすいません。まさに今から、検証いたします。

**Comment by corselia** [comment]
@koda-masaru
こちら、修正を確認いたしました。
ご対応ありがとうございました！

I checked v1.11.0 and it works correctly.
thank you fix it!
