### ISSUE TITLE
タグが数文字でスクロールして消えてしまう

### ISSUE THREAD

**Issue by kounoike** [support-project/knowledge#74]
![20150723-220417](https://cloud.githubusercontent.com/assets/6997928/8850944/00d6bb46-3187-11e5-9516-a7e6d0baecc5.png) のように、abcdefghijkl というタグを入力しようとしてもスクロールしてしまって前の方が見えなくなってしまいます。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
確かに、タグ入力のところで、長い文字を入力するとおかしくなります。
タグ入力の部分は、ライブラリ（bootstrap-tagsinput）を使っているのですが、
何か対策が無いか調べてみます。

**Comment by kounoike** [comment]
https://github.com/timschlechter/bootstrap-tagsinput/issues/344
この辺みたいですね
ちょこっとブラウザ側のインスペクタで試したところ、
input type="text" placeholder="タグ"のstyle属性を消すことで解決しそうです

**Comment by koda-masaru** [comment]
情報ありがとうございます :+1: 
試してみようと思います。

**Comment by koda-masaru** [comment]
タグの入力幅を300pxまで拡張しました。
いったん、リリースしましたので、issueはクローズします。
（もっと広い方が良いといった意見があれば、別issueで管理します）
