### ISSUE TITLE
default publication range in usermenu is different from real one

### ISSUE THREAD

**Issue by corselia** [support-project/knowledge#740]
### default publication range
default publication range after user created is `private` (ref below).

![default_publication_range_02](https://cloud.githubusercontent.com/assets/14275619/26573724/c7b542c2-4559-11e7-91cb-796f2247efed.png)

### in usermenu range
but in usermenu, selected `public (to all users)` initially (ref below).

![default_publication_range_01](https://cloud.githubusercontent.com/assets/14275619/26573744/d5f3f50e-4559-11e7-959a-acacd0480092.png)

### not intuitive?
if no operation in this usermenu, range is still `private` of course.
so users must push `save` button on purpose.
I think this non intuitive. How is this?

### ps
`Knowledge` is very very indeed sexy product! thanks! :-)

**Comment by koda-masaru** [comment]
I feel that it certainly is not intuitive.
And I will change the initial value on user menu to private.

By the way, the reason for the difference between the edit page default and the user menu defaults is as follows.

Initially, the default publication range was both "public". (if user setting was not exists, default value was "public")
However, during article editing, many users post by mistake, the default value of the editing page was change to "private". Also, at the time of this change, there was not a draft save function, so many users hoped that the initial value is better for "private".
And I forgot to change the initial value of the publication range of the user menu to "private".

**Comment by corselia** [comment]
@koda-masaru 
I see, I see 😄 

your aim is clear and understandable, and I also agree.
thank you for accepting my idea!

**Comment by koda-masaru** [comment]
Release v1.10.0 pre1 としてリリースしたためクローズします。
