### ISSUE TITLE
permission denied from different host (port number) access to existing articles?

### ISSUE THREAD

**Issue by corselia** [support-project/knowledge#743]
## summary
I changed `Knowledge` server address from `http://foo:8080` to `http://bar:8080`, for example. so I cannot edit existing articles (but can read).

## error message
error message about this problem is below, I considered.

```
WARN  2017-06-06 05:29:38,341 [HttpRequestCheckLogic(67)] It is a request from outside the system.
INFO  2017-06-06 05:29:38,342 [LoggingFilter(100)] POST  http://bar:8080/open.knowledge/marked  403     192.168.160.102 2[ms]
```

## cannot edit existing articles from other host (port number)?
I assume articles are recorded with hostname (port number) in db, so when host changed, cannot edit.

## notes
because of forecast without reading codes, sorry if incorrect.

**Comment by koda-masaru** [comment]
Sign in as an administrator, please click to "System Setting" -> "System Setting" menu and check the "Service URL" according to your environment.
If this URL does not equal access url, system send Forbidden [403] error on http post/put method.

Reason for change: Measures against CSRF vulnerability
"Knowledge" adopts the method of "Checking the Referer Header" and "Synchronizer (CSRF) Tokens" as measures against CSRF

https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Checking_the_Referer_Header
https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Synchronizer_.28CSRF.29_Tokens

Same issue on Japanese: #729

**Comment by corselia** [comment]
@koda-masaru 
oh...
I understand very well.
and apologize for duplicated issue such as #729 and #566, sorry 😓 

thanks for your precise answer.
