### ISSUE TITLE
デフォルトの公開範囲の設定を設定しているのに、新規作成時に設定されない

### ISSUE THREAD

**Issue by htakeda** [support-project/knowledge#744]
#741 と同じかもしれませんが、上げさせていただきます。

[メニュー]-[デフォルトの公開範囲の設定]画面で、「保護(公開先を選択)」を指定し、公開先を指定して保存しました。

しかし、新規作成画面に行くと、「公開範囲の指定」のフラグは「保護(公開先を選択)」になっているのですが、公開先は設定されていません。

内部的には設定されているのかと思ったのですが、投稿したあとの画面をみても設定されていませんでした。

対応しているのがフラグのみのようにみえます。

**Comment by koda-masaru** [comment]
テスト環境にて、 user3 のデフォルトの公開範囲を指定して、その後に記事を投稿してみたのですが、
その公開範囲の指定で設定されました。特に問題無く動いているように見えます。

https://test-knowledge.support-project.org/open.knowledge/view/7

公開先のグループ／ユーザ名が特殊であったりしますか？

**Comment by htakeda** [comment]
グループ名やユーザ名は特に特殊ではありません。
一番最初(グループにメンバー登録直後)は、作成表示されました。
しかし、2回目（トップページから「作成」をやった場合)には、表示されませんでした。
それ以降は、ずっと表示されません。

![2017-06-08_09h26_58](https://user-images.githubusercontent.com/11866919/26907261-5ab1df52-4c2d-11e7-878a-d3feb1abb326.png)
![2017-06-08_09h27_44](https://user-images.githubusercontent.com/11866919/26907262-5ab27660-4c2d-11e7-8b36-954311d8f8e8.png)

**Comment by koda-masaru** [comment]
なるほど。2回目だとセットされないのですね。
原因を調べてみようと思います。

**Comment by koda-masaru** [comment]
修正しました。デモサイトに最新を反映しましたので、お時間があれば確認願います。
https://test-knowledge.support-project.org/open.knowledge/list

**Comment by koda-masaru** [comment]
Release v1.10.0 pre1 としてリリースしたためクローズします。

**Comment by htakeda** [comment]
遅ればせながら、確認しました。
ご対応ありがとうございます。
1.10にもアップグレードして確かめてみました。
