### ISSUE TITLE
テンプレートを更新できない

### ISSUE THREAD

**Issue by ino9999** [support-project/knowledge#745]
はじめまして。

新規作成したテンプレートを項目変更し保存したのですが、保存内容が反映されません。

テンプレートを新規作成→保存
作成したテンプレートを選択→項目等変更→保存★更新しましたとメッセージが表示される
一覧に戻るボタンを押下→修正したテンプレートを選択
変更した項目が反映されていない　といった状態となります。

こちら何か設定が必要でしょうか？

**Comment by koda-masaru** [comment]
特に設定などは必要ありません。
テスト環境で、テンプレートを追加して試してみましたが、特に問題無く動きました。
https://test-knowledge.support-project.org/open.knowledge/view/6
（テスト環境は、定期的にデータクリアしているので、そのうち見えなくなります）

#746 と関連があるのかもしれません。

**Comment by ino9999** [comment]
koda-masaru 様
ご返答ありがとうございます。
#746 で対応しましたら、こちらも解決しました。ありがとうございました。
ただ、別の問題（運用回避可）が発生しましたので、他のissues に新規に登録させていただいます。

以上、よろしくお願いします。

**Comment by koda-masaru** [comment]
解決したようで良かったです。
issueはクローズいたします。
