### ISSUE TITLE
検索ワードが全角文字の場合検索結果のテキストリンクから遷移できない

### ISSUE THREAD

**Issue by ino9999** [support-project/knowledge#746]
お世話になります。

デモ環境では再現しないのですが、社内で作成している環境で以下の状態となります。
こちら何か設定が必要でしょうか。お手数おかけしますが、ご教示いただければ幸いです。

ナレッジを登録→ナレッジに含まれている全角ワードで検索→検索結果からテキストリンクで遷移→400エラー正しくない要求　と表示される
ナレッジを登録→ナレッジに含まれている半角英数で検索→検索結果からテキストリンクで遷移→可能

以上、よろしくお願いします。

**Comment by koda-masaru** [comment]
Knowledgeを動かしているサーバーはTomcatでしょうか？またバージョンはいくつでしょうか？
古いバージョンのTomcatでは、日本語を扱える設定が必要な場合があります。

以下のページが参考に設定をご確認願います。
http://pecoegg.com/website-105.html

**Comment by ino9999** [comment]
ご返答ありがとうございます。
tomcat です。バージョンは　8.5.15.0　です。
urlの情報ありがとうございます。試してみます。
すみません、可能でしたら、デモサイトで利用されているバージョンを教えていただいてもよろしいでしょうか。

**Comment by johiroshi** [comment]
knowledgeデモサイトのバージョンはこちらから確認できます。
https://test-knowledge.support-project.org/open.license

**Comment by ino9999** [comment]
johiroshi 様　ご返答ありがとうございます。
言葉足らずですみません。デモサイトで利用されているtomcatのバージョンを知れればと思って質問しました。

すみません、本件koda-masaru 様からご返答いただいたurlで対応しまして、再現しなくなりました。
ありがとうございました。

**Comment by koda-masaru** [comment]
解決したようで良かったです。
issueをクローズいたします。

**Comment by EbiSenbei** [comment]
お世話になっております。
表題の減少と同じ現象が発生しており、koda-masaru様の参考ページを対応しても
解消いたしませんでした。
他に原因となる設定はございますでしょうか？
■環境
　knowledge：v1.8、　Tomcat　 ：v8.5
 
どうぞ宜しくお願い致します

**Comment by koda-masaru** [comment]
今思いつく限りでは、他に思いつくところはありません。

[Knowledgeのデータディレクトリ](https://information-knowledge.support-project.org/backup-ja) の中に logs/app.log というログファイルがあると思います。
そちらに何かエラーが出力されていないでしょうか？

また、同じく app.log でアクセスされたパスを出力していると思いますが、その値が日本語を含む場合にどのような出力になっているでしょうか？

- このような出力になっています

```
INFO  2017-06-24 21:37:56,414 [LoggingFilter(100)] GET	https://service-knowledge.support-project.org/open.knowledge/list?keyword=%E3%83%86%E3%82%B9%E3%83%88
```

**Comment by hiroG3** [comment]
はじめまして。
現在、社内導入を検討中により、お試しで使用している者です。
■環境
・Tomcat：Ver 8.5.15
・Java：1.8.0.131
・OS：Windows7 SP1 (32bit版)
・ブラウザ：IE11
・Knowledge：Ver1.9.0

表題の事象が下名の環境でも起きたため、koda-masaru様ご紹介のサイトを拝見し、
Tomcatのserver.xmlに試してみましたが、改善しませんでした。
app.logも確認してみましたが、
以下のとおり、日本語部分がエンコードされている状態でした。
``
・GET	http://<IPアドレス>:<ポート>/knowledge/open.knowledge/list?keyword=%E8%AA%AC%E6%98%8E%E6%9B%B8
``

一旦、server.xmlを元に戻し、
下名なりに調査したところ、
以下のとおり、URLの『keyword=』部分に違いがあることがわかりました。

```
■日本語『説明書』という文字を検索`
（１）検索した結果を表示したときのURL
  http://<IPアドレス>:<ポート>/knowledge/open.knowledge/list?keyword=%E8%AA%AC%E6%98%8E%E6%9B%B8
（２）（１）の検索結果のリンク先を表示したときのURL(HTTPエラー400が出るURL)
  http://<IPアドレス>:<ポート>/knowledge/open.knowledge/view/6?keyword=説明書&tag=&tagNames=&template=&user=&offset=0&group=&groupNames=

■（１）と（２）の相違点
（１）では『keyword=』部分がエンコードされているのに対し、
（２）では検索した日本語がエンコードせずそのまま記述されています。
```

そこで確認ですが、
上記の（２）のURLの『keyword=』部分がエンコードされていないのは、仕様なのでしょうか？
なお、エンコードした文字に変更すると、HTTP400のエラーは表示せず、期待通りの動作になります。

お忙しいところ申し訳ありません。
回答をお願いいたします。

**Comment by koda-masaru** [comment]
@hiroG3 さん
URLエンコードを明示的にかければ解決しそうですね。
後で対応をいれてみて動きを確認しようと思います。
ただ、私の環境ではエラーが再現しないのが不思議ですが。。。

**Comment by Monota** [comment]
私のローカルでも再現しませんでした。
途中に Apache とか立てているのであれば、そちらの設定は問題ないでしょうか。
HTTP 400 を返しているのは Knowledge で正しいでしょうか。

**Comment by hiroG3** [comment]
koda-masaru様

回答頂きありがとうございます。

下名もChromeでも試して見たのですが、
確かに表題の事象は発生しませんでした。
また、URLの『keyword=』部分について見たところ、
全てエンコードしていない文字でした。

よって、IEの場合に限定して意図的に処理されているのかと思い、質問した次第でした。

参考になるかわかりませんが、
一応ご報告いたします。

よろしくお願いいたします。

**Comment by koda-masaru** [comment]
IEですか。IEはレガシーなシステムを動かすための設定などがあったりして、一括りにできない挙動をします。（御社内のIEの設定だと動かず、別の会社の設定では動くといったことがある）

> よって、IEの場合に限定して意図的に処理されているのかと思い、質問した次第でした。

上記のような状況ですので、IEを積極的にサポートをしようとは思いませんし、IEのための独自の処理を追加することもありません。

申し訳ありませんが、上記で対応するか検討すると書きましたが、本件についてIEのみで発生するという話であればクローズしようと思います。

**Comment by hiroG3** [comment]
Monota 様

コメントいただきありがとうございます。
下名はWebシステムについて初めて携わるため、
的を外した回答になるかもしれませんが、
その場合はご指摘ください。

>途中に Apache とか立てているのであれば、そちらの設定は問題ないでしょうか。
ApacheはTomcatのみで、設定については、conf/server.xmlファイルの
エンコード(useBodyEncodingForURI="true"追加)についてしか変更しておりません。

>HTTP 400 を返しているのは Knowledge で正しいでしょうか。
事象を発生させ、TomcatのログとKnowledgeのログを比べてみました。
その結果、HTTP400のエラーはTomcat側で吐いており、
Knowledgeにはその時間の記録がありませんでした。

犯人はTomcat側ということはわかりましたが、
すでにserver.xmlファイルのエンコードは設定済みですし、
それ以外に問題解決になりそうなことを調査してみます。

**Comment by hiroG3** [comment]
koda-masaru 様


コメントいただきありがとうございます。

>IEですか。IEはレガシーなシステムを動かすための設定などがあったりして、一括りにできない挙動をします。（御社内のIEの設定だと動かず、別の会社の設定では動くといったことがある）
IEを積極的にサポートをしようとは思いませんし、IEのための独自の処理を追加することもありません。

もちろん、IEをサポートしていく予定がないことは、
本サイトやブログで存じておりました。

ただ社内のブラウザは、現時点でIE11が標準なものでして。。。#688 の件もあり、
もしかしたらサポートいただけるかと淡い期待をもっておりました。
申し訳ありません。

最悪、解決方法がみつからない場合、ソースをダウンロードし、
弊社用にカスタマイズ(URLを意図的にエンコード)して
運用できるかも検討してみます。

色々とお手数おかけしました。
ありがとうございました。

**Comment by koda-masaru** [comment]
hiroG3 さん

自宅でちょっとずつ作っているものなので、やはり優先度の取捨選択は必要ですし、そうするとIEに対応することの優先度はどうしても高くできません。
潤沢なリソースがあれば、IEもサポートしていきたいとも思うのですが、、、
ご不便をおかけしてすみません。
いったんは、現状のまま（私としては）IEはサポートの対応はしないという方向でいこうと思います。
（他の対応に時間を割きたいので）

ただ、「IEに対応したもので、他に影響が無い」という対応のプルリクは歓迎しますので、もしよろしければプルリクを送ってください。

**Comment by Monota** [comment]
最新版の Tomcat で IE を使うと発生するようです。

```
29-Jun-2017 21:38:29.422 情報 [http-nio-8080-exec-2] org.apache.coyote.http11.AbstractHttp11Processor.process Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
        at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:283)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1045)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

Firefox、Chrome、Safari、Edge では再現しませんでした。おそらく

https://stackoverflow.com/questions/41053653/tomcat-8-is-not-able-to-handle-get-request-with-in-query-parameters

と同じかなと思うのですが、細かいことはわかっていません。これをみる限り、

Tomcat 7.0.73, 8.0.39, 8.5.7

よりも小さいバージョンにすれば起こらないのではないかと思います。しかし、Tomcat バージョンダウンについてはリスクを十分に考慮した上で自己責任でお願いします。

**Comment by hiroG3** [comment]
Monota 様

コメントいただき、ありがとうございます。
回答が遅くなり申し訳ありませんでした。

詳しい解析まで行っていただき、ありがとうございます。

>Tomcat 7.0.73, 8.0.39, 8.5.7
>
>よりも小さいバージョンにすれば起こらないのではないかと思います。しかし、Tomcat バージョンダウンについてはリスクを十分に考慮した上で自己責任でお願いします。

バージョンダウンはちょっと怖いので、
Tomcatは今のバージョンのままで行こうと思います。
また、HTTP400エラーが出る件については、
URLを意図的にエンコードさせて対処するようにしました。

色々とお手数をおかけしました。
ありがとうございました。

**Comment by koda-masaru** [comment]
解決済ですので、クローズします。
