### ISSUE TITLE
テンプレートを削除した後、それを利用した記事があると記事一覧で500エラーとなる

### ISSUE THREAD

**Issue by ino9999** [support-project/knowledge#747]
お世話になります。
度々issues に登録してすみません。

以下作業をしたところ500エラーが発生しました。
・新規でテンプレートAを追加→テンプレートAを利用して記事を作成→テンプレートAを削除→記事一覧を表示→以下500エラーが表示される

[以下で記事一覧は見れるようになりました]
/knowledge/open.knowledge/view/記事番号　を直接urlに入力して記事を表示される
　→記事に利用しているテンプレートを存在しているテンプレートBに変更→記事一覧表示可

記事が紐づいているテンプレートを消さない　ということで運用回避は可能ですが、
登録させていただきます。

[500エラーの内容]
Error

Internal Server Error
javax.servlet.jsp.JspTagException: 500 /WEB-INF/views/open/knowledge/partials/common_list.jsp at org.apache.taglibs.standard.tag.common.core.ImportSupport.acquireString(ImportSupport.java:329) at org.apache.taglibs.standard.tag.common.core.ImportSupport.doEndTag(ImportSupport.java:171) at org.apache.jsp.WEB_002dINF.views.open.knowledge.list_jsp._jspx_meth_c_005fimport_005f1(list_jsp.java:976) at org.apache.jsp.WEB_002dINF.views.open.knowledge.list_jsp._jspService(list_jsp.java:806) at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443) at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:467) at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:392) at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311) at org.support.project.web.common.HttpUtil.forward(HttpUtil.java:83) at org.support.project.web.boundary.ForwardBoundary.navigate(ForwardBoundary.java:23) at org.support.project.web.filter.ControlFilter.invoke(ControlFilter.java:51) at org.support.project.web.filter.ControlManagerFilter.doFilter(ControlManagerFilter.java:184) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.support.project.web.filter.MultipartFilter.doFilter(MultipartFilter.java:63) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.support.project.web.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:184) at org.support.project.knowledge.listener.CloseAbleAuthenticationFilter.doFilter(CloseAbleAuthenticationFilter.java:98) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.support.project.web.filter.LoggingFilter.doFilter(LoggingFilter.java:62) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.support.project.web.filter.SeqFilter.doFilter(SeqFilter.java:31) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.support.project.web.filter.EncodingFilter.doFilter(EncodingFilter.java:36) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748)

**Comment by koda-masaru** [comment]
「記事が紐づいているテンプレートを消さない」という運用にしていたため、気づかなかったのですが、削除してしまった後にエラーになるのは問題だと思うので、エラーにならないように修正しようと思います。

**Comment by koda-masaru** [comment]
Release v1.10.0 pre1 としてリリースしたためクローズします。
