### ISSUE TITLE
Change navbar design

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#749]
I am considering changing the design because easily access to the list of drafts and stocks.
Since PullRequest of # 727 is reflected on the demo site, if this design is acceptable, change the design with v1.10.

------
下書きとストックの一覧に簡単にアクセスするために、NavBarのデザインの変更について検討。
#727 のPullRequestをデモサイトに反映するので、このデザインでよければ、v1.10でデザインを変更する。「もっとこうした方が嬉しい」といった意見があれば、本issueで検討していきますので、意見を登録してください。

**Comment by koda-masaru** [comment]
I deployed a new design on the test site.
The new design needs to modify the correspondence of the responsive design.
- Fixed layout collapse with screen size change
- Push the button to make it cheaper when watching on the smartphone

Also, I think that there are opinions that it is easier to add colors to the buttons. (Since it has color so far)

-----

私はテストサイトに新デザインをデプロイしました。
新デザインはレスポンシブデザインの対応の修正をする必要がありそうです。
- 画面サイズ変更でのレイアウト崩れの修正
- スマートフォンで見たときにボタンを押し安くする

また、ボタンに色を付けたほうがわかりやすいといった意見もあるかなと思います。（今までは色がついているので）

**Comment by ikuko** [comment]
#761 でレイアウト崩れの部分を対応してみました。

**Comment by koda-masaru** [comment]
#761 をベースに、 #762 で少し調整したNavbarのデザインを、デモサイトにデプロイしてみました。
どんな印象でしょうか？ご意見などあればコメント登録願います。

**Comment by ikuko** [comment]
デモサイトのほうで確認しました。
よくなったと思います。
横幅が狭いときのボタンも対応ありがとうございます！

**Comment by koda-masaru** [comment]
確認ありがとうございました。いったん、このデザインで様子見して利用者の意見も聞いていこうと思います。

**Comment by koda-masaru** [comment]
Release v1.10.0 pre1 としてリリースしたためクローズします。

**Comment by johiroshi** [comment]
今週v1.11.0に更新し、新しいデザインを確認しました。
デザイン変更とは以下の右側の「作成」「ストック」「(メニュー)」のことで良いでしょうか？

**navbar**
![navbar](https://user-images.githubusercontent.com/15374413/33358860-86333db4-d50e-11e7-8fb1-ac92828e064e.png)

「下書きやストックへのアクセスをよくする」という意図はわかるのですが、「一覧」ボタンがなくなってしまい、少し使いづらくなりました。現行のデザインだとknowledgeの一覧を確認するには左側の「knowledge」というテキストリンクをクリックしなければならないと認識しているのですが相違ないでしょうか。

Qiitaのように、Google検索外部からの流入やURLを叩いてのアクセスに依存しているサービスであれば「一覧」ボタンは要らない気がするのですが、knowledgeは単体で閉じたサービス？なので「一覧」ボタンがなく迷子になりやすいと感じます。
