### ISSUE TITLE
サインインしていない状態でイベントに参加しようとするとエラー

### ISSUE THREAD

**Issue by ikuko** [support-project/knowledge#756]
サインインしていない状態で参加するボタンを押すと
```
{"children":[],"code":400,"message":"param is invalid.","result":null,"status":2}
```
のようなメッセージが表示されてしまいます。
ログイン状態から参加するボタンを押せば問題ありません。
常にログイン状態で使っていたのでリリースされてすぐにアップデートしてから今まで気付きませんでした。

問題のあるバージョンは `1.9.1pre1` です。
`1.8.0`, `1.8.1`, `1.9.0` は問題ありませんでした。
デモサイトでも再現しました。

**Comment by koda-masaru** [comment]
不具合ですね 😢 私の環境はログイン必須でしたので気づきませんでした。
ご連絡ありがとうございます。修正しようと思います。

**Comment by koda-masaru** [comment]
修正しました。デモサイトに最新を反映しましたので、お時間があれば確認願います。
https://test-knowledge.support-project.org/open.knowledge/list

**Comment by ikuko** [comment]
デモサイトのほうで確認しました。
問題なしです。
ご対応ありがとうございます！ 👍

**Comment by koda-masaru** [comment]
Release v1.10.0 pre1 としてリリースしたためクローズします。
