### ISSUE TITLE
公開範囲をグループに設定した記事を編集しようとすると、編集ユーザが公開範囲に追加される

### ISSUE THREAD

**Issue by takajun** [support-project/knowledge#757]
デモサイトv1.9.1 pre1でも再現しました。
実行上の問題はなく、見た目だけの問題となります。

# 再現手順
- グループ:group-testを作成し、user1とuser2を所属させる
- user1で記事を作成し、公開範囲をgroup-testに設定して投稿する
- user1で投稿した記事を編集しようとする

# 期待動作
user1はgroup-testに入っているため、公開範囲はgroup-testのまま変化なし

# 現在の動作
公開範囲がgroup-testに加えてuser1も追加される

**Comment by koda-masaru** [comment]
上の動作は、いったん現在の仕様になります。
というのも、公開範囲を限定した場合、その公開範囲に入っていないユーザは、記事の表示／編集はできなくなります。つまり、作成者であっても表示／編集ができなくなります。（処理を簡単にするために、このような実装にしています）
それでは困ると思うので、公開範囲を限定する場合は、編集しているユーザを公開範囲に自動でセットするようにしています。

**Comment by takajun** [comment]
ご回答ありがとうございます。
仕様意図としては
- 作成者/編集者が表示/編集できること（公開範囲に入ること）

だと理解しました。
指摘させていただいたのは、その部分を壊すことではなく、
- 編集者が、公開範囲に指定済みのグループ内に存在していれば、そのユーザを個別に公開範囲にセットしないこと

となります。
この場合、編集ユーザは公開範囲に指定済みのグループ内に存在しているので、個別の編集ユーザを公開範囲に加えなくても、元々の仕様意図である「編集者は公開範囲に入ること」を満たしているので、特に問題は起こりません。

繰り返しますが、権限など実行上の問題はありません。。。
特定グループに公開しており、その特定グループ内のメンバーが記事編集を重ねていくと、"公開範囲"がどんどん追加されて見た目が汚くなる（公開範囲を簡単に識別できるためにもグループを指定しているのに、、、）という状況です。

**Comment by takajun** [comment]
すみません、間違えてCloseしてしまったので、ご意見いただきたくReopenします。

**Comment by koda-masaru** [comment]
「その特定グループ内のメンバーが記事編集を重ねていく」という場合は追加が多くなるので、追加しないほうが良さそうですね。
私の環境では、そのような使われ方がなく、気づきませんでした。
こんご対応していこうと思います。ですが、権限まわりのデリケートな部分ですので、少し時間がかかると思います。
それまでご不便をおかけしますが、よろしくお願いします。

**Comment by johiroshi** [comment]
このような挙動は僕も気になっていました。

ただ「グループと経由で編集権限を既に与えられている編集者を共同編集者として追加するか否か」というよりも、「編集者にグループが含まれており、かつ、編集者に当該グループに所属するユーザがいる場合、編集画面に共同編集者として表示しない」という見た目上の問題という気もします。

**Comment by nagodon** [comment]
権限周りをいじるのはデリケートだと思うので一覧や詳細表示の保護部分の表示にグループに所属してるメンバーだった場合はそのメンバーは表示しないようにしてグループだけが表示される(所属してない場合は表示)するということで解決できそうな気がしています。

もしこの対応で問題なければ対応しようと思います。

**Comment by koda-masaru** [comment]
@nagodon 
なるほど。その方法だと問題なさそうですし、見た目も良くなりますね。
対応方法として問題ないと思います。

**Comment by takajun** [comment]
@koda-masaruさん、@nagodonさん、@johiroshiさん
ご検討とご意見、ありがとうございます。
公開範囲の対応として、@nagodonさんのご提示いただいた内容で満たされると考えています。

**Comment by nagodon** [comment]
@koda-masaruさん @takajunさん
了解です。
ではご提案させていただいた形で修正してみますね。
少しだけお時間いただきます。

**Comment by nagodon** [comment]
#825 で対応しました。
遅くなってすみません。

**Comment by takajun** [comment]
デモサイトで確認し、望みの動作となっていることを確認しました。
ご対応ありがとうございました！

**Comment by koda-masaru** [comment]
This is supported by v1.11.0.
I will close this.
