### ISSUE TITLE
Support web api 

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#760]
Knowledge will provide Web API to post articles from other system.

API feature
- Authentication
- Get user list
- Get group list
- Post articles
- Get articles
- Post comment
- Get comment list

----

他システムから記事の投稿などをできるように、WebAPIを提供する。
今のところの利用シーンは以下。
OutLookなどの特定の共用カレンダーに、イベントが登録されたら、Knowledgeにtype=eventで記事を投稿する。

**Comment by griffin-stewie** [comment]
いいねの数などを集計したいので Web API があるとうれしいです。

**Comment by koda-masaru** [comment]
いいねの数は、今のところ以下の２つで取得できるようにしようと思っています。

- ユーザ情報の取得で、そのユーザが獲得したいいねの数も取得
- 記事の取得で、その記事が獲得したいいねの数も取得

これで、足りますか？

**Comment by koda-masaru** [comment]
いったん、以下のWebAPIを使える形にした。いったん、利用できる程度には増えたので、本issueはクローズして、これ以外のWebAPIについては別issueで管理する。

- 'GET' /api/knowledges
   - 登録されている記事の一覧を取得
- 'GET'/api/knowledges/{:knowledgeId}
   - 登録されている記事の詳細を取得
- 'GET' /api/users
   - ユーザ一覧を取得
- 'GET'/api/users/{:userId}
   - ユーザの詳細を取得
- 'GET' /api/groups
   - グループ一覧を取得
- 'GET'/api/groups/{:groupId}
   - グループの詳細を取得
- 'GET'/api/groups/{:groupId}/users
   - 指定のグループに所属するユーザの一覧を取得
- 'GET'/api/groups/{:groupId}/knowledges
   - 指定のグループを公開範囲に指定した記事の一覧を取得
- 'POST' /api/knowledges
   - 記事の投稿
- 'PUT' /api/knowledges/{:knowledgeId}
   - 記事の更新
- 'DELETE' /api/knowledges/{:knowledgeId}
   - 記事の削除
- 'GET' /api/attachments/{:fileId}
   - 添付ファイルの取得

参考： https://service-knowledge.support-project.org/open.knowledge/view/19

**Comment by koda-masaru** [comment]
Release v1.10.0 pre1 としてリリースしたためクローズします。
