### ISSUE TITLE
テンプレート　項目の説明文を登録しても表示されない

### ISSUE THREAD

**Issue by ino9999** [support-project/knowledge#767]
お世話になります。

新規にテンプレートを作成して項目の説明文を登録したのですが、記事登録画面で
表示されません。こちら仕様でしょうか。

以上、よろしくお願いします。

**Comment by ino9999** [comment]
項目名に説明も含めて利用がなくなったのでクローズします。
失礼しました。

**Comment by koda-masaru** [comment]
利用が無くなったとのことですが、いったんご説明だけしますと、今のところ説明文は登録画面に表示していません。いずれ、ツールチップのような形で表示させようと考えているため、項目だけ用意しています。

**Comment by ino9999** [comment]
ご返答ありがとうございます。
承知いたしました。
お手数おかけしました。
