### ISSUE TITLE
Happening error that trying to delete templates

### ISSUE THREAD

**Issue by MatsumotoHiroko** [support-project/knowledge#772]
I want to delete templates.
But knowledge had shown error when I conducted these processes. 

テンプレートの削除が失敗してしまいます。
システム設定 > 管理者機能 > テンプレート > 適当なテンプレート > 削除 > 確認画面で[OK] > error
となってしまいます。
Javaのエラーはなく、ブラウザのjavascriptのエラーを見たところ、
request.getContextPath()関数が関数として機能せず、そのまま文字列として認識されているようでした。
多分ですが、
src/main/webapp/js/admin-template-edit.js

56行目 $('#templateForm').attr('action', '<%= request.getContextPath()%>/admin.template/delete');
を、
$('#templateForm').attr('action', request.getContextPath() + '/admin.template/delete');
のようにしたら正しく動作するのでは？と想像しておりますが、
私にmavenプロジェクトの知見が少なく、確認することができませんでした。
大変お手数ですが、お手隙の際にご確認いただいてよろしいでしょうか。

アプリケーションの確認環境
環境: mac os Sierra
ブラウザ: Firefox 54.0
（windows IEからも削除失敗しましたので、環境依存ではなさそうです）

---- 

別件ですが、eclipseでknowledgeを動かす方法（ビルドし、forkしたブランチにgitでのpushする方法）をどなたかご教授願えると非常に助かります。可能でしたらpull requestをお送りしたいと思っております。
eclipseは最新のNeonで、
https://sites.google.com/site/soracane/home/mavenpurojekuto
http://qiita.com/AkihikoOgata/items/bb22250e3096aa558170
こちらを見ながら行っておりますが、Run As => Maven build... がエラーになってしまい、
tomcatの設定など何かがおかしいのかとは思っております。
(buildのエラーは、
[ERROR] No plugin found for prefix 'tomcat8' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/xxxx/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
と言ったものが発生します。
そもそもこの参照サイトでknowledgeを動かすことが可能なのでしょうか・・・)

**Comment by Monota** [comment]
後者について簡単に書くと、
http://mergedoc.osdn.jp/
で macOS 版 Pleiades をダウンロードして、
http://qiita.com/cypher256/items/233795f4fc58a704ee47
に書いてある方法でインストールする。
Eclipse が起動できたら、
http://git-manual.net/make-eclipse-project-remote-git/
に書いてある方法で Project を作成する。
http://qiita.com/alpha_pz/items/57c574c622fdaba152ff
の方法でサーバービューに Tomcat が追加できたら、それを右クリックして「追加および除去」から knowledge を追加する。その後、再度右クリックして「デバッグ」または「開始」を選択する。
ここまでで起動できると思います。

あとは、そのままだとビルドが遅いので、
https://github.com/support-project/knowledge/blob/master/config/eclipse_memo.md
を参考に一部コメントアウトすると良いかもしれないです。

あと、ビルドがうまくいかない場合は、knowledge プロジェクトを選択して右クリックで Maven -> プロジェクトの更新を試してみてください。

ざっと書いたので不明点があれば再度ご質問ください。

**Comment by koda-masaru** [comment]
@MatsumotoHiroko さん
ご連絡ありがとうございます。
テンプレート削除の不具合ですが、急いで暫定的に対応した v1.9.1 pre1 の中でバグを入れてしました。
以下のプルリクエストで修正済になります。
https://github.com/support-project/knowledge/pull/766
src/main/webapp/js/admin-template-edit.js

**Comment by koda-masaru** [comment]
eclipseでknowledgeを動かす方法ですが、以前海外の人からの問い合わせに回答する際に、以下のような資料を作成しています。

https://www.slideshare.net/koda3/knowledge-how-to-develop

これでセットアップできますでしょうか？（少し古い情報ですが、やり方は同じかと思います。）

ちなみに、ローカライズの方法は、以下になります。
https://www.slideshare.net/koda3/knowledge-localization

**Comment by koda-masaru** [comment]
あと、ちょっと古いのですが、以下のようなブログも書いてました。

- http://koda3.hatenablog.com/entry/2015/04/27/062930
- http://koda3.hatenablog.com/entry/2015/04/08/061130
- http://koda3.hatenablog.com/entry/2015/02/17/213222
- http://koda3.hatenablog.com/entry/2015/02/15/205749

参考になりますでしょうか。

ちなみに、そろそろ IntelliJ IDEA に移行しようかと考え中です。
ただ、最近の業務ではNode.jsメインなので、しばらくは今のままかなぁ、、、

**Comment by koda-masaru** [comment]
あと、Eclipseから直接Gitを操作はしておらず、SourceTree か、gitのコマンドで GitHubへPushなどしています。
@Monota さんの書かれた方法でセットアップすると、GitをEclipseから操作できそうな感じがします。

**Comment by MatsumotoHiroko** [comment]
@Monota 様、詳しくありがとうございます。gitと連携できる方法とのことで、参照させていただいております。
ほぼ、問題なくセットアップできたのですが、

>サーバービューに Tomcat が追加できたら、それを右クリックして「追加および除去」から knowledge を追加する

こちらを試したところ、

![2017-06-27 10 32 23](https://user-images.githubusercontent.com/8297211/27567081-6ee49536-5b24-11e7-9176-0fb96e496816.png)

「サーバーに除去または追加できるリソースがありません」

といったエラーになりました。
また、

>右クリックで Maven -> プロジェクトの更新

![2017-06-27 10 32 44](https://user-images.githubusercontent.com/8297211/27567117-a22926fa-5b24-11e7-9d4c-7f1b66796f03.png)

こちらを試そうとしましたが、該当の項目がポップアップメニューに存在しない状態でした。

Pleiades All in One 4.6.3.v20170422
Eclipse 4.6 Neon 3（最新版）
をDLいたしましたが、バージョン的な問題でしょうか・・・？

今回、修正を送りたいと考えていた箇所は @koda-masaru 様がすでに対応していただけたとのことで、すぐにパッチを送ることが今のところないとは思いますので、本当にお手すきの際にでもご知見いただけますと幸いです 🙇‍♀️

**Comment by MatsumotoHiroko** [comment]
@koda-masaru 様、表題の件、すでに対応いただいたとのことでありがとうございます 🙇 感謝申し上げます。
また、eclipseの件ですが、情報を感謝申し上げます。
Monota　様のいただいたのと同様の箇所が乗っていたため（tomcatの追加および除去）、こちらの方法も解決が難しい場合、試してみたいと思います。
今すぐにパッチを送る必要がなくなりましたが、また何か見つけた際に検討したく思います。

おふた方とも、お忙しい中迅速に本当に感謝いたします。

**Comment by Monota** [comment]
プロジェクトを右クリックして、構成のMavenプロジェクトに変換をためしてみていただけますか？
うまくいかなければ、帰宅後に確認します。

**Comment by MatsumotoHiroko** [comment]
@Monota 様、ありがとうございます！
ご指摘の通り、
構成の「Mavenプロジェクトに変換」をしたところ、「追加および除去」「Maven -> プロジェクトの更新」この２つができるようになり、問題なく動作致しました。
本当に感謝いたします。
以後、パッチなど送りたい時に活用させていただきます　🙇 

お忙しい中、おふた方とも丁寧にお教えくださり非常に感謝いたします。

**Comment by Monota** [comment]
よかったです。
私も新参者なのでまだまだですが、@koda-masaru  さんが作られたこの素敵なプロダクトに少しでも貢献できたらと思っています。
