### ISSUE TITLE
差分バックアップ機能はないのですか？

### ISSUE THREAD

**Issue by thisprogrammer1** [support-project/knowledge#774]
Wikiのように差分バックアップ機能は無いのですか？一回、記事を上書きしたら元のデータはなくなってしまうのでしょうか？宜しくお願い致します。

**Comment by koda-masaru** [comment]
記事の本文については、変更の履歴を持っています。
以下のように更新履歴の内容を確認できます。
ただ、本文のみで、テンプレートの拡張項目や、添付ファイル、公開区分などは履歴管理されません。

----
![image](https://user-images.githubusercontent.com/10343517/27636116-ec3e3264-5c44-11e7-8176-b35c38d37605.png)

-----

![image](https://user-images.githubusercontent.com/10343517/27636147-0985fbcc-5c45-11e7-9134-9a4bda65d76a.png)

あと、履歴の途中の状態の表示を、もう少しわかりやすく表示することも検討中です。
（その時点の表示を見るとか）

**Comment by thisprogrammer1** [comment]
ご返信ありがとうございます。私の見落としでした。申し訳ございません。便利な機能の実装ありがとうございます。

**Comment by koda-masaru** [comment]
解決したためクローズします
