### ISSUE TITLE
WebHook can limit ranges of view using groups, tags and so on. (WebHook設定での公開範囲、タグ等での制限指定)

### ISSUE THREAD

**Issue by MatsumotoHiroko** [support-project/knowledge#784]
I hope that an additional fanction in the setting of WebHook.
It allow us to limit ranges of view by user goups, tags and so on.

--------

連続でのissueをあげてしまい、お忙しいところ大変恐縮です。

[システム設定→ WebHook 設定]
にて、knowledgeの投稿を各種チャットツール等に通知するWebHook機能の設定がございますが、現状、全ての投稿が指定のチャットツールに通知されます。
ここで、全てのチャットツールではなく、knowledgeの投稿時の「公開範囲の指定」で「保護（公開先を選択） 」のグループ等で範囲を絞った場合や、「タグ」に特定のタグを入れた場合など、「WebHook 設定」によって振り分けの可否の詳細を指定できると非常にありがたいのですが、こういった機能の実装予定などありますでしょうか？

developのcommitやソースコード、issueなどにそれらしいものが見当たらないため、提案させていただくことをお許しくださいませ 🙇‍♀️

**Comment by koda-masaru** [comment]
ご意見ありがとうございます 🙇 提案は大歓迎ですので、どしどしお寄せください。

「通知」に関して、絞り込みや振り分けの条件を指定したいという要望があがっています。
WebHook以外の、メール通知でも、特定の条件のもののみ通知して欲しいという要望をうけています。
ですので、WebHookに関しても、なんらかの条件で通知する／しないを切り替えたりも考えていきたいと思います。（上記を見ると、WebHook先を条件によって切り替えたいという要望もあるように見えます）

ただ、要望が貯まっておりますので、実現するのは少し時間がかかってしまうかもしれません。
申し訳ありませんが、それまでお待ち下さい。

**Comment by MatsumotoHiroko** [comment]
たくさんの要望のくる中で、迅速にご返答いただきましてありがとうございます 🙇‍♀️ 
色々と検討しましたところ、通知先のメールアドレスをチャットツール毎に分けたりすることで、WebHookでの振り分け条件による切り替えなどがなくても対応できそうだということがわかりました。
お忙しいところ、本当にありがとうございます。もし、実現しましたらとても嬉しいですが、他に優先の機能がたくさんあるかと思いますので、心待ちにしております。
いつもありがとうございます。
