### ISSUE TITLE
リバースプロキシを使用している時、ユーザ登録完了通知メールに生のURLが記載される

### ISSUE THREAD

**Issue by mokjpn** [support-project/knowledge#789]
ユーザ登録方法を、ユーザが自身で登録し管理者が承認する、としている場合に、管理者がユーザを承認するとユーザにメールで通知されますが、その際にシステムのURLがメール中に記載されます。

このURLは、ソースを拝見すると HttpUtil.getContextUrl(getRequest()); で取得されていますが、リバースプロキシの下で運用している場合、生のURL (http://localhost:8080...等)  が見えてしまいます。

SystemConfig.SYSTEM_URL の設定項目もあるので、そちらからURLを取得した方が良いかもしれません。

**Comment by koda-masaru** [comment]
管理者メニューの「システム設定」で、URLを設定するところがあり、その値がシステムのURLになっています。

----

![image](https://user-images.githubusercontent.com/10343517/27913843-598b87e2-629c-11e7-846a-d3ef04947715.png)

-----

![image](https://user-images.githubusercontent.com/10343517/27913908-820013a0-629c-11e7-9eba-6a727aadcef0.png)


このURLは、初めてアクセスがあった際に、そのアクセスURLから登録しています。
たぶん、リバースプロキシを設定する前に、お試しでリバースプロキシを通さず直接 `http://localhost:8080` にアクセスしたのではないかと思います。

こちら値を変更すれば、メールのURLを修正できます。お試しください。

**Comment by mokjpn** [comment]
システム設定のURLは変更しているのですが、メールには反映されていないようなのです。
ソースを変更して検証してみます。

**Comment by koda-masaru** [comment]
変更後、Knowledgeの再起動（Tomcatなどの再起動）が必要だったかもしれません。

**Comment by mokjpn** [comment]
設定後，Tomcatを再起動してユーザの追加をして，送られるメールを見てみましたが，やはり反映されていないようです．

org.support.project.knowledge.logic.MailLogic.sendAcceptedAddRequest()の中で，第２引数のurl の値が送られるメールに入っているようなのですが，これを呼び出している org.support.project.knowledge.control.admin.UsersControl.accept()を見ると，このurlはHttpUtil.getContextUrl(getRequest());で与えられており，SystemConfig.SYSTEM_URL を参照しに行っていないように思えるのですが...
ビルド環境を作るのに少し時間がかかってしまうかもしれませんが，変更してみて直るようであればPull Requestをお送りします．

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
ご指摘の通り、リクエストの値を指定していましたので、DBの値があれば、それを優先するように #792 で修正しました。

ただ、私の環境もリバースプロキシを使っていますが、特に問題は発生しておりません。
たぶん、リバースプロキシの設定で、リバースプロキシにアクセスされたURLを、そのままTomcatに渡すように設定しているからです。そのままでも問題は無いと思いますが、できれば以下のURLを参考に、生のアクセス情報がTomcatに渡るように設定を推奨します。
http://qiita.com/HeRo/items/7063b86b5e8a2efde0f4

**Comment by mokjpn** [comment]
早速修正いただき，ありがとうございます！
warを入れ替えて試したところ，問題なくなったことを確認しました．

リバースプロキシはnginxですとHostヘッダを自由に操作できるので，うまく設定できると思うのですが，Apache+mod_proxyを今のところ採用しているため，ProxyPreserveHostディレクティブを指定するとProxyPassReverseディレクティブが期待通りに動かなくなるのと，他のリバースプロキシ先にも同じ設定が適用されてしまう（適用範囲の限定ができない）ので，問題が起こってしまっていました．
今回の修正で，単純なProxyPassとProxyPassReverseだけの設定で，Apache+mod_proxyの下でも問題なく動くようになったと思います．ありがとうございました．
