### ISSUE TITLE
0.5.3で記事を作成するとCPU負荷があがる

### ISSUE THREAD

**Issue by irgaly** [support-project/knowledge#79]
Knowledge 0.5.3にしてから、記事を投稿するとサーバのCPU負荷があがりKnowledgeの反応が悪くなってしまいます。

topコマンドで確認するとjavaプロセスが二つ起動しており、生存時間の短いほうのプロセスがCPU使用率を上げているようでした。

MailSendBat.logを確認すると、次の出力で止まっています。

```
INFO  2015-08-18 16:32:59,332 [AbstractBat(26)] MailSendBat is start.
INFO  2015-08-18 16:33:12,601 [DBConnenctionLogic(35)] Custom connection setting is exists.
```

アップデート前の0.5.3pre3ではこの現象はありませんでした。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

 Knowledgeでは、Tomcatなどのサーバーで動くWebアプリのプロセスと、
Webアプリのプロセスから定期的に呼び出すバッチプロセスがあります。

そのバッチプロセスの中で、負荷が高くなりそうなところを探してみようと思います。

ちなみに、バッチプロセスには以下の種類があります。

- ナレッジの登録・更新やコメント登録やLikeなどのイベントがあった場合に、メール通知を希望しているユーザを抽出し、メールデータを作成するプロセス
    - NotifyMailBat

- 登録されているメールデータを送信する（メールは上記の通知メールの他に、Webアプリで登録する、パスワード初期化メールや、サインアップ時のダブルオプトインメールがあります)
    - MailSendBat

- 添付ファイルが登録された場合に、その添付ファイルに書かれている「中身」を抽出し、キーワード検索できるようにする
    - FileParseBat

- ナレッジを新規登録時に、添付ファイルを登録したあと、ナレッジを保存しないで閉じると、添付ファイルがナレッジと紐付かなくなります。この添付ファイルをクリアする処理
    - KnowledgeFileClearBat



- MailSendBat が怪しいですが、FileParseBat もパースするファイルの内容によっては負荷が高くなるかもしれません。

**Comment by irgaly** [comment]
ありがとうございます。
一度負荷があがると以下の状態となり30分以上まっても復帰しませんでした。

（仮想環境なので数字そのものは参考にはなりませんが...）

* Tomcatプロセスx2となり、片方はCPU使用率20~30%にあがっている
* Knowledge Webのレスポンスが20秒〜それ以上まっても返ってこない状態
* SSHで接続していてもコマンドを叩くたびに5秒~10秒またされたり、そもそも応答がなくなったり
* 時間がたつにつれ上記症状が悪化していき、最終的にはSSH接続をオープンできない状態になる

※今はKnowledge0.5.3pre3へ戻して運用しているので問題ありません

コマンドの応答が悪くなり、SSH接続がオープンできなくなるので、ファイルアクセスを伴った無限ループ処理に陥っているのではないかと想像していますが...

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

まだ、原因となるところを見つけられていないので、情報は助かります。

時間がたつにつれて症状が悪化するということなので、バッチ処理が無限ループで終了しないのにもかかわらず、次のバッチ処理が実行されてリソースを食いつぶすということなのかもしれません。

不具合は、再現できないと修正がなかなか難しいですね、、、、
無限ループになりそうなところを探してみます。

**Comment by koda-masaru** [comment]
原因がまだ見つけられないので、いったんバッチ起動間隔を長くし、
バッチ処理のログにシステムの負荷情報を出してみました。

プレリリース（Release v0.6.0 Pre1）を作成しましたので、
ご都合の良い時に試していただけますでしょうか？

**Comment by irgaly** [comment]
ありがとうございます。
0.5.3 および0.6.0 Pre1で試してみたのですが、どちらも再現がなくなっていました...

0.5.3でも、負荷が上がったりログが途中で止まっていたりすることはなく、正常でした。

```
INFO  2015-09-21 18:24:22,506 [AbstractBat(26)] MailSendBat is start.
INFO  2015-09-21 18:24:23,085 [DBConnenctionLogic(35)] Custom connection setting is exists.
INFO  2015-09-21 18:24:37,632 [MailSendBat(100)] MAIL sended. count: 3
```

現在最新の0.6.0 Pre2を入れて、しばらく様子を見てみたいと思います。

**Comment by koda-masaru** [comment]
ご連絡ありがとございます。
再現しないですか、、、　何が原因なんでしょう？？？
メール送信処理や、Markdownのパース処理を、かなり大きく変更しているので、
そのあたりが怪しいかなぁと思っているのですが、、、

いったん、様子見として、再現したら不具合の原因を解析しようと思います。

**Comment by koda-masaru** [comment]
@irgaly さん
いくつかのバージョンアップなどで、状況は変化しましたでしょうか？

**Comment by irgaly** [comment]
ありがとうございます。
その後、バージョンアップして利用していますが問題は発生していません。クローズで構わないと思います。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。ではいったんクローズいたします。
また、問題が発生したらissue登録したいと思います。
