### ISSUE TITLE
タグ追加中に新しく登録したタグが表示に反映されない

### ISSUE THREAD

**Issue by thisprogrammer1** [support-project/knowledge#791]
お世話になっております。バグを見つけました。

タグを追加中、次の画像のように新しいタグが表示されなくなります。（モザイクはプライバシー配慮です。）

改修のほどお願い致します。
１ページ目
![knowledge-tag01](https://user-images.githubusercontent.com/29744447/27943944-3ac5bec2-631e-11e7-894d-abbee45955d2.png)
２ページ目
![knowledge-tag02](https://user-images.githubusercontent.com/29744447/27943949-4184755a-631e-11e7-9ffb-d6db0d0433e6.png)

**Comment by koda-masaru** [comment]
すみません。現象を再現できません。
特に問題なくタグは追加できています。
もし問題があるのであれば、もう少し詳細な情報を提供願います。

**Comment by koda-masaru** [comment]
Since there is no reply, I think that it is solved and I will close it.
