### ISSUE TITLE
リストア後に403エラー

### ISSUE THREAD

**Issue by chakapoco** [support-project/knowledge#793]
サーバを移行したいと考えています。
サーバAでバックアップし、バックアップデータをサーバBでリストアしました。
リストア後、サーバBで投稿しようとすると画面右上に403エラーが表示されてしまい
投稿できません。また、新たにユーザーを作成しようとしてもForbiddenと表示され
ユーザーを作成できません。
データを移行し新しいサーバーで運用する方法はあるのでしょうか。ご教授ください。
よろしくお願いいたします。

**Comment by koda-masaru** [comment]
管理者でログインし、システムメニューの「システム設定」で、サービスのURLを確認してください。
たぶんAとBのURLが異なり、Aの設定のままになっているかと思います。

**Comment by koda-masaru** [comment]
Since there is no reply, I think that it is solved and I will close it.
