### ISSUE TITLE
How parameters do I input in POST WEB API on viewers?

### ISSUE THREAD

**Issue by MatsumotoHiroko** [support-project/knowledge#794]
I want to set viewers' limit at new knowledge.
I try to sent several patterns to posting web api.

----

頻繁にissueをあげてしまい大変失礼致します :bow:
いつも非常にお世話になっております。

https://github.com/support-project/EventRegister/blob/d8a59441bd94b98eb7d0216831d31972c0b4cb30/config/default.json
こちらを参考にweb apiのPOST(knowledge投稿)による記事投稿を試しております。
この中で、
https://github.com/support-project/EventRegister/blob/d8a59441bd94b98eb7d0216831d31972c0b4cb30/config/default.json#L29
```
"viewers": {
        "groups": [],
        "users": []
}
```
こちらの、公開先の指定が可能となっておりますが、具体的なパラメータをお教え願えませんでしょうか？

試しに
```
'publicFlag': 2
'viewers': {
    'groups': ['4'] # groups.group_id
}
```
などとしてみたところ、400 BAD_REQUESTが返ってきました。
'groups'を配列形式にするとBAD_REQUESTエラーになるようで、
templateItemsのように,
```
'viewers': {
    'groups': [
        {
            'label': '保護',
            'value': 'グループ名1'
        }
    ]
}
```
など、色々試行錯誤してみましたが、HTTPステータス201で投稿は成功しますが、公開先にグループは指定されていない状態で投稿されてしまいます。

WEB APIのマニュアルご準備中とのことで、後日パラメータが説明されることと思いますが、もし、ソースのこの部分を読めばわかるなど有りましたらご指導願えますと幸いです
（viewersで全文検索し、他にも'groupsLabel'などそれらしいものを入れたりもしてみましたが、公開先は設定できない状況でした）

**Comment by koda-masaru** [comment]
viewersは以下のように指定してください。（editorsも同様）

```
"viewers": {
        "groups": [],
        "users": [
            {
                "id": "1"
            }
        ]
    }
```

WebAPIのドキュメント整備ができていないので、簡単に説明を記載しようと思います。

WebAPIの knowledge のJSONの形式は、GetとPost/Putは共通にしています。
ですので、Knowledgeで試しにviewers（公開範囲を「保護」で公開対象を指定）をセットしていただき、その記事をGetで取得するとJSONが取得できます。
それを、そのままPost/PutのJSONに指定していただくと、情報をセットできると思います。

- Getで取得できる viewers の例：

```
"viewers": {
        "groups": [],
        "users": [
            {
                "id": "1",
                "name": "Administrator" // Post/Putのときには、idだけでOK
            },
            {
                "id": "2",
                "name": "user1"
            }
        ]
    }
```

**Comment by MatsumotoHiroko** [comment]
@koda-masaru さん、いつも迅速にありがとうございます 🙇‍♀️ 
なるほど、Getで個別の記事を取得した際にそのまま投稿できる値が出てくるのですね。盲点でした。
また、詳細の記載感謝いたします。こちらを参考に引き続き、POSTのバッチを組もうと思います。
本当にありがとうございました。
