### ISSUE TITLE
Can I upload new images or attachment files using WEB API?

### ISSUE THREAD

**Issue by MatsumotoHiroko** [support-project/knowledge#796]
I want to post new knowledge which includs new images or attachment files using WEB API.
I try to get parameters of a particuler knowledge.
Below parameters is the result.
```
{"attachments":[{"commentNo":0,"fileName":"cust_gp_item_mapping_rules_view.csv","fileNo":19,"fileSize":49544.0,"insertDatetime":"2017-07-12 02:38:49.276","insertUser":3,"knowledgeId":43,"updateDatetime":"2017-07-12 02:41:09.361","updateUser":-100},{"commentNo":0,"fileName":"image-20170712023132291.png","fileNo":20,"fileSize":58131.0,"insertDatetime":"2017-07-12 02:39:23.879","insertUser":3,"knowledgeId":43,"updateDatetime":"2017-07-12 02:41:09.748","updateUser":-100},
{"commentNo":0,"fileName":"image-20170712024007864.png","fileNo":21,"fileSize":254.0,"insertDatetime":"2017-07-12 02:40:07.864","insertUser":3,"knowledgeId":43,"updateDatetime":"2017-07-12 02:41:09.846","updateUser":-100}],
"commentCount":0,"comments":[],"content":"コンテンツテスト![image-20170712024007864.png](/knowledge/open.file/download?fileNo=21)","editors":{"groups":[],"users":[]},"insertDatetime":"2017-07-12 02:40:27.478","insertUser":3,"knowledgeId":43,"likeCount":0,"publicFlag":2,"tags":[""],
"template":"テンプレート１","templateItems":[],"title":"ファイルアップロード","updateDatetime":"2017-07-12 02:40:27.478","updateUser":3,"viewers":{"groups":[{"id":"4","name":"投稿者"}],"users":[{"id":"3","name":"管理者ユーザ"}]}}
```
This parameters show that it must needs had already uploaded any files before executing POST Web API.
I know that POST Web API can't post simultaneously any file.
Can you do that?

----

度々WEB APIでのPOST（knowledgeの記事投稿）に関する質問を失礼します。
新規の添付ファイルをPOSTでのAPIの実行と同時に記事に紐づけて投稿することは可能でしょうか？

添付ファイルは先に何かしらの方法でアップロードし、DBから必要パラメータを取得して同時に投稿というのでも構いません。
knowledgeのWEB APIではなく画面からの投稿時のDBのクエリを見たところ、添付した段階でfile noが発行されているようでしたので、事前になんらかの方法でファイルをKnowledge側に投稿する必要がありそうですが、ブラウザで手動で投稿せずなんらかの方法であげることは可能でしょうか？
DBにバイナリーデータを書き込んでいるようですので、一筋縄ではいかないように見えております。

今後の実装などに含まれていたら申し訳ございません。
お手すきの際にでもご検討願えますと幸いです。

**Comment by koda-masaru** [comment]
Attachment registration with the Web API is not implemented yet.
I will add it, please wait for a little while.

------

Web APIでの添付ファイルの登録は、まだ未実装です。
追加していこうと思いますので、少々お待ち下さい。

ちなみに、手順は上にかかれている通り、まず添付ファイルを登録し添付ファイル番号を取得します。
その後、Knowledgeの記事の保存を行い、その際に紐付ける添付ファイルの番号を指定することになります。（画面でもそうしています）

**Comment by MatsumotoHiroko** [comment]
Thank you for your quick response.
I'm hoping to add this function.
I really appreciate it.

----

@koda-masaru　様、
Web APIへの添付ファイルの実装はまだとのこと、早速のご返答感謝いたします。
色々なタスクがあるかと思いますので、実装の際は是非ともよろしくおねがいたします :bow:
本当にありがとうございます。

また、手順については、先に添付ファイルの登録が行われるとのこと、承知いたしました。
ご説明いただきまして、本当にありがとうございます。
少しでも何かお手伝いできればいいのですが、javaの解読に苦戦しております。
引き続き応援しております。
