### ISSUE TITLE
ユーザのLDAP認証

### ISSUE THREAD

**Issue by yoshimov** [support-project/knowledge#8]
ユーザの認証をLDAPで行えるようになると会社の中で使いやすくなります。

* 参考: <https://dev.gitblit.com/blob/gitblit.git/master/src!main!java!com!gitblit!auth!LdapAuthProvider.java>

**Comment by koda-masaru** [comment]
ご意見ありがとうございます。

たしかにLDAPにも対応すると良いかもしれませんね。
あとで対応しようと思います。

**Comment by koda-masaru** [comment]
Ldapに対応しようとしていますが、自分のPCにLdapの環境をうまくセットアップできずに苦戦中です。。。

**Comment by koda-masaru** [comment]
Ldapを使ったログインに対応してみました。
ただ、社内で稼働しているActiveDirectoryのようなちゃんとした環境を作成できなかったので、
ApacheDirectoryで試しています。
ApacheDirectory環境でのテストは問題なく動いているのですが、もし動かなかったという人がいれば連絡が欲しいです。。。

**Comment by kounoike** [comment]
0.5.3 Pre2 と http://qiita.com/kounoike/items/55505e0f68ee8ec15dd5 の手順で入れた OpenLDAP for Windows でLDAP認証がとりあえずログインまでは動作することを確認しました。
テスト用の環境なので気になることがあったら追加で確認できます。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
正常に動いているようで安心しました。

**Comment by yoshimov** [comment]
Active Directory連携でも動作しました。ありがとうございます。
ただBaseDNが固定なので、OUがツリー状に存在する環境ではログインできるユーザが同じOUに属する、例えば同じグループのユーザのみになってしまいます。

他のOSSで恐縮ですが、下記のようなdirect bindは可能でしょうか。
https://dev.gitblit.com/blob/gitblit.git/master/src!main!java!com!gitblit!auth!LdapAuthProvider.java#L307

＃該当箇所を調べてみようと思ったんですが、LdapLogic.auth()のソースが見つけられませんでした。

**Comment by koda-masaru** [comment]
情報ありがとうございます。
LDAPについては、あまり操作などしたことが無いので、いろいろ教えて頂いて助かります。
↑のソースを元に、修正したいと思います。

ちなみに、LdapLogic.auth()のソースは、
https://github.com/support-project/web
に公開しています。

webアプリの中の共通処理（認証とか、XSS対策とか）をライブラリ化したものです。
趣味で別のアプリも作っていて、それと共通化しているのでプロジェクトが分かれています。

Ldapの部分は、その中の

[LdapLogic.java] (https://github.com/support-project/web/blob/master/src/main/java/org/support/project/web/logic/LdapLogic.java)

[DefaultAuthenticationLogicImpl.java] (https://github.com/support-project/web/blob/master/src/main/java/org/support/project/web/logic/impl/DefaultAuthenticationLogicImpl.java)

あたりに書いています。ご参考まで。

**Comment by koda-masaru** [comment]
LDAP認証の方法を変更してみました。
たぶん、ツリー上の組織でもログイン出来るようになったと思うのですが、
LDAPに詳しく無いので、この設定方法で良いものか意見が欲しいです。

以下に、変更案を記載してみました。
お時間があるときに、この案で良いかご意見をください。

https://support-project.org/knowledge/open.knowledge/view/65

**Comment by koda-masaru** [comment]
BaseDN固定になってしまう部分の対策を施したものをプレリリースしました。

既にご利用の人もいるかもしれないので、影響が少なくなるように、今までどおりの使い方と、BaseDN固定の対策ができたものとを切り替えて利用できるようにしています。

LDAPの設定で切り替えると新しいものが利用出来ますのでお試しください。

**Comment by kounoike** [comment]
0.5.3でLDAP認証を設定時にLDAPサーバが落ちていた場合、サインインでユーザ名、パスワードを入力した後の画面が真っ白になってしまい、何が起こっているのか分からず困りました。
LDAP接続失敗のメッセージが出るようにできませんでしょうか？

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
たしかに、LDAPサーバーが落ちていた場合のエラーハンドリングの考慮が漏れてました。
（接続失敗と認証失敗を同じようにあつかっています）

エラー時のメッセージなど、検討したいと思います。
