### ISSUE TITLE
SearchのWebAPI対応について

### ISSUE THREAD

**Issue by Wallet0013** [support-project/knowledge#800]
現状記事一覧と、記事詳細しかございませんようですので、タグで検索等の実装ロジックが複雑になるためご確認させていただきました。

**Comment by Wallet1207** [comment]
Search用のWebAPIは有りますでしょうか？
現状一覧で取得のようですので、

**Comment by koda-masaru** [comment]
WebAPIでの一覧取得で、検索は画面の一覧と同じレベルで実施できたかと思います。（内部のロジックが共通化しているので）
そのうち、APIの仕様書を作成しようと思いますので、そこで正式な仕様を公開しようと思います。

**Comment by koda-masaru** [comment]
Same issue #783
I close this Issue.
