### ISSUE TITLE
複合検索画面 グループ作成者がいないとヒットしない

### ISSUE THREAD

**Issue by hiroG3** [support-project/knowledge#801]
お世話になっております。

バグ？らしき挙動がありましたのでご報告いたします。
お忙しいところ申し訳ございませんが、ご確認をお願いいたします。

準備
--
【手順1】グループ作成画面で権限：Administratorのユーザ（以降、adminユーザ）がグループAを作成。
【手順2】グループAのメンバーに、adminユーザとユーザ1を追加。
【手順3】ナレッジ投稿画面で公開先を「グループA」にし、ナレッジを投稿。
【手順4】グループ表示画面でadminユーザをグループAから除籍。

事象
--
上記の【手順4】のあと、複合検索画面で「グループA」を指定し検索すると、
投稿があるにもかかわらず、「存在しませんでした。」の表示になります。

調査
--
事象発生時のapp.logを拝見すると、以下のログが出力されていました。
『WARN　yyyy-MM-dd hh:mm:ss,fff [KnowledgeLogic(559)] Bad request group param』

また、上記の【手順4】のあとで
グループAのメンバー編集（以下パターン参照）→複合検索した結果を記載します。
【パターン1】　adminユーザを「グループA」のメンバーをとして復帰 → ○（検索ヒット）
【パターン2】　adminユーザを「グループA」の管理者として復帰 → ○（検索ヒット）
【パターン3】　adminユーザは除籍したまま、「ユーザ1」を「グループA」のメンバーに設定 → ×（検索ヒットせず）
【パターン4】　adminユーザは除籍したまま、「ユーザ1」を「グループA」の管理者に設定 → ×（検索ヒットせず）

原因の推察
--
グループ内にグループの作成ユーザが存在しないとき、
そのグループを複合検索で検索すると、ヒットしなくなる？

発生バージョン
--
Ver1.9.0, Ver1.10.0 pre2

**Comment by koda-masaru** [comment]
仕様かなと思います。
上記の説明だけでは、判断できないところがあります。それは、（検索ヒットせず）とありますが、「どのユーザで検索したときにHitせずなのかが明記されていないからです。

仕様を説明すると、グループに所属していないユーザで検索にHitしたら不具合になります。
公開範囲の「保護」でグループを指定している場合、そのグループに所属しているユーザのみに記事を公開していることになるので、所属していないユーザでは検索にHitしなくなります。

上の条件を鑑みて、動作がおかしいところはありますでしょうか？

**Comment by hiroG3** [comment]
koda-masaru 様

お世話になっております。
回答いただきありがとうございます。

> 仕様を説明すると、グループに所属していないユーザで検索にHitしたら不具合になります。
 公開範囲の「保護」でグループを指定している場合、そのグループに所属しているユーザのみに記事を公開していることになるので、所属していないユーザでは検索にHitしなくなります。

ご説明いただいたとおり、仕様であることを失念しておりました。
お手数をおかけし、大変申し訳ございませんでした。


> 上記の説明だけでは、判断できないところがあります。それは、（検索ヒットせず）とありますが、「どのユーザで検索したときにHitせずなのかが明記されていないからです。

下名の説明が不足し、申し訳ありません。
検索を行ったのは、adminユーザ（権限：Administratorのユーザ）でした。

ただ、１つ気になった点として、
adminユーザはすべてのナレッジ情報を閲覧できますが、
複合検索の場合、指定したグループにadminユーザが所属していないと、
検索にヒットしないというのは、閲覧と検索で仕様の違和感を覚えました。

adminユーザに限った動作なので、
あまり重要な部分ではありませんが、
その点についてはいかがでしょうか？

**Comment by koda-masaru** [comment]
やはり仕様だったということで安心しました。

「adminユーザで、グループに所属していないと」という点についても、違和感があると言われればそうですが、回避策もあり、私もあまり重要ではないと感じます。
時間があったら対応しても良いかなというレベルでしょうか（基本的に時間は無いので、、、ですが、、、）

**Comment by hiroG3** [comment]
koda-masaru 様

回答いただきありがとうございます。

色々と考えてみましたが、
運用面からみると、複合検索するのはuser権限のユーザが大半ですし、
作業リソースの視点でみると、本件より他の要望や開発に時間を費やした方が得策ですね。

お忙しいところ、大変お手数をおかけしました。
本件はクローズとしますね。
