### ISSUE TITLE
Web API のレスポンスの "title" が検索クエリが付くと html タグ付きになる

### ISSUE THREAD

**Issue by griffin-stewie** [support-project/knowledge#803]
## 事象

検証環境: 1.10.0 pre2 github.com/support-project/docker-knowledge の pre-japanese ブランチを使用

Web API でkeyword 検索のクエリを付けた場合(`api/knowledges?keyword=XXXX`)とただの一覧取得の場合(`api/knowledges`)、同一 Knowledge ID の記事であっても結果の内容が違っています。

違っている箇所は `title` の部分で検索クエリ付きの場合 HTML タグがくっついた状態になっています。

## 期待値

検索クエリの有無にかかわらず記事取得系 API で得られる `title` はプレーンテキストであることを期待します。

リリースの直前で申し訳ありませんがご確認いただけるとありがたいです。

### 検索クエリあり

```sh
curl -H "PRIVATE-TOKEN:${KNOWLEDGE_API_TOKEN}" "http://localhost/api/knowledges" | jq
```

上記コマンドから得られるレスポンスの一部

```json
{
    "commentCount": 0,
    "content": "### あああ\n",
    "insertDatetime": "2017-07-14 02:40:31.368",
    "insertUser": 1,
    "knowledgeId": 42,
    "likeCount": 0,
    "publicFlag": 0,
    "tags": [
      ""
    ],
    "template": "knowledge",
    "title": "Sample",
    "updateDatetime": "2017-07-14 02:40:31.368",
    "updateUser": 1,
    "viewers": {
      "groups": [],
      "users": []
    }
}
```

### 検索クエリなし

```sh
curl -H "PRIVATE-TOKEN:${KNOWLEDGE_API_TOKEN}" "http://localhost/api/knowledges?keyword=Sample" | jq
```

上記コマンドから得られるレスポンスの一部

```json
{
    "commentCount": 0,
    "content": "### あああ\n",
    "insertDatetime": "2017-07-14 02:40:31.368",
    "insertUser": 1,
    "knowledgeId": 42,
    "likeCount": 0,
    "publicFlag": 0,
    "tags": [
      ""
    ],
    "template": "knowledge",
    "title": "&lt;span class=&quot;mark&quot;&gt;Sample&lt;/span&gt;",
    "updateDatetime": "2017-07-14 02:40:31.368",
    "updateUser": 1,
    "viewers": {
      "groups": [],
      "users": []
    }
}
```

**Comment by koda-masaru** [comment]
たしかに、WEB APIでの検索の場合に限っては、titleのプロパティに関して検索キーワード部分のハイライトはしない方が良い気がします。
#804 のPRでTitleのハイライトをしないように変更しました。

なお、contentプロパティは今まで通りハイライトしようと思います。
これは、キーワード検索では、Knowledgeの本文の他に、コメント、添付ファイルの中身なども検索の対象になっており、ヒットした先によってcontentが切り替わるためです。
検索対象が本文だけでないため、DBに保存しているKnowledgeの本文を常に送れば良いということにはならないため、contentについてはそのままにしました。

**Comment by koda-masaru** [comment]
テスト環境にTitleのハイライトを解除した版をデプロイしました。
もしお時間があればお試しください。
少ししたら、 v1.10.0 のリリースに移ろうかと思います。

**Comment by griffin-stewie** [comment]
@koda-masaru さん
動作確認させていただきました。仕様についても承知いたしました。
ご対応いただきありがとうございました。
