### ISSUE TITLE
テーマ選択　advanced option の使い方

### ISSUE THREAD

**Issue by ino9999** [support-project/knowledge#808]
お世話になります。
メニュー＞テーマ選択
Advanced　option の項目はどのように利用すれが宜しいでしょうか。
独自のCSSを読み込ませたいのですが、可能でしょうか。

**Comment by koda-masaru** [comment]
テーマは、bootswatchとhighlight.jsを使っています。
この中には、Knowledgeで表示しているテーマ以外にも多くのテーマを持っています。
advanced optionは、表示されていないものも使えるようにする機能です。
（例えば、Code Highlightで `school_book` を有効にすると、面白いハイライトになります）

そんなわけですので、独自のCSSを読み込ませる機能ではありません。
（bootswatchにプルリクを送って独自のCSSを追加すれば、読み込ませることはできますけどね）

**Comment by ino9999** [comment]
koda 様
お世話になります。ご返答ありがとうございます。
承知しました。

**Comment by koda-masaru** [comment]
I think that it is solved and I will close it.
