### ISSUE TITLE
画像をアップすると、イメージファイルがコピーされて2個アップされる

### ISSUE THREAD

**Issue by htakeda** [support-project/knowledge#810]
pngファイルのようなイメージファイルをアップすると、別名でコピーされているようです。
ですので、画像が2つアップされているように見えます。
txtのようなファイルは、1個のままでした。

どちらか一方だけ、表示することはできないのでしょうか。

・画像ファイルは、1個アップすると2個アップされる
![2017-07-31_14h28_05](https://user-images.githubusercontent.com/11866919/28763999-1dbf67e6-75fd-11e7-8262-bf3595cd66ee.png)

また、画像をコピーしているということは、ストレージもその分使用(2倍になる)していると思うのですが、これは仕様でしょうか。
容量の無駄遣いのような気がするので、いつか改善していただけるとありがたいです。

**Comment by koda-masaru** [comment]
@htakeda さん
ご連絡ありがとうございます。
今、テスト環境で試してみたのですが、PNGをアップロードした時にファイルは1つだけ登録され、2つになることが確認できませんでした。

<img width="631" alt="2017-08-02 17 15 44" src="https://user-images.githubusercontent.com/10343517/28864109-7476087e-77a6-11e7-9b36-da3157d6d89a.png">

発生条件を知りたいので、上記の問題が発生したときの

- 操作手順
- クライアントの情報（ブラウザ, OSなど）
- サーバーの情報

を伝えられる範囲で教えていただけないでしょうか？

**Comment by htakeda** [comment]
返答ありがとうございます。

## バージョン情報
### サーバ
OS: CentOS 7.3
knowledge：1.10.0
PostgreSQL： 9.6.3
apache-tomcat：8.5.16
java：java-1.8.0-openjdk-headless-1.8.0.141-1.b16.el7_3.x86_64

### クライアント
OS：Windows10
利用ブラウザ：Chrome バージョン: 59.0.3071.115

## 画像情報
確認した画像ファイル種類：png、jpeg

## 再現方法
1. 「画像をアップロード」を選択。「画像をアップロード」画面が表示される。
2. 画像を1つ「画像をアップロード」画面にドラッグ＆ドロップする。
3. 2つファイルが作成される

「ファイルを選択」や直接ドラッグ＆ドロップした場合は、1個のままです。
「画像をアップロード」した場合のみ、2個になります。

よろしくお願いします。

**Comment by Monota** [comment]
@koda-masaru さん、

もともと画面全体が画像アップロードの対象領域になっているため、画像アップロードのダイアログを開いて指定の領域にファイルをドロップしたときに１回目がアップロードされて、Confirm ボタンをクリックしたときに２回目がアップロードされています。

画面を見る限りでは、
「添付するファイルをここにドロップすると・・・」
と書かれた領域のみがドロップ対象のように思いますが、最初からドキュメント全体がドロップ対象だったのか、あるとき変更したのかはわかりませんでした。

https://github.com/blueimp/jQuery-File-Upload/wiki/Options

ここを参照して dropZone を drop_target に指定してみたところ、現象は回避できました。

```js
    $('#fileupload').fileupload({
        url : url,
        dataType : 'json',
        autoUpload: true,
        maxFileSize: 5000000, // 5 MB
        dropZone: '#drop_target',
```

画面全体がドロップターゲットのほうが使いやすい気もする一方、

![2017-08-05 21 29 50](https://user-images.githubusercontent.com/9009605/28995542-c0e37700-7a26-11e7-8a54-5e1f854a7322.png)

この画面の指示内容とドロップ方法が異なるので、修正した方が良いか判断をお願いしたいです。ちなみに本事象だけを回避するなら、ダイアログが表示されたときだけファイルアップロードを防ぐといった策も考えられるかなと思いました（こちらはまだ試していません）。

**Comment by koda-masaru** [comment]
上記のドロップ領域をちゃんと指定するという対応で、問題無いかと思います。
そして、プルリクもありがとうございました。
マージしましたので、次のリリースで出していこうと思います。

**Comment by htakeda** [comment]
@Monotaさん、@koda-masaruさん

ご対応ありがとうございました。

**Comment by koda-masaru** [comment]
This is supported by v1.11.0.
I will close this.
