### ISSUE TITLE
Windows 10 + tomcat 9 + postgresql 

### ISSUE THREAD

**Issue by RiffChan** [support-project/knowledge#811]
can i have the installation procedure for Windows 10 + tomcat 9 + postgresql settings ?
many thanks

**Comment by koda-masaru** [comment]
Yes, you can install "knowledge" for the environment.
I write the recommended installation procedure.

- Download Java8 and install on GUI wizard
- Download Tomcat9 and install on GUI wizard
   - You shouldn't put a space in the installation path
- Download a latest knowledge.war from this release page and put this file on Tomcat's "webapps" directory 
- If you access the path of `http://localhost:8080/knowledge` in the browser of the PC you installed, knowledge's top page will be displayed

You are done with Knowledge installation. 
Next, you will switch the Database to PostgreSQL.

- Download PostgreSQL and install on GUI wizard
- Sign in to Knowledge by initial admin account
   - Initial admin account is `Id: admin / Password: admin123`
- Please click the menu in the following order and proceed to the page of database switch
   - Click `System Config` from the icon menu in the upper right
   - `Change Database` on the next page
- On the Change Database page, enter the connection setting of PostgreSQL you installed
   - This page is helpful: https://jdbc.postgresql.org/documentation/head/connect.html

You are completed switching to PostgreSQL.

-----

Alternatively, if you want to try knowledge for a while, you can use a Docker image.
Would you look the following URL?
https://hub.docker.com/r/koda/docker-knowledge/

**Comment by koda-masaru** [comment]
Since there is no reply, I think that it is solved and I will close it.
