### ISSUE TITLE
[ご提案] 記事を修正/投稿した後のタイムラインの表示に関して

### ISSUE THREAD

**Issue by aquaqgc** [support-project/knowledge#812]
# 対象の動作
一度投稿した記事を再編集し[投稿する]をクリックしたあと、記事がタイムラインのトップに表示される。

# 提案
記事を再編集し[投稿する]ボタンを押す際に、[タイムラインのトップに表示しない]といったオプションを追加できないでしょうか。

# 背景
グループでknowledgeを利用させていただいておりますが、利用者から「句読点などの軽微な修正のたびに、記事がタイムラインのトップに表示されないようにしたい」という意見がありました。

ご一考いただければ幸いです。よろしくお願いします:pray:

**Comment by koda-masaru** [comment]
あっても良い機能ですね。手があいたら追加しようと思います。

**Comment by koda-masaru** [comment]
This is supported by v1.11.0.
I will close this.

**Comment by johiroshi** [comment]
v1.11.0に更新して「タイムラインを更新しない」チェックボックスを確認しました。「一覧の表示順を記事の些末な変更に依存しないようにする」という意図には賛成ですが、チェックボックスは邪魔くさいと思いました。これはチェックボックス単体に対してというよりも、「投稿する」「下書き保存」「下書き保存」「キャンセル」「削除」も合わせた６つものボタン（アクション）が存在するのが煩わしいという意味です。その下に属性などの設定条件もあるので、編集画面は可能な限り使いやすい方が継続率につながりやすいと思いました。
