### ISSUE TITLE
Raspberrypi2または3でKnowledgeを動かすには

### ISSUE THREAD

**Issue by chakapoco** [support-project/knowledge#813]
表題のとおりです。
自分専用でKnowledgeを利用させていただいております。
こういった開発に関してド素人なので書き込みするのもおこがましいのですが、

http://qiita.com/laviee/items/afa82cbf5e36e85d45e3
を参考に実践してみたのですが、うまくいきません。そもそもこの記事は動作させる所までに至っていませんが。
Knowledgeはほぼ理想のソフトウェアなので、もし可能であればご対応願えませんでしょうか。

**Comment by koda-masaru** [comment]
ラズパイは持っていないので試せませんが、Linuxですので普通にインストールすれば動くと思います。上記のQiitaの記事のままの手順いけるとおもいますよ。
または個人利用ですあれば、ラズパイにDockerいれて、コンテナで起動しても簡単だと思います。お試しください。

**Comment by koda-masaru** [comment]
Since there is no reply, I think that it is solved and I will close it.
