### ISSUE TITLE
How to config ldap

### ISSUE THREAD

**Issue by lhcpig** [support-project/knowledge#816]
Can you give an example ？

**Comment by koda-masaru** [comment]
This is a ldap config example.

<img width="639" alt="2017-08-08 18 45 44" src="https://user-images.githubusercontent.com/10343517/29066317-d63dfed2-7c69-11e7-80d1-00d92fe07d22.png">

The explanation of each item is as follows:

Name(required): It is the name of the setting. 
Host(required): Server name or IP address of Ldap.
Port(required): Port of Ldap.
Bind DN(required): DN for accessing the Ldap.
Password(required): Password of Bind DN.
BaseDN(required): DN of starting point for searching user entry.
Filter(required): Filter to extract user entry.
Id Attribute(required): Attribute name of User ID. This ID will be the ID for sign in to Knowledge.
Name Attribute: Attribute name of User name. This name will be displayname of Knowledge.
Mail Address Attribute: Attribute name of mail.
Admin ID: A user with the specified ID becomes administrator of Knowledge. (optional)

**Comment by koda-masaru** [comment]
Since there is no reply, I think that it is solved and I will close it.
