### ISSUE TITLE
Language - variable name spelling mistake

### ISSUE THREAD

**Issue by garp5000** [support-project/knowledge#823]
Hello,

this wasn't a bug but just a little spelling mistake on a variable name in the files : 
- appresource.properties
- appresource_ja.properties
They're a variable named "knowledge.auth.label.request.init.passwoed", I think the right name should be "knowledge.auth.label.request.init.password"

By the case, you made a very good job, all seems to be very clean and pleasant to read! Thank you!

**Comment by garp5000** [comment]
Hello again,

I've found another one, the variable named "knowledge.auth.label.request.init.passwoed" instead of "knowledge.auth.label.request.init.password".

Another thing, when we edit a knowledge, I see the label "draft delete" doesn't have his self variable but is create by associate "label.draft" with "label.delete". Do you think it's possible to give him a full variable? (for exemple: label.draftdelete).

Thanks.

**Comment by koda-masaru** [comment]
Hi,

Thank you for your advice for typo. I will fix it.
Also, if you are not troubled, please send a pull request as well.

And I will change a button label `label.draft` &` label.delete` to 'label.delete.draft` on the edit page.

Regards.

**Comment by garp5000** [comment]
Thank you very much !

Best regards,

**Comment by koda-masaru** [comment]
This is fixed by v1.11.0.
I will close this.
