### ISSUE TITLE
Hide events from list

### ISSUE THREAD

**Issue by garp5000** [support-project/knowledge#828]
Hello,

I would like to know if it could be possible to hide events from the main list, and from search engine (maybe an option could be add in the system menu). 
Events are displayed directly in the calendar and can be selected by clicking on the date, so maybe it wasn't important to display them in the list, and focus the search engine only to knowledges by default.

Best regards

**Comment by koda-masaru** [comment]
Hi, 

Thank you for your valuable issue. I will add a filter by template to the list.
And filter value will saved to user config.
In this way, Events are not displayed in the list of users who think that they do not need to display events.

I Added new issue #829 

Best regards.

**Comment by koda-masaru** [comment]
This issue is available on v1.12.0 pre1.
