### ISSUE TITLE
ナレッジの編集画面のデザイン見直し

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#83]
ごちゃごちゃしているという意見をもらった。

他のMarkdownで編集できるサービス（Qiita、はてなブログとか）を参考に、
編集しやすい画面を検討しようと思います。

レスポンシブデザインを使っているが、いっそのこと、PCでの編集とスマフォでの編集では
画面を変えてしまう方が良いかも。

編集画面にあわせて、表示画面もデザインを見直す必要があるかも？

**Comment by johiroshi** [comment]
記事の表示画面のレイアウト案を考えました。

前回と同様に、.jspファイル内でコメントアウトを行い、今回はCSSも少し触りました。

***日本語の記事サンプル***
![日本語の記事サンプル](https://cloud.githubusercontent.com/assets/15374413/11492921/8e352f7a-9836-11e5-9853-668b610b8a70.png)

***英語の記事サンプル***
![英語の記事サンプル](https://cloud.githubusercontent.com/assets/15374413/11492931/a7855e5a-9836-11e5-8344-d8e4dd3c40ad.png)

***非公開の記事サンプル***
![非公開の記事サンプル](https://cloud.githubusercontent.com/assets/15374413/11492934/aebf9686-9836-11e5-8f70-5448db954e07.png)

現在、記事のレイアウトに対して大凡手を加え終わった状態です。
コメント欄や、記事編集画面のレイアウト案もぼんやりとあるのですが、一度に大きな変更を加えすぎるのもどうかと思い、今後の対応に迷っています。どのようにPRを出すのが適切でしょうか？

1. コメント欄や記事編集画面のレイアウトまで一通り終えてからPRを出す
2. 記事 / コメント欄 / 記事編集画面、など各要素ごとに修正を加え、個々にPRを出す
3. タイミングにとらわれず、出したいときにPRを出す
4. それ以外

また、git 的な作法についてもご教授いただけると幸いです。
現在、 ``` git pull upstream develop ``` 後、手を加えています。

**Comment by koda-masaru** [comment]
@johiroshi さん

レイアウト案の検討ありがとうございます。

PRは、2の「記事 / コメント欄 / 記事編集画面、など各要素ごとに修正を加え、個々にPRを出す」でお願いしたいです。
なお、今開発中の「0.7系」をリリースした後（もうすぐですリリースできると思います）、「0.8系」の開発の中でレイアウト変更を対応しようと思います。

**Comment by johiroshi** [comment]
@koda-masaru さん

返信ありがとうございます。

PRの出し方、リリースの件、了解です。

それと、言葉に誤りがあったので訂正します。「記事のレイアウト修正が終わった」と書きましたが、「Markdownを除く記事のレイアウト修正が終わった」でした。Markdown部については、また時間を置いてから取り組もうと考えています。

これからPRを出します。よろしくお願いします。

p.s. レイアウト変更が適用された後に社内で導入しようと考えていますので、リリース、楽しみにしています。

**Comment by koda-masaru** [comment]
了解しました。
いろいろ対応ありがとうございます。
