### ISSUE TITLE
Skip home page

### ISSUE THREAD

**Issue by garp5000** [support-project/knowledge#836]
Hello,

I've see that's possible to edit the home page on system menu -> Service custmize, but do you think it should be possible to be directly redirected to "open.knowledge/list" after login? Maybe by giving the choice in the "Service custmize" setting?

Best regards

**Comment by koda-masaru** [comment]
I thought the page after login was always good on the list page.
Therefore I change the page after login to the list page.

#837

Best regards.

**Comment by koda-masaru** [comment]
This is supported by v1.11.0.
I will close this.
