### ISSUE TITLE
クリップボードから直接画像を貼りたい

### ISSUE THREAD

**Issue by kounoike** [support-project/knowledge#84]
あったらいいな、という要望です。

紹介記事： http://yohshiy.blog.fc2.com/blog-entry-217.html
GitHub： https://github.com/peclik/clipboard_image_paste

Redmineのプラグインなのですが、とても便利なのでKnowledgeでも同じ機能があるとインストール記録などのナレッジ作成が捗ると思います。

**Comment by koda-masaru** [comment]
こんな機能があるのですね。知りませんでした。

技術的に面白そうなので、後で作ってみたいです :smiley: 

他にも要望があるので、ちょっと時間がかかるかもしれませんが、お待ちいただけると幸いです。

**Comment by kounoike** [comment]
もちろん、「あったらいいな」ですので、優先度低くてかまいません。

**Comment by koda-masaru** [comment]
一人で作っていると、アイディアが煮詰まりますので、要望を登録してもらえて嬉しいです。
すぐに対応できないのが心苦しいですが、、、

Webでクリップボードを操作できるということは、技術としても面白そうなので、
後でちょっといじってみたいと思います。（連休は家族サービスですが、、、）

**Comment by kounoike** [comment]
こちらこそ、Javaを書いていると体質的に受け入れられずいらいらしてしまうので、PRで実現できずにすみません。

技術的には、クリップボードのデータをそのまま貼り付ける→そのデータをcropして欲しいところだけにする。
の2段階だったと思います。
まずは、クリップボードそのまま貼り付けるだけでも実現すると便利になるでしょうね。

家族サービス、楽しんできてください。

**Comment by koda-masaru** [comment]
Javaは硬いところありますからね。
ただ、私は逆で仕事でNode.jsなので、Javaのように硬いものを触りたくなったので、今回はJavaで作ってます。

HTML5でクリップボードの情報を操作できるClipboard APIが使えるとは聞いていたのですが、
それを利用するアイディアが思いつきませんでした。

たしかに、クリップボードの内容をアップロードして、その画像を本文に埋め込めると便利ですね。

**Comment by koda-masaru** [comment]
ブラウザでクリップボードを扱えるライブラリで以下があるようです。
http://zenorocha.github.io/clipboard.js/

**Comment by kounoike** [comment]
clipboard.jsは文字列のコピー＆ペーストに限定したものだったような覚えがあります

**Comment by mitsugogo** [comment]
クリップボードの画像ファイルをアップロードする - Qiita
http://qiita.com/volpe28v@github/items/dc100c75c2371bb82a3b

こういうのだったら実装できそうですね！

**Comment by koda-masaru** [comment]
情報ありがとうございます。
じつは、v1.7 で、アカウントのアイコン画像のアップロードの際に、画像のどの部分をアイコンに設定するかを設定できるようにしてみました。（アイコン画像アップロードの機能が変更になっていると思うので、よかったらお試しください）

そこで使った技術を組み合わせると、クリップボードから画像アップロードも出来そうな気がしています。

issueが溜まっていてなかなか対応できていませんが、次バージョン(v1.8)には入れられるかな〜という気がしていますので、ご期待下さい！

**Comment by koda-masaru** [comment]
「クリップボードから画像をアップロード」の機能を作ってみました。
デモサイトで動作のイメージを確認できるようにしてみたので、良かったら見てみてください。

- 確認手順

1. 記事作成
2. 「画像をアップロード」ボタン（添付ファイルの部分にボタンを追加）
3. 画像編集ダイアログが表示されるので、そこでクリップボードから画像を張り付けできます
4. ダイアログでは、画像をトリミングしたり回転したり、マウスで線を書いたりできます
