### ISSUE TITLE
Contribution point

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#840]
Contribution point will shown.
Points will be attached to users and articles and show rankings
- Most contributing user 
- Most contributing articles

------

情報共有への貢献度を表示する。
ユーザと記事にポイントをつけ、ランキングのページで表示する
- 最も貢献しているユーザ
- 最も貢献した記事

**Comment by ikuko** [comment]
貢献度はどのようなルールで加点されていくのでしょうか？

**Comment by ikuko** [comment]
ありがとうございます。
おおよそどのような仕様か把握できました。

**Comment by koda-masaru** [comment]
This is supported by v1.11.0.
I will close this.
