### ISSUE TITLE
いいねを一人のユーザーが何回も行える

### ISSUE THREAD

**Issue by AziOGroup** [support-project/knowledge#841]
表題のとおりです。
記事の画面でいいねを何回も行えてしまいます（意図的な仕様ならすいません）
また、つけたいいねを取り消すにはどうしたら良いのでしょうか

宜しくお願い致します

**Comment by koda-masaru** [comment]
いいねは、何回もつけられるのは仕様です。
その回数で気に入った具合を表現できるように、制限をかけないのが初期設定になっています。

ただし、一人一回にしたい（KPIに使いたい）という要望があり、現在開発中のバージョンでは、一つの記事に対し一人一回に制限できるようになっています。
制限は、管理者メニューのシステム設定で指定します。

![image](https://user-images.githubusercontent.com/10343517/30025906-a63524c0-91b5-11e7-9a22-e18a684605bb.png)

一人一回に制限したい場合は、次のリリースをお待ち下さい。

なお、今のところ、いいねを取り消すことはできません。
今後については要検討ですが、取り消されたらモチベーションが下がると思います。
このため、いいねを取り消す機能はたぶん追加しないと思います。

**Comment by AziOGroup** [comment]
回答ありがとうございました。
元々そういう仕様だったのですね、知らなくて申し訳ございませんでした。
開発版が設定画面から帰れるとのことで次の正式リリースを待ちたいと思います。

いいねの取り消しに関してですが、
故意にいいねの大量に押して人気タブを無意味なものにしたりというユーザーが出た場合に管理者メニュー側から操作できたら良いなと思いました
（元々そのような規模で運用するものではないのかもしれませんが）

**Comment by takerushi** [comment]
> なお、今のところ、いいねを取り消すことはできません。
今後については要検討ですが、取り消されたらモチベーションが下がると思います。

その仕様と意図は素晴らしいと思います。

間違っていいねを押してしまったときのために、
数分間だけ（もしくは今開いているページのセッションだけ）取り消せると嬉しいです。

**Comment by koda-masaru** [comment]
> 故意にいいねの大量に押して人気タブを無意味なものにしたり

社内のイントラでの運用を想定しているので、自分の評価が下がるような子供じみた事をするユーザはいないと思って仕様を作っています。未ログインでもアクセスログで、だいたい誰が実行したか、調べようと思えば調べられますし、、、

> 間違っていいねを押してしまったときのため

KPIなどで使う＆人事評価にも使っているという組織もあるという話なので、
間違って押してしまった際に取り消せるといった機能も必要かと思いました。

今後検討していこうと思います。

ただ、基本的には、投稿を「活性化」する機能を優先した方が良い気がします。
その人にとっては間違って押したものであっても、そのまま「いいね」が付いていたほうが、投稿した人にとっては嬉しいと感じるのではと思います。

組織によっては、充分に活性化しており、次のステップ（投稿は充分に多い／次は投稿の内容の質を高める）に進みたい場合は、必要な機能なのだと思います。

**Comment by koda-masaru** [comment]
This is supported by v1.11.0.
I will close this.
