### ISSUE TITLE
テンプレート名称が投稿画面でエスケープされていない

### ISSUE THREAD

**Issue by nyoronjp** [support-project/knowledge#845]
システム設定>テンプレート>追加

テンプレート名称にHTMLタグ記述し保存。
![001](https://user-images.githubusercontent.com/3918654/30236814-cba25bf0-955d-11e7-8be3-c2eb8db62fbe.png)

投稿画面の種類でエスケープされずHTMLが解釈されている。
![002](https://user-images.githubusercontent.com/3918654/30236815-ce5294a0-955d-11e7-8e6a-ef6ca3b9a3e6.png)

scriptタグも使えました。

```html
<script>alert(1);</script>
```

管理者しかテンプレート追加ができないので仕様だったらすいません。

**Comment by koda-masaru** [comment]
管理者が登録する部分はご指摘の通り、HTMLのエスケープをわざとしていない所があります。
（例えばアナリティクスの設定とか。明示的にスクリプトを登録出来るようにしています。）
この部分も、別にいらないかなと思ってそのままにしたのですが、そこまで意味があるわけでもありません。
次のバージョンでは、エスケープするようにしようと思います。

**Comment by nyoronjp** [comment]
管理画面のXSS対策ってどこまでやるべきかの判断って難しいですね。イントラ内で使うものだと特に。
アナリティクスの設定だと全体に反映できるJavaScriptやCSS書けて便利ですし。

投稿で種類をbookmarkにし、URLに<code>javascript:alert(1)</code>と入力すればクリックすることでアラート出せます。
![image](https://user-images.githubusercontent.com/3918654/30255362-42a7515c-96de-11e7-8972-3f2dfdb135e2.png)
これも想定した使い方なんでしょうか？

**Comment by koda-masaru** [comment]
む、、、
これは、エスケープ漏れですね（ユーザが登録する部分はエスケープ対象）
次のバージョンまでに修正します。

**Comment by nyoronjp** [comment]
Knowledge v1.11.0 pre2

I confirmed.
Thanks.
