### ISSUE TITLE
ログローテーション

### ISSUE THREAD

**Issue by irgaly** [support-project/knowledge#85]
.knowledge/logs へ出力しているログの数が増えてきました。
3ヶ月よりも前のログは削除する、といった設定が可能だと嬉しいです。

**Comment by koda-masaru** [comment]
たしかに、今はログを出し過ぎかもです。
古いログ・ファイルの削除は検討しようと思います。

あと、ログのレベルは「INFO」レベルで出しているのですが、「WARN」以上に変更すると良いかもしれません。ログレベルの変更も考えます。

今はアプリでログをファイル出力していますが、VPSはDockerで運用しているので、Fluentd logging driver でログをFluentdに飛ばして、Fluentd + Elasticsearch +Kibana でログの監視を行うといった感じも試してみたいと思ってます。

**Comment by irgaly** [comment]
ログ監視がしっかりできるようになると良いですね。
まずはローカルログのローテーションだけでもあると助かります。

**Comment by koda-masaru** [comment]
v1.0.0pre1でリリース済み
