### ISSUE TITLE
通知設定に関する動作の質問

### ISSUE THREAD

**Issue by hiroG3** [support-project/knowledge#865]
お世話になっております。

ナレッジの通知設定の動作について質問です。

■確認1
まず、通知設定を以下のとおりに設定します。
![default](https://user-images.githubusercontent.com/29743423/30734557-a4b77cd8-9fb6-11e7-8d70-caa30fabdcbe.png)

このあと、他のユーザから公開先を**自分**にしたナレッジを投稿してもらったとき、
自分に対して投稿追加のメールが通知されるのですが、仕様でしょうか？
下名の認識では、上位の『メール通知』項目が『通知しない』の設定であれば、
下位の『通知する条件』の各項目の設定に関係なく、メール通知されないと思っておりましたが、
間違ってますでしょうか？

■確認2
通知設定にて、『自分宛の投稿が更新したら通知』を『通知する』に設定します。
公開先を**自分以外のユーザ**にし、自分がナレッジを投稿したとき、
自分に対して投稿追加のメール通知されますが、これは仕様でしょうか？
『自分宛の投稿』ではないので通知されるのは違和感がありますが、間違っていますでしょうか？

お忙しいところ申し訳ございません。
お手隙の際で構いませんので、回答をよろしくお願いいたします。

**Comment by koda-masaru** [comment]
@hiroG3 
以下に回答します。

> 自分に対して投稿追加のメールが通知されるのですが、仕様でしょうか？

仕様です

> 下名の認識では、上位の『メール通知』項目が『通知しない』の設定であれば、
> 下位の『通知する条件』の各項目の設定に関係なく、メール通知されないと思っておりましたが、
> 間違ってますでしょうか？

間違っていません。メールの通知は送らないと思います。
（サービス内の「通知」は送られます）

> 自分に対して投稿追加のメール通知されますが、これは仕様でしょうか？

仕様です。特に自分なので通知しないといった除外はしていません。

**Comment by koda-masaru** [comment]
あと、公開先を「自分以外」にしても、システムは自動的に自分を公開先に追加します。
（でないと自分で投稿したものを、自分で見れなくなります）

**Comment by koda-masaru** [comment]
Since there is no reply, I think that it is solved and I will close it.
