### ISSUE TITLE
OSのバージョンについて

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#87]
先日dockerfileのPR出したものです。
Ubuntu14.04(LTS)でknowledgeを動かしたいと思っています。

手元で試してる限りだと14.04で動かせない状態(パッケージがない等)なのですが
14.04で動くようにすることは可能でしょうか？

**Comment by GtTmy** [comment]
はじめまして。
14.04ではtomcat8がapt-getで入らないので、  
[How To Install Apache Tomcat 8 on Ubuntu 14.04](https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-8-on-ubuntu-14-04)

を参考にtomcat8を導入したところ、自分のところでは動作しています。

**Comment by nagodon** [comment]
@GtTmy  

はじめまして。
ご回答ありがとうございます。

自力インストールでは動く感じなんですね。
ちょっと手元で試してみます。

ありがとうございます。

**Comment by koda-masaru** [comment]
確かに、LTS環境で動かしたいという要望もありますね。
Ubuntu14.04(LTS)で動くDockerファイルも作成しようと思います。

**Comment by koda-masaru** [comment]
Ubuntu14.04(LTS) のDockerfileを作ってみました。

https://github.com/support-project/docker-knowledge/blob/ubuntu14.04/Dockerfile

- openjdk8がインストール出来なかったので、OracleのJDK8を入れました
- tomcat8も自分でダウンロードしてきて入れました

試したところ、動作はできています。
ご参考までに。

**Comment by nagodon** [comment]
@koda-masaru 

ありがとうございます。
早速`docker build`して起動と復元できました。

issueはクローズとさせて頂きます。
ありがとうございました。
