### ISSUE TITLE
依存パッケージのバージョン管理について

### ISSUE THREAD

**Issue by takerushi** [support-project/knowledge#873]
package.jsonとbower.jsonの依存パッケージのバージョンについて、`キャレット表記(^)`を除いたほうがよいかと思います。
それか、バージョンを固定する方法を使うと良いかと思います。

マイナーバージョンの違いでエラーとなることもあり得ますし、ご検討ください。
また、もしわざと^をつけているのであれば意図を教えてください。

参考
https://qiita.com/sotarok/items/4ebd4cfedab186355867
https://s8a.jp/node-js-package-version-fixed#%E3%81%BE%E3%81%A8%E3%82%81

**Comment by takerushi** [comment]
bower.jsonではバージョンを固定しているみたいですね。

**Comment by koda-masaru** [comment]
キャレット表記にしているのは、強い意味があるわけではありません。
ただ、基本的に node.js  (package.json) は、ツール（jsの圧縮など）での利用なので、厳密にバージョンを固定しなくても良いだろうと思って キャレット表記 にしています。

逆にbowerは、アプリケーションに組み込まれる（リリース物に含まれる）ライブラリを取得するものなので、バージョンを固定しています。でないと、テストするたびに下手をすると動きが変わってしまうので。

別にキャレット表記でないとダメということも無いので、固定しても良いかと思いますので、
後日、固定してしまおうかと思います。

**Comment by koda-masaru** [comment]
This is fixed by v1.11.0.
I will close this.
