### ISSUE TITLE
記事を開くと "protect.survey/load" 401 もしくは 404 が出ます

### ISSUE THREAD

**Issue by ikuko** [support-project/knowledge#879]
デモ環境でも発生しました。
記事を開くとコンソールに以下のようなエラーが出ます。
未ログインで 401、ログイン状態で 404 になるようです。

```
page-common-70be83d24b.js:3 GET https://test-knowledge.support-project.org/protect.survey/load/3 404 ()
```

Google Chrome 61.0.3163.100（Official Build） （64 ビット）
を使用しています。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。
ちょうど、アンケート部分のテストを作っていたところだったので、
ステータスを調整しました。

**Comment by nyoronjp** [comment]
似たような問題が投稿画面でも起こります。
投稿の種類をeventに切り替えると

> GET https://test-knowledge.support-project.org/bower/moment-timezone/data/meta/latest.json 404 ()

https://github.com/support-project/knowledge/blob/cc3ae09d54dacdab4ca807e219d07e904c4a21f9/src/main/webapp/js/template-item-input.js#L212

**Comment by koda-masaru** [comment]
This is fixed by v1.11.0.
I will close this.
