### ISSUE TITLE
ロゴ画像が欲しい

### ISSUE THREAD

**Issue by kounoike** [support-project/knowledge#88]
わがままを言います。

https://bitnami.com/stacks にある画像に張り込めるくらいのロゴ画像が欲しいです。
部署サーバのサービス一覧のリンクページ（サーバのトップページ）を作っていて、画像が揃っていないと落ち着きが悪いので・・・

**Comment by koda-masaru** [comment]
bitnami形式では無いのですが、以下のURLにアイコンの画像があります。

https://applishow.com/detail/RrUIXnfVVmCA/

Applishowという、アプリの紹介のサイトの担当者様からお声掛けいただき、
Knowledgeの紹介を登録した際に作成したものです。
この画像ではいかがでしょうか？

イメージとあっていましたら、Gitにも上記の画像を登録しようと思います。

**Comment by kounoike** [comment]
返信遅れてすみません。
適当に加工させていただき、bitnamiのものと並べて見栄えのする画像ができました。
（加工がＮＧってことはないですよね？）

ありがとうございました。

**Comment by koda-masaru** [comment]
上記の画像は、加工など自由にしていただいてかまいません。

この画像は、Font Awesome (https://fortawesome.github.io/Font-Awesome/) というフリーの
サイトのアイコンを元に作成したのですが、ちゃんとデザインした方が良いのかもしれません。
別途検討いたします。
ただ、デザインのセンスが無いので悩みますが。。。
