### ISSUE TITLE
XSS possible in tag name input field and group name input field.

### ISSUE THREAD

**Issue by nyoronjp** [support-project/knowledge#882]
タグ名入力欄とグループ名入力欄でXSS可能

1. ナレッジ投稿画面のタグ入力欄にスクリプトを入力し記事を投稿する。
![image](https://user-images.githubusercontent.com/3918654/31171132-a9501b92-a939-11e7-9df2-6ac41652da58.png)
2. 再度ナレッジ投稿画面を開きタグ入力欄で先程入力したスクリプトの一部を入れサジェストを表示させる。
![image](https://user-images.githubusercontent.com/3918654/31171346-4400a760-a93a-11e7-8d5d-abdd8299b3cb.png)

流れとしては、
エスケープされたタグ名`&lt;script&gt;alert(&quot;Cross-Site Scripting&quot;);&lt;/script&gt;`を
https://github.com/support-project/knowledge/blob/cc3ae09d54dacdab4ca807e219d07e904c4a21f9/src/main/webapp/WEB-INF/views/protect/knowledge/partials/partials-edit-scripts.jsp#L73
でアンエスケープし、Bootstrap Tags Inputプラグインに渡しているため、
https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/blob/41fe4aa2201c4af4cfc4293fa3fc8260ad60bf35/dist/bootstrap-tagsinput.js#L346
スクリプトの評価されても問題ない部分(文字列部分等)のハイライトが行われた場合、スクリプトが評価され任意のスクリプトが実行されてしまいます。

グループ名でも同様にサジェストされる箇所（どこか失念）で起こりました。
#870 でも書きましたがタグ名やグループ名に使用できない文字を決めてしまうのがいいと思います。

こんなIssueばっかですいません。。。

**Comment by koda-masaru** [comment]
@nyoronjp 

Thank you for your issue.
But It can not be reproduced on test site.

https://test-knowledge.support-project.org/open.knowledge/view/4

What is the version you use?

-------

ご連絡ありがとうございます。
テスト環境で試したのですが、再現させることができません。
ご利用のバージョンは何でしょうか？

**Comment by nyoronjp** [comment]
I used v1.11.0 pre1, v1.11.0 pre2 and this demo site.
Chrome and Edge on Windows 10, Chrome on Windows 7.
Used browser version is latest.
---

自サーバ内の1.11.0 pre1とpre2に上げたKnowledgeとデモサイトの1.11.0 pre1とpre2で確認しました。

今朝もチラッとみたのですが、`<script>alert("hoge");</script>`というタグがある状態で、
新規投稿画面に`h`と入力することでalertが出ました。

**Comment by koda-masaru** [comment]
Thank you for answering.
I could reproduce this problem, and fixed on #887 pull request.

**Comment by nyoronjp** [comment]
OK, I wasn't able to occur XSS.
