### ISSUE TITLE
記事のコメントの再編集時にpdfのリンクボタンが「画像表示」となる

### ISSUE THREAD

**Issue by Wallet0013** [support-project/knowledge#884]
## 概要
ある記事へのコメントへの新規登録時にpdfをアップした際には正しく、スライドボタンとなりますが
当該コメントの編集時にはスライドボタンであるべきリンクボタンが、画像表示のリンクボタンとなってしまいます。

## 環境情報
demoページでの再現を確認しました。

## 取り急ぎのワークアラウンド
画像リンクボタンボタンからドキュメントの番号を把握し、[slide 222] のように手動で差し替える

**Comment by koda-masaru** [comment]
Thank you for your issue.
I will fix this problem later.

**Comment by koda-masaru** [comment]
This is fixed by v1.11.0.
I will close this.
