### ISSUE TITLE
投稿時の注意みたいなメッセージを表示したい

### ISSUE THREAD

**Issue by kounoike** [support-project/knowledge#89]
わがまま続きです。

投稿時に「機密情報の投稿禁止」みたいな案内を出したいです。
（機密はちゃんとしたファイルサーバに入れることになっているため）

そういったメッセージの表示設定機能を追加することは可能でしょうか？

**Comment by koda-masaru** [comment]
なるほど。監理者からのメッセージなどを登録できる機能を検討したいと思います。
以下のような手段で、メッセージ表示を考えようと思います。

1. ナレッジ登録／更新画面で「説明」を表示
    - ちょうど、ナレッジのテンプレート化の対応をしています
        - 種類で「knowledge」と「bookmark」を選択しているもの
        - その他の種類（登録のテンプレート）を追加できる
    - テンプレートに対し、そのテンプレートの「説明」を登録できるように考えていました
    - その「説明」で、「機密情報の投稿禁止」を登録すれば、登録の際に表示されます

2. 監理者メッセージ
    - 監理者がメッセージを登録すると、ユーザがログインした際に表示する

その他、こうして欲しいなどありましたらご連絡ください。

**Comment by koda-masaru** [comment]
1. ナレッジ登録／更新画面で「説明」を表示

の部分を作成しました。

2. 監理者メッセージ

は別のissueで管理しようと思います。

**Comment by koda-masaru** [comment]
以下の機能を作成しました。次回のリリースに含めますので、ご確認ください。

- 管理者でログインすると、設定の機能に「テンプレート」の編集機能が表示されます。
    - 今のところ「knowledge」と「bookmark」のみ
- テンプレートの編集機能で、そのテンプレートの「説明」を編集できます
- 登録時に、「knowledge」「bookmark」を選択しますが、その際に、設定した「説明」が表示されます
    - 「説明」に「機密情報の投稿禁止」と書いておけば、情報登録時にそれが表示されます
