### ISSUE TITLE
ユーザ追加通知のメッセージの情報量を増やしたい

### ISSUE THREAD

**Issue by irgaly** [support-project/knowledge#90]
現在の実装ではユーザ追加時の通知は以下のフォーマットとなっていますが、
ユーザ番号だけでは情報が乏しいため、ユーザ名やメールアドレスの情報なども追加していただけないでしょうか。

```
ユーザを追加しました。念のため確認してください。

ユーザ番号: 29

------------------------------------------
※本メールはシステムより自動で送信されています。
このメールに対する返信は出来ませんので御了承ください。
```

通知を眺めていてそういえばわかりにくいなと気づいただけのものなので、
対応の優先度は低くしていただいて構いません。

**Comment by koda-masaru** [comment]
issue登録ありがとうございます。
ユーザ登録時のメールのメッセージについては、ちょうど、他の要望も受けていたところでした。

----
ユーザ追加通知メールのユーザ番号に該当する情報が見当たらない 
- ユーザ追加時に管理者にメールを送信する設定にしていますが、メール文中のユーザ番号に該当する情報が見当たらないため、誰が追加されたのか分かりません
- ユーザ一覧画面等でユーザ番号が分かるようにする、または追加通知メールの文中に、追加されたユーザのメールアドレスと名前を入れることは出来ないでしょうか？ 

----

それも踏まえて、通知メールの内容を増やそうと思います。
