### ISSUE TITLE
メール送信から投稿の設定の宛先での条件指定が適用されない

### ISSUE THREAD

**Issue by kyanon30** [support-project/knowledge#902]
メールを投稿する条件の「1.宛先に条件文字が含まれる場合」で宛先アドレスの一部文字列(@より前の部分)を指定し、そのアドレスにメールを送っても投稿されません。
MailReadBat.logを見ると以下のログが出力がされます。

Receive mail is not target condition. <送信したメールの件名>

「2.~~宛先~~件名に条件文字が含まれる場合」で件名の一部文字列を指定した場合は、正常に投稿されます。

ご確認、ご対応をお願いします！

**Comment by koda-masaru** [comment]
Thank you for your issue.

The condition of the post is checking whether the address all matches.
I'm not sure to imagine how to use such that only some of the letters are matched, so I did so.
What is the purpose of judging by matching only some character?

------
メールアドレスの場合、一部だけ一致というユースケースが想定できなかったのですが、どのようなユースケースを想定していますでしょうか？

**Comment by kyanon30** [comment]
お忙しいところご回答いただき、ありがとうございます。

「1.宛先に条件文字が含まれる場合」はメールアドレス完全一致判定だったのですね。
「2.件名に条件文字が含まれる場合」と同じく部分一致判定だと勘違いしておりました。
失礼いたしました。

ユースケースは以下のようなものになります。
```
・設定したメールボックスには以下の例のような複数のメーリングリスト宛のメールが届く
　例)
　　system1_error@xxx.co.jp
　　system1_warn@xxx.co.jp
　　system1_info@xxx.co.jp

　　system2_error@xxx.co.jp
　　system2_warn@xxx.co.jp
　　system2_info@xxx.co.jp

　　...

・メールボックスに届いたメールの内、
　宛先が「system1_~」のメールは公開範囲をグループ「system1」に、
　宛先が「system2_~」のメールは公開範囲をグループ「system2」
　にして投稿する
```

上記のようなユースケースであれば、メーリングリスト毎に「メールを投稿する条件」を作成すれば良いのですが、可能な限り作成/管理する「メールを投稿する条件」は少なくできればと考えています。

つきましては優先度は低くで問題ありませんので、「1.宛先に条件文字が含まれる場合」についても部分一致で判定できるようにしていただければ幸いです。
ご検討のほど、よろしくお願いいたします。

**Comment by koda-masaru** [comment]
I understand your usecase.
And I will change a check condition to part of the mail address matches to post article from E-mail.

-----

利用シーンを理解しました。受信メールボックスが一つなので複数のメールアドレス宛のメールが届くことは無いと思っていたので完全一致にしていたのですが、上記の場合では、確かに部分一致もできると良いですね。
部分一致指定を可能に変更します。

**Comment by kyanon30** [comment]
ありがとうございます！よろしくお願いいたします。

**Comment by koda-masaru** [comment]
This is supported by v1.11.0.
I will close this.
