### ISSUE TITLE
テンプレートのタグ初期値のお願い

### ISSUE THREAD

**Issue by enimit** [support-project/knowledge#904]
テンプレートへの機能追加のお願いです。

* タグの初期値を設定できるようにしていただけないでしょうか。タグ付けルールがある程度強制されて、良いように思います。もしくは、コンテンツの初期値が設定できれば、タグの代わりに検索に掛かるようにキーワードを入れておくこともできます。

* テキストエリアにMarkdownで入力できないようなので、コンテンツエリア項目の追加が欲しいです。ただ、この要望もコンテンツの初期値が設定できれば済む問題かもしれません。

ご検討のほどよろしくお願いいたします。

**Comment by koda-masaru** [comment]
In v1.11 you can set the initial value in the content.
Since the request for the initial value has already been realized, please check the operation with v1.11.0 pre2.

**Comment by enimit** [comment]
ご指摘ありがとうございました。助かります。
