### ISSUE TITLE
v1.9.0以降のldap認証の挙動について

### ISSUE THREAD

**Issue by bomura** [support-project/knowledge#919]
v1.8.1以前とv.1.9.0以降ではユーザ認証時の挙動が異なるようです。
相違点として、v1.9.0以降では、ログインユーザがbase dnを検索する手順が増えています。(必要のない手順に思えます)
ldap認証時の正しい挙動を知らないので、正しいものに変わっただけかもしれないのですが、確認をお願いします。

`試した限りでは、v1.9.0以降のstableバージョンにおいて、各ユーザにbasednの読み取り権限を付与することで、ldap認証を突破できます。`

- v1.8.1以前　成功時(各ユーザにbasednの読み取り権限なし)
1. (conn=1121 op=0) <bind.dn>でldapにログイン
1. (conn=1121 op=1) <base.dn>をfilter=(uid=:userid)で検索
1. (conn=1122 op=0) 見つかったログインユーザ(:userid)で認証
```
59e934d7 conn=1121 fd=27 ACCEPT from IP=172.18.0.3:59448 (IP=0.0.0.0:389)
59e934d7 conn=1121 op=0 BIND dn="<bind.dn>" method=128
59e934d7 conn=1121 op=0 BIND dn="<bind.dn>" mech=SIMPLE ssf=0
59e934d7 conn=1121 op=0 RESULT tag=97 err=0 text=
59e934d7 conn=1121 op=1 SRCH base="<base.dn>" scope=2 deref=3 filter="(uid=<:userid>)"
59e934d7 conn=1121 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
59e934d7 conn=1122 fd=29 ACCEPT from IP=172.18.0.3:59450 (IP=0.0.0.0:389)
59e934d7 conn=1122 op=0 BIND dn="cn=<:userid>,<base.dn>" method=128
59e934d7 conn=1122 op=0 BIND dn="cn=<:userid>,<base.dn>" mech=SIMPLE ssf=0
59e934d7 conn=1122 op=0 RESULT tag=97 err=0 text=
59e934d7 conn=1121 op=2 UNBIND
59e934d7 conn=1121 fd=27 closed
59e934d7 conn=1122 op=1 UNBIND
59e934d7 conn=1122 fd=29 closed
```

- v1.9.0以降　成功時(各ユーザにbasednの読み取り権限を付与)
1. (conn=1128 op=0) <bind.dn>でldapにログイン
1. (conn=1128 op=1) <base.dn>をfilter=(uid=:userid)で検索
1. (conn=1129 op=0) 見つかったログインユーザで認証
1. (conn=1129 op=1) 見つかったログインユーザで<base.dn>をfilter=(uid=:userid)で検索
```
59e9363c conn=1128 fd=27 ACCEPT from IP=172.18.0.3:59490 (IP=0.0.0.0:389)
59e9363c conn=1128 op=0 BIND dn="<bind.dn>" method=128
59e9363c conn=1128 op=0 BIND dn="<bind.dn>" mech=SIMPLE ssf=0
59e9363c conn=1128 op=0 RESULT tag=97 err=0 text=
59e9363c conn=1128 op=1 SRCH base="<base.dn>" scope=2 deref=3 filter="(uid=<:userid>)"
59e9363c conn=1128 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
59e9363c conn=1129 fd=29 ACCEPT from IP=172.18.0.3:59492 (IP=0.0.0.0:389)
59e9363c conn=1129 op=0 BIND dn="cn=<:userid>,<base.dn>" method=128
59e9363c conn=1129 op=0 BIND dn="cn=<:userid>,<base.dn>" mech=SIMPLE ssf=0
59e9363c conn=1129 op=0 RESULT tag=97 err=0 text=
59e9363c conn=1129 op=1 SRCH base="<base.dn>" scope=2 deref=3 filter="(uid=<:userid>)"
59e9363c conn=1129 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
59e9363c conn=1128 op=2 UNBIND
59e9363c conn=1128 fd=27 closed
59e9363c conn=1129 op=2 UNBIND
59e9363c conn=1129 fd=29 closed
```

**Comment by koda-masaru** [comment]
I have recently changed the processing of LDAP authentication. (I forgot when)
Please check the latest release (v1.11.0 pre3).

-----

私は最近LDAP認証の処理を変更した記憶があります。（いつだか忘れましたが、、、）
最新のリリース（v1.11.0 pre3）を確認してください。

**Comment by bomura** [comment]
v1.9.0pre3から変わっていました。
下記コミットで変更されてそうなので、調べてみます
support-project/web@ba9d5fa189997cb692b128553beaddfa385bf176

**Comment by bomura** [comment]
Sent a pull request. support-project/web#97

----
プルリクエストを送りました。support-project/web#97

**Comment by koda-masaru** [comment]
I am grateful for your cooperation. your pull request has been merged.

----

プルリクありがとうございます。先程マージしました。

**Comment by koda-masaru** [comment]
As a result of checking the operation, it can not be confirmed whether the password exists by using bind (dn, password) alone.

-----

動作確認したところ、bind(dn, password)だけでは、パスワードがあっているかの確認にならない。
不要と指摘があった、bind後の検索は必要であったため、元に戻します。
