### ISSUE TITLE
0.6pre1から0.6pre2にバージョンアップするとテーブルがないと怒られる

### ISSUE THREAD

**Issue by h-honda** [support-project/knowledge#92]
アップデートして記事の追加ボタンをおすと
TEMPLATE_MASTER
がないためエラーが出て記事が追加できなくなる

管理者でProxy設定を開こうとした時も同様なエラーなエラーがでる。

新たにテーブルが増えたようですが、うまく生成されていないようです
データベースにはPostgreSQLを使っています。

**Comment by koda-masaru** [comment]
knowledgeでは、起動時にDBのマイグレーションを実行しています。

その処理のなかでエラーが発生したと思います。

app.logにエラーが出力されていると思いますので、それを教えていただけますでしょうか？


なお、以下のSQLを実行します。

src/main/resources/org/support/project/knowledge/deploy/v0_6_0pre2/migrate.sql

https://github.com/support-project/knowledge/blob/develop/src/main/resources/org/support/project/knowledge/deploy/v0_6_0pre2/migrate.sql


私もPostgreSQLで運用していて、マイグレーションが成功しているので、PostgreSQLのバージョンによって、動かないということがあるのかも知れません。
PostgreSQLのバージョンは何をお使いでしょうか？

**Comment by h-honda** [comment]
取り急ぎPostgreSQLのバージョンをお伝えします。

PostgreSQL9.4.4です。

**Comment by koda-masaru** [comment]
PostgreSQL9.4.4 にて、マイグレーションのSQLが正常に実行できました。
原因はSQLではなさそうです。

新たなテーブル追加などのマイグレーションは、Knowledgeを起動すると実施しています。
再度、サーバーを再起動してお試しください。

マイグレーション処理でエラーがあった場合は、ログに何か出力されると思いますので、
ログの内容を教えていただけると助かります。

**Comment by koda-masaru** [comment]
古いバージョンで、かつ、再現性が不明なので、いったんクローズします。
マイグレーションに失敗などの問題が発生した場合は、別途issueを登録します。
