### ISSUE TITLE
アカウント登録確認メールのURL認証直後に[Get Start!]押下すると Not Found 

### ISSUE THREAD

**Issue by ohmix1** [support-project/knowledge#926]
v1.10.0 でアカウント登録メールのURL認証直後に[Get Start!]すると Not Found  になります。
Get Start!のURLは以下のようになります。
http://localhost/knowledge/open.signup/activate/open.knowledge/list

https://github.com/support-project/knowledge/issues/684 で初期登録されるHTMLで相対パスにしたのが影響してるのではないでしょうか。
とりあえずはカスタムTOPページのHTMLを消せば発生しません。

**Comment by koda-masaru** [comment]
Thank you for your post.
I would like to fix it later.

-----

ご連絡ありがとうございます。
いずれ修正したいと思います。

**Comment by koda-masaru** [comment]
This issue is available on v1.12.0 pre1.
