### ISSUE TITLE
タグ一覧ページの2ページ目以降が表示されない

### ISSUE THREAD

**Issue by akai-inu** [support-project/knowledge#93]
デバッグ環境の用意がつらくて(Java開発環境の用意からなので)テストせず投稿してすみませんが、

https://github.com/support-project/knowledge/blob/master/src/main/java/org/support/project/knowledge/logic/TagLogic.java#L49

こちらの部分で `offset * offset` とオフセットを指定してるからか、タグ一覧の2ページ目以降に何も表示されません。

`limit` が20ですので、2ページ目はオフセットが200以降のタグを表示するような形になっているのではないかと思います。確認をお願いします。

**Comment by koda-masaru** [comment]
返信が遅くなり申し訳ありません。
しばらく、ネットに接続出来ませんでした。

ご指摘のとおり、オフセット値の指定の間違いです。
ご連絡ありがとうございます。
