### ISSUE TITLE
1.11.0で解決されたはずのIssueが一部直っていない

### ISSUE THREAD

**Issue by aruneko** [support-project/knowledge#943]
はじめまして。いつも利用しています。

先日リリースされたバージョン1.11.0ですが、[解決済み](https://github.com/support-project/knowledge/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3Av1.11)となっているうち
いくつかのIssueが直っていない可能性があります。

といいますのも、Pre4をそのままリリース版としているため
Pre4以降のIssue解決コミットがバイナリに反映されていないためです。

改めてビルドし直していただき、全てのIssueが解決されればと思います。
よろしくお願いします。

**Comment by koda-masaru** [comment]
pre4をベースにしてはいますが、最新のdevelopからリリースしていますので大丈夫だと思います。
また、pre4以降で解決したissue無かったと思います。
具体的に○○が動かないところがあれば、別途issueをあげてください。
