### ISSUE TITLE
投稿済み記事編集時に画像を削除すると、記事編集をキャンセルしても投稿済みの記事で画像が表示されなくなる

### ISSUE THREAD

**Issue by Takumon** [support-project/knowledge#947]
## 概要
投稿済み記事の編集画面において
投稿済みの画像ファイルを削除して`キャンセル`ボタンを押した場合、
削除した画像も復元されると思ったのですが、
実際には削除されてしまい、　投稿済み記事には画像ファイル名だけが表示されます。
（もしかしてそういう仕様なのでしょうか？）

## 事象再現手順
デモ環境にて再現可能です。
1.  画像付きの記事を投稿する
1. 投稿した記事詳細画面で`投稿を編集`ボタンを押す
1. 記事編集画面で画像の`削除`ボタンを押す
1. `キャンセル`ボタンを押して記事詳細画面に戻る 
1. 記事詳細画面には画像は表示されず、画像のファイル名が表示される

**Comment by koda-masaru** [comment]
It's in the specifications.
The operation will be reflected at the timing of the operation of the attached file.

-------

仕様です。
添付ファイルは操作した時点で、その操作が反映されます。

-------

※ 最近、海外のかたのアクセスも増えてきて、「できれば英語で書いてほしい」というリクエストが来ています。このため、できれば英語と日本語を併記をお願いします。日本語のみでの問い合わせは以下のサイトに登録願います。
https://service-knowledge.support-project.org/

**Comment by Takumon** [comment]
わかりました。
今後日本語での問い合わせは[こちら](https://service-knowledge.support-project.org/)にさせていただきます。
