### ISSUE TITLE
グループの削除時にNot foundページに遷移する

### ISSUE THREAD

**Issue by nagodon** [support-project/knowledge#95]
フォームからSubmitする時にPostで送られてきますが、コントローラのアノテーションが@GetになってるためNot foundになってると思われます。

https://github.com/support-project/knowledge/blob/master/src/main/java/org/support/project/knowledge/control/protect/GroupControl.java#L238

後ほどPR出させて頂きますね。

**Comment by koda-masaru** [comment]
ご指摘ありがとうございます。確かに、メソッドの指定が間違ってました。
プルリクエストとっても助かります。
