### ISSUE TITLE
Enable stealth access to articles

### ISSUE THREAD

**Issue by koda-masaru** [support-project/knowledge#952]
The administrator can access to all articles. Because, in order to manage whether there are articles violating the rules.
However, if the history of the access from the administrator remains, the user will shrink.
For this reason, I prepare a mode to make accessible without adding history.

----

管理者は全ての記事を参照可能です。なぜならば、規約違反の記事など無いか確認するためです。
しかしながら、管理者からアクセスがあったことが履歴に残ると、ユーザは萎縮してしまうと思います。（監視されてるとう気持ちになる）
このため、履歴をのこさずアクセス可能にするモードを用意します。

**Comment by johiroshi** [comment]
記事の閲覧履歴、足跡機能はどのような意図で実装されたのでしょうか？

**Comment by koda-masaru** [comment]
貢献度の高い記事ランキングや、貢献度の高いユーザランキングを出すためです。
社内での事例報告の時に使いました。

「貢献度は、「なんらかのアクションを実施する（記事登録とかコメントを登録したり）」「なんらかのアクションをうける（記事にイイネが押される）」などで増えます。」と説明しています。

いずれ画面でも表示したいと思っています。（事例報告のときは、DBから直接集計しました）

**Comment by koda-masaru** [comment]
This issue is available on v1.12.0 pre1.

**Comment by johiroshi** [comment]
ありがとうございます。
とすると、閲覧履歴や足跡機能はその情報自体を伝えるというよりも、ランキングを出すための材料、ということですね。急に管理できる情報が増えたのでびっくりしました。
