### ISSUE TITLE
メール送信テスト機能

### ISSUE THREAD

**Issue by irgaly** [support-project/knowledge#98]
メール設定画面でSMTP情報を設定したあと、
正しくメールが送れるかテストをしたいです。

現状では記事を作成するなどして確認が必要だが、
メール設定画面から「メール送信テスト」を実行して確認ができると
手軽に設定を確認できて嬉しい。

**Comment by koda-masaru** [comment]
なるほど。その通りですね。
テスト機能の検討をしようと思います。

**Comment by koda-masaru** [comment]
v1.0.0pre1でリリース済み
