### ISSUE TITLE
記事作成メール通知が届かない

### ISSUE THREAD

**Issue by irgaly** [support-project/knowledge#99]
Knowledge 0.6pre2へアップデート後、記事作成通知が届かなくなりました。すべての通知を受け取るように設定していますが、ユーザ追加通知のみ届き、他の通知は届かない状態となっています。

アップデート前はKnowledge0.5.3pre3でしたが、0.5.3pre3ではナレッジ登録やナレッジ更新通知が届いていました。

まずは起票いたします。

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます。

通知設定の部分で、マイグレーションが失敗しているのかもしれません。

または、メール通知処理にメールアドレスのフォーマットチェックを追加しましたので、そのチェックで、「メールアドレスでは無い」と判定されているかもしれません。

メールアドレスチェックは、正規表現で以下のパターンをチェックしています。
このフォーマットでメールアドレスと判定されますでしょうか？

```
^[a-zA-Z0-9!#$%&'_`/=~\\*\\+\\-\\?\\^\\{\\|\\}]+(\\.[a-zA-Z0-9!#$%&'_`/=~\\*\\+\\-\\?\\^\\{\\|\\}]+)*"
			+ "@" + "[a-zA-Z0-9][a-zA-Z0-9\\-]*(\\.[a-zA-Z0-9\\-]+)*$
```

もしお時間があれば、ご確認願います。

**Comment by irgaly** [comment]
Javaで上記正規表現をチェックしたところ、メールアドレスとして判定されました。

ユーザ追加通知が届き、記事作成通知が届かない点が気になっています。
ログやDBの中身など確認してみたいのですが、どの情報が必要でしょうか。

**Comment by nagodon** [comment]
@koda-masaru @irgaly 

こちらですがもしかすると記事が削除されたか何かで記事が取得できない時に
バッチ処理が落ちてしまって届いてないかもしれません。

こちらでもメールが送られない現象に遭遇していて調査していたのですが
記事やコメント、参考になったのデータがない時はスキップする処理を入れてみたところ
通知処理が動くようになりました。

@irgaly 

NotifyMailBat.logが下記の形でずっと流れてないでしょうか？

```
INFO  2015-10-17 00:13:29,747 [DBConnenctionLogic(35)] Custom connection setting is exists.
INFO  2015-10-17 00:14:29,300 [AbstractBat(26)] NotifyMailBat is start.
INFO  2015-10-17 00:14:29,664 [DBConnenctionLogic(35)] Custom connection setting is exists.
INFO  2015-10-17 00:15:31,811 [AbstractBat(26)] NotifyMailBat is start.
```

**Comment by nagodon** [comment]
nagodon/knowledge@08ba3c28fa11d42986820737424a0dd297487038
こちらのコミットでデータが取得できない場合はスキップするようにしてみました。

**Comment by irgaly** [comment]
ありがとうございます。NotifyMailBat.logのログはご指摘の通りとなっています。
#106 で指摘されているような、記事の作成 -> すぐに記事を削除 といった動作は通常の利用でもありえるため、同じ原因の可能性が高いと思います。

対応をマージしていただけましたので、次回リリース時に通知動作を確認してみます。

**Comment by koda-masaru** [comment]
ありがとうございます。
週末あたりに、リリースしようと思いますので、お手数ですが確認をお願いいたします。

**Comment by irgaly** [comment]
遅くなりましたが、v0.6.1で動作を確認し、メールが送信できるようになっていることを確認しました。
ありがとうございました。:+1:

**Comment by koda-masaru** [comment]
ご連絡ありがとうございます :smile: 
正しく動作したようですので安心いたしました。
