### ISSUE TITLE
Image resizing issue

### ISSUE THREAD

**Issue by hibihogehoge** [support-project/knowledge#990]
According to[ instruction page](https://github.com/support-project/docker-knowledge/tree/pre-japanese), I built the environment using Docker. (docker on Mac and Ubuntu 16.04 on Virtualbox on Windows 7)
I was able to confirm that the system is working, but the image resizing function does not work well.

I was able to resize the image in [the test system](https://test-knowledge.support-project.org/). Therefore, I think that there is no problem with the browser(Safari and Firefox) and description method.

**Comment by koda-masaru** [comment]
The reason why the image resizing function does not work is the version difference.
The image of Docker Is v1.11.0 stable.
And the test environment is v1.12.0 pre1 is running.

I will release v1.12.0 stable soon, and I update docker image's version.
so please wait this update.

**Comment by hibihogehoge** [comment]
I updated the software to the latest version and checked the image resizing function.
I confirmed that it worked well. 
Thank you very much.
