### ISSUE TITLE
webapi/knowledgesで全記事取得するには？

### ISSUE THREAD

**Issue by uRe29** [support-project/knowledge#993]
api/knowledgesで記事一覧を取得すると最新の10件しか取れませんでした。
全記事を取得する手段はありますか？

**Comment by koda-masaru** [comment]
You can get all data from web api with query parameter that is "offset".

-----

クエリパラメータの offset を利用すれば全ての情報を取得できます。

**Comment by hiro-icear** [comment]
横から失礼します。
同じくWebAPIで全件取得に苦労しています。
pagesizeの指定のイメージがよくわかっていません。
クエリパラメータの指定サンプル等をご教示お願いできますでしょうか？

pythonの抜粋です。
```
    query= {
　　　# 略・・・・
        'offest': 0
    }
    headers = {
        'Content-type': 'application/json',
        'PRIVATE-TOKEN': self.token
    }
    restext = requests.get(
        self.url,
        json=self.query,
        headers=headers)
```

**Comment by hiro-icear** [comment]
クエリーパラメータ(json)に記載しての動作はうまくいきませんでしたが、URI上のパラメータに直接'?offset=10'と書いた場合は動作しました。　limit=20と書けば20件取れました。

**Comment by uRe29** [comment]
URLパラメータに?offset=10を指定して、繰り返し取得で全件取得できました！
